### ISSUE TITLE
the tagged files reappear in ”Batch Operations"

### ISSUE THREAD

**Issue by yushizui** [Difegue/LANraragi#1001]
**LRR Version and OS**
0.9.1 docker
**Bug Details**

After the update, the tagged files reappear in ”Batch Operations“
They are all comics that have been deleted from ehentai. I have manually added tags, "source: no source "and other tag

**Comment by Difegue** [comment]
What do you mean by "reappear"? Please provide more details.

**Comment by yushizui** [comment]
![image](https://github.com/Difegue/LANraragi/assets/130179532/a016e4ca-9ebb-4c07-9d4c-13fb218e9d23)
After adding the source: tag before, it will not appear in "Batch Operations"
