### ISSUE TITLE
"Pin this Category" in wrong

### ISSUE THREAD

**Issue by yushizui** [Difegue/LANraragi#1006]
**LRR Version and OS**
0.9.1 docker
**Bug Details**
https://github.com/Difegue/LANraragi/issues/689 There seems to be an error in the category sorting after the update. It does not seem to be sorted according to the alphabetical order mentioned above, and the "Pin this Category" seems to be invalid. I don’t know if it has something to do with the use of Chinese.

**Comment by yushizui** [comment]
I just created a new docker and tried it, I think it's because the existing sorting method is not compatible with other language.

Would you consider compatibility with other languages,Seems like it could be solved by adding a letter to the front as well，I have quite a few  Categories. If you consider compatibility, I won’t modify them for the time being.

**Comment by Difegue** [comment]
The sorting just relied on basic javascript comparison -- I've pushed a change to rely on [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) instead which might improve the situation for non-english languages.  

No idea why pinning wouldn't work though

**Comment by yushizui** [comment]
> The sorting just relied on basic javascript comparison -- I've pushed a change to rely on [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) instead which might improve the situation for non-english languages.
> 
> No idea why pinning wouldn't work though -- Feel free to reopen this if you still have issues

pinning will only fail if other language is used.

**Comment by mayziran** [comment]
Sorting for other languages ​​has been fixed，But "Pin this Category" is still wrong, and seems to have nothing to do with the language，I created a new docker to try and use English for all categories，The pin's gallery is not topped, only a red pin icon appears next to it

**Comment by yushizui** [comment]
> The sorting just relied on basic javascript comparison -- I've pushed a change to rely on [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) instead which might improve the situation for non-english languages.
> 
> No idea why pinning wouldn't work though -- Feel free to reopen this if you still have issues

Sorting for other languages ​​has been fixed，But "Pin this Category" is still wrong, and seems to have nothing to do with the language，I created a new docker to try and use English for all categories，The pin's gallery is not topped, only a red pin icon appears next to it

**Comment by myzzh5** [comment]
You can add this icon before the label name to fix the label in the first place
📌
