### ISSUE TITLE
Ksk metadata filter error

### ISSUE THREAD

**Issue by shinji257** [Difegue/LANraragi#1007]
**LRR Version and OS**
Docker - 0.9.1

**Bug Details**
When using the Koushoku.yaml metadata plugin I'm getting the following error.
```
Error while processing ID 43140aeebd8c237a47b7db6401e1eae74a4b652b (Can't use string ("T-Heaven") as an ARRAY ref while "strict refs" in use at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/Metadata/Ksk.pm line 81.
)
```

**Matching Logs**
No external plugin logs appear.  I get the above when trying to do a batch.

**Screenshots**
N/A as it would just be the above text.

**Additional Info**
I'll note that where I got my archives from the format that they used changed a little.  Fields like Artist and Circle used be set as a yaml list where now they are just on the same line.

So instead of 
```yaml
Parody: 
  - Original Work
```
It's now
```yaml
Parody: Original Work
```

**Comment by Difegue** [comment]
Thanks, should be fixed now.
