### ISSUE TITLE
Plugin system 2.0

### ISSUE THREAD

**Issue by Difegue** [Difegue/LANraragi#102]
- [x] Move arguments from an array to a hash in order to introduce basic typage(bool/int/string)
- [x] Handle boolean-type arguments with a toggle switch in configuration/batch tagging
- [x] Allow plugins to add the original gallery URL to metadata as well (this is a maybe)
- [x] Allow plugins to embed a small base64 image to show as an icon in configuration (this is also a maybe)
- [ ] Add non-metadata plugins, that can be triggered from the plugin configuration page.
- [ ] Add API to trigger plugins remotely
- [x] Update plugin documentation

**Comment by wtfabear** [comment]
Hi I just wanted to drop by and say that I'm really looking forward to the third item: adding original gallery url to the metadata. I was reading through the plugin docs and you added the ability for plugins to grab the title information from the original panda gallery, Could we have your original eh plugin updated with the new plugin abilities?

**Comment by Difegue** [comment]
Yeah, that's planned too. I'd like to make modifying the archive title a toggleable option in the E-H plugin, which brings us back to boolean arguments.

**Comment by wtfabear** [comment]
Nice. Amazing work by the way. Yours is easily the best of the content organizers, and I think it's mostly the container installation requirements that's making most users shy away from it.

**Comment by Difegue** [comment]
Thanks! I agree that the installation requirements are really steep for end-users. I've always struggled to provide an easy way to try and install the software, and containers have proven to be the best "bang for my buck(time)" solution.

I'd like to eventually provide huge 300MBs installation packages including perl and the whole kitchen sink like HPX and Hydrus do with Python, but that'd still probably exclude Windows due to a bunch of stuff not having ready-made equivalents. :mask:

**Comment by Difegue** [comment]
Essentially all done as of this PR; I don't think I'll be doing non-metadata plugins for the time being.
