### ISSUE TITLE
Cannot connect to localhost since latest update (WSL2 issue?)

### ISSUE THREAD

**Issue by defski** [Difegue/LANraragi#1020]
**LRR Version and OS**
Dead Man Walking, W10

**Bug Details**
I'm not able to connect to my localhost server on a separate device. Tried using port 4000 and 3000 with similar results.

**Matching Logs**
Error in console: "Can't create listen socket: Address in use at /usr/local/share/perl5/site_perl/Mojo/IOLoop.pm line 124."

**Comment by Difegue** [comment]
See https://github.com/Difegue/LANraragi/discussions/378
