### ISSUE TITLE
Koushoku.yaml plugin indev adds magazine tag even if it doesn't exist in the original info.yaml file

### ISSUE THREAD

**Issue by shinji257** [Difegue/LANraragi#1025]
**LRR Version and OS**
0.9.1

**Bug Details**
Note: I sideload added the Ksk.pm file from dev branch as a new item with a changed name so I could test it.  It only changed the  name and namespace fields in the plugin_info area in order to make sure that there were no conflicts.

When tagging an info.yaml as described in a previous ticket (single line vs the older multi line) the plugin erroneously added a magazine tag even if it doesn't exist in the info.yaml file.  This does not happen with the older format.  The issue also technically applies to the  artist and series fields as well but most info.yaml files that it would process should already have them however since it will still drop those empty tags in a info.yaml file laid out different suggests that those should be blocked if empty as well.

**Matching Logs**
```
Started Batch Operation...
************
Processed ID c28cceb4094e5f8baa4be8592a642d546060e096 with "kskyamlmeta-dev" (Added tags:  artist:, series:, magazine:)
```
**Screenshots**
Result:
![image](https://github.com/user-attachments/assets/f3bd2434-51a0-43e4-b9b1-d8bed07c1f10)

**Comment by siliconfeces** [comment]
I've made a PR (#1023) that should fix that issue, if you want you can try it out in [my branch](https://github.com/siliconfeces/LANraragi/blob/koharu_support/lib/LANraragi/Plugin/Metadata/Ksk.pm)

**Comment by shinji257** [comment]
Thanks.  I see that your PR is already merged so I pulled the copy off this repo's dev branch to sideload into 0.9.1.
