### ISSUE TITLE
Please fix Restore Featrue on v0.9.1

### ISSUE THREAD

**Issue by bennyz327** [Difegue/LANraragi#1029]
**LRR Version and OS**
OS: Windows 11 Pro build 22631.3880
Using LANraragi v.0.9.1 (LANraragi.msi)

**Bug Details**
WebUI show following message after upload the "backup.json" file
"An error occured server-side. woops.
Maybe your JSON is badly formatted ?"

**Steps to Reproduce**
1. Install with LANraragi.msi
2. Download "backup.json" file from other lanraragi server (v.0.9.0)
3. Upload "backup.json" file to my lanraragi server (v.0.9.1)
4. An error occurred
After error occurred, I checking the status of the file.
My lanraragi server only imports the data for the first archive row (backup.json has about 1700 archive data row)

**Try**
In the JSON file I backed up, the first row of archive is A.
When I run recovery, only row A will be imported, and when I remove A, the first row of archive in the JSON file will be B, and then my server will only import row B.

**Comment by bennyz327** [comment]
Matched log in DEBUG mode

`[2024-07-24 14:20:58.75389] [61] [trace] [0f9Jj4MMFf5l] POST "/backup"
[2024-07-24 14:20:58.75413] [61] [trace] [0f9Jj4MMFf5l] Routing to controller "LANraragi::Controller::Login" and action "logged_in"
[2024-07-24 14:20:58.75435] [61] [trace] [0f9Jj4MMFf5l] Routing to controller "LANraragi::Controller::Backup" and action "restore"
[Backup/Restore] [info] Received a JSON backup to restore.
[Archive] [info] Saving automatic backup to /home/koyomi/lanraragi/autobackup.json
[Backup/Restore] [info] Restoring Category SET_1712253494...
[Backup/Restore] [info] Restoring Category SET_1712168945...
[Backup/Restore] [info] Restoring Category SET_1712262403...
[Backup/Restore] [info] Restoring metadata for Archive 59105f939c2db7787e699dd743624367d444b8ce...
[2024-07-24 14:21:00.64759] [61] [error] [0f9Jj4MMFf5l] Undefined subroutine &LANraragi::Model::Backup::set_summary called at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Backup.pm line 135.

[2024-07-24 14:21:00.64790] [61] [debug] Template "exception.development.html.tt2" not found
[2024-07-24 14:21:00.64809] [61] [debug] Template "exception.html.tt2" not found
[2024-07-24 14:21:00.64822] [61] [trace] [0f9Jj4MMFf5l] Rendering cached template "mojo/debug.html.ep"
[2024-07-24 14:21:00.65035] [61] [trace] [0f9Jj4MMFf5l] 500 Internal Server Error (1.896452s, 0.527/s)`

**Comment by bennyz327** [comment]
Because the new field "summary" not found in old backup.json I guess?

**Comment by bennyz327** [comment]
On my server using LANraragi v.0.9.1 download backup.json then upload to my server
also get same error

**Comment by bennyz327** [comment]
I found this error is fix in nightlies version ( #1024 )
But I dont know how to run nightlies version
Unable to recover from a backup issue that prevents old users from upgrading

So, how long does it take to release a version with this bug fix?

**Comment by bennyz327** [comment]
Additional Follow-up Test

I installed Docker in the Ubuntu 22.04 subsystem on Windows 11 WSL 2 and tried the Docker nightly version of Lanraragi. I performed the same database backup and restore operations and still encountered the same issue. I'm not sure if the nightly version addresses this problem.

**Comment by Difegue** [comment]
Docker nightlies are out of date due to issues with the latest alpine version; Unfortunately I'm still not quite sure what causes the issue and it's blocking the release for now.  

Windows nightlies are up to date and should be usable.

**Comment by Difegue** [comment]
I've fixed nightlies with #1030, feel free to pull the image down again.  
I'll try having a 0.9.2 out in the near-ish future.
