### ISSUE TITLE
"Pin this Category" in wrong

### ISSUE THREAD

**Issue by yushizui** [Difegue/LANraragi#1038]
**LRR Version and OS**
0.9.21 docker

**Bug Details**
https://github.com/Difegue/LANraragi/issues/1006#issuecomment-2198808208, Sorting for other languages ​​has been fixed，But "Pin this Category" is still wrong, and seems to have nothing to do with the language，I created a new docker to try and use English for all categories，The pin's category is not topped, only a red pin icon appears next to it

**Comment by yushizui** [comment]
There seems to be another problem ， "add to catogory" is not sorted alphabetically

**Comment by yushizui** [comment]
There is a new discovery, I tried several computers, when using firefox, "Pin this Category" is working, when using the chroium kernel browser, "Pin this Category"  is wrong

**Comment by Difegue** [comment]
I see, I only test on FF so that'd explain it. I'll take another look at some point.
