### ISSUE TITLE
Impossible to add any external custom plugin. 

### ISSUE THREAD

**Issue by tricktricktrick** [Difegue/LANraragi#1039]
LRR Version and OS:

  Version: Latest (both base and nightly versions)
  OS: Docker on Windows

Bug Details:

I am experiencing an issue where it is impossible to add any custom plugin to the app since the last update. This issue occurs in both the normal and nightly versions of LANraragi.
Initially, I thought the problem was with my custom build, but I confirmed that the issue also occurs with the base images. Here are the steps and commands I used to reproduce the issue:

Steps to Reproduce:

1. Pull the latest LANraragi image and run it using Docker with the following command:
    docker run --name=lanraragi -p 3000:3000 `
    --mount type=bind,source="F:/Save backup/Lanraragi/Lanraragi_newcontent",target=/home/koyomi/lanraragi/content `
    --mount type=bind,source="F:/Save backup/Lanraragi/Lanraragi_database",target=/home/koyomi/lanraragi/database `
    --mount type=bind,source="F:/Save backup/Lanraragi/Lanraragi_Thumb",target=/home/koyomi/lanraragi/content/thumb `
    difegue/lanraragi
    
Or : 

    docker run --name=lanraragi -p 3000:3000 `
    --mount type=bind,source="F:/Save backup/Lanraragi/Lanraragi_newcontent",target=/home/koyomi/lanraragi/content `
    --mount type=bind,source="F:/Save backup/Lanraragi/Lanraragi_database",target=/home/koyomi/lanraragi/database `
    --mount type=bind,source="F:/Save backup/Lanraragi/Lanraragi_Thumb",target=/home/koyomi/lanraragi/content/thumb `
    difegue/lanraragi:nightly

2. Attempt to add a custom plugin.
3. The application throws permission errors.

**Matching Logs**

Container start log : 
Status: Downloaded newer image for difegue/lanraragi:nightly
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service init: starting
Starting LANraragi with UID/GID : 9001/9001
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
usermod: no changes
s6-rc: info: service legacy-cont-init successfully started
Fixing permissions, hold on!
rm: can't remove '/home/koyomi/lanraragi/public/temp/server.pid': No such file or directory
rm: can't remove '/home/koyomi/lanraragi/public/temp/shinobu.pid': No such file or directory
rm: can't remove '/home/koyomi/lanraragi/public/temp/shinobu.pid-s6': No such file or directory
rm: can't remove '/home/koyomi/lanraragi/public/temp/minion.pid': No such file or directory
rm: can't remove '/home/koyomi/lanraragi/public/temp/minion.pid-s6': No such file or directory
s6-rc: info: service init successfully started
s6-rc: info: service redis: starting
s6-rc: info: service redis successfully started
s6-rc: info: service lanraragi: starting
s6-rc: info: service lanraragi successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Attempting to create directory /home/koyomi/perl5
Server PID will be at /home/koyomi/lanraragi/public/temp/server.pid

ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!!!!!
[LANraragi] [info] LANraragi 0.9.21 started. (Production Mode)
[LANraragi] [info] Plugin Detected: Chaika.moe
[LANraragi] [info] Plugin Detected: Chaika.moe api.json
[LANraragi] [info] Plugin Detected: ComicInfo
[LANraragi] [info] Plugin Detected: Tag Copier
[LANraragi] [info] Plugin Detected: Add Timestamp Tag
[LANraragi] [info] Plugin Detected: E-Hentai
[LANraragi] [info] Plugin Detected: eze
[LANraragi] [info] Plugin Detected: FAKKU
[LANraragi] [info] Plugin Detected: HentaiAtHome plugin
[LANraragi] [info] Plugin Detected: Hdoujin
[LANraragi] [info] Plugin Detected: Hentag
[LANraragi] [info] Plugin Detected: Hentag Online Lookups
[LANraragi] [info] Plugin Detected: Hitomi
[LANraragi] [info] Plugin Detected: koromo
[LANraragi] [info] Plugin Detected: Koushoku/Koharu.yaml
[LANraragi] [info] Plugin Detected: Mayriad's EH Master Script
[LANraragi] [info] Plugin Detected: Pixiv
[LANraragi] [info] Plugin Detected: Filename Parsing
[LANraragi] [info] Plugin Detected: nHentai
[LANraragi] [info] Script Detected: Subfolders to Categories
[LANraragi] [info] Script Detected: Source Finder
[LANraragi] [info] Script Detected: nHentai Source Converter
[LANraragi] [info] Downloader Detected: Chaika.moe Downloader
[LANraragi] [info] Downloader Detected: E*Hentai Downloader
Minion will use the Redis database at 127.0.0.1:6379/1
[LANraragi] [info] Successfully connected to Minion database.
[Minion] [info] Starting new Minion worker in subprocess with 8 parallel jobs.
[Minion] [info] Minion worker 114 started
[2024-07-26 09:32:48.91513] [91] [info] Listening at "http://*:3000"
[LANraragi] [info] Routing done! Ready to receive requests.
Web application available at http://127.0.0.1:3000
[2024-07-26 09:32:48.91559] [91] [info] Manager 91 started
[2024-07-26 09:32:48.92104] [132] [info] Worker 132 started
[2024-07-26 09:32:48.92622] [138] [info] Worker 138 started
[2024-07-26 09:32:48.92950] [144] [info] Worker 144 started
[2024-07-26 09:32:48.93064] [91] [info] Creating process id file "/home/koyomi/lanraragi/public/temp/server.pid"
[2024-07-26 09:32:48.93300] [150] [info] Worker 150 started

Adding a plugin to the app give : 

[2024-07-26 09:33:20.05447] [144] [error] [d1ddQvMP8lCe] Can't open file "/home/koyomi/lanraragi/lib/LANraragi/Plugin/Sideloaded/Wrapper_TagExtractor.pm": Permission denied at /usr/local/share/perl5/site_perl/Mojo/Asset/Memory.pm line 46.

[2024-07-26 09:34:36.00075] [144] [error] [-AxW8u3SD5Go] Can't open file "/home/koyomi/lanraragi/lib/LANraragi/Plugin/Sideloaded/GlobalDownloader.pm": Permission denied at /usr/local/share/perl5/site_perl/Mojo/Asset/Memory.pm line 46.

**Comment by Difegue** [comment]
due to the new volume for sideloaded plugins, I think you'll need to add a new bind mount go your docker setup.

**Comment by tricktricktrick** [comment]
Sorry and tyvm for your time it worked. I didnt saw the change, its my mistake.

**Comment by E78870** [comment]
adding "--mount type=bind,source=/mnt/nfs/lanraragi/database/sideloaded_plugin,target=/home/koyomi/lanraragi/lib/LANraragi/Plugin/Sideloaded" is working.
And found that owner of "/home/koyomi/lanraragi/lib/LANraragi/Plugin/Sideloaded" is root instead of koyomi others folder in "Plugin" using.
