### ISSUE TITLE
Unable to get all tags with ComicInfo plugin

### ISSUE THREAD

**Issue by gabmak** [Difegue/LANraragi#1047]
**LRR Version and OS**
Docker (Linux) with version 0.9.21

**Bug Details**
ComicInfo plugin not catching anything under < Tags >

Here the ComicInfo.xml

```
<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Title>異種姦オーガズム</Title>
  <Summary>[7zu7] Ishukan Orgasm [Chinese] [1208201-1600x]
</Summary>
  <Writer>7zu7</Writer>
  <Tags>translated, artist:7zu7, male:monster, female:ahegao, female:anal, female:big breasts, female:mind break, female:mind control, female:schoolgirl uniform, female:stockings, female:tentacles, female:vore, Manga, Uploaded</Tags>
  <LanguageISO>zh</LanguageISO>
</ComicInfo>
```

I'm trying to migrate my Calibre library to LANrargi but I'm having trouble importing all the tags in my cbz using the plugin.

If I manually copy the < Tags > line in the edit Metadata tag field, LANraragi has no problem dealing with it. 

**Matching Logs**
Post any logs you have encountered when reproducing the bug.  

[2024-08-08 23:06:55] [ComicInfo] [info] Sending the following tags to LRR: group:7zu7, language:zh

**Comment by Difegue** [comment]
`<Tags>` isn't in the ComicInfo standard I believe, that's something Calibre added.  
I've added support to it, feel free to check out nightlies to give it a spin.

**Comment by gabmak** [comment]
Thank you very much! Confirm the tags are working with the nightly build.

Cheers :)

**Comment by shinji257** [comment]
I know.  It's old but I thought to at least drop this somewhere it is appropriate.
ComicInfo metadata docs
https://anansi-project.github.io/docs/comicinfo/documentation

Includes information regarding Tags metadata.
