### ISSUE TITLE
Can't open any archive. Image::Scale related problem.

### ISSUE THREAD

**Issue by RaulDJ** [Difegue/LANraragi#105]
**LRR Version and OS**
LANraragi 0.5.9 running from source on Ubuntu 18.04.2 LTS, Odroid HC2 (Odroid XU4, armv71).

**Bug Details**
When trying to open any archive, I get the following errors:

When opening an archive with .jpg files: 

```
It's likely the archive is corrupt.
Some more info below if available:

Image::Scale was not built with JPEG support 
```

When opening an archive with .png files: 

```
It's likely the archive is corrupt.
Some more info below if available:

Can't locate object method "save_jpeg" via package "Image::Scale" at /mnt/HC2/LANraragi/LRR/script/../lib/LANraragi/Utils/Archive.pm line 32. 
```

By following this [installation procedure](https://sugoi.gitbook.io/lanraragi/for-regular-users/index/source-linux), I got a lot of problems related to Image::Scale not being able to be built, but I "fixed" them somehow and could continue with the installation proccess, at least until I realized I couldn't open anything. Other functions of the software seem to be working.

**Matching Logs**
[Mojolicious] Template "exception.development.html.tt2" not found
[Mojolicious] Template "exception.html.tt2" not found
[Mojolicious] Rendering cached template "mojo/debug.html.ep"
[Mojolicious] 500 Internal Server Error (0.042304s, 23.638/s)
[Mojolicious] Image::Scale was not built with JPEG support

**Comment by Difegue** [comment]
Well, the obvious issue here is that indeed, Image::Scale was not built with JPEG support.  
Normally if you install libjpg properly, Image::Scale should detect and use it when building itself.

**Comment by RaulDJ** [comment]
Yeah, that's what I first tried to do but I get "Building Image-Scale-0.14 ... FAIL", and a log which I attached to this post. Bulding Image::Scale with --force doesn't work either.

By installing Image::Scale in some strange way I somehow "solved" that problem, but the result was what I posted in the OP.

Thanks for your help.

[build.log](https://github.com/Difegue/LANraragi/files/3005913/build.log)

**Comment by Difegue** [comment]
From the log, it seems your libjpeg is badly built. Have you downloaded it from the ubuntu repositories directly, or tried to build it from source? As long as the build log indicates `libjpeg version unknown`, it's probably worrying.

**Comment by RaulDJ** [comment]
I'm installing in the same way you show on your guide, this is by `apt-get install`. This is quite strange as I had LANraragi working on a Raspberry Pi around 5 months ago, but I tried updating it starting march I got to the same problem with Image::Scale.

**Comment by Difegue** [comment]
Huh, maybe the ARM libjpeg package is behaving weirdly for some reason. Guess you can try installing an older version or building it from source then?

**Comment by RaulDJ** [comment]
The thing is that it seems that the newest version of libjpeg is from 2013 so... there's no "older version" that could have worked for me by that time. I will try messing with it a little more and then try to go the Docker route.

**Comment by Difegue** [comment]
Now that I think of it, 5 months ago Image::Scale wasn't used, so that probably explains the discrepancy. 🤔 Sorry for misleading you.

**Comment by RaulDJ** [comment]
Oh boy... gonna check that out too, then. Thing is I don't wanna miss the new things you are adding either...

**Comment by RaulDJ** [comment]
Welp, in the end I made a Docker image from the Odroid itself and runned it and _it just werks_ so I'm quite hapy with the result, as all the chinese crap is back online.

Keep the hard work and thanks for this great software!
