### ISSUE TITLE
Excessively wide tag column

### ISSUE THREAD

**Issue by wtfabear** [Difegue/LANraragi#107]
**LRR Version and OS**
LANraragi 0.5.9 on Docker Toolbox vm on Windows 7.

**Bug Details**
The tags column takes up a ton of space forcing the text in the other columns to get cut off and hard to read. Is this expected behavior? Is there any way to adjust this? Image example is from Chrome Version 73.0.3683.86 (Official Build) (64-bit)

![whyyyy](https://user-images.githubusercontent.com/48998037/55291520-2571f000-5394-11e9-83ec-23f1013d1d93.jpg)

**Comment by Difegue** [comment]
Normally the tag column has a maximm width of 150 pixels, so your case is odd indeed.  
Since the CSS was wholelifted from exhentai when I started development, a bunch of the css classes still have similar names. Do you have any scripts/extensions enabled that might affect the look of the page?

**Comment by wtfabear** [comment]
No I don't. My Chrome browser only uses adblock plus, and the problem remains even if I deactivate it.

**Comment by Difegue** [comment]
Might be a chrome thing then, I'll look it up.

**Comment by Difegue** [comment]
Yup, busted in chrome due to dumb table width priority differences with my other test browsers (FF/Edge).
Copying the change I made in the commit above should be enough.

**Comment by wtfabear** [comment]
Was this fix included in the latest release? I updated my container on latest and it's still showing this problem.

**Comment by Difegue** [comment]
It wasn't! I only slipstreamed the updated plugins from the dev branch in that release.
