### ISSUE TITLE
Feature Request: Support for OR-based Searches/Categories in Lanraragi

### ISSUE THREAD

**Issue by Echronix** [Difegue/LANraragi#1075]
I am writing to propose an enhancement to Lanraragi's search functionality/archiving function. Currently, the search system and dynamic category system allows for filtering based on exact matches using commas to combine tags, but it does not support OR-based searches where users can search for items that match either one tag or another.

Problem Statement:

The existing search functionality only supports filtering results where all specified tags or conditions are matched simultaneously. For example, searching with: "cat boy, cat girl" returns only results that include both tags. However, there are use cases where users might want to find items that match either one tag or another. For instance, a user might want to search for items tagged with either cat boy or cat girl or make a dynamic category for their "Best artists", which would then show the works of only their favorite artists they added in the predicate, but the current system doesn't support this kind of OR-based search. (Or at least I don't believe it does, from testing around a bit)

Proposed Solution:

I propose adding support for OR-based searches and categories. This could be implemented by allowing the search syntax to include an OR operator (e.g., |) or a specific keyword that signifies OR conditions. Example: Syntax: Users could enter search queries like cat boy | cat girl to find items tagged with either cat boys or cat girls.

**Comment by Difegue** [comment]
See #754.
