### ISSUE TITLE
Filename Parsing Plug-in function request

### ISSUE THREAD

**Issue by hucurve** [Difegue/LANraragi#1084]
![image](https://github.com/user-attachments/assets/a8939a8a-0e52-4692-809f-d792707a5045)
I'm using the built-in Plug-in for file metadata recognition, which I think is very useful and robust, but I still have two pain points that I hope to resolve one day：
1.Only the first can be recognized when multiple artists are present, while the others are in others
My file name =[黒ねずみいぬ, 市川和秀, 猪去バンセ, カサイこーめい, きしぐま, ＳＵＶ, 重丸しげる, ちんぱん☆Mk-Ⅱ, ばんじゃく, 英, ふぁい, 水樹 凱, やさごり]XXXX.zip
![image](https://github.com/user-attachments/assets/bd42cf48-4d64-4bc8-86e6-b9ad137b2d2d)

2.I often change the original file name, and after re-scanning, the changed file will not trigger the plug-in, but still use the original name. There is also no way to select the changed file in the batch tool. This often confuses me

I hope someone can see my request, anyway I still like LRR this beautiful software:)

**Comment by Difegue** [comment]
This is a bit unconventional as far as using the naming standard goes, but I think it'd be pretty easy to check if the tags contain commas after regex parsing and assign the namespace to each one.

**Comment by IceBreeze** [comment]
I was toying with this plugin a bit and this was an issue that I wasn't sure whether I wanted to handle or not.
This could also be applied to "groups", "series" and "languages" as well, but I knew for certain that at least the series can have a comma in their names.

I was going to break down just the language string where I can verify the generated tokens, but I can do the same for the rest and blindly accept the result.
It should be refined, but I can make a PR to dicuss.

**Comment by Difegue** [comment]
I think it makes sense to have this behavior for language and groups.  
Series can have commas, but for those I think we should take them out as it'll break the tag storage.  

I do wonder if groups with commas in their names exist.. I don't think that'd be too common.
