### ISSUE TITLE
Default Password

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#11]
Hey. Has the default password changed? 
I overwrote my files with the ones from the repository and I can't login anymore.

**Comment by Difegue** [comment]
I haven't touched anything related to password usage for a while now. 
Will do some testing on my side later, maybe there's been a regression or two.

**Comment by Difegue** [comment]
Tested in the upcoming 0.4 release on the demo instance, password switching and login works properly.

If something got mangled in your setup (can happen I guess), you can manually disable password protection through the Redis CLI: 

```
redis_cli
hset LRR_CONFIG enablepass 0
```

**Comment by cseverino** [comment]
For the current version (0.8.90) you'll need to use redis database # 2 so here's the commands:

```
redis-cli -n 2
hset LRR_CONFIG enablepass 0
```
