### ISSUE TITLE
e-hentai download plugin part is invalid

### ISSUE THREAD

**Issue by mhdy2233** [Difegue/LANraragi#1101]
e-hentai updated the exhentai page rules, causing the e-hentai download plug-in to be unable to download the gallery in exhentai. Can the e-hentai download plug-in be updated?

**Comment by glop102** [comment]
Ah, so not just me encountering a problem with exhentai. I can also confirm that e-hentai  for the same gallery does work.

**Comment by blackgu4rd** [comment]
Same issue - commented on a discord support thread with details.

**Comment by Difegue** [comment]
Fixed in nightlies - Thanks for the report.  

It's likely EH itself will also break at some point when the archiver key requirement is gone, but the fix should be easy at least.

**Comment by bossanovaorca** [comment]
yeah it looks like EH is now broken as well. looking forward for the fix to land in stable!

**Comment by pwnfu** [comment]
It looks like the archive key requirement is actually gone in EH.
