### ISSUE TITLE
api/search/random Endpoint Sometimes Doesn't Return Amount Requested in count Parameter

### ISSUE THREAD

**Issue by hibikikuze4dan** [Difegue/LANraragi#1119]
**LRR Version and OS**
 Version 0.9.21, "Telling Lies (Paradox mix)" - Synology NAS - Docker

**Bug Details**
I've noticed when supplying a larger number to the `count` parameter for the `api/search/random` endpoint like 63 for example, the amount of archives in the response is sometimes less than the number provided in `count` like 61 instead of 63. As stated, this only happens sometimes at about a 25-33% rate. It's not exactly a huge deal, I just wanted to bring attention to the fact that this exists.

**Matching Logs**
Nothing of note in the logs from what I could tell.

**Screenshots**
![Screenshot 2024-11-27 133214](https://github.com/user-attachments/assets/8c2562df-482b-4d2b-8059-854b368cf210)
![Screenshot 2024-11-27 133139](https://github.com/user-attachments/assets/74e7f58a-aff7-45b5-89ca-cdfa0e60cfac)

**Comment by hibikikuze4dan** [comment]
> If your search query has less total IDs than your `count`, the API will stop after including every existing result in the random selection.
> 

That makes sense, but the behavior I described was happening even when no search query was being supplied.

**Comment by Difegue** [comment]
I see - Guess it's worth taking a closer look at some point, might be some logic error in the way the server pulls random IDs out of the results?
