### ISSUE TITLE
Unable to upload files properly

### ISSUE THREAD

**Issue by LawdStalker** [Difegue/LANraragi#113]
**LRR Version and OS**
LANraragi v.0.6.0 Beta 1
OS: Windows 10 x64 Build 1809
Installation method: WSL Ubuntu 18.04 from source

**Bug Details**
When I try to upload files from the browser upload page the zip file is copied to the /content/ folder but isn't loading properly neither fetching tags with the respective plugin.

**Matching Logs**
```
Use of uninitialized value $filecheck in string eq at ./lib/Shinobu.pm line 332.
Use of uninitialized value $filecheck in concatenation (.) or string at ./lib/Shinobu.pm line 335.
[Shinobu] [info] Building JSON cache...This might take some time.
Use of uninitialized value $filecheck in string eq at ./lib/Shinobu.pm line 332.
Use of uninitialized value $filecheck in concatenation (.) or string at ./lib/Shinobu.pm line 335.
```

- Debug Mode
```
[Mojolicious] POST "/upload" (9e9969e8)
[Mojolicious] Routing to controller "LANraragi::Controller::Login" and action "logged_in"
[Mojolicious] Routing to controller "LANraragi::Controller::Upload" and action "process_upload"
[Shinobu] [debug] Received inotify event 128 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Adding /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip to Shinobu filemap.
[Mojolicious] command sent is not an octet sequence in the native encoding (Latin-1). Consider using debug mode to see the command itself. at /usr/local/share/perl/5.26.1/Redis.pm line 268.

[Shinobu] [debug] Computed ID is db26ecf0dc23525ee8c18f331e1274661d110689.
[Mojolicious] Template "exception.development.html.tt2" not found
[Shinobu] [info] Building JSON cache...This might take some time.
[Mojolicious] Template "exception.html.tt2" not found
[Mojolicious] Rendering cached template "mojo/debug.html.ep"
[Shinobu] [debug] JSONing 538f7c5c7aead5013c0d22c7126242cdf0b4007e -> /home/koyomi/lanraragi/content/[Muta] Lil' Devil Academy.zip
[Mojolicious] 500 Internal Server Error (0.038225s, 26.161/s)

[Shinobu] [debug] Received inotify event 1073741856 on /home/koyomi/lanraragi/content
[Shinobu] [debug] Received inotify event 1073741840 on /home/koyomi/lanraragi/content
[Shinobu] [debug] Received inotify event 32 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 16 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 32 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 16 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 32 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 16 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 1073741856 on /home/koyomi/lanraragi/content
[Shinobu] [debug] Received inotify event 1073741840 on /home/koyomi/lanraragi/content
[Shinobu] [debug] Received inotify event 32 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 16 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 32 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 16 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 32 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 16 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 32 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 16 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 32 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 1 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 16 on /home/koyomi/lanraragi/content/(COMIC1☆12) [abgrund (Saikawa Yusa)] Fuun na Tabibito no Hanashi  The Tale of an Unfortunate Traveller (Kino no Tabi) [English].zip
[Shinobu] [debug] Received inotify event 1073741856 on /home/koyomi/lanraragi/content
[Shinobu] [debug] Received inotify event 1073741840 on /home/koyomi/lanraragi/content
```

**Screenshots**
<details> 
  <summary>Blank upload webpage even after uploading file </summary>
 <img src="https://user-images.githubusercontent.com/50067181/56936214-83e1d980-6acc-11e9-9f2e-1d98f66ed719.png">
</details>
<details> 
  <summary>Files with no metadata loaded after upload </summary>
 <img src="https://user-images.githubusercontent.com/50067181/56936232-9d832100-6acc-11e9-9ce5-287ba33abbc8.png">
</details>

**Comment by Difegue** [comment]
The uploader is hitting a 500 and therefore freezes - I should really get to implementing better error handling in that one.  

Can you try performing the upload again with browser dev tools on? You should be able to see the request that 500s in the Network tab and get a more detailed error message out of it.

**Comment by LawdStalker** [comment]
>Your archive gets on the server so I'm guessing it's bugging out on filename parsing.

Could the filename length cause any problems?

> Can you try performing the upload again with browser dev tools on? You should be able to see the request that 500s in the Network tab and get a more detailed error message out of it.


**Console log:**
```
fa-solid-900.woff2:1 Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js:2 POST http://127.0.0.1:3000/upload 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
send @ jquery.fileupload.js:925
_onSend @ jquery.fileupload.js:988
(anonymous) @ jquery.ui.widget.js:148
data.submit @ jquery.fileupload.js:688
(anonymous) @ jquery.fileupload.js:218
c @ jquery.min.js:2
add @ jquery.min.js:2
add @ jquery.fileupload.js:217
_trigger @ jquery.ui.widget.js:701
(anonymous) @ jquery.fileupload.js:1057
each @ jquery.min.js:2
_onAdd @ jquery.fileupload.js:1050
(anonymous) @ jquery.ui.widget.js:148
(anonymous) @ jquery.fileupload.js:1256
c @ jquery.min.js:2
add @ jquery.min.js:2
always @ jquery.min.js:2
_onChange @ jquery.fileupload.js:1246
(anonymous) @ jquery.ui.widget.js:148
handlerProxy @ jquery.ui.widget.js:610
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```
[**Network tab .har**](https://github.com/Difegue/LANraragi/files/3133353/127.0.0.1.zip)

**Comment by Difegue** [comment]
I don't think filename length is at cause here, especially if all your archives aren't going through. You'd probably hit the windows file length limit before we'd have a hitch on our side anyways.  

I dissected the .har to get the mojolicious error page for the 500 but it's the non-development mode one so it has no logs whatsoever -- Did you restart the app after enabling debug mode?  
The server can't switch to dev mode mid-flight for the moment, so you're getting my debug logs but not the mojolicious ones.  

(Although there's nothing in the mojo docs saying it can't; I should add the code for that and test it out in a future release)

**Comment by LawdStalker** [comment]
> I dissected the .har to get the mojolicious error page for the 500 but it's the non-development mode one so it has no logs whatsoever -- Did you restart the app after enabling debug mode?

I had disabled debug mode and forgot to re-enable before the network tab recording. 
Here's the dev mode .har:
[Upload-error-debug-mode.har](https://github.com/Difegue/LANraragi/files/3133416/upload-error-debug-mode.zip)

**Comment by Difegue** [comment]
`command sent is not an octet sequence in the native encoding (Latin-1).`

Welp, it's good ol' encoding bug rearing his ugly head again.  
I decided in the last release to abandon all forms of encoding for filenames and store them as the OS gives me, which spared a lot of headache.  
It's OS-proof for sure now, but since you're going through the upload tool, it's (incorrectly) using a filename given by the web browser, who's smuggling in UTF-8 encoded characters. Should've seen that one coming.  

It's an easy fix on my side, but for now you've got two immediate solutions:
* Drop your archives in the content folder directly instead of using the web uploader
* Remove the unicode characters from your archives before uploading them (in this case, the ☆ )

**Comment by LawdStalker** [comment]
> * Drop your archives in the content folder directly instead of using the web uploader

Thanks, I went with this approach, because I was trying to add a lot of files and removing all unicode characters would be hard.

But I had an minor issue: When the files are copied directly to the folder the apps detects a few of them and stops detecting midway for some reason. And I need to restart the app for the remaining files to be detected.

**Comment by Difegue** [comment]
Sounds like a file is crashing the background worker, restarting it from the Options menu when this occurs should be enough.
