### ISSUE TITLE
Homebrew 0.9.30 version can't find zh language

### ISSUE THREAD

**Issue by vuhe** [Difegue/LANraragi#1138]
**LRR Version and OS**
0.9.30  homebrew version, on macOS 15.2 (Native)

**Bug Details**
I upgraded to v0.9.30, but it still appears in English and not in Chinese

**Matching Logs**
```
[2024-12-29 16:53:17.44977] [39051] [trace] [-qwJ2uiHJBgt] Detected language: zh
[2024-12-29 16:53:17.45057] [39051] [trace] [-qwJ2uiHJBgt] No handle for language: zh, fallback to en
```

**Screenshots**

**Comment by Difegue** [comment]
Looks like the homebrew version might've forgotten to include the new `locales` folder? I don't build that one so I haven't checked.

**Comment by Difegue** [comment]
Yep, right on the money - I've opened a PR on homebrew to fix this, they should handle it soon. https://github.com/Homebrew/homebrew-core/pull/202813
