### ISSUE TITLE
[Suggestion] Usability Improvements

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#114]
LRR has a very nice web-interface and I've been impressed overall, however there are some QoL changes I'd like to see to make it more usable.

- [ ] Option to scale images to browser Width.
   - [ ] Options to Limit how much an image gets resized e.g don't scale above native image resolution, or limit it to only scaling up by a specified percentage e.g 200%, 300%, 400%
- [x] Retain search terms and page number when returning to the library view after editing a gallery's meta-data or viewing a gallery. (I'd also like to see this working with the browser's back button, I guess the only way to do that would be to change the URL based on the page count and search terms?)
- [x] Delete archive button (with confirmation) in the library view
- [ ] Improve how LRR finds cover images, by e.g trying to find portrait oriented images first, or having certain (specified) filenames be preferred over others e.g "!cover".
- ~~Remove "hover to show tags" and just make it show tags whenever hovering over the gallery. I can see how the tool-tip might accidentally get in the way, so perhaps a 0.5sec hover delay would fix that?~~
- [x] Add view random gallery button to the bottom of page navigation.
- ~~Change the "Disable Automatic Bookmarking" setting to have a (configurable) value of pages you can limit it to. Allowing users to disable automatic bookmarking on galleries with e.g less than 40 images. Change it to 0 to disable it completely, or uncheck the setting to have it be enabled on everything.~~
- [ ] Ability to hide "Series" column from list view
- [ ] Add support for shorthand namespaces in the search field e.g `a:`=`artist:`, `c:`=`character`, `m:`=`male:`, `f:`=`female:`  just like how it's done on E-H.
- [x] Remove name-spaces from the tag column in list-view and color-code them instead (for more space).
  -  Alternatively, just switch to using the shorthand namespaces in the list-view e.g `a:` = `artist:`
- [x] Add a short delay (roughly 0.2sec?) to updating search results. I found making searches in LRR a bit hard as LRR constantly refines it's search results as you type resulting in typo's due to the delay before keys register.
- [ ] In the batch tagger make gallery names link to their meta-data page or add a button.
- [ ] Implement a way to hide galleries which have tags or are not already ticked from the batch-tagger.
When I had a few galleries in my large library missing tags, it was quite hard to find them.
- [ ] Add a way to rename and if possible move gallery archives/folders inside the meta-data page, if moving is too hard simply changing the path the database points to would be enough.
- [ ] (Minor) Option to either hide padding around images, or remove top padding when "hide top-level navigation" is enabled. I know this affects some themes more than others, but it'd be nice to have more of the image shown without needing to scroll down a little. If scale to width is implemented then that should remove the side padding too so the image can take up the full width of the browser.
- [x] Make clicking on a gallery's tag fill the search box with namespace:tag format instead of just the tagname.
- [x] Wrap 'Archive Overview' in some kind of JavaScript onclick action so that opening archive with 500 pages does not cause all 500 pages to be loaded by browser if user is not interested in checking overview. Alternatively paginate overview.
- [ ] Add div with tags on reader.
- [x] Show read pagecount indicator in thumbnail view

**Comment by Difegue** [comment]
Thanks for the detailed breakdown! Github doesn't allow me to comment easily on checklist items, so I went ahead and checked off the ones I don't plan on doing.  

Your first option sounds like what Scale to View already does -- not sure what else you need from it ?

For editing, the easiest solution is to move it to a new window/tab. I'm a personal middle-click abuser so I open most of my stuff in new tabs by default, but I agree it'd make for a better UX.
I'm mixed on the delete button - I don't mind adding it, but I'd like avoiding cluttering the gallery view with icons. An option I could try out is to move save/edit to a custom context menu ala google drive, and add delete there.  

![image](https://user-images.githubusercontent.com/8237712/56986835-2319d600-6b8c-11e9-99a7-beb3317dd47f.png)

I agree that landscape covers showing up atm is a bit weird, but I'm not sure how to improve on that without making the thumbnailing a mess. Cropping landscape thumbnails to fit portrait might work better here.  

I think moving the tag overlay to the entire gallery area is a bad idea as it hinders navigation, and adding hover delay just makes it harder to find out the tag overlay actually exists. I don't think it's that much of a QoL improvement here either. (You get more space to put your mouse over, at the cost of having to wait longer for the overlay to appear)  

I'm not big on duplicating the random button either -- It makes sense on the reader, less so for a button that's usually not used when you already did some scrolling. I could make it a floating button, not sure yet. Giving that one a meh.

For the automatic bookmarking, I kinda see the point (not saving progress on small, 20-page doujins which you're not going to resume most of the time), but it's a lot of extra complexity for both me and end-users whereas you could just click on the first page button.

I'm ok with the rest - not sure if there's a "standard" color code for namespaces somewhere?

**Comment by Asinin3** [comment]
**Image Scaling**
The current "Scale To View makes it fit into the browsers window, what I was trying to suggest was a new option that instead of making sure the image fits completely into the window the smallest dimension (which would be width for 99% of pages) would be scaled to the width of the window. This would mean as a viewer you would just scroll downwards. And for double pages where they have more width than height it would scale the height to the window so you only had to scroll left or right to view the whole image for those pages. 

The second task would expand upon that by adding options to limit that functionality by e.g not allowing it to scale above the original resolution, or not allowing it to scale the width above a certain %. I hope that makes sense. The current implementation is especially not that great for double-pages, you need to turn scale to view on and off all the time or zoom in manually to make the images take up more of your browser.

**Metadata & Delete button**
Fair enough, they aren't huge issues anyway. I think the delete button being added wouldn't be "cluttering the gallery view" much if e.g it didn't show up unless you were logged in with proper privileges though it isn't a huge deal.

**Landscape covers**
I found that there are a number of galleries with images named like 000a. 000b. for the landscape images, maybe just ignoring files with certain names and looking for images with "cover" in the name etc would help without having to check image dimensions is too hard.

**Tags on hover**
Personally I'd find it a lot better having them appear on hovering gallery thumbnails rather than having to hover over the "hover here for tags" then you could remove the "hover here for tags" and it would suddenly free up space for more buttons or perhaps showing the artist or some other info like image count at the bottom. I only suggested adding a delay in-case you thought people would constantly accidentally have the over-lay get in the way. But it's definitely a more subjective thing.

**Random Archive Button**
To me, it just seems a bit silly having to go back to the library page then click on the random gallery button rather than be able to do it directly from the image viewing page. It could just be a small icon at the bottom navigation with a question-mark or something. I don't think it would be in the way.

**Namespace Colors**
This is what HPX uses for Artist, Circle and Parody. IIRC it is a standard because I remember seeing it used elsewhere. I'll do some more digging when I get unbanned from exH for too many page visits lol.
Artist - Hex: #22a7f0 / Red 34 Green 167 Blue 240
Circle - Hex: #36d7b7 / Red 54 Green 215 Blue 183
Parody - Hex: #d2527f / Red 210 Green 82 Blue 127

**Comment by Asinin3** [comment]
I've added some more suggestions at the bottom of the list, would be curious on your thoughts.

**Comment by Difegue** [comment]
Haven't had time to review the new ones until now; Sounds like good QoL improvements to me, I'll try working them in for beta 3 alongside regex searches and the like.

**Comment by AnyByte** [comment]
I would also suggest adding [this](https://stackoverflow.com/a/4407335) to the image container css in reading mode because it gets selected every time I quickly click through pages.

And ideally it would be great to add this on other pages or elements that are not supposed to be highlighted.

**Comment by Jisagi** [comment]
A small idea to extend the "Retain search terms and page number" part, since the total page count has been mentioned ther as well. How about showing the gallery page count (maybe only in thumbnail view). The only way to neatly add this to the list view, might be an extended kinda list view with a double/multi lined list with additional information. The (latter) idea came from e-h (obviously) and their different views.

**Comment by Difegue** [comment]
I've had a few requests for pages read/total count in the survey; For the list view I wager a simple xx/yy number could fit. (likely replacing the New! icon)

**Comment by CirnoT** [comment]
- Have clicking on tag fill search box with namespace:tag format.
- Wrap 'Archive Overview' in some kind of JavaScript onclick action so that opening archive with 500 pages does not cause all 500 pages to be loaded by browser.

**Comment by xXmeme-machineXx** [comment]
Please add sort by date added

**Comment by Difegue** [comment]
Related to #195.

**Comment by wongsaraf** [comment]
Can I asked for a way to changed Lanraragi logs time zone?
I tried to add TZ=mytimezone in my OMV, but it seem doesn't affecting Lanraragi.

**Comment by Difegue** [comment]
The Docker containers are alpine-based and therefore [don't support timezones](https://www.grainger.xyz/timezone-in-docker-alpine-not-using-environment-variable-tz/) by default.  

If this is really a blocker for you please open a new issue so it can be tracked properly! 😀

**Comment by Difegue** [comment]
Closing, see https://github.com/Difegue/LANraragi/issues/274#issuecomment-617350732.  

This issue was growing a bit too messy with multiple comments from different persons anyway -- A lot of it has been tackled so I'd like separate issues for the few remaining improvements. 😃
