### ISSUE TITLE
0.9.30 breaks first archive overview thumbnail

### ISSUE THREAD

**Issue by okaros** [Difegue/LANraragi#1142]
**LRR Version and OS**
LRR Docker 0.9.30

**Bug Details**
In 0.9.30, visiting the any archive's Overview results in the first thumbnail showing the brown "no thumbnail" image, even when all the rest of the thumbnails load fine.  This happens with both already-generated thumbnails and fresh archives that haven't generated thumbnails before., and it occurs with both "normal" and "high-quality" thumbnail modes.  Changing themes does not have any impact either.

Rolling back to 0.9.28 displays the thumbnails correctly.

**Matching Logs**
Even in Debug mode, no errors are generated in any of the logs, and the minion console reports no issues.
(There appear to be no logs whatsoever for overview thumbnails being accessed/generated, but I can see the logs for extracting/accessing the images inside the archive and there are no errors/warnings being reported)

**Comment by Difegue** [comment]
Fixed.  
I've also taken the opportunity to untether page 1 thumbnails from the covers entirely, which fixes the old issue of "when i set a page as thumbnail, it becomes the new page 1 in archive overview".
