### ISSUE TITLE
Arrows in web reader DO NOT work in zh locale

### ISSUE THREAD

**Issue by PalonCheng** [Difegue/LANraragi#1145]
**LRR Version and OS**
docker difegue/lanraragi:latest  v.0.9.30

**Bug Details**
![图片](https://github.com/user-attachments/assets/b0095298-fbbb-4bca-a1b0-828beb4d123b)
the arrows DO NOT work in zh locale

after rm the zh.po and restart the container 
they do work in en locale

**Matching Logs**
In debug mode , there is no error

**Comment by PalonCheng** [comment]
I modify the zh.po
revert the translate for outer-left left right outer-right
it seems like this
"
msgid "Display all images in a vertical view in the same page."
msgstr "在同一页面中以垂直视图显示所有图片。"

msgid "outer-left"
msgstr "outer-left"

msgid "left"
msgstr "left"

msgid "right"
msgstr "right"

msgid "outer-right"
msgstr "outer-right"

msgid "Reader Settings"
msgstr "阅读器设置"
"

and now the arrows work!

maybe these words  are not necessary to translate
they do not show in the browser

and maybe it is handled in /public/js/reader.js (I just find the word "outer-right")
from line 789  Reader.handlePaginator
for the several case
(They are fixed in case)

**Comment by Difegue** [comment]
Yup, that's the issue. Thanks for sleuthing on this!
