### ISSUE TITLE
HDoujin plugin is not working

### ISSUE THREAD

**Issue by ShapeOfBinary** [Difegue/LANraragi#115]
**LRR Version and OS**
Windows 10 x64, latest Vagrant version 0.6.0 Beta 1, VirtualBox 6.0.6

**Bug Details**
I use HDoujin Downloader to download them and it created a info.json in every archive but the activated plugin don't read out the info.json in the zip. An Error raises top left that no info.json is in the zip archive but it is in every.

**Matching Logs**
can't restart with 'vagrant halt' and 'vagrant up' without errors, so i cant enable debug mode -.- 

error after halt and up again here my complete command promt (running as administrator):
https://pastebin.com/CkcAkw8M

I need always readd all my archives, because my database is empty after that. In plugin view logs is only Date Added Plugin displayed.

**Screenshots**
got this message:
![FZFD7qRhCD](https://user-images.githubusercontent.com/38085474/56999924-a699ee00-6bb1-11e9-8134-480fa5c7d1ad.png)

but it is in zip archive:
![1IT5EapTp4](https://user-images.githubusercontent.com/38085474/56999947-b7e2fa80-6bb1-11e9-944c-e7c6c12318a6.png)

**Comment by Difegue** [comment]
You've still got the vbguest plugin installed it seems -- I've dismissed it as being incredibly shitty with newer Vagrant versions(reason number 1 as to why I switched to SMB tbh), as it caused the same setup errors on my test machine.  

Remove it with `vagrant plugin uninstall vagrant-vbguest`, teardown and rebuild your VM(vagrant destroy/vagrant up) and hopefully things should go smoothly.

**Comment by ShapeOfBinary** [comment]
now it restarts without errors but it still don't enable debug mode or bring back my database sadly

**Comment by Difegue** [comment]
Sounds like the database isn't accepting writes for some reason. There might be some errors related to that in the logs even if you're not in debug mode.

**Comment by ShapeOfBinary** [comment]
View Mojolicious Logs: https://pastebin.com/w9znSE0k
View Plugin Logs: https://pastebin.com/tPhKqDKS

**Comment by Difegue** [comment]
huh, looks like a big load of nothing at all. Let's go for something more involved:  

type `vagrant ssh` in a command line
type `docker logs lanraragi` to get the redis&mojo bootup logs. There ought to be something in those.

**Comment by ShapeOfBinary** [comment]
here is the output:
https://transfer.sh/10uGOj/log.txt

**Comment by Difegue** [comment]
The database problem occured with another user, and we found out that running `vagrant provision` between `vagrant halt` and `vagrant up` persisted his database properly. Maybe this will fix your problem as well?  

I'm not seeing anything wrong in that last log either, so I'm chalking this up to a vagrant problem at this point.

**Comment by ShapeOfBinary** [comment]
plugin still does not work but my database is back

**Comment by Difegue** [comment]
Good to know about the database - I'll be amending the Vagrant documentation with the fix for others.  

As for the Hdoujin plugin, well I'm guessing it's either busted or your info.json file is malformed. You should be able to get debug mode logsz now.

**Comment by ShapeOfBinary** [comment]
i have installed now LANraragi on Ubuntu with default linux commands without docker and vagrant and the plugin still not working same error and no log info.

i sended you you an email (the cock.li one) with an test archive with a info.json so u can test it.

**Comment by Difegue** [comment]
Turns out recent changes to the tempfolder functions broke the old code for partial file extraction. That certainly was a headache to debug out. Latest nightlies should work properly for your archive.

**Comment by ShapeOfBinary** [comment]
need i update the vagrant file? vagrant destroy and then vagrant up does not change anything i get still the message: 'No Hdoujin info.json file found in this archive!'

**Comment by Difegue** [comment]
Run `vagrant provision` between destroy and up. Normally you'd have to change the Vagrantfile to target docker nightlies instead of latest, but I accidentally pushed that out with 0.6.0's vagrant update. 👀

**Comment by ShapeOfBinary** [comment]
tested it again with the nightly vagrant file
plugin is not working for me

**Comment by Difegue** [comment]
Looks like you didn't update properly to latest nightlies - you should have more info in debug mode at the very least.

**Comment by ShapeOfBinary** [comment]
==> default: Pulling Docker images...
==> default: -- Image: difegue/lanraragi:nightly
==> default: nightly: Pulling from difegue/lanraragi

vagrant used the nightly,

here are all logs from web view:
https://pastebin.com/y7jxQzHh
https://pastebin.com/6UT99aJJ
https://pastebin.com/A53P61Eg
https://pastebin.com/CvbYtZug

and here is the docker log
https://pastebin.com/Db6E5sRX

**Comment by ShapeOfBinary** [comment]
can't run vagrant provision before vagrant up

error: ==> default: VM is not currently running. Please, first bring it up with `vagrant up` then run this command.

but i found the solution now:
i changed in the Vagrantfile  d.run "difegue/lanraragi", to d.run "difegue/lanraragi:nightly",
and now it seems to work
