### ISSUE TITLE
Certain UTF-8 characters not mapping to Unicode (Windows)

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#117]
Certain characters such are causing the following error to occur in LRR:
`UTF-8 "\x81" does not map to Unicode at /usr/local/share/perl5/site_perl/File/Find/utf8.pm line 191.`
Which prevented me from opening gallery's with these symbols:  ` × `, ` ~ `, `☆`, `／` `｜` and `？`. About 35% of my gallery can't be opened due to this.

When I checked my logs, I had a similar errors for galleries with ` é ` and ` × ` in their name.
`[error] Failed to open '/home/koyomi/lanraragi/content/×2.cbz' at /usr/local/lib/perl5/site_perl/Archive/Peek/Libarchive.pm line 13.`

[tést ×²~.zip](https://github.com/Difegue/LANraragi/files/3135529/test.x.zip)

**Comment by Difegue** [comment]
I'm going to take an educated guess and assume your filesystem is currently not encoded in UTF-8, but in something `similar but not quite there` that maps most japanese characters fine but chokes on some symbols. Your test archive runs fine on my development setups. 

I use File::Find::utf8 when getting the images in an extracted archive to avoid killing myself over archives that have non-ascii characters in their internal hierarchy, but it's sadly no magic bullet.  

I plan to switch this part of the code back to regular File::Find and deal with filenames as they come in straight from the filesystem. It's more work, but hopefully I should finally have a fully encoding-agnostic codebase after this one.

**Comment by Difegue** [comment]
![image](https://user-images.githubusercontent.com/8237712/57185279-8ecfac00-6ec8-11e9-8b74-989409359bc8.png)
