### ISSUE TITLE
Batch Tagging isn't detecting all Untagged Galleries

### ISSUE THREAD

**Issue by LawdStalker** [Difegue/LANraragi#118]
**LRR Version and OS**
LANraragi v.0.6.0 Beta 1
OS: Windows 10 x64 Build 1809
Installation method: WSL Ubuntu 18.04 from source

**Bug Details**
Batch Tagging page doesn't detect all entries where tagging is needed.

In my understanding, it should check/tick all entries that only have the namespaces parsed by LANraragi, but currently  it's only checking those namespaces: _Artist, parody, language, event_ and _group_ 
(According to the Subroutine _LANraragi::Utils::Database::find_untagged_archives_)
When it should check those namespaces: _Artist, parody, language, event, group_ and **series**.
(According to the Subroutine _LANraragi::Utils::Database::parse_name_ )

**Matching Logs**
I don't think it's necessary, but here it is.
```
I[Mojolicious] GET "/batch" (09895203)
[Mojolicious] Routing to controller "LANraragi::Controller::Login" and action "logged_in"
[Mojolicious] Routing to controller "LANraragi::Controller::Batch" and action "index"
[Mojolicious] Rendering template "batch.html.tt2"
[Mojolicious] 200 OK (0.26814s, 3.729/s)
[Mojolicious] GET "/css/webfonts/fa-solid-900.woff2" (febcc3b7)
[Mojolicious] Template "not_found.development.html.tt2" not found
[Mojolicious] Template "not_found.html.tt2" not found
[Mojolicious] Rendering template "mojo/debug.html.ep"
[Mojolicious] 404 Not Found (0.113416s, 8.817/s)
[Mojolicious] GET "/api/untagged" (06aa239b)
^* matches null string many times in regex; marked by <-- HERE in m/^* <-- HERE .+\.(png|jpg|gif|bmp|jpeg|PNG|JPG|GIF|BMP)$/ at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Reader.pm line 109.
[Mojolicious] Routing to controller "LANraragi::Controller::Api" and action "serve_untagged_archivelist"
[Mojolicious] 200 OK (0.348807s, 2.867/s)
```

**Screenshots**
Example of untagged entry unchecked for batch tagging:
![image](https://user-images.githubusercontent.com/50067181/57088010-af84df80-6cd7-11e9-920f-3b8858333a64.png)

**Comment by Difegue** [comment]
oops, I forgot to amend the tagger when I changed default autoparsing behavior from parody: to series:  

Thanks for catching this!
