### ISSUE TITLE
[Vagrant] Empty library after every "vagrant up" until you run "vagrant provision" (doesn't effect first run)

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#119]
Happens with LRR 0.59 & 0.60 Beta1
Using Win10 with Vagrant 2.2.4

Whenever I run `vagrant halt`, then `vagrant up` LRR shows an empty library and all settings are back to their defaults until I run `vagrant provision`. This happens on both fresh installs of 0.59 and after updating to 0.60. While Running `vagrant provision` does "fix" it, you will have to do it every time you want to start vagrant.

**Comment by Difegue** [comment]
I'm just gonna consider vagrant expects people to run `provision` every time to setup the shared folders now. ¯\_(ツ)_/¯
