### ISSUE TITLE
(Minor) Tool-tip for untitled archives has html inside it

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#121]
![firefox_2019-05-05_4884](https://user-images.githubusercontent.com/15137035/57193606-0579b180-6f7c-11e9-827b-937920828d27.jpg)
https://github.com/Difegue/LANraragi/blob/2fdd53ec434f7434055b64b870498c0fb78307eb/lib/Shinobu.pm#L345
Only happens in Thumbnail view.

**Comment by Difegue** [comment]
Yeah that makes sense, the untitled archive thing is a quick database hack that actually drops the html in as-is. I could just use the raw filename instead now tbh.
