### ISSUE TITLE
Temporary folder exceeding specified size limit

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#122]
**LRR: 0.60 Beta1
Windows 10
Vagrant 2.2.4 and WSL are both affected**

![firefox_2019-05-06_4889](https://user-images.githubusercontent.com/15137035/57213487-21399200-7026-11e9-912b-7ad60439daf9.jpg)

**Comment by Difegue** [comment]
Well that's a weird one, I'm assuming the folder/VM really weighs that much and it isn't just a calculation fuckup on my end.

The folder check/cleanup code is triggered through inotify norifications in the background worker - does restarting it trigger a cleanup ?

**Comment by Asinin3** [comment]
Yeah, restarting with `vagrant halt` > `vagrant up` does clean the temporary folder. The temporary folder was only like 80mb before i started to open a bunch of galleries.

**Comment by Difegue** [comment]
I meant restarting the background worker from within the settings page -- A vagrant restart does the same thing essentially, but I'm pretty sure just rebooting the worker would be enough.

**Comment by Asinin3** [comment]
When I restart the worker it still shows the same file-size in the worker and the vbox share (which I assume is where the temp folder is located) is still the same size.

**Comment by Asinin3** [comment]
As an update, restarting the worker after it dies, does clean up the temporary folder. But restarting it when it's still running doesn't seem to.

**Comment by Difegue** [comment]
Is this still a thing under WSL? I'll be closing this as wontfix if it's a Vagrant-only issue.

**Comment by Asinin3** [comment]
Yeah, I edited the OP a few hours ago to indicate that it also happens on WSL. It's easy to reproduce too.

**Comment by Difegue** [comment]
I was able to reproduce it pretty easily on WSL, yeah. Fixed.
