### ISSUE TITLE
[Vagrant] Major 0.60 issue with SMB Shares - Unable to launch LRR after fresh install or restart

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#123]
LRR 0.60 Beta1
Vagrant 2.2.4
Windows 10

Upon making a fresh install of LRR 0.60 (i.e not updating from 0.59 with a `vagrant provision`) vagrant will ask for your username and PW for the SMB share then no matter what you enter, will give the following error and LRR will be unable to start properly.
```
==> default: Preparing SMB shared folders...
    default: You will be asked for the username and password to use for the SMB
    default: folders shortly. Please use the proper username/password of your
    default: account.
    default:
    default: Username:
    default: Password (will be hidden):

Vagrant requires administrator access to create SMB shares and
may request access to complete setup of configured shares.

==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3000 (guest) => 3000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
[default] GuestAdditions 6.0.4 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Mounting SMB shared folders...
    default: F:/Fraps/E/ex => /vagrant
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t cifs -o vers=2.0,credentials=/etc/smb_creds_vgt-639f315e8c788d27e8389981285a0bdb-6ad5fdbcbf2eaa93bd62f92333a2e6e5,uid=1000,gid=1000 //192.168.1.237/vgt-639f315e8c788d27e8389981285a0bdb-6ad5fdbcbf2eaa93bd62f92333a2e6e5 /vagrant

The error output from the last command was:

mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

The only way to ""fix"" it, is to make a fresh install of 0.59, then once LRR has started run `vagrant provision`. But this is only a temporary fix. As the next time you restart your PC it will run into the same error and you'll have to do another fresh install of 0.59 then do another vagrant provision if you want to update it to 0.60 again. (Note: `vagrant halt` is not enough to cause this error, it only completely breaks on full system restarts).

This issue has really took me awhile to figure out what was causing it due to me almost never restarting my PC, but has resulted in a lot of frustration and me destroying my vagrant install 8+ times and deleting my database 4 times in an attempt to fix the issue. If it can't be fixed I hope we move back to using vbox shares.

**Comment by Difegue** [comment]
I'll be reverting the documentation and Vfiles to shared folders for beta 2 -- I got enough negative feedback to convince me that it was a bad move.

**Comment by Difegue** [comment]
Done. Feel free to make PRs to the documentation if details are potentially missing -- At this point I think end-users have way more experience with Vagrant than I do.
