### ISSUE TITLE
Docker deployment messes with file permissions

### ISSUE THREAD

**Issue by Suika** [Difegue/LANraragi#124]
**LRR Version and OS**
docker: difegue/lanraragi@sha256:9d745d82fd6674877b92eb82df1c9f965478ebb19b5bb398ae269b22bc59a3fc

**Bug Details**
Recursive chown/mod in [here](https://github.com/Difegue/LANraragi/blob/dev/tools/DockerSetup/entrypoint.sh#L16-L17) is a no-no.
Even if it's in good faith, the content folder is inside `/home/koyomi/lanraragi`. You are directly messing with user mounted content using root permissions.

If you intend to "step down" from root, it would be more reasonable to run the container as a non-root user and have the ability to modify the uid of the user executing all the things.

**Possible solution**
```
# DOCKER-VERSION 0.3.4
FROM        alpine:latest
LABEL       git="https://github.com/Difegue/LANraragi" 

ENTRYPOINT ["/home/koyomi/lanraragi/tools/DockerSetup/entrypoint.sh"]

#Environment variables overridable by the user on container deployment
ENV LRR_NETWORK http://*:3000

#Default mojo server port
EXPOSE 3000

#Enable UTF-8 (might not do anything extra on alpine tho)
ENV LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8

#Add koyomi user
ARG LRR_USER_ID=9001
ARG LRR_GROUP_ID=9001

ENV LRR_USER_ID=$LRR_USER_ID
ENV LRR_GROUP_ID=$LRR_GROUP_ID

RUN \
  if [ $(getent group ${LRR_GROUP_ID}) ]; then \
    adduser -D -u ${LRR_USER_ID} koyomi; \
  else \
    addgroup -g ${LRR_GROUP_ID} koyomi && \
    adduser -D -u ${LRR_USER_ID} -G koyomi koyomi; \
fi

WORKDIR /home/koyomi/lanraragi

#Copy cpanfile and install script before copying the entire context
#This allows for Docker cache to preserve cpan dependencies
COPY --chown=koyomi:koyomi /tools tools
COPY --chown=koyomi:koyomi /package.json package.json

ENV EV_EXTRA_DEFS -DEV_NO_ATFORK
#Run the install script as root
RUN chmod +x ./tools/DockerSetup/install-everything.sh ./tools/DockerSetup/entrypoint.sh && sh ./tools/DockerSetup/install-everything.sh

#Copy remaining LRR files from context
COPY --chown=koyomi:koyomi / /home/koyomi/lanraragi

#Run container as non-root
USER koyomi
```

Moved a few part a little bit to take full use of cache. If `chmod/own -R` is still needed, then it should be done in Dockerfile. After this, if you adjust the entry point to read the `LRR_USER_ID` and `LRR_GROUP_ID`, and then you modify the uid/gid of the user. Somewhere an alpine issue exists for running and changing the uid of the non-root users.

**Comment by Difegue** [comment]
The recursive chmod is indeed only meant to ensure 755 on the app itself. I kinda forgot about the content folder doing this, and obviously it's not intended behavior.  

Creating the user and switching down to it in the Dockerfile doesn't work as its UID will then be set in stone. As a bunch of users are using the premade containers I build, they wouldn't be able to set their own UID as a replacement without rebuilding the image.

I'm pretty sure just replacing the chown/chmod with the following should be enough: 
```
path_list=$(find /home/koyomi/lanraragi)

for path in $path_list
do
   if test $path != "/home/koyomi/lanraragi/content"
   then
       chown -R koyomi $path
       chmod -R 755 $path
   fi
done
```

**Comment by alexwh** [comment]
You can do `find /dir -not -path /dir/content` instead.
I'd also personally prefer not everything being set to executable, and rx for files(?), too. Perhaps `install` could help here?

**Comment by Suika** [comment]
The linked solution with user-/groupmod id change would be a better solution, in my eyes.

For, if everything is done in Dockerfile, then there is no need to do any chmod/-own'ing. 
And you will have a consistent image that has all the right permissions.

Done in right order, the caching will not be disturbed and the one thing that will be edited post-build, is the uid/gid.

That way this can be consolidated into a single line with your default permissions.
```
ARG LRR_USER_ID=9001
ARG LRR_GROUP_ID=9001

ENV LRR_USER_ID=$LRR_USER_ID
ENV LRR_GROUP_ID=$LRR_GROUP_ID

RUN \
  if [ $(getent group ${LRR_GROUP_ID}) ]; then \
    adduser -D -u ${LRR_USER_ID} koyomi; \
  else \
    addgroup -g ${LRR_GROUP_ID} koyomi && \
    adduser -D -u ${LRR_USER_ID} -G koyomi koyomi; \
fi
```

**Either your or mine solution is fine, as long as the user data is not touched needlessly.**

**Comment by Difegue** [comment]
Went for a hybrid approach in the end; I used most of your dockerfile improvements but kept the final entrypoint running as root to keep a bit of potential leeway if I need to make further changes down the road.  

The recursive chmods aren't necessary to run the app, so I took them out and simply left a 744 on the main folder itself, which seems to be needed by supervisord.
