### ISSUE TITLE
Eze plugin can't find info.json file after gallery has already been added to the database

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#126]
**LRR 0.60 Beta1
Windows 10
Vagrant 2.2.4**
I've been manually adding info.json files to archives that were missing them, and when I go to run the eze plugin on the gallery it always says it can't find the info.json file even though it's there. Cleaning temporary folder and JSON cache didn't help. LRR can find the json file properly when the gallery is first added to the library (if it's there). But if I add the json file to the archive's .zip after the gallery's already in LRR's library it won't be able to find the json file even when doing a manual check.

**Comment by Difegue** [comment]
Pretty sure this is the same problem as #115 . Can you try nightlies?

**Comment by Asinin3** [comment]
How do you get the nightlies with vagrant?

**Comment by Asinin3** [comment]
I downloaded the nightly vagrant file and its still the same, though the settings page still says I'm on beta1, so I'm not entirely sure I'm on the nightly build. Especially when I'm still getting https://github.com/Difegue/LANraragi/issues/117 which should be fixed in nightly builds right?
