### ISSUE TITLE
Eze plugin doesn't work if the info.json file is in a sub-folder

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#127]
**LRR 0.60 Nightly
Windows 10
Vagrant**
So I have `info.json` files in sub-folders because I archived all my folders into .zips, but LRR can't find the json file unless it's in the root of the archive. ~~I also have json files (downloaded with the sadtorrent extension) with gallery names in the json filename e.g `GALLERY_NAME.info.json` which don't get detected. Even `a.info.json` doesn't work.~~

**Comment by Difegue** [comment]
Pretty sure subfolders should work seamlessly with the current code, I'll look at it. 

Modified names are a wontfix though, I won't try guessing what is a eze json and what isn't.

**Comment by Asinin3** [comment]
Subfolders work seamlessly with images and being detected as galleries, it's just the eze plugin not working with them. And yeah, don't worry about the other issue, it's not that important anyway.
