### ISSUE TITLE
Eze plugin can't read files with latin or superscript characters like é or ³

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#129]
LRR 0.60 Nightly
Vagrant 2.2.4
While this gallery does open just fine if I want to view it normally, if I try to run the eze plugin on it I get this error:
`Failed to open '/home/koyomi/lanraragi/content/éÂ³.cbz' at /usr/local/lib/perl5/site_perl/Archive/Peek/Libarchive.pm line 28.`

**Comment by Difegue** [comment]
A bunch of old code was still trying to utf8-decode filenames, leading to those issues.  
This should fix the problems with thumbnail generation too!

**Comment by Asinin3** [comment]
Confirmed fixed 👍
