### ISSUE TITLE
Metadata plugins failed when archive names contains apostrophe

### ISSUE THREAD

**Issue by rucciva** [Difegue/LANraragi#142]
**LRR Version and OS**
v.0.6.0-BETA.2 docker

**Bug Details**
When the archive names contains apostrophe, the plugin failed to fetch the metadata from associated sites. 

**Matching Logs**
-

**Screenshots**
-

**Comment by Difegue** [comment]
Can't reproduce. Do you have error logs on hand from the culprit plugin?

**Comment by rucciva** [comment]
It just say 'no matching gallery found'.

Oh i might have forgotten to say that this is done when no url is specified. When url is manually specified.

**Comment by Difegue** [comment]
Guessing this is because of the search url we build from the title. Do you have a gallery URL on hand I can use to test?

**Comment by rucciva** [comment]
[here](https://nh*****.net/g/228990/)

**Comment by Difegue** [comment]
Should be good now. The nH plugin is pretty fickle since it only does text search, I recommend you try using e-h for most stuff these days.
