### ISSUE TITLE
LANraragi start loop

### ISSUE THREAD

**Issue by Nekomare** [Difegue/LANraragi#143]
At W10, ver1903
Using 0.6.0 beta 2 windows installer

After installing i got prompt for first time set up, i set the folder and ticked both options to start with windows and start server automatically however that wouldn't work and LANraragi just had question marks instead of it is running so i tried to uninstall and install clean again.
Nevertheless after fresh install and trying to start LANraragi would prompt me that it is starting automatically and disappear without anything starting.
Reinstalling would do the same result.
can't provide any logs unfortunately.

**Comment by Difegue** [comment]
Sounds related to #144.

**Comment by Nekomare** [comment]
fixed it
