### ISSUE TITLE
[Karen] Crash when clicking start

### ISSUE THREAD

**Issue by LordZero25** [Difegue/LANraragi#144]
**LRR Version and OS**
**OS**: Win 10 v1903
**Installation**: [v.0.6.0-BETA.2](https://github.com/Difegue/LANraragi/releases/download/v.0.6.0-BETA.2/LANraragi_Windows_Installer.zip)

**Bug Details**
It just crashes upon clicking _**Start**_

**Matching Logs**
I would like to provide any info but my only clue is the screenshot.

**Screenshots**
[Screenshot](https://i.postimg.cc/MHC1NXr7/Untitled.jpg)

**Comment by Difegue** [comment]
The question marks basically mean you have an installed WSL distro, and yet trying to run programs/commands against it fails.  

Try opening up a Windows terminal: Can you enter the WSL distro using the `wsl.exe -d lanraragi` command? And when in there, can you run the following command: `perl -pe "last if $. > 10" /home/koyomi/lanraragi/lrr.conf` to display the contents of the configuration file?

**Comment by tangbat** [comment]
Experiencing the same problem.
`wsl.exe -d lanraragi` command doesn't do anything.

![image](https://user-images.githubusercontent.com/22623827/62002602-3ae5f500-b0bc-11e9-86d5-3a80c3bc0a80.png)

**Comment by LordZero25** [comment]
Same result as @tangbat

**Comment by Difegue** [comment]
This is looking more and more like a WSL bug; I'd suggest opening an issue [on their own tracker](https://github.com/microsoft/WSL/issues) if you're feeling up to it.  

If you don't, I'll likely do it myself, but I'd need the detailed WSL logs you can get by following the instructions [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by LordZero25** [comment]
The output was not a text file so i can't read it. I don't what to report to WSL. If you don't mind I'll leave it to you.

[lxcore.zip](https://github.com/Difegue/LANraragi/files/3440170/lxcore.zip)

**Comment by Difegue** [comment]
Yeah, the Windows Performance Analyzer is needed to read .etl files.  
I'll try to get a bug report written soon, thanks!

**Comment by Difegue** [comment]
Shower thought: Do you get a different output by executing `wsl.exe -d lanraragi /bin/sh` ?

**Comment by LordZero25** [comment]
Still does nothing.

**Comment by Difegue** [comment]
For info, I've opened up an issue on WSL here: https://github.com/microsoft/WSL/issues/4361#issuecomment-517128243

**Comment by Difegue** [comment]
Well, it got closed. I guess they're not super interested in debugging issues with custom distros, which is understandable.  

I'll be reworking the way the Windows zips are built soon(ish) to make them a bit cleaner thanks to Actions v2, so maybe that'll fix your issues alongside it.

**Comment by Difegue** [comment]
That soon(ish) took a bit longer than planned, but I think the new Windows builds should fix this problem. Distro installation is sturdier and WSL has progressed quite a bit too since then.
