### ISSUE TITLE
[Suggestion] API: Backup Route

### ISSUE THREAD

**Issue by Jisagi** [Difegue/LANraragi#146]
Would it be possible to add an API route for creating (and restoring) backups? When creating, one could maybe select to either get the full backup as json response, or just start the creation task wihtout a json response and use the already created `backup.json` inside the lanraragi content folder. The idea is to be able to easily automate database backups

**Comment by Difegue** [comment]
I've been going through the survey results and I got a few suggestions about automated/rolling backups; API-fying the current backup system would probably make those people happy as well as they could automate their own schemas.
