### ISSUE TITLE
[Suggestion] Gallery Favorites

### ISSUE THREAD

**Issue by sleet556** [Difegue/LANraragi#147]
I think Gallery Favorite feature (Or collection?) would be great.

Like E-H, I want to organize my galleries with favorite feature.
(vanila goes to favorite 1, One-shota goes to favorite 2...)

Thanks for your great job.

**Comment by Difegue** [comment]
I've explained this in a bit more detail [here](https://tvc-16.science/lrr-survey.html), but you should use the favorite tags feature as a replacement in LRR.  

Archive sets might fit your workflow better whenever I get to implementing them.
