### ISSUE TITLE
Shinobu.pm using 100% CPU (single core)

### ISSUE THREAD

**Issue by CirnoT** [Difegue/LANraragi#148]
**LRR Version and OS**
LRR from master branch from git as of date of writing this bug report.
`Linux riko 5.0.18-1-pve #1 SMP PVE 5.0.18-1 (Wed, 24 Jul 2019 08:13:30 +0200) x86_64`
Ubuntu 18.04.2 LTS running in LXC container with `/db` directory exposed via mount point to local directory on host.

**Bug Details**
~Shinobu registers for all possibly inotify events and keeps handle on files when browsing or viewing archives which causes infinite loop of inotify event 1 (IN_ACCESS) to be sent to Shinobu.pm to be handled in `inotifysub`. This consumes 100% of single thread and causes unneeded load on machine running LRR. This COULD be an issue with LXC mountpoint, however I don't have time to verify this further. Note that this seems to happen only when opening reader or going to any page other than first. I am able to reproduce it across multiple restarts of Shinobu worker as well as both container and host reboot. Nothing else on host is accessing this directory and no other container has access to it. My proposed solution would be to change `IN_ALL_EVENTS` to `IN_MOVED_TO | IN_DELETE | IN_CREATE`. This situation does not end even when there is no user activity for long period of time, as seen on this screenshot https://u.gensokyo.re/d/7Aro3O68 showing CPU usage. Since around 1:30 AM there was absolutely no user activity or access to LRR instance yet the load continued until Shinobu was restarted.~
(see post below)

**Matching Logs**
n/a

**Screenshots**
https://u.gensokyo.re/d/sYYp9wCk

**Comment by CirnoT** [comment]
Okay, I have found the issue. Please disregard my rambling above, it was not an issue at all. After firing up Perl debugger I was able to narrow the issue to temp cleaning and recent commit https://github.com/Difegue/LANraragi/commit/df7a1a595c372ac566eaa0e4a4b9e10a8a60291c that changed it's behavior. It seems that whenever temp folder is touched an insane amount of events is generated and when it's size is big (mine is over 1 GiB) the size calculation eats CPU cycles as well as produces some unneeded I/O activity trying to re-calculate temp folder size countless of times. That being said, I still propose to change to `IN_MOVED_TO | IN_DELETE | IN_CREATE` for watching directories as these are the only events that Shinobu actually acts upon and there is no need for her to handle others being shoved into her only to be ignored as it is generates additional overhead in CPU cycles as well as context switches.

As for the actual issue - for now I've personally opted to use 'IN_MOVED_TO | IN_DELETE | IN_CREATE' for temp too, but I think changing it to being called every 15 minutes or so is better solution instead of relying on inotify there.

**Comment by Difegue** [comment]
Right, I specifically remember changing it to ALL_EVENTS in order to work around WSL's poor inotify support. I didn't think it would cause issues on other systems, but large enough temp folder sizes can certainly cause it to go haywire on Linuxes that properly implement inotify.  
I'll likely switch this up to `IN_MOVED_TO | IN_DELETE | IN_CREATE` with an extra check for WSL using `uname` or something.  

A 15-minute timer for temp cleaning only would be a good solution, but I aim to keep the Shinobu module from becoming any more complex than it already is, so keeping the folder cleanup inside the inotify event listener is simpler for now.  
Maybe in the future when I get rid of the JSON cache concept and refactor the .pm a bit.

**Comment by Difegue** [comment]
Turns out `IN_MOVED_TO | IN_DELETE | IN_CREATE` is also more than enough on the latest WSL, so that makes my life easier.

**Comment by CirnoT** [comment]
The same should apply to watching archive directories, since Shinobu is not acting on any of the other events anyway.
