### ISSUE TITLE
A new plugin metadata suggestions

### ISSUE THREAD

**Issue by elakwmq1** [Difegue/LANraragi#151]
Hi i using "koromo copy"(hitomi manga downloader) program.
this program can save gallery metadata for made json file.
but LRR not support this json file.
I have so many files that it is hard to query with ehenti metadata plugin
can you add plugin with "koromo copy"s json file?
i can give json files if you want. thx

koromo copy github: https://github.com/dc-koromo/koromo-copy/issues
i attach info.txt(metadata file)
[Info.txt](https://github.com/Difegue/LANraragi/files/3445113/Info.txt)

**Comment by Difegue** [comment]
I recommend you look at the [Eze](https://github.com/Difegue/LANraragi/blob/dev/lib/LANraragi/Plugin/Eze.pm) plugin, who also imports json files, and try to modify it to suit your needs.  

Sadly, I can't really implement the billion different metadata json formats that exist out there.

**Comment by Difegue** [comment]
Closed by #214. Great stuff!
