### ISSUE TITLE
Using Batch Tagging on massive amount of archives always fails in Code 1006

### ISSUE THREAD

**Issue by Bireechi** [Difegue/LANraragi#153]
Hello,

I have around 47000 archives, and im trying to Batch Tag them, but around when it gets to around 300-500, it always crashes with the Code 1006, for example

```
Plugin error while processing ID 79cd567171bae6e8ddc90ed0b9f20771db724941(No matching nHentai Gallery Found!)
************
(code 1006)
```

Sorry if this has already been answered somewhere, i tried to look through the Issue list.

Also, many thanks to you for the whole program!

**Comment by Difegue** [comment]
Hmm, that's a new one. Code 1006 is a [reserved error code](https://stackoverflow.com/a/19305172) meaning that the browser shut down the websocket connection on its own.  

You should probably look in your browser's developer tools for additional output in this case; Trying a different browser might also be a solution.

**Comment by Bireechi** [comment]
Yeah, the thumbnail generation takes quite a while, i was wondering if there is anyway to cache all the thumbnails? I have TB:s of space left so there is no problem on that front.

Btw, huge huge thanks for making this, ill be sure to remember you with multiple cups of coffee once i get everything up and running well. 👍

**Comment by Difegue** [comment]
I'm looking up #145 and will have a fix out ASAP; It's really weird that the bug came back considering the nuclear option I use for unicode folders, but well shit happens. ¯\_(ツ)_/¯  

Thumbnails are cached in your content folder once generated.

**Comment by Bireechi** [comment]
Now im getting an error code

2019-08-01 21:21:53,012 DEBG 'lanraragi' stdout output:
[Batch Tagging] [info] Client disconnected, halting remaining operations
[Batch Tagging] [info] Client connected to Batch Tagging service

No matter what browser i use, this happens, though edge can get up to 900, best fo far, just gonna be slow restarting it every once in a while ¯\(ツ)/¯

**Comment by Difegue** [comment]
Yeah, the error just means the browser shut down the connection on its own.  
It's certainly not a server-side issue; I guess browsers shut down websocket connections past a certain amount of data transferred?

**Comment by Bireechi** [comment]
Now i cannot use the Batch tagging at all, even tried updating to the latest Windows-nightlies, immedietly after starting the tagging, it gives out

Started Batch Tagging operation...
************
************
(code 1009)

Doesn't matter which brower, and nothing in the logs or windows log window.

**Comment by Difegue** [comment]
This error code is `1009 – the message is too big to process`.  
I don't have any leads on that atm.

**Comment by Bireechi** [comment]
Could it be that some of the file names are too long for it to handle?

**Comment by Difegue** [comment]
Looking back at the batch tagging code, the list of archives to tag is sent as a single message when starting the session.  

I'm guessing you have too many archives checked, making the message too big. Do you still get the error when checking a few files only?

**Comment by Bireechi** [comment]
Nope, when i select only a few, it goes without problems. Next problem is that i need to manually click every box, is there a way to select multiple?

**Comment by Difegue** [comment]
Save for the select all button, not currently. I guess you could run some quick javascript to check the first X checkboxes:  

~~~~
var els = $('input');
for (var i = 0; i < 2000; i++) {
    els[i].checked = true;
}
~~~~

Replacing 0 and 2000 as you go. It's absolutely not optimal, but you should be able to proceed with that for the time being.

**Comment by Bireechi** [comment]
Thank you so much, since its crashing around the 900 mark im doing it in batches anyway, atleast now i can progress! Thanks again! 👍

**Comment by Difegue** [comment]
I've updated batch tagging to no longer rely on a single big message and go back-and-forth with the browser instead. This should allow for a basically infinite amount of archives checked.

**Comment by itsalwaysyou** [comment]
Have this issue(code 1006) on 0.9.5 on windows 11 using Zen browser(FF fork). Works fine with Chrome like your original suggestion. 

Non-issue, but just wanted to put this out there in case someone else needs it

**Comment by bossanovaorca** [comment]
I'm also seeing this issue exclusively on Firefox
