### ISSUE TITLE
Adding or Editing an archive wont show up/show changes before restarting the server.

### ISSUE THREAD

**Issue by Bireechi** [Difegue/LANraragi#154]
Hello again,

Its pretty much the same problem as issue #110 , but im not using docker since i couldnt get it to work (See issue #152 )

Im adding around 1000 archives per restart, im afraid i will break the DB if i restart the server before its done adding the archives. (Going at 49k atm, 62k left to add.)

**Comment by Difegue** [comment]
What are you using then? Sorry I couldn't reply to #110 earlier, it's been pretty hard keeping up with the influx of new users.  

Server restarts shouldn't break the database, as it's not table-based and saves to disk after data entry.

**Comment by Bireechi** [comment]
Im using the nightywindows version.

**Comment by Difegue** [comment]
Woops, didn't reference the correct issue up here.  

#110 only referred to uploads made through the web uploader, so this is a different issue.  

It's more of an enhancement though: Currently, no JSON cache is built until all files have been accounted for and added to the database. This works well for incremental uploads, but not so much when you suddenly drop 100.000 files in the content folder.  

A few versions ago I had something in place to build a cache every 50 or so files processed, but dropped it when I introduced the filemap concept.

**Comment by Difegue** [comment]
Much like #120, this is resolved by the JSON cache being essentially gone.  
The search cache replacing it is built from the database on-demand, and busted as soon as something changes on the database side.
