### ISSUE TITLE
Provided Docker images are x86 only and lack an ARM variant for Raspberry Pis

### ISSUE THREAD

**Issue by EfronC** [Difegue/LANraragi#161]
**LRR Version and OS**
Hardware information:

- Operating System: Raspbian GNU/Linux 8 (jessie)
- Kernel: Linux 4.4.11-v7+
- Architecture: arm

LANraragi: Docker version, difegue/lanraragi:latest

**Bug Details**
When installing LANraragi with Docker on a Raspberry, launches exec format error, which supposedly is because the docker image does not match the Architecture, but i'm not sure how to change this.

**Matching Logs**
Unable to find image 'difegue/lanraragi:latest' locally
latest: Pulling from difegue/lanraragi
e7c96db7181b: Pull complete 
5f40aa2f35d2: Pull complete 
d34e170d6805: Pull complete 
daab9fc0a114: Pull complete 
626d3071e606: Pull complete 
2a0b42f37dc2: Pull complete 
863c32440ba8: Pull complete 
4f1ed5be35fc: Pull complete 
Digest: sha256:f5847ae888d53c604e1e6fa03947ca23af23931faaa77f4d68cb66fd539ffe74
Status: Downloaded newer image for difegue/lanraragi:latest
standard_init_linux.go:190: exec user process caused "exec format error"

**Screenshots**

**Comment by UnixNight** [comment]
This also happens when running Ubuntu Server on a Raspberry Pi. I am currently seeing this on a Pi 3B+

`ubuntu@ubuntu:~$ sudo docker run --name=lanraragi -p 3000:3000 --mount type=bind,source=/home/ubuntu/content,target=/home/koyomi/lanraragi/content difegue/lanraragi
standard_init_linux.go:190: exec user process caused "exec format error"`

**Comment by Difegue** [comment]
You need to build the Docker image yourself for now using the Dockerfile in the repo, as the images from the hub don't have an ARM variant.

**Comment by EfronC** [comment]
Could you give a little help in how to build(which command and where) the image? I tried `sudo docker build -t lanraragi .`, but launched the error `COPY failed: stat /var/lib/docker/tmp/docker-builder419359094/tools: no such file or directory` on `Step 11/16 : COPY --chown=koyomi:koyomi /tools tools`, i've been trying to investigate a little of what could be the cause, but seems to be many according to [this](https://github.com/docker/for-mac/issues/1922) that i think it would be better if i first tried to reproduce the way you build it.

**Comment by Difegue** [comment]
I see this is an issue for Docker for mac, which won't give you an ARM-compatible container since it's running on an x86 machine.  

What should work is running the following on your RPi itself:  

~~~~
git clone https://github.com/Difegue/LANraragi.git
cd lanraragi
docker build -t difegue/lanraragi -f ./tools/DockerSetup/Dockerfile .
~~~~

**Comment by EfronC** [comment]
I'm not sure why did you edit your answer, but `docker build -t difegue/lanraragi -f ./tools/DockerSetup/Dockerfile .` worked, i just got a few errors during build
`
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.10/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.00740ba1.tar.gz: No such file or directory
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.10/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.d8b2a6f4.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  shadow (missing):
    required by: world[shadow]
  su-exec (missing):
    required by: world[su-exec]
  supervisor (missing):
    required by: world[supervisor]
./tools/DockerSetup/install-everything.sh: line 10: curl: not found
./tools/DockerSetup/install-everything.sh: line 10: perl: not found
./tools/DockerSetup/install-everything.sh: line 14: cpanm: not found
./tools/DockerSetup/install-everything.sh: line 17: cpanm: not found
./tools/DockerSetup/install-everything.sh: line 18: npm: not found
WARNING: Ignoring APKINDEX.00740ba1.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.d8b2a6f4.tar.gz: No such file or directory
`
But still got to 
`
Successfully built 68b5f8d02106
Successfully tagged difegue/lanraragi:latest
`

Tried using `docker run --name=lanraragi -p 3000:3000 --mount type=bind,source='/media/pi/Western Digital Blue/Expansion/LANraragi/Media',target=/home/koyomi/lanraragi/content difegue/lanraragi -e LRR_UID=``id -u $USER`` -e LRR_GID=``id -g $USER`` difegue/lanraragi` to run the image and got 
`
Starting LANraragi with UID/GID : 9001/9001
/home/koyomi/lanraragi/tools/DockerSetup/entrypoint.sh: line 10: usermod: not found
/home/koyomi/lanraragi/tools/DockerSetup/entrypoint.sh: line 11: groupmod: not found
/home/koyomi/lanraragi/tools/DockerSetup/entrypoint.sh: exec: line 20: su-exec: not found
`
Do i need another parameter? BTW I'm running all the commands as root.

**Comment by Difegue** [comment]
Oh, I edited it because it seemed like you already had the Dockerfile setup, in which case you didn't need to clone the entire repository.  

Looks like the alpine package repository wasn't able to download some of the required packages.  
You might want to try again later.

**Comment by EfronC** [comment]
Ok, before trying again, do i need to delete the difegue/lanraragi and alpine images?

**Comment by Difegue** [comment]
A rebuild should delete them on its own.

**Comment by EfronC** [comment]
Ok, new update.

Retried the build, didn't work, so i choose to search a little if the fetch url had any or anything, but i ended up finding that a possible cause for this problem was a problem with Docker, so i restarted with `sudo systemctl restart docker` and it worked, now didn't launch any error.

Then, to check if everything was correct, i started the Docker with `docker run --name=lanraragi -p 3000:3000 --mount type=bind,source='/media/pi/Western Digital Blue/Expansion/LANraragi/Media',target=/home/koyomi/lanraragi/content difegue/lanraragi -e LRR_UID=``id -u $USER`` -e LRR_GID=``id -g $USER`` difegue/lanraragi` again, but it started to launch this log over and over (From the (ﾟ∀ﾟ) face, it started to launch over and over, i understand is because it was retrying).

_Starting LANraragi with UID/GID : 9001/9001
usermod: no changes
2019-08-03 19:01:21,574 INFO supervisord started with pid 1
2019-08-03 19:01:22,582 INFO spawned: 'lanraragi' with pid 13
2019-08-03 19:01:22,592 INFO spawned: 'redis' with pid 14
2019-08-03 19:01:22,661 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 1984339280 for <Subprocess at 1984336680 with name redis in state STARTING> (stdout)>
2019-08-03 19:01:22,662 DEBG fd 14 closed, stopped monitoring <POutputDispatcher at 1984339920 for <Subprocess at 1984336680 with name redis in state STARTING> (stderr)>
2019-08-03 19:01:22,663 INFO exited: redis (exit status 1; not expected)
2019-08-03 19:01:22,665 DEBG received SIGCHLD indicating a child quit
2019-08-03 19:01:23,667 INFO success: lanraragi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-03 19:01:23,674 INFO spawned: 'redis' with pid 15
2019-08-03 19:01:23,741 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 1984339920 for <Subprocess at 1984336680 with name redis in state STARTING> (stdout)>
2019-08-03 19:01:23,743 DEBG fd 14 closed, stopped monitoring <POutputDispatcher at 1984339800 for <Subprocess at 1984336680 with name redis in state STARTING> (stderr)>
2019-08-03 19:01:23,745 INFO exited: redis (exit status 1; not expected)
2019-08-03 19:01:23,747 DEBG received SIGCHLD indicating a child quit
2019-08-03 19:01:24,165 DEBG 'lanraragi' stderr output:
Attempting to create directory /home/koyomi/perl5

2019-08-03 19:01:25,724 DEBG 'lanraragi' stderr output:
^* matches null string many times in regex; marked by <-- HERE in m/^* <-- HERE .+\.(png|jpg|gif|bmp|jpeg|webp|PNG|JPG|GIF|BMP|JPEG|WEBP)$/ at /home/koyomi/lanraragi/script/../lib/LANraragi/Utils/Generic.pm line 34.

2019-08-03 19:01:26,733 INFO spawned: 'redis' with pid 16
2019-08-03 19:01:26,792 DEBG fd 14 closed, stopped monitoring <POutputDispatcher at 1983901744 for <Subprocess at 1984336680 with name redis in state STARTING> (stderr)>
2019-08-03 19:01:26,795 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 1984339800 for <Subprocess at 1984336680 with name redis in state STARTING> (stdout)>
2019-08-03 19:01:26,796 INFO exited: redis (exit status 1; not expected)
2019-08-03 19:01:26,797 DEBG received SIGCHLD indicating a child quit
2019-08-03 19:01:29,137 DEBG 'lanraragi' stderr output:
Could not connect to Redis server at 127.0.0.1:6379: Connection refused at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Config.pm line 38.
	...propagated at /usr/local/share/perl5/site_perl/Redis.pm line 613.

2019-08-03 19:01:29,143 DEBG 'lanraragi' stdout output:


ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!!!!!

2019-08-03 19:01:29,174 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 1984339720 for <Subprocess at 1984315024 with name lanraragi in state RUNNING> (stderr)>
2019-08-03 19:01:29,175 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 1984336480 for <Subprocess at 1984315024 with name lanraragi in state RUNNING> (stdout)>
2019-08-03 19:01:29,175 INFO exited: lanraragi (exit status 111; not expected)
2019-08-03 19:01:29,176 DEBG received SIGCHLD indicating a child quit
2019-08-03 19:01:30,186 INFO spawned: 'lanraragi' with pid 17
2019-08-03 19:01:30,199 INFO spawned: 'redis' with pid 18
2019-08-03 19:01:30,295 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 1984339720 for <Subprocess at 1984336680 with name redis in state STARTING> (stdout)>
2019-08-03 19:01:30,297 DEBG fd 15 closed, stopped monitoring <POutputDispatcher at 1983901744 for <Subprocess at 1984336680 with name redis in state STARTING> (stderr)>
2019-08-03 19:01:30,299 INFO exited: redis (exit status 1; not expected)
2019-08-03 19:01:30,301 DEBG received SIGCHLD indicating a child quit
2019-08-03 19:01:31,304 INFO success: lanraragi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-03 19:01:31,306 INFO gave up: redis entered FATAL state, too many start retries too quickly
2019-08-03 19:01:33,236 DEBG 'lanraragi' stderr output:
^* matches null string many times in regex; marked by <-- HERE in m/^* <-- HERE .+\.(png|jpg|gif|bmp|jpeg|webp|PNG|JPG|GIF|BMP|JPEG|WEBP)$/ at /home/koyomi/lanraragi/script/../lib/LANraragi/Utils/Generic.pm line 34._

And in localhost:3000 launches _Message Corrupt_

**Comment by Difegue** [comment]
Looks like redis can't start. Maybe something else is hogging port 6379?

**Comment by EfronC** [comment]
Not that i'm aware of

![rpi](https://user-images.githubusercontent.com/5926318/62417496-d6281e80-b616-11e9-9ea2-09895d0cde5b.png)

**Comment by EfronC** [comment]
Ok, found the problem, seems like, when i started the docker, i used source='/media/pi/Western Digital Blue/Expansion/LANraragi/Media' because i want an External Drive to be the place where all the content is storaged, but seems like redis is nit able to recognize that path, i changed it to a local path /home/pi/Extras, and it started correctly

![rpi](https://user-images.githubusercontent.com/5926318/62417657-b692f500-b61a-11e9-85f1-0c74f1b1f948.png)

Any option to have an External Drive as the source?

**Comment by UnixNight** [comment]
Is the drive up?

**Comment by EfronC** [comment]
Yes

![rpi](https://user-images.githubusercontent.com/5926318/62417855-84849180-b620-11e9-8326-2287ac38f5e8.png)

**Comment by Difegue** [comment]
It's a bit of a bad hack, but you can probably just symlink your drive to a folder on your SD card and it'll work.  

As to why the redis server inside the image can't access the mounted drive, I haven't the foggiest.

**Comment by EfronC** [comment]
Actually, i already tried the Symlink, i linked my External Drive folder to Extras folder with `sudo ln -s '/media/pi/Western Digital Blue/Expansion/LANraragi/Media' '/home/pi/Extras'` but doesn't work, the test rar i have there doesn't appear on LANraragi, but i can see it on Extras folder.

Another note is that, when i open the Admin settings on the web view, in Archive Directory appears '/home/koyomi/lanraragi/content' which is not where the content should be, Could this be related?

**Comment by Difegue** [comment]
That's normal, the content folder is mapped on the docker command: `source='/media/pi/Western Digital Blue/Expansion/LANraragi/Media',target=/home/koyomi/lanraragi/content` in your example above.  

What do you get if you try uploading a file through the web interface?

**Comment by EfronC** [comment]
Nothing

![Screenshot (2)](https://user-images.githubusercontent.com/5926318/62418051-a2082a00-b625-11e9-985d-0b7530b814fa.png)

![Screenshot (3)](https://user-images.githubusercontent.com/5926318/62418053-a896a180-b625-11e9-9911-fb0d1bd44bbc.png)

And they're not on neither /media/pi/Western Digital Blue/Expansion/LANraragi/Media, nor /home/pi/Extras, nor a folder called content is on /home/koyomi/lanraragi

**Comment by colin969** [comment]
If your issue is in spaces in the mount point then just change the mount point. I'm running it through a pi also with an external WD drive, so it will work with enough nudges.

Redis did like to stop launching for a while (I shut off lanraragi then unmount myself before a shutdown now) but that fixed itself when running Redis myself with the included config. 

`docker exec -it lanraragi redis-server /home/koyomi/lanraragi/tools/DockerSetup/redis.conf` should work. If it launches successfully then stop and start the container.

**Comment by EfronC** [comment]
Ok, not sure if this has anything to do with my problem, but something i made caused to start appearing this
![err](https://user-images.githubusercontent.com/5926318/62484582-1951d100-b780-11e9-8044-088e8e795ec1.png)

First time it appeared, i just clicked to refresh the cache, and solved the problem, but since the second time, this has been appearing, and don't understand how to solve it.

Basically things i've done are:

First, since after running the docker run command the console was being used as the log of the same, i needed to do ctrl-c to then use the docker stop command, i think one of the times i did this caused the problem for the first time(Do i need to use the & with the command so i can use the other commands to restart, or is it neccesary to kill the run command to do the stop - start?).

Second, and i think this caused the error, was when i tried to upload one Doujin from the D&D view, because that Doujin didn't marked that finished uploading, instead just stopped the bar almost at half, and then, when i re started the app, it started marking this, and this time, doesn't matter how many times i try to refresh the cache, it doesn't solve it.

Is there a way to restore the DB? Doesn't have anything, so i don't care about data lose at this moment.

**Comment by EfronC** [comment]
Just in case someone is followinf this topic, the problem with the database somewhat solved itself, or at least i'm not sure what made it work. 

There are 2 things i did: The first one was to clear space unistalling things from my RPi, so i went from 50 MB, to 1.7 GB, not sure if somewhat i uninstalled, or if extra space maybe helped. The second one was to change the source folder from /home/pi/Extras to /home/pi/Pass (An empty folder), this one has more chances from being the problem, because maybe the dissapearence of files, or the symbolic link i made, was what affected the DB, by changing to a new folder, it builded again the filemap and the JSON, which made things work again.

Now i still need to make the program work with my EHDD, but at least is one problem less.

**Comment by Difegue** [comment]
It seems Github Actions just went nuclear and added cross-platform VM support without constraints, so I'll probably be able to add automated ARM builds soon(ish).

**Comment by EfronC** [comment]
Then, i think i'll wait for your version, since i couldn't make it work, and now i fucked up everything, meanwhile i'm making a python version of the reader just to wait.

**Comment by Difegue** [comment]
I'm having [pretty good success](https://github.com/Difegue/LANraragi/runs/196602858) building cross-architecture images, but I'm getting cockblocked by docker's poor CLI login failing on Actions v2.  

I'm sure I'll eventually find a workaround.

**Comment by Difegue** [comment]
![image](https://user-images.githubusercontent.com/8237712/63299342-db06f680-c2d5-11e9-9c07-19133d5e4135.png)
They live! I'll eventually add multi-arch support so that just pulling `latest` will work no matter the architecture you're on, but for the time being you can play around with those tags.

**Comment by Difegue** [comment]
![image](https://user-images.githubusercontent.com/8237712/63303078-15c15c80-c2df-11e9-8d69-071cea71cb25.png)
And it is done.
