### ISSUE TITLE
Opening a new gallery triggers a full filemap rebuild every time

### ISSUE THREAD

**Issue by Crayphish** [Difegue/LANraragi#162]
**LRR Version and OS**

- OS: Ubuntu Server 18.04.2
- LRR Version: 0.6.0-BETA.2 (Source-compiled)
- Perl Version: 5.3.0 (non-vendor, userspace, perlbrew)

**Bug Details**
Shinobu rebuilds filemap whenever a new gallery is opened, instead of just rebuilding JSON cache. On lower spec hardware and/or encrypted filesystems, this generates a lot of load.

LANraragi::Utils::Database::invalidate_cache() touches the .shinobu-nudge file, triggering an inotify watcher in Shinobu.pm which rebuilds filemap and JSON cache. This is called every time a new gallery is opened by LANraragi::Model::Reader::build_reader_JSON().

In my local copy, I have removed the build_filemap() call from the inotify sub in Shinobu.pm to resolve the problem. I don't see any other tasks that rely on invalidate_cache() or the file nudge that would require a full filemap rebuild, so this seems to work OK. Sorry I'm a git/github pleb so I have no idea how to create a pull request for this.

**Matching Logs**
When accessing multiple new galleries, Shinobu info log is full of:
[Shinobu] [info] Building filemap...This might take some time.
[Shinobu] [info] Building JSON cache...This might take some time.

**Screenshots**
n/a

**Comment by Difegue** [comment]
I looked at all uses of invalidate_cache(), and indeed there's nothing that requires a filemap rebuild.  
I probably put that in there to be safe, but the filemap is a heavy operation that shouldn't be called frequently.
