### ISSUE TITLE
Update nginx documentation to reflect client_max_body_size behavior

### ISSUE THREAD

**Issue by CirnoT** [Difegue/LANraragi#163]
While documentation does make mention of changing `client_max_body_size` to 0 in `server` block, it is important to mention that setting `client_max_body_size` to 0 outside `http` block will revert its value to value from previous parent block. As such, if `client_max_body_size` is set to 20MiB in `http` block, setting it to 0 in `server` block will ensure that `server` block value for it is the same as in `http` block (so 20MiB). If you really want to increase the value, you have to do it explicitly or set value to 0 in highest priority block, so in `http`. `http` is the only block that accepts value 0 as 'no limit'.

**Comment by Difegue** [comment]
Could you make a PR on the documentation with the matching changes?  

I'm on holidays currently and don't have push access: The documentation is hosted within the repo, so there's nothing extra to do. For the nginx part, the file you'll want to edit is located [here.](https://github.com/Difegue/LANraragi/blob/dev/tools/Documentation/installing-lanraragi/methods.md)
