### ISSUE TITLE
Removing archive does not drop it from Redis database

### ISSUE THREAD

**Issue by CirnoT** [Difegue/LANraragi#166]
**LRR Version and OS**
74751bdbcf39c3166da8fb2b5e3fe61050dca590

**Bug Details**
Removing archive by deleting file via Shinobu does not remove associated entry from Redis database. As a consequence, database may contain invalid entries such as
```
                {
                    "arcid": "c0cfa338cdb7768cdad8595f1e32a587287296bf",
                    "title": "asdf",
                    "tags": "",
                    "thumbhash": "",
                    "filename": ""
                },
```

**Matching Logs**
```
[2019-08-06 20:05:53] [Shinobu] [info] /db/[Kawaisounako (Ichino, YU-YU)] DeepSnow2 (Mahouka Koukou no Rettousei)[English][TheLustyLadyProject].rar was deleted from the content folder!
```

**Screenshots**
n/a

**Comment by Difegue** [comment]
Oh, that one's actually a feature. Since the background worker is pretty agressive at detecting file changes, deleting stuff from the database runs a risk of unwanted data loss for people that have their archives on network drives or something that can occasionally disconnect.

**Comment by CirnoT** [comment]
I understand it, however it does seem to generate warnings from Perl about undefined variables when any of the values in database is null (for example `thumbhash` because of broken archive that was removed). While at the moment this is not of a concern, it may be a thing to be aware of in future.

**Comment by Difegue** [comment]
I think I'll have to rework this system anyway when I start work on server-side processing, so the filter might be a good idea.

**Comment by Jisagi** [comment]
Wouldn't some kind of purge feature be a neat little workaround then? Keeping the current behaviour, but additionally a manually trigger somewhere in the settings to purge old non existing gallieries from the db. With a warning after clicking the option, the user would be responsible for potential data loss then, but it's probably safe when you only trigger it when needed.

**Comment by Difegue** [comment]
Sure! Adding a button to wipe the database somewhere was already on my to-dos, so this can be done alongside it.

**Comment by Difegue** [comment]
Added said button a few days ago, so closing.
