### ISSUE TITLE
Restoring database does not clear previous Redis database

### ISSUE THREAD

**Issue by CirnoT** [Difegue/LANraragi#167]
**LRR Version and OS**
74751bdbcf39c3166da8fb2b5e3fe61050dca590

**Bug Details**
Restoring database via UI does not cause Redis database to be cleared. As a result, data is either appended or updated but never removed. 

Code should either compare Redis keys and delete ones that are not present in file used to restore database or clear all keys and restore everything with isnew flag set to false.

**Matching Logs**
n/a

**Screenshots**
n/a

**Comment by Difegue** [comment]
I won't go further on this than just running the regular DB clean routine before restoring a backup -- It's possible to drop the DB from settings if one really wants to restore from scratch anyway.
