### ISSUE TITLE
Viewing Modes

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#17]
Hello. 
Are there plans for more viewing modes?
As in fit to width/height, full size image as well as paged images? Also an exclusive mode where the image is the only thing visible since there are hotkeys for everything anyways. I'm not sure whether I'm asking or making suggestions at this point :D.

**Comment by Difegue** [comment]
Not planning on implementing those in the base app for now.

All those suggestions can be done with CSS rather easily though, and we do have support for custom CSS through themes. 😎

**Comment by xd1986k** [comment]
Huh. I can't believe I didn't notice the CSS folder. 
A dropdown to change theme from the viewing page would be nice to carry out switches on the fly but this works for me.
Thanks.

**Comment by Difegue** [comment]
You might be happy to know that 19aa4957f1d33671b3a4992e19e7056ab74139e5 achieves this by moving theme switching to a global footer.
