### ISSUE TITLE
API does not return HTTP error codes

### ISSUE THREAD

**Issue by Guerra24** [Difegue/LANraragi#170]
I'm developing an app for this but I'm unable to handle errors because it doesn't return the http error code. 

Docs say that given a missing or wrong key it should return HTTP 401 Unauthorized but is not the case.

![image](https://user-images.githubusercontent.com/9023392/62813688-5ba14800-bac9-11e9-9b89-867547c684b9.png)

Missing ID should return HTTP 400 Bad Request.

![image](https://user-images.githubusercontent.com/9023392/62813837-382acd00-baca-11e9-833b-59c378c38d2f.png)

It seems that all request regardless of result return HTTP 200 OK.

**Comment by Difegue** [comment]
Indeed, it looks like I never added http codes to the render messages. That's embarassing. 

I'll do it myself when I'm in front of a computer again, but in the meantime you can add the error codes pretty easily yourself in the `render` calls like so: 

`$c->render(text => 'Oops.', status => 500);` 

The 401 is handled in Controller/Login.pm, whereas the various 400s are in Controller/Api.pm.

**Comment by Difegue** [comment]
Fixed in #171.
