### ISSUE TITLE
Issue with getting SSL working with self-signed certificate

### ISSUE THREAD

**Issue by rettisances** [Difegue/LANraragi#172]
**LRR Version and OS**
Lanraragi 0.6.0 Beta 2, Docker, Linux Mint 19.1 Tessa

**Bug Details**
I've been trying to get SSL to work in LRR for a while and I always get these errors that I'm sure come down to some kind of syntax error, but I can't get it to work using the guide's instructions. I'm trying to get my LRR server to listen on port 2022 with a self-signed certificate consisting of .crt and .key files. This is what I type in to start up the docker container:

`sudo docker run --name=lanraragi -p 2022:2022 --mount type=bind,source=/mnt/NASHDD1/H-Content/,target=/home/koyomi/lanraragi/content -e lrr_network="https://*:2022?cert=/mnt/NASHDD1/Certs/prim.crt&key=/mnt/NASHDD1/Certs/prim.key" difegue/lanraragi:nightly`

The server starts up successfully, but I can't connect to it at all, Firefox just throws me an "Unable to connect" message or PR_END_OF_FILE_ERROR. Is there something I'm missing here?

**Matching Logs**
```
Starting LANraragi with UID/GID : 9001/9001
usermod: no changes
2019-08-12 20:45:06,164 INFO supervisord started with pid 1
2019-08-12 20:45:07,167 INFO spawned: 'lanraragi' with pid 15
2019-08-12 20:45:07,170 INFO spawned: 'redis' with pid 16
2019-08-12 20:45:07,422 DEBG 'lanraragi' stderr output:
Attempting to create directory /home/koyomi/perl5

2019-08-12 20:45:08,140 DEBG 'lanraragi' stdout output:


ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!!!!!
[LANraragi] [info] LANraragi 0.6.0-BETA.2 started. (Production Mode)
[LANraragi] [info] Plugin Detected: Chaika.moe
[LANraragi] [info] Plugin Detected: Tag Copier
[LANraragi] [info] Plugin Detected: Date Added
[LANraragi] [info] Plugin Detected: E-Hentai
[LANraragi] [info] Plugin Detected: eze
[LANraragi] [info] Plugin Detected: Hdoujin
[LANraragi] [info] Plugin Detected: nHentai

2019-08-12 20:45:08,437 DEBG 'lanraragi' stdout output:
[Shinobu] [info] Shinobu Background Worker started.

2019-08-12 20:45:08,437 INFO success: lanraragi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-12 20:45:08,437 INFO success: redis entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by Difegue** [comment]
The `LRR_NETWORK` environment variable runs inside the Docker container's context, so your cert and key must be present in the Docker environment as well.  

You should add an extra `bind` command mapping /mnt/NASHDD1/Certs to /home/koyomi/ssl or something like that and edit the environment variable accordingly.

**Comment by rettisances** [comment]
I just tried this and it runs, but I'm still unable to connect to it. Did I format something incorrectly in the environment variable or something?
`sudo docker run --name=lanraragi -p 2022:2022 --mount type=bind,source=/mnt/NASHDD1/H-Content/,target=/home/koyomi/lanraragi/content --mount type=bind,source=/mnt/NASHDD1/Certs/,target=/home/koyomi/ssl -e lrr_network="https://*:2022?cert=/home/koyomi/ssl/prim.crt&key=/home/koyomi/ssl/prim.key" difegue/lanraragi:nightly`

**Comment by Difegue** [comment]
Looks OK at a glance, not sure what's wrong.

**Comment by Difegue** [comment]
Is this still a thing for you? I rarely get feedback on the certificate options since most people use a reverse-proxy to handle https.

**Comment by rettisances** [comment]
Yes, it is still a bug for me. I was hoping that the typical certificate and key pair would be good for getting SSL implemented instead of doing a reverse proxy as that takes a good amount more work. I just tried to run the docker container with the arguments I used before and it still will not load the page. The server appears to start and run on the console output, but I can't access it.

**Comment by Admiral124** [comment]
Admittedly I don't have much experience with Docker so it's possible I'm just doing things wrong, but following @rettisances' formatting I'm also having troubles.
`sudo docker run --name=lanraragi -p 3000:3000 --mount type=bind,source=/mnt/Kanako/sadbackup/,target=/home/koyomi/lanraragi/content --mount type=bind,source=/mnt/Kanako/.ssl/,target=/home/koyomi/ssl -e lrr_network="https://*:3000?cert=/home/koyomi/ssl/hentek.crt&key=/home/koyomi/ssl/hentek.key" difegue/lanraragi`
The server does indeed start, but you can only connect to it via http, not https.

**Comment by Difegue** [comment]
Alright, I'll try to get some further debugging done on this in a few days, if time allows it.

**Comment by Difegue** [comment]
Managed to get an SSL Docker setup working on my end: There are a few pitfalls here that weren't properly documented.  

The command I used was `docker run --name=lrr-ssl -p 3333:3333 --mount type=bind,source=/home/shinji/ssltest/,target=/ssl -e LRR_NETWORK="https://*:3333?cert=/ssl/crt.crt&key=/ssl/crt.key" difegue/lanraragi:nightly`  
The environment variable is actually case-sensitive, so if you don't input it in uppercase it won't work.  
I noticed this by seeing the server was still starting on port 3000 with the lowercase env variable. Weird that we didn't see this before but well ¯\\\_(ツ)_/¯

Past that, you might get some permission errors:  
```
2019-09-24 09:57:29,478 DEBG 'lanraragi' stderr output:,
Mojo::Reactor::Poll: I/O watcher failed: SSL_key_file /ssl/crt.key can't be used: Permission denied at /usr/share/perl5/vendor_perl/IO/Socket/SSL.pm line 2284.,
```  
which can be fixed by chmodding the cert and keys on your host filesystem.

**Comment by Admiral124** [comment]
Stupid question, but what permissions is it looking for? I have the crt file set to 444 and the key is 400 and is owned by root:root, but I still get the SSL_key_file permission denied error.

**Comment by Difegue** [comment]
I just set both to 777 for testing tbh, so I don't really have recommendations to give here.

**Comment by UnixNight** [comment]
I hate to comment on an old issue but I have proper SSL certs from Let's Encrypt that I want to use. Those come in .pem files. How would I go about using them with Docker and LRR?

**Comment by Difegue** [comment]
https://stackoverflow.com/questions/13732826/convert-pem-to-crt-and-key
