### ISSUE TITLE
Few questions and general observations.

### ISSUE THREAD

**Issue by waz1500** [Difegue/LANraragi#174]
**LRR Version and OS**
Version 0.6.0-BETA.2 - "Moss Garden", Docker https://github.com/Difegue/LANraragi/commit/cbb1f39748dfa468701d73aca5626c595a089edd

I've been attempting to write a plugin to work with my existing metadata utilising the program Hdoujin downloader V2 of the text metadata.  Many thanks for providing documentation and example. They are really proving useful. Writing this plugin, and having a play with Lanraragi, I've noticed a few things. 

- I know the colour coding suggestion has been mentioned at #114. I too would like a multitude of colours for various things. 
My issue is that adding metadata using the `artist:` tag it will be coloured on the "List View". If I use my tag of `Artist:` or even `ARTIST: `, it won't detect it as `artist:` and won't be coloured appropriately.
It would be nice if it wasn't so specific in terms of lettercase. 

Also to add colour information when you hover over the tags in Thumbnail View. 

- My initial plan was to add all my metadata to the manga/doujin but noticed the tag cloud statistics got very messy very quickly. 
It seems to add every type of Tag I have. From URL information to page count. 

Could be nice to differentiate? Or possible to exclude certain metadata from the tag cloud statistics. Perhaps just the "tags:" data only and not things my metadata contains such as Title and Original Title. I perhaps I could strip these out but it's nice to have.  Ability to generate tag clouds based solely on Artists, Characters or even Parody. 
![LANRARAGI tag website clutter](https://user-images.githubusercontent.com/17833884/62964641-4e52c900-bdfb-11e9-9ca6-07c89bb0e33d.jpg)

It would also be be great if you could click on these tags to get you to the relevant set of manga or collections based on that tag you clicked. 

- What differentiates between Tags and Other? When my metadata is this:
title: Albedo, original title: アルベド, artist: Ginhaha, tags: Blowjob, Dark Skin, Demon | Incubus, Double Penetration, Full Color, Gangbang, Group Sex, Handjob, Harem, Nakadashi, Spitroast, Textless

*I worked it out with a bit more testing. Lanraragi likes it when I affix `tags:` before the actual tag for **every** tag. 
Would you be able to implement something perhaps for overall like the following example?

tags: Blowjob, Dark Skin, Demon, Double Penetration
characters: Albedo, Overlord

in conjunction with what you have at the moment which is:

**tags:** Blowjob, **tags:** Dark Skin, **tags:** Demon, **tags:** Double Penetration
**characters:** Albedo, **characters:** Overlord

With anthologies, I've noticed the metadata takes a while to generate and can get quite messy in edit mode because of the extra stuff being added like **tags:** for every tag etc..

- Is it possible to clean up the metadata and make it a bit more user friendly. Those that have large metadata such as multiple artists, groups, series, parodies and characters as well as tags, can be quite difficult If I need to make edits. 
![metadata](https://user-images.githubusercontent.com/17833884/62968272-9cb79600-be02-11e9-80f7-ff1216b4b064.jpg)
It would certainly be a lot more easier if you implemented my idea above with the tag encompassing overall tags. First box is what it does at the moment and the second box below it my idea. 

- I've noticed you associate **Parody** with **Series** and vice versa. I'm used to having two separate fields for these. Series if more fitting for regular manga whereas Parody fits doujinishi content quite well. 
I do like how you associate **Groups** and **Circle** together and I don't it's necessary to distinguish between the two. The colour information when in List Mode works on both tags.

- I've read your recent blog post about the recent survey that went out. I was going to request and perhaps still am, some sort of favourite list without the need to edit the metadata and perhaps a quick way to go back and forth from the list. I'm aware this can be done via the Tag Favourite section in settings, but I would have to edit existing metadata. 

 

- When uploading new manga. The "new" icon is incredibly small and the text is almost illegible on my monitor. 1080x1080. Perhaps make it bigger? Even a text version `**NEW**` would be nice instead of the icon.

- I'll most likely strip this out in the plugin code but I have noticed the metadata doesn't like when I add my own URL tag. eg, `url: http://www.google.com` Instead it appears under "Other" slightly malformed. `url,http://www.google.com`
![LANRARAGI tag cut out](https://user-images.githubusercontent.com/17833884/62966527-1f3e5680-bdff-11e9-8695-814fc54e30aa.jpg)

- I've noticed on the manga edit page, the metadata text box has the following text

> Metadata on info there is a "Tags (separated by hyphens, i.e : tag1, tag2)"

Not sure how hyphens "**-**" are used when it seems it's only working with colons ":" and commas ",". Possibly a typo? 

I am not familiar with the perl language code or even writing code in it, so this has been a huge learning curve for me, but with all the documentation you provided I was able to understand the code a little better and compiled a working plugin in a few days that did the bare minimum. Hopefully I can adjust the plugin code to work with my collection better.

**Comment by Difegue** [comment]
This is a lot to read, so here are just a few takes I'm seeing right away:
* The "Other" category is for tags that don't have a namespace. Adding "tags:" in front of your stuff counts as a namespace, but it's not needed.  

* I should be able to ignore lettercase for the namespace coloring easily. Mistake on my part..

* Not sure if there's an easy way to format the textbox like that. 

* For urls, look at the existing implementation in the e-h plugin.

* That is indeed a typo on the edit page.

**Comment by CirnoT** [comment]
> Could be nice to differentiate? Or possible to exclude certain metadata from the tag cloud statistics. Perhaps just the "tags:" data only and not things my metadata contains such as Title and Original Title. I perhaps I could strip these out but it's nice to have. Ability to generate tag clouds based solely on Artists, Characters or even Parody.

You seem to be misunderstanding. Metadata field is comma separated list of tags in form of either `tag` or `namespace:tag`. Adding 'tags:` in front of actual tags do not mark them as tags, it marks such tags as belonging to namespace 'tags', similarly how 'title:' does not mark proceeding text as gallery title, but as tag in namespace named 'title'. You can of course create any namespaces you want, and they will be displayed in metadata pop-up with uppercase like 'Tags' or 'Series' or 'Title', but do not make a mistake - from LRR point these are just that - thats. Title is stored separately and right now LRR does not support multiple titles (per language). The concept on which LRR works is very similar to E-Hentai tags, in that everything except title is a tag that can be searched for, and tags can be parented to namespaces, such as 'artist:somerandomguy' means that 'somerandomguy' is a tag that belongs to namespace 'artist', hence it is understood and 'somerandomguy' is artist. In similar way, namespaces on E-H are used to differentiate between gender, like 'female:rape' or 'male:rape' depending on whom action is taken on.

**Comment by waz1500** [comment]
Thanks for taking commenting. 
Perhaps it was a little too lengthy for some. I do encourage you to read it at length if you get the time. Next time I can post just individual issues in separate threads to make it easier for everyone. 

I understand how Lanraragi uses the namespace to manage it's metadata and did make an edit on my original post about it but it's easily missed. Sorry if I confused anyone.

For me, when attempting to write the script it was more about seeing if there was a way for a single namespace to encompass a bunch of tags. 

```
tags: Blowjob, Dark Skin, Demon, Double Penetration
characters: Albedo, Overlord
```
rather than:
```
tags: Blowjob, tags: Dark Skin, tags: Demon, tags: Double Penetration
characters: Albedo, characters: Overlord 
```
But now understanding Lanraragi's logic a little better, I got my answer which is essentially No. 

I'm not proficient enough in scripting in perl to adjust the eze script to fit Lanraragi's naming schema for those of us using Hdoujin's alternative format .TXT files. #25 

Thanks Diffegue for committing some of the other changes.
