### ISSUE TITLE
docker nightly - cannot add new gallery

### ISSUE THREAD

**Issue by Jisagi** [Difegue/LANraragi#176]
**LRR Version and OS**
docker nightly with the [latest](https://github.com/Difegue/LANraragi/commit/c29c650854c44bc7f993ae19a6824042843b7a10) commit on debian 10

**Bug Details**
I cannot add any new gallery. Neither adding a file to the content folder or uploading via the webinterface. Uploading via the webinterface "works" and I can open the edit window for the uploaded gallery (thorugh the upload window) but it will never show in the main menu. It does seem to get added to the db, since uploading it again returns "gallery already exists". 
Deleting the gallery manually from the folder produces the expected log output `[...] was deleted from the content folder`. I don't get any kind of log output when uploading/adding a new gallery.

I tried reverting to the normal beta release which didn't work at all. It endlessely spams this into the log when I try to start it, so downgrading isn't an option either.
Here the log for that:
```
ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!!!!!

2019-08-17 18:45:13,610 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140195850945096 for <Subprocess at 140195853112384 with name lanraragi in state RUNNING> (stderr)>
2019-08-17 18:45:13,611 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 140195851346432 for <Subprocess at 140195853112384 with name lanraragi in state RUNNING> (stdout)>
2019-08-17 18:45:13,611 INFO exited: lanraragi (exit status 111; not expected)
2019-08-17 18:45:13,611 DEBG received SIGCHLD indicating a child quit
2019-08-17 18:45:14,615 INFO spawned: 'lanraragi' with pid 59
2019-08-17 18:45:14,888 DEBG 'lanraragi' stderr output:
^* matches null string many times in regex; marked by <-- HERE in m/^* <-- HERE .+\.(png|jpg|gif|bmp|jpeg|webp|PNG|JPG|GIF|BMP|JPEG|WEBP)$/ at /home/koyomi/lanraragi/script/../lib/LANraragi/Utils/Generic.pm line 34.

2019-08-17 18:45:15,889 INFO success: lanraragi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-17 18:45:17,923 DEBG 'lanraragi' stderr output:
Could not connect to Redis server at 127.0.0.1:6379: Connection refused at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Config.pm line 38.
        ...propagated at /usr/local/share/perl5/site_perl/Redis.pm line 606.

2019-08-17 18:45:17,924 DEBG 'lanraragi' stdout output:
```

What can I do, to get more info if needed, fix the issue, or downgrade to the release version?

**Comment by Jisagi** [comment]
I tested more ways to add galleries:
1. **Adding files and then restarting docker:** Doesn't work, same result as above
2. **Adding files while the container is offline and the starting it:** Works, but it's kinda bad to always stop LRR before adding new galleries.

I'm still not really sure why this ahppens though, but maybe it helps you identify the problem.

**Comment by Jisagi** [comment]
After some more testing, I get even more confused. I just added 14 galleries just fine and they even got tagged, but then I just randomly zipped a few pictures and tried to add those and it resulted in nearly the same as before.
Adding a single gallery seems to always fail. Adding multiple ones either works just fine, or exactly one of them doesn't get added. I couldn't see a pattern beside it either being the first or the last one (sorted by filename) not being added correctly.
BTW, I always use "reset json cache" to make sure it catches new files, but same result.

**Comment by Difegue** [comment]
Sounds similar to #140.  
I have no idea what causes this bug at the moment -- It seems to stem from container updates fucking up the existing Redis database? It's weird.

**Comment by Jisagi** [comment]
I'm currently running LRR on a machine with 4GB RAM on a fairly large and new SSD. In theory this should be enough I guess. I'll watch RAM/Swap usage in teh future when I try to import new galleries.
I kinda wanna try to reset everything by creating a backup and redownload the nightly version again and then import the backup. Maybe this fixes it, who know, worth a try I. Is there an easy way to setup a new instance of LRR without it trying to index every single file inside the content folder right away and running a backup before?

**Comment by Difegue** [comment]
You can try keeping the .rdb database in the next install, but if the fuckup is in the database itself that might carry the issue over to the new install. It's worth a try though.

**Comment by Jisagi** [comment]
I specifically wanted to start with a fresh install without using the old db and see if the db is the issue or the nightly build itself. At least that was my thought behind that.
As fair as I understood https://github.com/Difegue/LANraragi/issues/167, even when I set up a new instance, I would need to be fast enough to restore the db from a file before it tries to index everything by itself and then not(?) overwrite the existing already indexed files? Can I somehow about the indexing right away or do anything else so I can first run a restore and then let it do whatever it wants?

**Comment by Difegue** [comment]
Thing is, restoring a backup will only restore metadata for IDs that are already in the database; If you're going fresh with a new database there's currently no way to avoid the parsing.  

It should be pretty fast if you don't enable auto-plugin, though.

**Comment by Jisagi** [comment]
A ok, so I s´would need to let everything get parsed, deactivate the auto-plugins and afterwards run a restore to reimport all the tags and such, correct? And would that only add tags to the parsed and therefore existing files or also the ones which didnt get deleted from the old db, which should still be in the export?

**Comment by Difegue** [comment]
That'd basically be it, yeah. It'd only add tags to existing files.

**Comment by Jisagi** [comment]
Ok, I tried what is described above and it seems to work right now. I can't say for sure if the problem is gone completely, but right now it seems to be.

What I did:
1. Create a backup and move the `backup.json` somewhere
1. Delete the `database.rdb`
1. Delete the docker container, redownload it and run it with the command listed in the installation guide. I did add `-d` to it, so it runs in the background right away
1. Be asap to disable the Auto-Tag and Auto-Plugin in the settings and then press "reset JSON cache"
1. Some waiting .... didn't take long, not even a minute for ~2,5k galleries
1. Restore the database from the `backup.json`
1. (Optional) My thumbnails did get messed up, so I deleted the `thumb` folder inside my folder

I assume by this you can also downgrade back to an older version as well, but I didn't test that.
This is also a great (not) way to get rid of non existing entries in the database, till a feature is implemented for it :smile: 

I'll close the issue (and hope the problem doesn't reoccur). Thanks for the help!!
