### ISSUE TITLE
External HDD source does not work

### ISSUE THREAD

**Issue by EfronC** [Difegue/LANraragi#180]
**LRR Version and OS**
LRR Version: Nightly.
OS: Ubuntu Server 18.04.3 LTS for RPi (CLI)

**Bug Details**
After installing correctly Lanraragi on my RPi using the nightly version, and confirming it works correctly with a pair of test folders with one zip, i tried to change the content directory to an external directory, with thousands of zips, but it just doesn't work.

I mounted my hdd with(Ubuntu server does not auto detect the HDD, need to mount it):
```
mount /dev/sda1 /media/contenthdd/
```

Then i used: 
```
docker run --name=lanraragi -p 3000:3000 --mount type=bind,source=/media/contenthdd/Death/LANraragi/Media/,target=/home/koyomi/lanraragi/content -e LRR_UID=``0 -u $USER`` -e LRR_GID=``0 difegue/lanraragi:nightly
```

But only got a message that JSON cache was corrupt(Check Screenshot section), and i'm not sure why didn't work. I tried to create a symbolic link to /media/contenthdd/Death/LANraragi/Media/ on /home/ubuntu/link (Which created a folder inside link called Media, that was the SL), and then used:

```
docker run --name=lanraragi -p 3000:3000 --mount type=bind,source=/home/ubuntu/link/,target=/home/koyomi/lanraragi/content -e LRR_UID=``0 -u $USER`` -e LRR_GID=``0 difegue/lanraragi:nightly
```

But then just started as if the folder was empty, like not recognizing the folder Media(This is another question, Does LANraragi works if files are in subfolders? Because all the zips on my HDD are inside subfolders for every site i've downloaded), then i tried:

```
docker run --name=lanraragi -p 3000:3000 --mount type=bind,source=/home/ubuntu/link/Media,target=/home/koyomi/lanraragi/content -e LRR_UID=``0 -u $USER`` -e LRR_GID=``0 difegue/lanraragi:nightly
```

But got the same JSON corrupted error. Do i need to mount the HDD on an specific way, with an additional parameter or something? Another thing worth mentioning is that the logs were different while trying to mount on my Test folder(Which worked), and on the HDD(Which didn't), check the Matching Logs section. Is there any way to get more information of what could be the problem? 

**Matching Logs**
This is the end of the log when mounting on /home/ubuntu/test
```
2019-08-23 15:54:08,848 DEBG 'lanraragi' stdout output:
[Shinobu] [info] Shinobu Background Worker started.

2019-08-23 15:54:09,029 DEBG 'lanraragi' stdout output:
[Shinobu] [info] Working dir is /home/koyomi/lanraragi
[Shinobu] [info] Building filemap...This might take some time.
[Shinobu] [info] Building JSON cache...This might take some time.
[Shinobu] [info] Adding new file /home/koyomi/lanraragi/content/test/[RevolverWing] Corrupting the Busty Duelists! (Yu-Gi-Oh!, Yu-Gi-Oh! GX).zip with ID de35de59539eca054f541193cf4281f1e1238d26
[Auto-Plugin] [info] Executing enabled plugins on archive with id de35de59539eca054f541193cf4281f1e1238d26.
[Shinobu] [info] Adding inotify watches to content folder /home/koyomi/lanraragi/content

```

This one is when i mount on /media/contenthdd/Death/LANraragi/Media/ (It gets only until this message).

```
2019-08-23 16:12:50,624 DEBG 'lanraragi' stdout output:
[Shinobu] [info] Shinobu Background Worker started.
```

**Screenshots**
This is what i see when putting the content folder on my HDD.

![62484582-1951d100-b780-11e9-8044-088e8e795ec1](https://user-images.githubusercontent.com/5926318/63604782-3ebd4800-c592-11e9-9b56-a7e8836528c6.png)

**Comment by Difegue** [comment]
I'd say this is more of an issue with your HDD or Linux installation than with LRR at this point: Mounting and such is completely transparent to the application and as long as it can read the folder(and subfolders) it'll certainly try.

**Comment by Difegue** [comment]
You can try enabling debug mode to see if you get more interesting logs though; Great to see that the ARM images do work as expected though!

**Comment by EfronC** [comment]
Actually, i've made a new discovery, hadn't added as as edit since wanted to try it first(Need to get to my home), but yes, the problem seems to be the folders: Took a pair of files from /media/contenthdd/Death/LANraragi/Media/EH and moved to /media/contenthdd/Death/LANraragi/Test so they were outside a folder, and then used source=/media/contenthdd/Death/LANraragi/Test and now the log showed me this:

```
2019-08-23 19:02:22,886 DEBG 'lanraragi' stdout output:
[Shinobu] [info] Shinobu Background Worker started.

2019-08-23 19:02:23,164 DEBG 'lanraragi' stdout output:
[Shinobu] [info] Working dir is /home/koyomi/lanraragi
[Shinobu] [info] Building filemap...This might take some time.
[Shinobu] [info] Building JSON cache...This might take some time.
[Shinobu] [info] Adding new file /home/koyomi/lanraragi/content/[Toranoe] Z Teishoku Special ♡ (Pokemon Sun Moon) [English] [Zero Translations].zip with ID 22d88a9fcae023d48764c6c68d514daf364794e6
[Auto-Plugin] [info] Executing enabled plugins on archive with id 22d88a9fcae023d48764c6c68d514daf364794e6.
[Shinobu] [info] Adding new file /home/koyomi/lanraragi/content/[RevolverWing] Corrupting the Busty Duelists! (Yu-Gi-Oh!, Yu-Gi-Oh! GX).zip with ID de35de59539eca054f541193cf4281f1e1238d26
[Auto-Plugin] [info] Executing enabled plugins on archive with id de35de59539eca054f541193cf4281f1e1238d26.
[Shinobu] [info] Adding inotify watches to content folder /home/koyomi/lanraragi/content
```

Passed from the Shinobu state message, and detected the Zips(Hasn't checked if they show on the Frontend, forgot to start my VNC app for that, so in 2-3 hours i'll be checking it), so either LANraragi has a problem with subfolders on External Drives, or 1 file on those subfolders cause the problem, i'll make a few extra tests, and will update this post if just don't having subs is the solution(Which probably is, since i think i remember someone on 4Chan saying that subfolders caused problems with LANraragi), or if a file was the problem.

**Comment by EfronC** [comment]
Ok... This is a little embarassing, but i just discovered the problem. No, is not that LANraragi was failing or something like that, the problem is that /Media, between all the subfolders, had more than 4000 files, and of course, that's the reason it stopped on 

```
2019-08-23 19:02:22,886 DEBG 'lanraragi' stdout output:
[Shinobu] [info] Shinobu Background Worker started.
```

Because it was loading the folder, and didn't print any additional log until then, and of course, since i opened the frontend and saw those red letters marking that the DB was corrupted, i thought the loading had failed. While this is completely my error for not waiting enough time, as a matter of feedback of this experience, i think a good enhancement is that, after the previous message, since it could take a few minutes, that it had some kind of loader, like the `loading...` with 3 points appearing and dissapearing, or the `|` spinning, of course if possible, just to know that the program hasn't freezed, if not, just a message of loading to mark you to wait, and that the program hasn't stopped because of an error.

Well, if you don't have any additional commentary for the topic, i think you can close the issue, for the moment thanks for making easier to install this on an RPi, and congratulations for so great program :)

**Comment by Difegue** [comment]
Well, normally the `[Shinobu] [info] Building filemap...This might take some time.` line is supposed to appear before the whole file parsing happens to clue users in that stuff is happening behind the scenes.  

A bit odd that it wouldn't show up in your case: I'm guessing something in your setup clogged STDOUT. Glad it works though!
