### ISSUE TITLE
[Suggestion] Add a complete list of clickable tags to the Archive Index

### ISSUE THREAD

**Issue by izgtbvdb** [Difegue/LANraragi#189]
Before I start, I'd first like to say one of my requests was going to be adding auto-complete when searching tags, but see that has just been added to the latest release, so thanks for that!

1) [Improvement] I feel the popup that appears when hovering over tags would be more useful if when clicking a tag, it added/removed it from the search query, so you could click on multiple tags to form a string of search terms.  Currently you can only click on one tag at a time to search that one tag only, overwriting whatever else is in the search box. It should probably also include the namespace that the tag belongs to.

2) [Addition] Sometimes I'm not sure what I'm looking for, and just like to see a complete list of tags to choose from. A button on the main screen that opens a full-size version of the tag preview window would be perfect. Searching would work as described above. Something like attached image

![ll1](https://user-images.githubusercontent.com/50206297/64468738-3eb96c80-d17c-11e9-9afa-d99040629b40.jpg)

**Comment by CirnoT** [comment]
> Sometimes I'm not sure what I'm looking for, and just like to see a complete list of tags to choose from.
You realize that while it works for 10 archived, when you have 1365 different tags like me, it simply won't work.

**Comment by izgtbvdb** [comment]
I see your point, guess I didn't think that one through completely.  

That is quite the collection of tags you've got there. Looking [here](https://ehwiki.org/wiki/Category:Tag) there are apparently 641 tags in exsistence, the vast majority of which I imagine would never appear in my collection, though of course everyone's going to be different.

Perhaps it would be workable with initially just letter headings being visible (A-Z) which could then be clicked on to expand. 

I think  for people like me with a more modest collection, it would be a nice option to have.

**Comment by Difegue** [comment]
I kinda like the idea since it reminds me of the criminally unused win10 sort-by-letter program list: 

![image](https://user-images.githubusercontent.com/8237712/65080846-81f8b400-d9a2-11e9-9ee8-7ec778104152.png)  

Won't do it myself as this is a very minor enhancement, but the data for this is already loaded in the index thanks to tag suggestions, so it's really just a matter of gluing some JS together to make this happen. No perl knowledge required!  

Tagging for the upcoming hacktoberfest, maybe someone'll pick this up.

**Comment by Mayriad** [comment]
> That is quite the collection of tags you've got there. Looking [here](https://ehwiki.org/wiki/Category:Tag) there are apparently 641 tags in exsistence, the vast majority of which I imagine would never appear in my collection, though of course everyone's going to be different.

This is not feasible. You were only looking at the list of fetish tags on the EH wiki. I guess the total number of tags on EH is probably around 120,000 thanks to random misc tags created by high-power users. If you remove misc tags, the number should come down to about 16,000 (already excluding slave tags), but that is still not doable. By the way, Sankaku Channel had 900,000 tags the last time I checked more than two years ago; I would not be surprised if it has 1,500,000 tags now.

**Comment by Difegue** [comment]
A detailed tag breakdown is now available below the tag cloud in the statistics page. 👏
