### ISSUE TITLE
Update Screenshots

### ISSUE THREAD

**Issue by Difegue** [Difegue/LANraragi#206]
The screenshots used in the [README](https://github.com/Difegue/LANraragi/tree/dev/tools/_screenshots) are from old versions and some of them could use a refresh.  

If someone knows how to better annotate images for the screenshots in the [Documentation](https://github.com/Difegue/LANraragi/tree/dev/tools/Documentation/.gitbook/assets), I'm all in too!

**Comment by tthompson899** [comment]
I can work on this

**Comment by Difegue** [comment]
Thank you! It should be pretty easy to get an install going for screenshotting purposes by following the [documentation.](https://sugoi.gitbook.io/lanraragi/)  

I've also updated the demo website, so you can use that instead. :)

**Comment by Difegue** [comment]
Closed by #207.
