### ISSUE TITLE
Namespace Display

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#21]
Hey. Thanks for adding namespace support. 
When a lot of tags are added to a namespace. The tags in the namespace expand upwards and downwards which is confusing as there is no clear demarcation between two namespaces. Could you either
1: Make clear demarcation
2: Have the tags begin from the same line as the namespace
Thanks.

**Comment by Difegue** [comment]
Yeah, I noticed this as well earlier when testing with my own archive collection.  
I'm planning to go with option 2 here.
![](https://a.pomf.cat/cszsgh.png)

**Comment by xd1986k** [comment]
I just noticed, if you create a large tag like so comic:slakdjkladhljksadhjklhfjkdfhdskjfhslkfhlksjfhskjfhskjfhls, the tag is truncated in one line to the extent it can display. And it causes alot other tags to be pushed out of bounds as well.

**Comment by Difegue** [comment]
Both of those should be fixed by the above commit.

Thanks for testing!
