### ISSUE TITLE
☆ Character Display

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#22]
Archives with "☆" in their names are imported but give an error on opening.

**Comment by Difegue** [comment]
Tried an archive with a ☆ (and a bunch of japanese characters for good measure), imported and opened flawlessly.

I did spy some opening errors on other files of my 1000+ archive testing dataset, so I'll try fixing those and see if it solves your issues.

**Comment by Difegue** [comment]
737163ba0b477ee10757eebe01fd6c02e5c093da solves this issue on Docker/Vagrant builds for me.  
Waiting for confirmation before closing.

**Comment by xd1986k** [comment]
Working perfectly. Thanks!
