### ISSUE TITLE
Hey man

### ISSUE THREAD

**Issue by oniyakun** [Difegue/LANraragi#226]
I am ex.gaygay.me maintainer and I saw something interesting manga uploaded on my site, is that u? include that “2B” R18 manga. Im so glad to saw the messages that u leaved.

**Comment by Difegue** [comment]
:^) I found the site through the repo's tracking references if you must know:  
![image](https://user-images.githubusercontent.com/8237712/68075213-27c27f80-fda5-11e9-8520-38fa5fdaa322.png)

Wasn't planning on snooping too much but I saw the JS authentication and couldn't resist trying to bypass it. Sorry! 😅 I think a simple HTTP basic authentication would've been better here.

I didn't upload the 2B manga by the way, so I guess I wasn't the only one paying you a visit.

**Comment by oniyakun** [comment]
Yeh I just build a simple JS auth for my friends so... I wasnt think that complicated. As well I did some localization for friends. btw I added GA auth in it, but u know... based on Js auth (・_・ヾ, whatever its no matter but still thx. I'll try PR the localization if I cloud bcz Im really dont know how to use the god damn Git,(Im a fool), Thx for ur advice!

**Comment by Difegue** [comment]
Closing this since the matching PR #227 was merged to a side branch.
