### ISSUE TITLE
archive using the same thumbnail

### ISSUE THREAD

**Issue by damarsimple** [Difegue/LANraragi#23]
I uploaded 100 archives 10 of them using the same thumbnail

i cant speak english
using google translate

**Comment by Difegue** [comment]
Sounds like a weird bug - I'm going to need some more information.

* Which version(or commit) did you install, and how ? (Docker, Vagrant, Native?)
* If possible, could I get a screenshot of the /thumb folder in your archive content folder? It should contain all your thumbnails ordered by id, like this:

![](https://a.pomf.cat/vgakfq.JPG)

**Comment by damarsimple** [comment]
vagrant releases 045 dev
do i need to screenshots lanraragi web?
all of them R18 stuff
![untitled](https://user-images.githubusercontent.com/10891460/36570639-8e80b51a-1865-11e8-98a9-5a80ce1bc3fa.png)

**Comment by damarsimple** [comment]
![untitled](https://user-images.githubusercontent.com/10891460/36570697-d7d46afe-1865-11e8-8915-656daef08086.png)

**Comment by damarsimple** [comment]
thank you it looks like the bug has been fixed in mojolicous port 
tried it in native windows install
