### ISSUE TITLE
Cannot sort by tags

### ISSUE THREAD

**Issue by wongsaraf** [Difegue/LANraragi#231]
**LRR Version and OS**
LRR Version 0.6.6 

Windows 10 1083

Docker
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

**Bug Details**
Sorting list by Title, artist and series works normally.
Trying to sort by tags doesn't do anything, no error log written in the logs too.

**Matching Logs**
[2019-11-10 22:57:40] [Search Engine] [debug] Search request: --artist-1-
[2019-11-10 22:57:40] [Search Engine] [debug] Using cache for this query.
[2019-11-10 22:57:46] [Search Engine] [debug] Search request: --series-0-
[2019-11-10 22:57:46] [Search Engine] [debug] Using cache for this query.
[2019-11-10 22:57:48] [Search Engine] [debug] Search request: --series-1-
[2019-11-10 22:57:48] [Search Engine] [debug] Using cache for this query.

**Screenshots**

**Comment by Difegue** [comment]
The tags column isn't meant to be sortable.  
Clicking on it does nothing as the sort is disabled client-side. Although the sorting arrow still appears, which is something I should get around to fixing...

In any case, this is a wontfix for me. (Unless you have a very compelling argument for why tags should be sortable but ehh ¯\\\_(ツ)_/¯ )

**Comment by wongsaraf** [comment]
> 
> 
> The tags column isn't meant to be sortable.
> Clicking on it does nothing as the sort is disabled client-side. Although the sorting arrow still appears, which is something I should get around to fixing...
> 
> In any case, this is a wontfix for me. (Unless you have a very compelling argument for why tags should be sortable but ehh ¯\_(ツ)_/¯ )

I usually use sort by tags to sort untagged archives, usually stuff that doesn't exist in sadpanda or chiaka and doesn't got tagged by batch tagging.
By sorting by tags I can sort all untagged archive into the first page and then manually add the tags my self.
Right now my only solution is to sort by new and then search every page for an untagged archive which is very time consuming, even worst if something happen to my database and I need to redone everything again.

Is there a way to view non-tagged archives only without using the sort feature? Maybe i missed it.

**Comment by Asinin3** [comment]
You can just do a exclusion search for something your galleries all use. For instance, -language:english

**Comment by Difegue** [comment]
You can leverage the API to get a list of untagged archives: 
see https://lrr.tvc-16.science/api/untagged as an example.

It automatically excludes tags added by auto-tag as well. There's no webpage associated with the API yet since to be frank, I don't know where I could add it.

**Comment by wongsaraf** [comment]
How do I use that API list to my local archives?

> 
> 
> You can leverage the API to get a list of untagged archives:
> see https://lrr.tvc-16.science/api/untagged as an example.
> 
> It automatically excludes tags added by auto-tag as well. There's no webpage associated with the API yet since to be frank, I don't know where I could add it.

Okay, this seem much easier than searching the page one by one.
But I still need manually copy the id and then paste it to url bar one by one, but it's still better than my previous option.

I hope there' will be an option to view untagged galleries in the future, maybe something similar like "show archives new only" button.
