### ISSUE TITLE
[eze plugin] Use gallery name from json files instead of using filename

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#232]
Since I have .json files for every single gallery in my archive I opted to disable the "Auto-Tag" feature in order to stop uneeded tags popping up if the filenames weren't up-to-date. However, now all the galleries I add are using their full file-name as the gallery title instead of just the name of the gallery itself.

A gallery with the filename `(C96) [Some Group (Artist)] Amazing Book (Berserk) [English]` will always use that exact filename as it's title instead of the expected `Amazing Book` which the auto-tag feature would use. This happens regardless of if you use the eze plugin to scan json files or eh/chaika to scrape them. The data is there, I don't see why LRR isn't using it. 

If there are any people that do actually want to have the full file-name as the gallery title for some reason, then it could be added as an option instead. But even then it's a bit weird when this is exactly what tags and all the columns in list view are for.

**Comment by Difegue** [comment]
The eze plugin hasn't been updated to be able to set archive names, unlike the e-H/nH/chaika ones.  

For those, keep in mind modifying the title has to be enabled in plugin configuration:
![image](https://user-images.githubusercontent.com/8237712/68590419-b95d7b80-048e-11ea-9845-bdd40c1d0a6f.png)

**Comment by Asinin3** [comment]
Ah okay i missed the settings drop-down on the others, hope eze gets updated though. I will update the title.

**Comment by Difegue** [comment]
I'll try gettiing this done in a few, just need an example eze json with a filename field since I lost my examples -- might be a good opportunity to add a test for it as well.

**Comment by Difegue** [comment]
Done. I've also added in support for the `source:` namespace, which wasn't being parsed.
