### ISSUE TITLE
Unable to reset database

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#233]
**LRR 0.6.6 - Windows 1903 - Karen/WSL**

Whenever I try to reset my database I am greeted with the following error:
![image](https://user-images.githubusercontent.com/15137035/68621397-9038fb80-051f-11ea-9883-a8c3045d6119.png)
I have checked all the logs and didn't see anything written anywhere about the error.

**Comment by Difegue** [comment]
Likely an error due to `vm_overcommit` not being enabled in WSL Distros. I don't know how RAM is allocated to the distro so that might've led to Redis lockouts.  

Should be fixed now!

**Comment by Asinin3** [comment]
Still not fixed in latest nightly 
![image](https://user-images.githubusercontent.com/15137035/69901955-0b335a80-13d8-11ea-896e-1a07cf355bb1.png)

**Comment by wongsaraf** [comment]
Same thing happening here, whenever I tried to reset database "raptor not found." always pop out with an image of black raptor.

I'm using OMV 5.3.8-1 with docker on Portainer.

**Comment by Difegue** [comment]
If you enable debug mode, you'll get some extra logs instead of the black raptor. Those should be useful!

**Comment by Difegue** [comment]
Turns out #266 was a global issue, so it was probably the source of this bug as well. Closing for now, hopefully I won't have to reopen it a second time 👀
