### ISSUE TITLE
Shinobu doesn't start, no logs.

### ISSUE THREAD

**Issue by xXmeme-machineXx** [Difegue/LANraragi#235]
**LRR Version and OS**
LRR f17e27250474235ab60b9cb5a56876eb9a9162be (master)
Also happens on dev (9847e9bab17e8a7b14d026f59f2f6d469f53c99a)
Ubuntu 18.04

**Bug Details**
Shinobu worker immediately crashes with no log output even in debug mode.

**Matching Logs**
```
Can't locate File/ChangeNotify.pm in @INC (you may need to install the File::ChangeNotify module) (@INC contains: /ho
BEGIN failed--compilation aborted at ./lib/Shinobu.pm line 25.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/52387080/68928925-31f75d00-0759-11ea-945a-95eeea6f6c69.png)

**Comment by xXmeme-machineXx** [comment]
Seem like `cpanm File::ChangeNotify` fix it. Good idea to document this in the install instruction.

**Comment by Difegue** [comment]
File::ChangeNotify is in the cpanfile -- I suspect you forgot to re-run the installer script after a version upgrade.
