### ISSUE TITLE
Error on WSL Installation

### ISSUE THREAD

**Issue by Cupbox** [Difegue/LANraragi#240]
LRR 1.5
Windows 10

When Lanraragi opens the command windows to install WSL, it throws the following error
'C:\Users\John' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\John Smith\AppData\Local\Temp\MSIAE8E.tmp->

I'm assuming the issue is the space in the path.

**Comment by Difegue** [comment]
You're right -- I think I forgot to add some single quotes to the code [here](https://github.com/Difegue/Karen/blob/dd063874db10234ff907423b7aee77017725db89/Setup/Program.cs#L123), so cmd doesn't know what to do.  

You can circumvent this by installing to a path without spaces for the time being.

**Comment by Cupbox** [comment]
That fixes it. 
Thanks.

**Comment by zer0shikiseihai** [comment]
How did you get around the space in the user home directory? I'm having the same issue and I can't get it to install even if I pick a path without spaces.
