### ISSUE TITLE
[Win10] Trying to use either symlinks or network drive locations borks Lanraragi

### ISSUE THREAD

**Issue by Hakker** [Difegue/LANraragi#244]
**LRR Version and OS**
Win10 0.67 installation. Didn't had luck in Docker also although that could be my wrongdoing

**Bug Details**
Using either symlinks ( mklink /D ) or mapped network drives makes Lanraragi not respond and throwing you the default browsers error page. putting in a normal directory and it works again although it will not scan symlinked folders. and simply goes kaput.

**Matching Logs**
can't find it yet so I made a screenshot of it

**Screenshots**
https://prnt.sc/qhyjnc
first one is a symlink from the D drive and 3rd folder but then a subfolder which refers to the S drive.
The second one is the actual S drive location.
3rd one is working but shows nothing.

**Comment by Difegue** [comment]
I'll have to try a bit on my side, but looking at the screenshot this seems like either a limitation of WSL or Perl's File::Find with NTFS links -- Not sure it's an easy fix.

**Comment by Difegue** [comment]
For network drives, I thought those were auto-mounted by WSL like regular NTFS drives, but apparently not! According to [this](https://docs.microsoft.com/fr-fr/archive/blogs/wsl/file-system-improvements-to-the-windows-subsystem-for-linux) post, you have to create the mountpoint manually.  
`mkdir /mnt/y && mount -t drvfs Y: /mnt/y`  

After that, launching LRR will work as usual. Detecting and pre-mounting network drives before launching the app is a reasonable enhancement request.  

Haven't looked into NTFS symlinks yet.

**Comment by Hakker** [comment]
I hope you tested this and that it works, because here the new release doesn't fix it. Also can't give a log or even a screenshot because the launcher that should open the log says it can't find it.

**Comment by Difegue** [comment]
Worked when I tested it, thanks for assuming that much. 😅  
Not sure I understand your second sentence tho, do you mean that the status console isn't showing at all when you try to open it?

**Comment by Hakker** [comment]
No when opening the log through the tray app I get the following:

Error: Could not find config file ./tools/DockerSetup/supervisord.conf For help, use /usr/bin/supervisord -h
Also later on I get to see the following when adding a network share.
touch: content: no such file or directory

I simply try to select a network share in Karen in this case T:\share\comics on port 5151 which is open but firefox here after starting simply gives me an unable to connect on localhost:5151

**Comment by Difegue** [comment]
`/tools/DockerSetup` means you're using an old version of the launcher somehow -- The path to the supervisord.conf file has changed since then.

**Comment by Hakker** [comment]
you were right for some reason an old instance of karen was still being launched. When removing it manually it worked.
A small note to check since I didn't specifically check for it is if the uninstaller removes Karen during uninstallation. I didn't uninstall before installing the new version which might have caused the issue. I hope this will help.

**Comment by Difegue** [comment]
I'll add a todo to my list to check if karen is properly replaced during upgrades -- This is normally handled by WiX on its own but well, you never know. Glad you got it working!
