### ISSUE TITLE
Search suggestions do not appear if they begin with a - for exclusion

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#247]
Pretty self explanatory.
![image](https://user-images.githubusercontent.com/15137035/72658904-5dbbeb00-3a07-11ea-92bb-12937d2327d7.png)
![image](https://user-images.githubusercontent.com/15137035/72658910-6ad8da00-3a07-11ea-8ab6-67d324f9633d.png)
Obviously clicking on the suggestion should keep the `-` at the front for exclusion as well.

**Comment by Difegue** [comment]
While I pushed a fix for exclusion, autocompletion still won't help for the other possible characters. (wildcards and quotes)  
That'd require wildly expanding the filter functions beyond their current dumb regex.
