### ISSUE TITLE
input data from text inside archive

### ISSUE THREAD

**Issue by damarsimple** [Difegue/LANraragi#25]
I downloaded a doujin from a program called hdoujin downloader that supports entering doujin info into text within the archive

can lanraragi input tags data from within the text in the archive
using google translate
sample info.txt
![untitled](https://user-images.githubusercontent.com/10891460/36678601-c7209f58-1b43-11e8-9736-ffdf7ee70ccd.png)

**Comment by Difegue** [comment]
Very much possible, but you'd need to write a plugin for it.
Once 0.5 is out, I plan to write a demonstration plugin for [eze](http://dnsev-h.github.io/eze), which stores txt files inside archives containing metadata in a similar fashion.

I'd advise you to wait for that plugin, then study/tweak it to fit hdoujin downloader's format.

**Comment by damarsimple** [comment]
Thank You !
