### ISSUE TITLE
Regression: Windows installer no longer works on nightly builds

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#251]
After this commit: https://github.com/Difegue/LANraragi/commit/5a583e00f81c2bf69ace1bfb6cd8bcad2128411c was made, the windows installer no longer works. The cmd window opens during the installation and gives me the following error: 
```
The filename, directory name, or volume label syntax is incorrect.
C:\Users\Someone\AppData\Local\Temp\MSI5529.tmp->
```

**Comment by Difegue** [comment]
A nightly with the fix is building.

fucking cmd lemme tell ya
