### ISSUE TITLE
Search suggestions should treat underscores as spaces

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#254]
![image](https://user-images.githubusercontent.com/15137035/73131620-76a74a80-405e-11ea-9cd1-215c0f1b60db.png)
![image](https://user-images.githubusercontent.com/15137035/73131628-98083680-405e-11ea-85f7-32f60b08f5f9.png)

This is probably only really helpful for people with tons of galleries and when trying to find something with a pretty generic name, but should still be fixed nonetheless.

**Comment by Difegue** [comment]
Underscores normally match any character; It'd be better for autocompletion to actually follow the full syntax but that implies digging into the innards of [Awesomplete](https://leaverou.github.io/awesomplete/) a bit more than what I did for the "-" operator.  

The code handling suggestions is [here](https://github.com/Difegue/LANraragi/blob/9f30610d9027dc6baea064d2b34e2161b808a2e1/public/js/index.js#L191), if anyone wants to take a stab at it.

**Comment by siliconfeces** [comment]
Search terms are separated by commas now, so I guess this isn't necessary anymore?
