### ISSUE TITLE
[question] Managing host volume with Priviliges using Portainer 

### ISSUE THREAD

**Issue by wongsaraf** [Difegue/LANraragi#263]
So I decide to move my docker installation on another PC using Openmediavault and Docker plugin.
I managed to install Lanraragi and running it, binding the content and host volume to the OMV Shared Folders.

At first the content folder works normally because I not yet added limitation on how to access the content and database folder with username and password.
But when I added user and password to content folder using OMV, Lanraragi cannot access the folder anymore.

```

Can't opendir(/home/koyomi/lanraragi/content): Permission denied


 at ./lib/Shinobu.pm line 129.



2020-03-17 15:25:58,941 DEBG 'lanraragi' stderr output:


Can't opendir(/home/koyomi/lanraragi/content): Permission denied


 at /usr/local/share/perl5/site_perl/File/ChangeNotify/Watcher/Inotify.pm line 172.
```

I know I need to add my Lanraragi my user and password so it can access the folder again, but the problem is I didn't know where or how to do it.
Sorry if this such a trivial problem, but i kinda new with Portainer.

**Comment by Difegue** [comment]
The permissions in the container are inherited from the USERID/GROUPID combo you can set as environment variables.  

I don't know how OMV does it, but I guess you'd need to get the UID/GID of an user that has access to the folder, and give that to the container. See https://sugoi.gitbook.io/lanraragi/installing-lanraragi/docker#changing-the-port .

**Comment by wongsaraf** [comment]
I got this error when I tried that.
`root@openmediavault:~# docker run [wassup] -e LRR_UID=``id -u $USER`` -e LRR_GID=``id -g $USER`` difegue/lanraragi
docker: invalid reference format.
See 'docker run --help'.
`
After that I tried using UID/GID i used when I installed Plex container.
Plex still can read host volume behind user privileges, so I disable plex container.
Copy the UID/GID to newly build container.
And still got this error both using the the uid/guid 9001/9001 or the one from Plex.

https://pastebin.com/eGfwpYTe

https://pastebin.com/Jfcv9NPW

A screencap of Plex and Lanraragi container.
https://imgur.com/a/NDS8oYr

**Comment by Difegue** [comment]
Looking at the portainer config at a glance, things should work -- You might want to temporarily try setting UID/GID to 0 for the LRR container so it runs as root. If you're still getting permission issues with that, the issue might come from somewhere else.

**Comment by wongsaraf** [comment]
I fixed the issue, someone on OMV discord said I need to change the UID to 1000.
I set the LLR_UID to 1000 without changing the LRR_GUID and now Lanraragi got privilege access to content folder.
