### ISSUE TITLE
[bug] OMV Docker portainer can't reset database 

### ISSUE THREAD

**Issue by wongsaraf** [Difegue/LANraragi#266]
OMV 5.3.8-1 Usui
Portainer 1.23.1 

Unable to reset database, the only way to reset everything is to remove lanraragi docker installation and removed the database in database folder.
I doubt its permission issue because the database can write new archives normally.

This error come out when I try to reset database

https://imgur.com/a/188NuIZ
https://pastebin.com/n5LS4xWY

redis logs
`27:M 18 Mar 2020 15:59:33.645 # Server initialized
27:M 18 Mar 2020 15:59:33.645 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
27:M 18 Mar 2020 15:59:33.645 * DB loaded from disk: 0.000 seconds
27:M 18 Mar 2020 15:59:33.645 * Ready to accept connections`

Mojolicious logs

https://pastebin.com/aCXKDv58

Also got this when i try to clear the temporary folder.

`Error while cleaning Temporary Folder :
Problem unlinking /home/koyomi/lanraragi/public/temp: cannot remove directory: Permission denied `
The temp folder actually got cleared, the button seem working normally despite showing that error notice.

**Comment by Difegue** [comment]
Huh, turns out the `drop_database` endpoint was wired incorrectly on the JS side all this time.  
That's embarassing, I wonder when that happened?
