### ISSUE TITLE
Moving the thumb folder to database folder

### ISSUE THREAD

**Issue by wongsaraf** [Difegue/LANraragi#267]
Currently the content folder will create a out of place folder called thumb in it.
I wished we can moved it to database folder so everything that related to Lanraragi database will be in one single folder.

**Comment by Difegue** [comment]
The database location is completely dissociated from the server, so moving it to another folder was easy enough for Docker installs.  
For thumbs it's a bit more complex as that is referenced directly in the server code -- changing this would mean finally cracking open the bottle and adding an extra (optional)setting for a second folder.  
Certainly doable though!

**Comment by polak14** [comment]
I'd definitely  like to see  this if  possible. In  my case I would prefer to have the thumbs on the SSD instead of the big content folder on the spinning drives that take long time to spin up etc.

**Comment by Difegue** [comment]
![683bd073c7f957b672e56fff338791732e5ca18c7ecac2dca93e421cf724ffda](https://user-images.githubusercontent.com/8237712/110699302-feaecc00-81ee-11eb-9b1e-7de0e4c3c29c.jpg)
