### ISSUE TITLE
Archives with unicode folder names not opening

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#27]
Hello
As mentioned, an archive with unicode folder names i.e
D-Frag! (ディーふらぐ! ) 02.zip
  └─D-Frag! (ディーふらぐ! ) 02
      └─001.jpeg
      └─002.jpeg
will not open and keep reloading.

**Comment by xd1986k** [comment]
I should also mention that while an archive having files with Unicode filenames may load, it does not generate a thumbnail. 
Also the file name section above the image in the viewer does not display unicode and shows the hex codes of each character..

**Comment by Difegue** [comment]
Internal unicode folders often give messy results. I'll look it up.

**Comment by Difegue** [comment]
Turns out the core File::Find Perl module, which is used to find images in extracted archives, doesn't play too well with UTF8. 

Switching up to its [fully aware UTF-8 version seems to fix those issues.](https://metacpan.org/pod/File::Find::utf8). Commit soon.

**Comment by Difegue** [comment]
I ran into some Docker issues on the last few commits (for something completely unrelated), but 31cd64857c7bfae0154ab985ef1a782fe471f527 built fine and contains the fix for this.

**Comment by Difegue** [comment]
Closing this as I haven't found the issue again.
