### ISSUE TITLE
Error on Clean Database

### ISSUE THREAD

**Issue by w1kl4s** [Difegue/LANraragi#270]
**LRR Version and OS**
v0.6.9, native, debian 10

**Bug Details**
Error thrown out while performing Clean Database.

**Matching Logs**
`[2020-04-05 00:40:59.69168] [8239] [error] [qp6HAZRh] Can't locate object method "FIRSTKEY" via package "Parallel::Loops::TiedHash" at /home/w1kl4s/lanraragi/script/../lib/LANraragi/Utils/Generic.pm line 71.`

**Comment by Difegue** [comment]
I've received a few reports about this bug already but hadn't committed it to a github issue -- Thanks for doing that.  
I plan to fix this for 0.7.0.

**Comment by Difegue** [comment]
Welp, that was easier than I thought.
