### ISSUE TITLE
search.t not working

### ISSUE THREAD

**Issue by Bl4Cc4t** [Difegue/LANraragi#271]
First of all, I’m not sure how I overlooked that. Sorry about that, this delays the native homebrew inclusion of LRR for yet another subrelease :/
It’s pretty strange though, since it worked previously…

---
The `search.t` test does not work.
```
Failed 15/17 subtests 
```
That is most likely due to the fact that the 5 sample comics from the demo server are not present on the testing system. I’m not sure what to do about that. Maybe you can come up with something else, since bundling the 5 comics is not really an option…

**Comment by Bl4Cc4t** [comment]
On another note, the `chaika.moe SHA-1 reverse search test` did not work either, but I saw that you updated `plugins.t`. With the new version, that test succeeded again.

**Comment by Difegue** [comment]
The tests 100% don't need the sample comics to work, since they're ran in github actions from a clean environment on each push.  

I did some digging a few days ago and found an issue in the formula I gave you a PR for -- https://github.com/Bl4Cc4t/homebrew-core/pull/1 , the tests weren't running at all until I added this.  Can't remember if that fixed the 15/17 problem or not.  

I suggest we keep the PR at homebrew-core open so we can keep cross-checking against their CI to see if anything's wrong. :) Hopefully we'll get this clean and working for 0.7.0.

**Comment by Bl4Cc4t** [comment]
wtf, I didn’t even saw that you made a PR.
I already closed the PR though

**Comment by Difegue** [comment]
Found the issue with homebrew:  
While the tests don't need the example comics, the search engine **does** verify if the file linked in the database exists before including it in a search result.  

The mocks bypass this by setting all the files to README.md, which I thought would always be there...
![image](https://user-images.githubusercontent.com/8237712/79689529-c0ff2880-8255-11ea-9e48-05225147d4f1.png)
Except the homebrew version uses different paths, so I'm hosed. 😓 I'll have a fix pushed shortly.

**Comment by Difegue** [comment]
https://github.com/Difegue/LANraragi/commit/4359686022cd7bcb198e484c03aac2a3b1fde36c fixes it. I've successfully ran `brew install, brew test` and `brew audit` with this version and the existing Formula.  

I plan to put out a hotfix release soon for various other things, so maybe this will finally be the one.

**Comment by Difegue** [comment]
https://github.com/Difegue/LANraragi/runs/601967009?check_suite_focus=true I've added some CI for Homebrew on my side as well, so I can effectively track if code changes break the full install/test/audit suite.  

Brew doesn't seem to allow building a formula off a local tarball easily, so I just went ahead and stashed a formula on Gist referring to the dev branch, that I build through github actions. https://gist.github.com/Difegue/e0d291f0274b32ec0834fcad795a1f89

**Comment by Bl4Cc4t** [comment]
Okay, looks good :D
You could also create a PR yourself at core once you’re ready 
If you need any help, feel free to ping me
