### ISSUE TITLE
Using LRR_NETWORK to change the outgoing port of the container flags it as unhealthy

### ISSUE THREAD

**Issue by wongsaraf** [Difegue/LANraragi#272]
Saw these inside portainer Lanraragi's docker logs during idle.
I don't know if these are errors, I only reporting this because inside Portainer Lanraragi container state is unhealty.
https://imgur.com/a/YslGZXG

2020-04-16 09:03:31,597 DEBG 'lanraragi' stderr output:
Use of uninitialized value $sortkey in concatenation (.) or string at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Search.pm line 33.
2020-04-16 09:11:07,574 DEBG 'lanraragi' stderr output:
Use of uninitialized value $newfilter in string eq at /home/koyomi/lanraragi/script/../lib/LANraragi/Controller/Search.pm line 78.
2020-04-16 09:11:07,574 DEBG 'lanraragi' stderr output:
Use of uninitialized value $untaggedf in string eq at /home/koyomi/lanraragi/script/../lib/LANraragi/Controller/Search.pm line 78.
2020-04-16 09:11:07,639 DEBG 'lanraragi' stderr output:
Use of uninitialized value $sortkey in concatenation (.) or string at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Search.pm line 33.
2020-04-16 09:15:40,907 DEBG 'lanraragi' stderr output:
Use of uninitialized value $newfilter in string eq at /home/koyomi/lanraragi/script/../lib/LANraragi/Controller/Search.pm line 78.
Use of uninitialized value $untaggedf in string eq at /home/koyomi/lanraragi/script/../lib/LANraragi/Controller/Search.pm line 78.
2020-04-16 09:15:40,967 DEBG 'lanraragi' stderr output:
Use of uninitialized value $sortkey in concatenation (.) or string at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Search.pm line 33.
2020-04-18 02:11:51,876 DEBG 'lanraragi' stderr output:
Use of uninitialized value $newfilter in string eq at /home/koyomi/lanraragi/script/../lib/LANraragi/Controller/Search.pm line 78.
Use of uninitialized value $untaggedf in string eq at /home/koyomi/lanraragi/script/../lib/LANraragi/Controller/Search.pm line 78.
2020-04-18 02:11:51,974 DEBG 'lanraragi' stderr output:
Use of uninitialized value $sortkey in concatenation (.) or string at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Search.pm line 33.
2020-04-18 08:02:06,532 DEBG 'lanraragi' stderr output:
Use of uninitialized value $newfilter in string eq at /home/koyomi/lanraragi/script/../lib/LANraragi/Controller/Search.pm line 78.
Use of uninitialized value $untaggedf in string eq at /home/koyomi/lanraragi/script/../lib/LANraragi/Controller/Search.pm line 78.
2020-04-18 08:02:06,620 DEBG 'lanraragi' stderr output:
Use of uninitialized value $sortkey in concatenation (.) or string at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Search.pm line 33.

This is what happen inside redis log

5199:C 16 Apr 2020 09:01:06.106 * DB saved on disk
5199:C 16 Apr 2020 09:01:06.107 * RDB: 4 MB of memory used by copy-on-write
27:M 16 Apr 2020 09:01:06.168 * Background saving terminated with success
27:M 16 Apr 2020 09:03:34.139 * 1 changes in 1 seconds. Saving...
27:M 16 Apr 2020 09:03:34.139 * Background saving started by pid 5212
5212:C 16 Apr 2020 09:03:34.277 * DB saved on disk
5212:C 16 Apr 2020 09:03:34.278 * RDB: 4 MB of memory used by copy-on-write
27:M 16 Apr 2020 09:03:34.340 * Background saving terminated with success
27:M 16 Apr 2020 09:11:10.288 * 1 changes in 1 seconds. Saving...
27:M 16 Apr 2020 09:11:10.289 * Background saving started by pid 5261
5261:C 16 Apr 2020 09:11:10.428 * DB saved on disk
5261:C 16 Apr 2020 09:11:10.428 * RDB: 4 MB of memory used by copy-on-write
27:M 16 Apr 2020 09:11:10.489 * Background saving terminated with success
27:M 18 Apr 2020 02:11:59.829 * 1 changes in 1 seconds. Saving...
27:M 18 Apr 2020 02:11:59.830 * Background saving started by pid 20310
20310:C 18 Apr 2020 02:11:59.967 * DB saved on disk
20310:C 18 Apr 2020 02:11:59.968 * RDB: 4 MB of memory used by copy-on-write
27:M 18 Apr 2020 02:12:00.030 * Background saving terminated with success
27:M 18 Apr 2020 08:02:10.393 * 1 changes in 1 seconds. Saving...
27:M 18 Apr 2020 08:02:10.394 * Background saving started by pid 22460
22460:C 18 Apr 2020 08:02:10.532 * DB saved on disk
22460:C 18 Apr 2020 08:02:10.533 * RDB: 4 MB of memory used by copy-on-write
27:M 18 Apr 2020 08:02:10.595 * Background saving terminated with success

**Comment by Difegue** [comment]
Nothing wrong in those logs really, the unhealthy status pops up if the app doesn't respond reliably on port 3000 for a given amount of time.

3000 is hardcoded in the healthcheck, so if you've modified the outgoing port on the Docker side through LRR_NETWORK, I guess it'd show up as unhealthy...

**Comment by Difegue** [comment]
While the healthcheck could be modified to take the environment variable into account, said variable is pretty flexible and can do a lot of stuff (SSL, systemd fd's and the like), so tracking it in the healthcheck would be a pain, considering you can just leave it to 3000 and remap ports through Docker itself.  

That's a wontfix for me.

**Comment by Salvora** [comment]
I have tried to do as recommended but couldn't get rid of the unhealthy status. I am using SSL for the LLR_NETWORK.
I tried a couple of combinations but it is always unhealthy (when using SSL).

```
    ports:
      - 3000:3000
    environment:
      LRR_NETWORK: "https://*:3000?cert=/ssl/fullchain.pem&key=/ssl/privkey.pem"

    ports:
      - 3000:3000
      - 3333:3333
    environment:
      LRR_NETWORK: "https://*:3333?cert=/ssl/fullchain.pem&key=/ssl/privkey.pem"

    ports:
      - 9340:3000
    environment:
      LRR_NETWORK: "https://*:3000?cert=/ssl/fullchain.pem&key=/ssl/privkey.pem"
```
