### ISSUE TITLE
[Bug] Plugin upload not working after failed upload

### ISSUE THREAD

**Issue by Mayriad** [Difegue/LANraragi#275]
*This issue comes from #274 my big list of LRR bugs and suggestion. Please refer to that to see details of my setup and usage.*

**LRR Version and OS**

LANraragi for Windows 0.6.9 (MSI installer) on Microsoft Windows 10 version 10.0.18363.720. Archives are located on a NAS and accessed via a mount point in the content folder.

**Bug Details**

After a plugin is uploaded to LANraragi using the "upload plugin" button but fails due to some problem like syntax error, uploading the fixed, working version of the same plugin can lead to this error popup:

```
Error uploading plugin
Could not load namespace LANraragi::Plugin::Metadata::*! Your Plugin might not be compiling properly.
Here's an error log: Attempt to reload /home/koyomi/lanraragi/lib/LANraragi/Plugin/Metadata/*.pm aborted. Compilation failed in require at /home/koyomi/lanraragi/script/../lib/LANraragi/Controller/Plugins.pm line 167.
```

This error will not go away until LANraragi is restarted i.e., after a reboot the same plugin will be successfully uploaded, but before that uploading this plugin will always give this error. You should be able to reproduce this if you intentionally break a plugin, upload it, and finally upload the working version again.

**Comment by Difegue** [comment]
See #286.
