### ISSUE TITLE
[Bug] Date_added namespace still hiding truly untagged archives

### ISSUE THREAD

**Issue by Mayriad** [Difegue/LANraragi#277]
*This issue comes from #274 my big list of LRR bugs and suggestion. Please refer to that to see details of my setup and usage.*

**LRR Version and OS**

LANraragi for Windows 0.6.9 (MSI installer) on Microsoft Windows 10 version 10.0.18363.720. Archives are located on a NAS and accessed via a mount point in the content folder.

**Bug Details**

The dates added by the DateAdded plugin are `date_added:` tags, and all galleries will become "tagged" when this plugin is used, even if some of them are not linked to source and have no real metadata. This plugin will therefore hide truly untagged archives that require manual tagging.

Difegue commented in #274 that:

> IIRC the "look for untagged archives" functions already ignore the dateadded namespace for this exact reason. If you have a clean reproduction case please file a separate bug issue.
> I don't plan on modifying LRR's data model at the time, which means no extra storage fields for dates.

However, at my end the "look for untagged archives" functions never ignores the `date_added:` namespace, so any archive that has such a tag will not be included in the list of untagged archives. I cannot provide a reproduction case because everything is a reproduction case on my side.

As Difegue said, this problem can be fixed by ignoring the namespace, but I think in the long term dates should eventually be stored and handled differently from tags, so that they can be actually useful in advanced searching and sorting of archives. I will probably bring this up again in the distant future.

By the way, as I mentioned in #279, I think it will be better to rename the `date_added:` namespace to `imported:`, because two words + underscore looks out of place among single word namespaces.

**Comment by Difegue** [comment]
I really thought I'd done this already, but apparently not! Thanks again for reporting this.  

re: changing the namespace, doing so would break compatibility with Ichaival, which has extra features available if you use `date_added` namespaced tags. So it's not in the cards for the time being.
