### ISSUE TITLE
E-H Plugin 

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#28]
Hey.
I'm guessing standard metadata fetching is only using the title and only the first result of multiple hits is requested? I'm asking because most of my tags are from french and russian galleries. English and Japanese galleries tend to be the most extensively tagged and accurate. So I was wondering whether you could add the tags scraped from file during query like so 
parody:"fate grand order$" language:english$ "Blah Blah(Title)"

**Comment by Difegue** [comment]
> I'm guessing standard metadata fetching is only using the title and only the first result of multiple hits is requested? 

Yeah that's basically how it works - I used to add the author into the mix but it wasn't very helpful. 

I'll add language tags into the search when they are present - This should give more precise results.

**Comment by xd1986k** [comment]
Speaking of, could you add an option to specify preferred language? Seeing as japanese galleries do not specify language in their titles.

**Comment by Difegue** [comment]
Done in 1d66636f92d0f881219b23eaea38f0644695910d - Although this sacrifices the option to disable reverse image search due to the way plugin arguments currently work.  

Will open another issue for that.
