### ISSUE TITLE
[Suggestion] Better gallery lookup routine for the E-Hentai plugin

### ISSUE THREAD

**Issue by Mayriad** [Difegue/LANraragi#280]
*This issue comes from #274 my big list of LRR bugs and suggestion. Please refer to that to see details of my setup and usage.*

I think the subroutine `lookup_gallery()` in the E-Hentai plugin can use more and better steps to find the source. Right now, depending on `$usethumbs`, it is either a title search using the filename or a reverse image search using the cover. It is too prone to no-match and mismatch.

I have not deeply tested this issue and any alternatives, because I have been using and testing my own metadata plugin, but I think at least the plugin can use two steps, where it will try the image search for archives left unmatched after title search. There is probably room for more complex methods that can increase its accuracy from like 95% to 99%.

**Comment by Difegue** [comment]
After re-reading, the current behavior of the plugin is indeed image search -> title search if thumbnails fail.  
Closin' this 🙌

**Comment by Mayriad** [comment]
Oh, my bad then. Still, it could use safer methods if any developer is interested.
