### ISSUE TITLE
[Suggestion] Delay between requests for auto-plugin

### ISSUE THREAD

**Issue by Mayriad** [Difegue/LANraragi#281]
*This issue comes from #274 my big list of LRR bugs and suggestion. Please refer to that to see details of my setup and usage.*

I think the auto-plugin does not have a effective delay between metadata requests, or the delay is not safe enough. I have only used LANraragi to retrieve metadata from EH and, from my experience, adding 1,000 - 2,000 galleries would lead to a temporary ban.

After tests using the batch tagging functionality, I think a delay setting of 4 second is the minimum required to safely avoid a ban. Alternatively, instead of pausing a little after every archive, LANraragi can use a longer break after quickly tagging a small batch of archives.

**Comment by Asinin3** [comment]
Yeah it would be good if there were some sane defaults in place, and when you set it to use a plugin to scan the archive files for local tags, e.g with eze plugin, it should set it back to 0.

**Comment by Difegue** [comment]
It is true that there's a bit of a discrepancy between batch allowing delays and auto just going full blaze it 420.  
Default values could be added in the plugin metadata and leveraged in both auto and batch, do you have any values in mind ?  
I think there were some already in the old mega-issues I closed (gomen), so I'll go take a look at that whenever I get to this.

**Comment by Mayriad** [comment]
> Default values could be added in the plugin metadata and leveraged in both auto and batch, do you have any values in mind ?

That would be good. I imagine different sites would have different levels of tolerance. I can only say I found a delay of 4 seconds to be safe for EH when I tested batch tagging. 3 seconds once got me a temporary ban.

**Comment by Difegue** [comment]
Metadata plugins can now specify a `cooldown` value which will be displayed as a suggestion in batch tagging and used internally in auto-tagging.  

![image](https://user-images.githubusercontent.com/8237712/94573104-0d717a00-0272-11eb-94cc-1eacc2699f77.png)
