### ISSUE TITLE
[Bug] Plugin update not effective until LANraragi is restarted

### ISSUE THREAD

**Issue by Mayriad** [Difegue/LANraragi#286]
*This issue comes from #274 my big list of LRR bugs and suggestion. Please refer to that to see details of my setup and usage.*

**LRR Version and OS**

LANraragi for Windows 0.6.9 (MSI installer) on Microsoft Windows 10 version 10.0.18363.720. Archives are located on a NAS and accessed via a mount point in the content folder.

**Bug Details**

When I upload a new version of an existing plugin to LANraragi using the "upload plugin" button, some types of changes are not effective until I restart LANraragi. Some changes like changes to descriptions of plugin options are visible after a refresh, but other changes like a new `$logger->info()` line, or fixing missing arguments in function calls are only effective after rebooting LANraragi. These are also the ways to reproduce this bug.

When a plugin is uploaded, the message says "refresh the page to see it," so I expect the update to be fully effective without having to restart the program. It would help developers test plugins if you actually fix this, but if you think there is not enough need, you can avoid this problem by detecting whether it is a new plugin or a update in `Plugin.pm` and changing the message to say something like "you may need to restart LANraragi to see some changes."

**Comment by Difegue** [comment]
I was lowkey waiting for https://github.com/Difegue/LANraragi/pull/283 before looking at this bug 😉 

Reading through the details, I think the problem stems from the old class staying loaded into perl's @INC somehow.  (But not the metadata subroutine? It's weird) I'll look it up.

**Comment by Mayriad** [comment]
#275 could have the same cause.

**Comment by Difegue** [comment]
Fixed it, as expected there was some INC fuckery at hand.  

This commit fixes both issues, although now whenever you upload a plugin that doesn't compile, it'll still show up in the plugin list until you restart the app.  
Since you can now upload fixed versions of the plugin and they'll be loaded properly, I don't think it's a problem.
