### ISSUE TITLE
Tachiyomi extension not working with latest version of Tachiyomi

### ISSUE THREAD

**Issue by MystifyingShadow** [Difegue/LANraragi#289]
**LRR Version and OS**
Tachiyomi 0.9.2 with LANraragi extension 1.2.1

**Bug Details**
It seems that the latest version of Tachiyomi broke the LANraragi plugin, LANraragi doesn't appear on the sources menu.

**Comment by Difegue** [comment]
I don't maintain the Tachiyomi extension, you should bring this issue up at https://github.com/inorichi/tachiyomi-extensions .
