### ISSUE TITLE
[Suggestion] Move and rename galleries by changing filepaths on metadata page

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#296]
Moving/renaming a gallery/archive is a process that is a bit clunky at the moment. Especially if you have the files on a server you interface to via FTP. While that's not LRR's fault, I think it'd be great if we could simply change the path in the metadata page for a gallery and LRR would move/rename the the gallery and update the database to point to the new location.

At the moment, doing this manually isn't picked up by LRR, the old location will still be in the database, and LRR will try and add the gallery from the new location and complain about a duplicate, and that the gallery in the old location is now missing.

You can run a gallery clean and have LRR add the gallery again from the new location. But that means you lost gallery tags and pagecount, LRR would have to regenerate the thumbnail, and if the tags were custom, or no-longer available it'd be even more problematic.

If LRR could pick up on gallery moves or renames with inotify automagically this could be closed though.

**Comment by Difegue** [comment]
> If LRR could pick up on gallery moves or renames with inotify automagically this could be closed though.

iirc this has been done with the Shinobu rewrite in 0.7.7. Closing! 🙌
