### ISSUE TITLE
Preload Images

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#3]
Would it be possible to add preloading 5 images before and after the current image? And navigating via AJAX for instant page change?(I have no idea what I'm talking about and just typed the description of this [script](https://openuserjs.org/scripts/anka-213/Webcomic_Reader) which does the above for Ex among other sites.

**Comment by Difegue** [comment]
While this is certainly doable in the current architecture (The software extracts everything from an archive as soon as it's opened for fast access), I'm not really seeing the benefits one'd get from basically switching the reader from a series of HTML pages to a all-in-one JS page. 

Keeping this as enhancement for now, but you might want to ask the creator of the webcomic reader script to add support to LANraragi-powered pages.

**Comment by xd1986k** [comment]
I'll try asking.
Anyhow the only benefit I could give you is speed. LANraragi loads a new page in about a second while the script will switch instantaneously. Do give the script a go and see for yourself.

**Comment by Difegue** [comment]
The reader improvements planned for the next release will include this, as well as a thumbnail preview of the entire archive(been wanting to do this for a while!) and saving the last page read in browser storage (for picking back up where you left).

I've started work on converting the whole shebang to full-JS, and it **is** way faster.

**Comment by Difegue** [comment]
Done as of the last few commits. Gonna try getting 0.4 out before the end of the year.
