### ISSUE TITLE
Lanraragi doesn't resized thumbnail in thumb folder 

### ISSUE THREAD

**Issue by wongsaraf** [Difegue/LANraragi#300]
It seem the latest update broke something.
Lanraragi usually create a jpg files with size around 50KB, now it only copy the first file in the archive and put them in the thumb folder without resizing them.
My Lanraragi thumb folder now is around 8 Gigabytes with only 6600 jpg files.

**Comment by Difegue** [comment]
By "latest update", do you mean 0.6.9-EX or the nightlies ? 
Thumbnailing shouldn't have changed that much in the nightlies -- If you just upgraded to the EX release make sure you have imagemagick installed.

**Comment by wongsaraf** [comment]
The version said it is "Version 0.6.9 - "The Myth" " in the setting.
I created it using docker command difegue/lanraragi:latest at 2020-04-26.
There are no logs that mention anything about thumbnails processing or errors in debug mode.
I wasn't the first one that notice about this bug, how do I install imagemagick for Lanraragi in docker?

**Comment by Difegue** [comment]
If it's Docker it's installed normally so no extra work on your side.  
You are however out of date if the settings don't show 0.6.9-EX.  
Make sure you pulled the latest err, `latest` and check if the bug is still there.

**Comment by wongsaraf** [comment]
Removed the docker image and try to recreate the container again.
Deleted all the thumbnails file in the thumbs folder before starting Lanraragi.
Now it said " Version 0.6.9-EX - "Covid Cahoots" " in the setting.
Thumbnail still used original image instead of resizing them.

I tried to enable the Resizing function in setting to see if imagemagick actually working.
Here the are the size of the image when I opened the gallery and the thumbnail of said gallery.


https://anonfile.com/beW4E3x7oe/Capture_PNG

**Comment by Asinin3** [comment]
I can confirm this has been happening since 0.6.9 The Myth. Affecting me on my WSL install as well.

**Comment by Difegue** [comment]
Should be good now -- This thumbnailing code was pulled out of an old version, maybe it was wrong all this time?

**Comment by Asinin3** [comment]
Confirmed fixed
