### ISSUE TITLE
Random CPU usage during idle with today Nightly

### ISSUE THREAD

**Issue by wongsaraf** [Difegue/LANraragi#302]
Recreate docker version with difegue/lanraragi:nightly to fix'd the thumbnail problem.
Everything seem normal for a moment then I notice my Netdata system overview stats that usually idle at 5% suddenly got random spike every 1 seconds after I installed Lanraragi nightly version.

Already checked the logs, nothing running or doing anything unusual with the database or plugins.
Nothing using Lanraragi from the network, thumbnail doesn't write anything anymore.
No disk usage from Lanraragi, can't find the source of random CPU usage spike.
Everything that said Auto already got turned off.

What weird was Lanraragi who its always Building Filemap after a restart, it used less CPU usage.
But once it done building and the logs looks idle, the CPU usage still goes on and higher with one second interval between them.

The other things that looks different is I got perl keep using my CPU also and never goes down.
If I disable Lanraragi, the perl usage also stopped.

https://imgur.com/a/TSSXH2F

**Comment by wongsaraf** [comment]
I tried roll back using the Latest instead of Nightly version.

The problem is gone, it seem the bug is happening only in nightly version.

**Comment by Difegue** [comment]
I'm testing 0.7.0 for release and did notice huge cpu spikes in Shinobu.pm -- It appears the filewatcher is reverting to the default on Docker images again:  

```
[2020-05-21 16:08:37] [Shinobu] [debug] Watcher class is File::ChangeNotify::Watcher::Default
```

**Comment by Difegue** [comment]
Hmm, I said back when we refactored the Dockerfile that installing Linux::Inotify2 manually wasn't needed as it's done in the installer, but I'd forgotten we don't actually run the full installer in Docker builds. 😅 This commit should restore previous performance.
