### ISSUE TITLE
Feedback on categories in nightly build

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#305]
While it's still WiP there's a few small things that would make the implementation of categories better.

- Clicking on show new archives should de-select the (static) category you have selected
- Clicking on a (static) category should de-select the new archives filter
- The list of galleries when creating a static category should be alphabetically sorted. When I went to create a category for a series it required using the browsers search functionality for every chapter to find it in the list rather than just finding the first chapter and adding them all as they would be next to each other

Perhaps have an option to display the category in the index as a single gallery, and when you open it, it opens the first page of the first gallery inside the category instead of still showing each individual chapter? I thought it would work this way to help keep people's indexes being too messy.

**Comment by Difegue** [comment]
I added alpha sorting in the commit fixing tag suggestions.  
The thing with the new filter feels oddly specific, shouldn't it also deselect the untagged archives filter if you have that on ? I think being able to combine filters is a strength and shouldn't be nerfed unnecessarily.  

Sliding categories alongside regular galleries in the index was the initial plan, but mixing it in with server-side search would've been a mess so I dropped it. Now that the data model is in place tho, there's nothing stopping further clientside modifications in later releases. 😎

**Comment by Asinin3** [comment]
I just think that since static categories are galleries that are selected manually, i can't see many people wanting to filter out a static category from newer or older archives, or untagged ones at that. It was just a little bit of a nuisance having to select and deselect the new archives filter each time. It was more about trying to stop the initial "why aren't my galleries showing" then trying to nerf the filters.

For dynamic categories it makes sense though.

**Comment by Asinin3** [comment]
As the main sorting issue was fixed and the rest was more of a nitpick, I'm closing this issue.
