### ISSUE TITLE
Tag suggestions broken in newest nightly

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#306]
![image](https://user-images.githubusercontent.com/15137035/82136869-820ec380-9851-11ea-8d72-9d9ed434372a.png)
You might already be aware of this, but since the nightly has been upped to 0.7.0 i figured it'd be better to make sure it's reported rather than 0.7.0 needing a hotfix.

**Comment by Difegue** [comment]
Fixed. I bumped he version number but don't plan on making the release straightaway, probably in one or two weeks?
