### ISSUE TITLE
Can't open LRR in browser (API Protected error) in latest nightlies

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#308]
![image](https://user-images.githubusercontent.com/15137035/82268452-302f8000-99ae-11ea-89a2-295c93be8aff.png)
This error has been coming up for me since https://github.com/Difegue/LANraragi/commit/6b16081d97c108c891297a2025a8d828fc139cd1 . However it may have been caused by a commit slightly earlier. The weird part about this error is that it was running fine at first but then seemed to have appeared over-night.

I do have an api key, so I'm thinking maybe Firefox lost my cookie, and is trying to bring up the page where you enter your api password to sign-in, but it can't due to this error.

**Comment by Difegue** [comment]
Should be fixed now, thanks.

**Comment by Asinin3** [comment]
Confirmed working, thanks
