### ISSUE TITLE
Specify listening interface in native install

### ISSUE THREAD

**Issue by jmhickman** [Difegue/LANraragi#31]
Perhaps I'm just dumb and missed it, but I don't see where I can tell a native installed lanraragi to bind to any interface other than loopback/localhost. I looked in the lrr.conf but all I saw was the redis config, and nothing about the npm webserver.

I suppose I could set up a reverse proxy setup with nginx, but I'd rather not. : /

**Comment by jmhickman** [comment]
Okay, apparently it *does* bind to all addresses...it just doesn't *say* so, and neither do the docs.

Not sure what is the intended bahavior at this point, so I'll leave the ticket open.

**Comment by Difegue** [comment]
Yup! Default behaviour is listening on `http://*:3000`, which equals all IPv4 interfaces.  
LRR currently relies on [the built-in Mojolicious webserver](http://www.mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#DEPLOYMENT), which accepts changing the listen locations through the `-l` flag if that's not what you want.

However, it's true that this flag can't currently be used through the `npm start` shortcut.  
So while you can do `perl ./script/lanraragi daemon -l http://127.0.0.1:8000` for example, you can't do `npm start -l http://127.0.0.1:8000` .  This might be worth looking into.

**Comment by Difegue** [comment]
Both `npm start` and `npm run dev-server` now support setting the listening interfaces as an argument.  
All listen locations ![supported by "listen" in Mojo::Server::Daemon](http://www.mojolicious.org/perldoc/Mojo/Server/Daemon#listen) are valid.

**Comment by jmhickman** [comment]
Thanks for taking care of that.
