### ISSUE TITLE
Can we add a right click menu for moving archieves to the category?

### ISSUE THREAD

**Issue by gth7754125** [Difegue/LANraragi#313]
0.70 Version is so great. The dynamic categories can mostly deal with the collected request.
However, **the static category function on Modify Categories Page** is a little bit inconvenient to use since it lists all your archieves directly without thumbnails display.

i guess the static category function mainly has two purpose:
 1) For the archieves which already classified in our local file system.
     Then, Through the  **Subfolders to Categories Script** , we can add them to LANraragi directly.
2) For some people, they use eh tags and dynamic category function to classify the archieves.
    But as  eh tags is limited and the search function cannot implement **the OR Operator** technically, we need to classify some archieves to static folders manually. 

so i expect to add two right click menu such as **Add it to category** and **Add the selected to category** . Or we can have another convenient way to deal with the case **2)** above.

Anyway, we may need to deal with it since the static category can't update automatically.

**Comment by Difegue** [comment]
Thank you for the report.  
Add to Category in the right-click menu was planned but not implemented as I wanted to get the version released. I think it's a good feature to have so I'll try getting it in for 0.7.1.

**Comment by gth7754125** [comment]
Thanks for your reply.

**Comment by Difegue** [comment]
I'll keep this issue open for the time being, so I can track progress and others can +1 it if they want the same feature. :)

**Comment by gth7754125** [comment]
em... As for the category, by the way, can we just merge them into a **Class**?
For example, you can use a kind of super category which has dynamic and static properties:
 1) **Dynamic:** people can create unlimited rules or predicate.
    each rules can make effect dividely, like rule B will not effect rule A.  So you can break the **OR Search Problem**. But you may need to deal with the repeat appending.
2) **Static:** just like static folder, you can add archieves manually.

Sure, it becomes more complicated, but i think it's a better solution in some situations after you add a **fastly appending function** for static category.

**Comment by Difegue** [comment]
The right-click part of this issue is done, so I'll be closing it.  
The class idea can go into a new suggestion issue if you wish to. :)
