### ISSUE TITLE
[Suggestion] Webtoon/Vertical page mode.

### ISSUE THREAD

**Issue by IagoMega** [Difegue/LANraragi#315]
**Webtoon/Vertical page mode**
Add a reader option for read in continuous mode like Webtoons.

**Comment by Difegue** [comment]
See #242 .

**Comment by IagoMega** [comment]
> Duplicate of #242 , I think. The userscript there might help you for the time being 😀

Thank for Answer but how do i install this script ? which folder i can put ?
