### ISSUE TITLE
[Bug] Gallery titles with ＜＜text＞＞ aren't displayed properly

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#316]
![image](https://user-images.githubusercontent.com/15137035/84562576-8bc61100-ad94-11ea-86de-6bf4b2e4eb8b.png)
The title on the meta-data page shows correctly, but on the index the full title isn't shown. The symbols on the filename are converted to special characters that work on filenames for windows: `＜＜＞＞` not sure if that matters since I have a info.json file for the eze plugin to get the title from, and the symbols inside the json are of course the normal `<<>>` characters.

**Comment by Difegue** [comment]
As reported on discord, it seems that the titles aren't escaped properly when shown in the index, so html-alikes go straight thru. Woops™

**Comment by Difegue** [comment]
Should be good now.
