### ISSUE TITLE
[Bug] LRR stops being able to scan for galleries after hitting cache limit

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#317]
**LRR 0.7.0, Windows 10 1909**
WSL

Whenever I hit the temporary cache limit, the cache clears properly, but if you dump a gallery into the LRR library folder this error occurs.

```
[Temporary Folder] [info] Current temporary folder size is 4045.05 MBs, Maximum size is 500 MBs. Cleaning.
[Temporary Folder] [info] Done!
Undef did not pass type constraint "Str" (in $args->{"path"}) at /usr/local/share/perl5/site_perl/File/ChangeNotify/Watcher/Inotify.pm line 255
    "Str" is a subtype of "Value"
    "Value" is a subtype of "Defined"
    Undef did not pass type constraint "Defined" (in $args->{"path"})
    "Defined" is defined as: (defined($_))
```
It doesn't matter if I hit the cache from dumping a ton of galleries onto LRR's folder, or if I just hit the cache limit by viewing images then dropped one gallery into the folder. Very easy to reproduce with small cache size set.

**Comment by Difegue** [comment]
Haven't had time to try reproducing this yet, but I'll put a tentative WSL label as it's known to be a bit wonky on the inotify side.

**Comment by Asinin3** [comment]
I can't reproduce this on 0.7.2 I did do a fresh Windows 2004 install recently though. But regardless it seems fixed.
