### ISSUE TITLE
Backup/Restore broken due to wrong json encoding

### ISSUE THREAD

**Issue by Guerra24** [Difegue/LANraragi#318]
Backup encoding either generates or exports unescaped line breaks at file level causing the restore feature to fail with `invalid character encountered while parsing JSON string, at character offset 10071 (before "\r\n series:COMIC Ka...") at /usr/local/share/perl5/site_perl/Mojo/JSON.pm line 39.`

Some errors in backup file.
```json
 {
         
   "arcid": "eb39dc6c8077f59a4400d25ebbe21aa70ba1df0f",
            "title":
```
```json
            "tags":
 "language:english",
            "thumbhash": "36c68ab2019099f6733c7f7aa53e89a60d5cde76",
```
```json
            "tags": "...",
            "thumbhash":
 "8559991df66fb916550ab607807a9fbce479c3e0",
            "filename": "..."
        },
```
```json
            "arcid": "1d83b9720f75b90ae4dd082478f39a494c70d850",
            "title": "... ",
            "tags": "...",
            "thumbhash": "ad725888eef5ceefe0afde88187b60824ab9fb56",
            "filename": "...
 ..."
        },
```

I was not able to replicate it but the file contains `\r\n` line breaks. I'm not sure what could have caused it but I would suggest using proper json encoding just in case. JSON snippets from Gojira's backup file from discord.

**Comment by Difegue** [comment]
Removed the last few lines of code that were crafting JSON by hand. Good riddance!
