### ISSUE TITLE
Reverse proxy compatability

### ISSUE THREAD

**Issue by jmctune** [Difegue/LANraragi#32]
Would love a supported way to reverse proxy LANraragi over my Nginx server to give me the ability to read on the go. 

I've got a really janky way of it working right now, but I'm missing the page style. 

My location blocks:

	location /manga/ {
		include /config/nginx/auth_basic.conf;
		proxy_pass http://172.20.0.8:3000/;
	}
	
	location /js/ {
		include /config/nginx/auth_basic.conf;
		proxy_pass http://172.20.0.8:3000/js/;
	}
	
	location /js/vendor/ {
		include /config/nginx/auth_basic.conf;
		proxy_pass http://172.20.0.8:3000/js/vendor/;
	}
	
	location /css/ {
		include /config/nginx/auth_basic.conf;
		proxy_pass http://172.20.0.8:3000/css/;
	}

	location /css/vendor/ {
		include /config/nginx/auth_basic.conf;
		proxy_pass http://172.20.0.8:3000/css/vendor/;
	}

**Comment by Difegue** [comment]
From what I'm seeing, you need to add the following location block to get themes:  

```
location /themes/ {
	include /config/nginx/auth_basic.conf;
	proxy_pass http://172.20.0.8:3000/themes/;
}
```

As for specific reverse proxy support, I can't really do anything more than what's already there, i.e specifying port/interfaces for the server to listen on.  

I don't know much about nginx, but if it's like apache your best shot is to map all of port 3000 to a subdomain, if possible:  
https://whatididtodowhatidid.wordpress.com/2014/03/14/subdomains-for-ports-on-same-ubuntu-server-with-nginx-reverse-proxy/

**Comment by jmctune** [comment]
Thanks for the really quick response there.

That was the missing piece. Themes are pulling in now. All of the above was required, along with your additional location block. Thanks a lot!

**Comment by fullmetal1** [comment]
So I just tried this and found that there's a lot more locations that would need to be passed for this to work now. Would it be possible to implement a base url config option like many other self hosted webservers have?

**Comment by Difegue** [comment]
You can find a cleaner reverse proxy nginx config here: https://sugoi.gitbook.io/lanraragi/installing-lanraragi/methods#warning-reverse-proxies

**Comment by fullmetal1** [comment]
So base url is 'will not support'?

**Comment by Difegue** [comment]
Not for now since there's no built-in support for it in mojo and I'd have to whip up something -- Feel free to make a new issue about it though!  

https://stackoverflow.com/questions/31864849/how-do-i-set-the-base-url-for-my-proxied-app 
https://stackoverflow.com/questions/25170147/base-url-in-mojolicious-template-rendering

**Comment by fullmetal1** [comment]
Seems like the mojolicious guys don't want to add direct support for base-url 

https://github.com/mojolicious/mojo/issues/484

However, there is documentation on using the before-dispatch hook to rewrite URLs.

https://docs.mojolicious.org/Mojolicious/Guides/Cookbook#Rewriting
