### ISSUE TITLE
Broken permission on content folder during Docker install 

### ISSUE THREAD

**Issue by rshxyz** [Difegue/LANraragi#320]
**LRR Version and OS**
Please tell which version you're running, as well as your OS and installation method. (Vagrant, Docker, Native)
Latest build on Docker. 

Docker-Compose File:
version: '3'
services:
  lanraragi:
    container_name: lanraragi
    image: difegue/lanraragi
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /media/hen/content:/home/koyomi/lanraragi/content
      - /home/gecko/apps/docker/lanraragi/database:/home/koyomi/lanraragi/database

**Bug Details**

Seems like when you do a clean install of the lastest build from docker, the content folder has broken permission and is owned by root. The lanraragi and content folder are created when you intialize with docker-compose. So when you try to upload an archive you fail with "The file couldn't be moved to your content folder!". 

Please detail the bug here. 
gecko@PC~/apps/docker$ ls -lat | grep lanraragi
drwxr-xr-x  3 root  root      4096 Jul 15 23:40 lanraragi

gecko@PC~/apps/docker$ ls -lat lanraragi
total 12
drwxrwxrwx  2  9001 root  4096 Jul 15 23:42 database
drwxr-xr-x  3 root  root  4096 Jul 15 23:40 .
drwxr-xr-x 17 gecko gecko 4096 Jul 15 23:40 ..

gecko@PC:~/apps/docker$ ls -lat lanraragi/database/
total 12
drwxrwxrwx 2 9001 root 4096 Jul 15 23:42 .
-rw-r--r-- 1 9001 9001  958 Jul 15 23:42 database.rdb
drwxr-xr-x 3 root root 4096 Jul 15 23:40 ..

gecko@PC:/media/hen$ ls -lat
total 20
drwxr-xr-x  4 gecko gecko 4096 Jul 15 23:40 .
drwxr-xr-x  2 root  root  4096 Jul 15 23:40 content

**Matching Logs**
Post any logs you have encountered when reproducing the bug.  
If possible, switch the app to Debug Mode in order to have more logs.
docker-compose up lanraragi
WARNING: Some networks were defined but are not used by any service: t2_proxy
WARNING: Found orphan containers (makemkv, traefik) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating lanraragi ... done
Attaching to lanraragi
lanraragi    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
lanraragi    | [s6-init] ensuring user provided files have correct perms...exited 0.
lanraragi    | [fix-attrs.d] applying ownership & permissions fixes...
lanraragi    | [fix-attrs.d] done.
lanraragi    | [cont-init.d] executing container initialization scripts...
lanraragi    | [cont-init.d] 01-lrr-setup: executing... 
lanraragi    | Starting LANraragi with UID/GID : 1000/1000
lanraragi    | chown: /home/koyomi/lanraragi/content/thumb: No such file or directory
lanraragi    | chmod: /home/koyomi/lanraragi/content/thumb: No such file or directory
lanraragi    | rm: can't remove '/home/koyomi/lanraragi/script/hypnotoad.pid': No such file or directory
lanraragi    | rm: can't remove '/home/koyomi/lanraragi/.shinobu-pid': No such file or directory
lanraragi    | WARNING: overcommit_memory is set to 0! This might lead to background saving errors if your database is too large.
lanraragi    | Please check https://redis.io/topics/faq#background-saving-fails-with-a-fork-error-under-linux-even-if-i-have-a-lot-of-free-ram for details.
lanraragi    | [cont-init.d] 01-lrr-setup: exited 0.
lanraragi    | [cont-init.d] done.
lanraragi    | [services.d] starting services
lanraragi    | [services.d] done.
lanraragi    | Attempting to create directory /home/koyomi/perl5
lanraragi    | 
lanraragi    | 
lanraragi    | ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!!!!!
lanraragi    | [LANraragi] [info] LANraragi 0.7.0 started. (Production Mode)
lanraragi    | [LANraragi] [info] Plugin Detected: Chaika.moe
lanraragi    | [LANraragi] [info] Plugin Detected: Tag Copier
lanraragi    | [LANraragi] [info] Plugin Detected: Date Added
lanraragi    | [LANraragi] [info] Plugin Detected: E-Hentai
lanraragi    | [LANraragi] [info] Plugin Detected: eze
lanraragi    | [LANraragi] [info] Plugin Detected: Hdoujin
lanraragi    | [LANraragi] [info] Plugin Detected: koromo
lanraragi    | [LANraragi] [info] Plugin Detected: Mayriad's EH Master Script
lanraragi    | [LANraragi] [info] Plugin Detected: nHentai
lanraragi    | [LANraragi] [info] Script Detected: [PREVIEW] E*Hentai Downloader
lanraragi    | [LANraragi] [info] Script Detected: Migrate Favorite Tags
lanraragi    | [LANraragi] [info] Script Detected: Subfolders to Categories
lanraragi    | [LANraragi] [info] Script Detected: Source Finder
lanraragi    | [LANraragi] [info] Routing done! Ready to receive requests.
lanraragi    | [LANraragi] [info] Warming up search cache...
lanraragi    | [LANraragi] [info] Done!
lanraragi    | Web application available at http://127.0.0.1:3000

**Screenshots**

**Comment by Difegue** [comment]
Woops I totally missed this issue haha 👀💦  

Looks like your compose file doesn't specify a UID/GID for the content folder, so it should default to 1000/1000.  
I haven't heard reports of the folder chowning to root otherwise, so this might be a configuration issue.  
Closing for now since it's a bit old, feel free to reopen if you still encounter the problem.
