### ISSUE TITLE
Implement different sorting methods for archives in list/grid view

### ISSUE THREAD

**Issue by rettisances** [Difegue/LANraragi#321]
**LRR Version and OS**
Linux Mint 19.1, LRR 0.7.0

**Bug Details**
There should be different ways to sort archives in list/grid mode such as when it was added to the database (asc/desc), etc. As it is now, it is only alphabetical.

**Matching Logs**
N/A

**Screenshots**
N/A

**Comment by Difegue** [comment]
See https://github.com/Difegue/LANraragi/issues/195 .
