### ISSUE TITLE
[Bug] (WSL) Closing LRR while log is open temporarily breaks LRR

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#325]
**0.7.2 Windows 10 2004,** happened in old builds as well, old bug.

**Bug Details**
If you have the log window open and then click quit through Karen, LRR closes but the log stays open. And you're unable to close the log window normally aside from killing processes in task manager. Initially I thought that LRR was unable to be opened after this happened, but it just takes a **lot** longer than normal to start if the log window is still open.

**Comment by Difegue** [comment]
I couldn't repro this -- Normally clicking quit automatically disposes the log console once the WSL distro is closed.  

I'm guessing the distro closing part fails, leading to the console not being disposed (and the app not being entirely cleanly shut down either.)  
I added some try/finallys to the quit sequence [here](https://github.com/Difegue/Karen/commit/b5115462c92c5d697648e0c0e14c6cf4d934e1ed#diff-b0b24c4d60125779e676e3ea390b4923L66) but that's about all I can do.
