### ISSUE TITLE
[enhancement?] Komga / MangaDex style image player

### ISSUE THREAD

**Issue by zFerry98** [Difegue/LANraragi#327]
I found the full page reader as a plugin for Tampermonkey (so only for chrome desktop pc) but:
1) Put double page
2) If you have a small screen (even enabling "fit") the images are not adapted to the screen.
3) They are still uncomfortable.

I would like to understand if somewhere in the program you can change the player with a Komga / MangaDex style or anyway on the same basis as the application for W10:
https://sugoi.gitbook.io/lanraragi/advanced-usage/external-readers
![image](https://user-images.githubusercontent.com/17975351/90331119-86fb2480-dfb2-11ea-8e5d-d0bd972ca361.png)
Last thing, why if I open anything it always creates me a new tab instead of refreshing the page?

**Comment by Difegue** [comment]
I don't really plan on adding substantial changes/modes to the web reader for the time being.

If you like LRReader's view I can only encourage you to use it instead of the web reader for the time being! 😁
