### ISSUE TITLE
[Bug] Clicking tags to search fails due to control characters in string

### ISSUE THREAD

**Issue by sserenade** [Difegue/LANraragi#329]
**LRR Version and OS**
0.7.2, Docker on Debian.
Tested on Firefox 79 and Chromium 84.0.4147.125 on Arch Linux, as well as on Firefox Mobile.

**Bug Details**
When clicking a tag to search by (either in List mode, or in the mouseover menu), no results are returned. The search bar is populated with a string that looks like it contains excessive whitespace:
```
language:					 English
```

Watching the value of the bar via dev tools shows the string contains control characters:
```
arcTable.search():"language:\n\t\t\t\t\t English"
```

The previous example is from clicking the mouseover menu. When clicking a tag in any column in list view, the string has control characters at the end as well:
```
series:						Various					
```
```
arcTable.search(): "series:\n\t\t\t\t\t\tVarious\n\t\t\t\t\t"
```

I'm guessing this is due to [this line](https://github.com/Difegue/LANraragi/blob/40c953f14a7dab672ab5e2ae5a32d5e1015de625/public/js/index_datatables.js#L310) and [this one](https://github.com/Difegue/LANraragi/blob/40c953f14a7dab672ab5e2ae5a32d5e1015de625/public/js/index_datatables.js#L113) containing some tabs and newlines, but I'm not sure how to best clean it up (read: I can't into JS), so I'm opening an issue instead of a PR.

**Matching Logs**
No errors are emitted in the browser console, and there aren't any server logs that show the issue.

**Screenshots**

Search Bar:
![2020-08-17_23 08 08](https://user-images.githubusercontent.com/6497404/90476701-e22a3580-e0de-11ea-9378-42460ae1601b.png)

Value in debugger:
![2020-08-17_23 00 04](https://user-images.githubusercontent.com/6497404/90476747-f5d59c00-e0de-11ea-8246-d38354f429bd.png)
![2020-08-17_22 59 55](https://user-images.githubusercontent.com/6497404/90476753-f79f5f80-e0de-11ea-951d-dd42e7370e47.png)

**Comment by Difegue** [comment]
Thanks for investigating.
I've noticed this issue myself but haven't taken time to go back and fix it yet. 

(I'm pretty sure I can't into JS either at this point 🤔)
