### ISSUE TITLE
Support for embedding chapters into main title names?

### ISSUE THREAD

**Issue by jmctune** [Difegue/LANraragi#33]
Currently, I have the following showing up in my LANraragi library:

    Fairy Tail Ch. 1-4
    Fairy Tail Ch. 5-8
    ...
    Fairy Tail Ch. 529
    Fairy Tail Ch. 530

Is there any way to create "parent titles", with the chapters residing within that parent?

Example:

    Fairy Tail
     | - Fairy Tail Ch. 1-4
     | - Fairy Tail Ch. 5-8
     | - ...
     | - Fairy Tail Ch. 529
     | - Fairy Tail Ch. 530

For books with LOTS of chapters, there can be pages of these. It'd just be nicer/cleaner to be able to drill down into each series and find the chapters there.

**Comment by Difegue** [comment]
There's nothing of the sort currently present, but it's a worthwhile functionality to add. 

If I were to implement it, it'd probably be as sets: You could create a set with a given name, and assign archives to that set. 

The set name would then show up in the archive list, as a classic dropdown list.

**Comment by noirscape** [comment]
Out of curiosity, is something like this still being worked on?

**Comment by Difegue** [comment]
Ehhh it's supposed to be categories whenever I'll implement them, but I haven't started anything on that path thus far.

**Comment by Difegue** [comment]
![image](https://user-images.githubusercontent.com/8237712/81446426-28383a80-917b-11ea-88a2-8f0284bf7569.png)

**Comment by Difegue** [comment]
![image](https://user-images.githubusercontent.com/8237712/81843009-47551480-954d-11ea-9a03-5234c26b613a.png)

Missing essentially all the documentation, but it's done.  
Categories completely replace favorite tags and show up at the same place they used to be, for the time being.
