### ISSUE TITLE
successful import counter on upload page

### ISSUE THREAD

**Issue by CuddleBear92** [Difegue/LANraragi#331]
Would really like a counter if the form of say 25/75 on the upload page.
This should count up the number with every successful upload/import.
This makes sense for when you are doing large bulks and want to make sure everything is imported correctly. 

finishing touch on this feature could have a green checkmark next to the numbers for when its completed imports and queue is up to sync.

**Comment by Difegue** [comment]
Sounds reasonable -- I need to give the upload page a pass whenever I'll finish work on the downloaders anyway so I'll try to think about this.

**Comment by Difegue** [comment]
![image](https://user-images.githubusercontent.com/8237712/94370122-4f71b300-00ee-11eb-94d0-8a537f1911bd.png)
