### ISSUE TITLE
Arch Linux AUR installer.

### ISSUE THREAD

**Issue by satiricon** [Difegue/LANraragi#333]
I don't know if this is the right way to ask for a documentation change. If not, please delete this.

I created a Arch Linux build package for LRR. [Link](https://aur.archlinux.org/packages/lanraragi/).

Using the AUR package the installation process in Arch Linux would be as easy as entering `pikaur -S lanraragi` in the command line if the user is using pikaur. Using other AUR managers should be just as easy.

If the user is not using a AUR package manager the installation process would be something like:

```
wget https://aur.archlinux.org/cgit/aur.git/snapshot/lanraragi.tar.gz   -O - | tar -xz
cd lanraragi
makepkg -rsi
```
That would take care of installing LRR together with build and normal dependencies and deleting build dependencies after successful building and installing.

The installer also creates a lanraragi.service unit file for starting, restarting and stopping LRR with systemd's `systemctl`. If Redis is down it will get it up.

ej: `systemctl start lanraragi.service`
`systemctl restart lanraragi.service`
`systemctl stop lanraragi.service`
`systemctl status lanraragi.service`

This also gives an easy way to read the log if necessary.

`journalctl -u lanraragi -f`

**Comment by Difegue** [comment]
Wow, this is great! It ain't a real open source project until someone stuffed it into the AUR.  

I'd recommend making a pull request for the [Documentation](https://github.com/Difegue/LANraragi/tree/dev/tools/Documentation) to integrate your changes. That, or I can just copy-paste the text of this issue directly as it's clear enough...

**Comment by satiricon** [comment]
I'll make the pull request. Should I add another installation section in `methods.md`? Or a subsection in `source.md`?

**Comment by Difegue** [comment]
I've been thinking about a new installation section - If it's only about the AUR package for now it's fine but I might extend it into a "community" installation methods section later on.

It'd give me an excuse to mention the existing unraid community package as well!

**Comment by Svadkos** [comment]
@satiricon It gives me this error

```
Can't load application from file "/usr/lib/lanraragi/script/lanraragi": Can't locate local/lib.pm in @INC (you may need to install the local::lib module) (@INC contains: /usr/lib/lanraragi/script/../lib /usr/lib/perl5/5.32/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.32/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.32/core_perl /usr/share/perl5/core_perl) at /usr/lib/lanraragi/script/../lib/LANraragi.pm line 3.
BEGIN failed--compilation aborted at /usr/lib/lanraragi/script/../lib/LANraragi.pm line 3.
Compilation failed in require at (eval 102) line 1.
Compilation failed in require at (eval 101) line 1.
```

Also it creates perl5 directory with libraries inside $HOME during build process.
