### ISSUE TITLE
Add a toggle in the archive index to crop or not landscape thumbnails

### ISSUE THREAD

**Issue by Difegue** [Difegue/LANraragi#339]
Currently, thumbnails that don't fit a regular A4 page are cropped to only show the left side.  
![image](https://user-images.githubusercontent.com/8237712/94173876-d1669f80-fe94-11ea-9213-d59ec496f93c.png)

This is potentially not helpful for collections that mostly contain image sets or the like.  
(But it's good for archives where the thumbnail is both the front and back cover, which is why it's there)

The fix is dead-simple to implement in CSS:  
```
div.id3 img {
    box-shadow: 0 2px 5px 0 
rgba(0, 0, 0, 0.16), 0 2px 10px 0
    rgba(0, 0, 0, 0.12);
    max-height: 275px;
    max-width: 202px;
}
```
It's mostly a matter of adding the toggle somewhere and wiring it to a localStorage preference.

**Comment by Vortex2wenty** [comment]
Hello, I would like to help. Thanks.
