### ISSUE TITLE
Update screenshots in README

### ISSUE THREAD

**Issue by Difegue** [Difegue/LANraragi#343]
A Hacktoberfest classic by now.

**Comment by SaulEiros** [comment]
Hi! Can I give you a hand with this? Thank in advance! Very cool project, btw!

**Comment by Difegue** [comment]
Sure! Thank you. Make sure to use the just-released 0.7.3 to take your screenshots with. 👍

**Comment by SaulEiros** [comment]
Sure thanks!

**Comment by SaulEiros** [comment]
Hey! I think i cant reach the admin configuration screen because i dont have the password to log in. Is there a way I can see those screens?

**Comment by Difegue** [comment]
You'd have to deploy/install the server yourself to update the screenshots for those parts.  
As for the permissions, wouldn't you normally push your changes to a fork of the repo then use that to make the PR here? That's standard github flow.
