### ISSUE TITLE
[Suggestion] Sort by date w/ DateAdded plugin

### ISSUE THREAD

**Issue by whilelooking** [Difegue/LANraragi#347]
So I read through this issue (https://github.com/Difegue/LANraragi/issues/67), but the 'new' button has some flaws. Since the gallery and the 'new' page sort alphabetically it's not always the easiest to find recently added archives and browsing becomes a bit of a chore. Would it be possible to have the option to sort by the timestamp generated by the DateAdded plugin? Thanks!

**Comment by Difegue** [comment]
Would be solved by #195 .

**Comment by whilelooking** [comment]
Awesome!

**Comment by whilelooking** [comment]
It occurred to me, would making this view default be an option? Perhaps optimizing the database around this sorting method also because for the most part I never need to see the archives in alphabetical order unless it's maintenance sort of stuff.
