### ISSUE TITLE
file names with a | in it give a error trying to add from computer

### ISSUE THREAD

**Issue by 4-77mhz** [Difegue/LANraragi#349]
**LRR Version and OS**
Docker Version 0.7.3
OS Ubuntu 20.04

**Bug Details**
when trying to upload a file example:
[Meganei] Shishunki no Obenkyou ｜ Puberty Study Session Ch. 5.5 [English].cbz

I get the following error message:

Error checking Minion job status
Error: Couldn't open /tmp/fi69Tt1Bxd/[Meganei] Shishunki no Obenkyou ï½ Puberty Study Session Ch. 5.5 [English].cbz :No such file or directory at /home/koyomi/lanraragi/script/../lib/LANraragi/Utils/Database.pm line 260.

**Comment by Difegue** [comment]
Might be the same as #348 .  
Have you tried the nightlies?

**Comment by 4-77mhz** [comment]
Yes, the nightly fixes that
