### ISSUE TITLE
[Suggestion] Tag siblings

### ISSUE THREAD

**Issue by whilelooking** [Difegue/LANraragi#351]
Currently depending on where you get your metadata, you can get both `parody:xyz` and `series:xyz`. It would be nice to be able to consolidate the two into one tag. I see a couple ways that this could be implemented, but approach that came to mind is to have something to similar to tag blacklisting where on metadata import tags would be adjusted. There would have to be an option to retroactively replace tags in the database perhaps with a file that is read and processed `cyan -> blue, series:* -> parody:*`. The alternative that came to mind is a sibling/symbolic link system where one tag would refer to another, but that might be too logic intensive. Thanks!

**Comment by Difegue** [comment]
Available in https://github.com/Difegue/LANraragi/releases/tag/v.0.8.0 . 👍
