### ISSUE TITLE
[feature request] The JSON database backup file doesn't contain Tag's blacklist. 

### ISSUE THREAD

**Issue by gth7754125** [Difegue/LANraragi#353]
Question above.
It seems the json backup file can only restore the metadata and category, would you like to add custom tag's blacklist to the json file ?

**Comment by Difegue** [comment]
The idea for the backup functionality was always to mostly keep the important data that takes the most time to build up - aka archive metadata and now categories. Other settings can be quickly copied so I don't really see the point.
It also allows one to carry over his metadata to another LRR instance, which if it included extra settings would be kinda annoying. ("I only wanted to copy those tags and now my password changed!")

Adding other stuff in backups wouldn't be too hard from a dev standpoint, but I don't think I'll do it.
If you want to backup/restore everything you're probably better off saving the Redis .rdb database directly.
