### ISSUE TITLE
[Question] How to force LRR to rescan the content directory manually ?

### ISSUE THREAD

**Issue by gth7754125** [Difegue/LANraragi#355]
**LRR Version and OS**
LRR 0.73 docker version

**Operation Details**
> When i edit archieve's metadata, I manually rename the archieve from local File system, 
   However, LRR seems not to rescan my file, and it can't find out this archieve anymore. Only when i remove the archieve from local directory, and then add it again.The file can be scanned out.

So how can i manually trigger the scan operation for LRR ?  Only add new files to the content directory ?

**Comment by Difegue** [comment]
Restarting the Shinobu File watcher in the app settings should force a content directory rescan.
