### ISSUE TITLE
Can't select categories from the dropdown

### ISSUE THREAD

**Issue by Radioo** [Difegue/LANraragi#357]
Clicking categories that are contained in the dropdown menu does nothing.
![image](https://user-images.githubusercontent.com/9533160/97307283-ca4dfb00-185f-11eb-8f93-4758bc90eada.png)

**Comment by Difegue** [comment]
Hmm that used to work, do you have any kind of error in the browser console? I'll take a look later.

**Comment by Radioo** [comment]
Only this but idk if it's related, nothing new pops up when selecting from the dropdown too. Also tried different browsers including on mobile and nothing.
![image](https://user-images.githubusercontent.com/9533160/97335365-127c1600-187e-11eb-8825-d68853c71675.png)

**Comment by Difegue** [comment]
Alright, so the feature does work... but only on Firefox. (https://stackoverflow.com/questions/9972280/onclick-on-option-tag-not-working-on-ie-and-chrome)  
You'd think something as prehistoric as `onclick` would work the same everywhere but I guess not.  (╯°□°）╯︵ ┻━┻  

I've replaced the implementation by something that should work everywhere.
