### ISSUE TITLE
Cannot use reader options on mobile

### ISSUE THREAD

**Issue by Pickleshub** [Difegue/LANraragi#360]
**LRR Version and OS**
Please tell which version you're running, as well as your OS and installation method. (Vagrant, Docker, Native)
I'm currently running 0.7.3 on Ubuntu server 18.04, using docker.
**Bug Details**
Please detail the bug here. 
On mobile, the reader options is scaled poorly and results in me not being able to save my options. Please see the attached screenshot to see what I mean. I've tried both Firefox and chrome, and have the same issues on both browsers.

**Matching Logs**
Post any logs you have encountered when reproducing the bug.  
If possible, switch the app to Debug Mode in order to have more logs.

**Screenshots**
![Screenshot_Frost+_20201107-053605~2](https://user-images.githubusercontent.com/74097360/98439100-50b6d800-20bd-11eb-9ee7-5971073e9754.png)

**Comment by Difegue** [comment]
Some media queries were missing for the settings overlay -- Should be better now.
![image](https://user-images.githubusercontent.com/8237712/98712307-6dd1fc00-2386-11eb-9964-af4de69af1c1.png)
