### ISSUE TITLE
OPDS API went wrong.

### ISSUE THREAD

**Issue by bensonwind** [Difegue/LANraragi#361]
**LRR Version and OS**
LANraragi v.0.7.4 - Chilly Down under Windonws 10 LSTC 1807 with WSL1

**Bug Details**
The OPDS API returns errors. If debug mode is off, the web page "We're sorry, something went wrong." is shown, otherwise  it says "[exists] ERR Protocol error: invalid bulk length,  at /usr/local/share/perl5/site_perl/Redis.pm line 275."

**Matching Logs**
The error even occurs on the demonstration page: https://lrr.tvc-16.science/api/opds

**Screenshots**
![err](https://user-images.githubusercontent.com/33997937/98672674-20a75780-2391-11eb-81dc-63c651a67989.png)

**Comment by Difegue** [comment]
Oh that's embarassing, some modifications weren't reported to the OPDS API and wound up breaking it. I should test it more often..  
I've pushed a fix for the issue.

**Comment by bensonwind** [comment]
Solved, many thanks for your excellent work and dedication!
