### ISSUE TITLE
I made categories angry

### ISSUE THREAD

**Issue by jmhickman** [Difegue/LANraragi#366]
**LRR Version and OS**
Debian Buster
0.7.4

**Bug Details**

I seem to have made my static categories angry somehow. I keep a category for things I haven't read yet. I noticed that now, all of my archives appear in this category view, even though only one or no files might be selected in the Modify Categories view. 

I tried deleting and remaking the category, including with a different name. The behavior persists. The two other categories I use, strangely, are unaffected. They display only the items that I have placed in them.

**Matching Logs**

Not sure which, if any, logs would be relevant here.

**Screenshots**

![functioning category](https://user-images.githubusercontent.com/6581761/99911046-6fb98a80-2cb7-11eb-89e9-4d22d9ab2f6c.png)
![broken view](https://user-images.githubusercontent.com/6581761/99911048-6fb98a80-2cb7-11eb-9482-ca80059ce86d.png)
![empty selection](https://user-images.githubusercontent.com/6581761/99911049-70522100-2cb7-11eb-8542-53ba9baeb48b.png)

**Comment by Difegue** [comment]
That's pretty weird - You can try making a backup to dump the categories so we can see what's going on with that Unread one.

**Comment by jmhickman** [comment]
[backup.zip](https://github.com/Difegue/LANraragi/files/5579975/backup.zip)

**Comment by Difegue** [comment]
Unread is indeed empty, so there's seemingly nothing wrong.  

Filtering gets a bit weird in 0.7.4 if your category has 0 or 1 archives in it - It's been fixed since thanks to https://github.com/Difegue/LANraragi/pull/362 so that might be the issue you're having?

**Comment by jmhickman** [comment]
Hrm. It seems you're correct. If I add 3-4 random items to the category, it displays only those things. I noticed the issue when I was down to only one unread thing so that makes sense.

**Comment by jmhickman** [comment]
Thanks for pointing me in the right direction on that!
