### ISSUE TITLE
Unnecessary database directory permission

### ISSUE THREAD

**Issue by pastalian** [Difegue/LANraragi#371]
I don't think this `777` is necessary. Is there any reason not to use `u+rwx` like the other chmod?

https://github.com/Difegue/LANraragi/blob/fc1bdf572a3972cd2fa056604a36b52a096c524b/tools/build/docker/s6/cont-init.d/01-lrr-setup#L23-L25

**Comment by Difegue** [comment]
It's never been changed since users almost never interact with the database folder, but I guess `u+rwx` would work fine?  
The redis server runs under koyomi user as well so I don't see why it wouldn't work.

**Comment by pastalian** [comment]
yeah I changed it to `u+rwx` and tried the basic operations, but it seems to be fine.
`777` directories look ugly in my ls output so I'd be happy if you could change it :)
