### ISSUE TITLE
[Bug] Database cleaning not working correctly

### ISSUE THREAD

**Issue by Mayriad** [Difegue/LANraragi#373]
**LRR Version and OS**

LANraragi for Windows 0.7.5 (MSI installer) on Microsoft Windows 10 build 19042.685. Archives are located on a NAS and accessed via a mount point in the content folder. Please refer to #274 my big list of LRR bugs and suggestions to see more details. Some problems may be caused by my relatively awkward setup.

**Bug Details**

When I remove some or all of my archives from the content folder and click "clean database", the LRR notification will say "Successfully cleaned the database and removed * entries!" with the correct number. However, whenever I open the library after that (even after restarting LRR), I get a browser notification that says
```
DataTables warning: table id=DataTables_Table_0 - Requested unknown parameter 'isnew' for row 0, column 4. For more information about this error, please see http://datatables.net/tn/4
```
After I click "OK", the removed galleries will all show up in the library with no thumbnail and "undefined" for title. The "* ancient chinese lithographies" message still gives the pre-removal count of archives.

If I click "clean database" again after that, the LRR notification will say "Successfully cleaned the database and removed 0 entries!", which is again correct. It seems the cleaning was not fully completed and reflected in the library?

**Comment by Difegue** [comment]
Might be the cache not being wiped post-cleanup? If you reproduce the bug but clear out the search cache manually before returning to the index, I think it should work.

**Comment by Mayriad** [comment]
Yes, resetting the search cache using the button in settings fixed it. Please implement this fix.
