### ISSUE TITLE
[Feature Request] Remove from category option to gallery context menu

### ISSUE THREAD

**Issue by waz1500** [Difegue/LANraragi#375]
Would love an option to directly remove items from a particular category directly in the thumbnail context menu without going to Modify Categories and trying to search for it in the list. 

![remove from catagory](https://user-images.githubusercontent.com/17833884/102108427-d3eceb80-3e2a-11eb-910e-dbaafad1b222.jpg)

**Comment by Difegue** [comment]
This is something I'd like to add as well - It's a bit more involved than the add dialog since I need to keep track of which categories an archive is in, but it's def. doable.

**Comment by jmhickman** [comment]
I'd like this as well. I'm completely switched to using categories for tracking progress in series and such, so being able to remove a chapter from my 'unread' category directly from the reader or from the list view would be great.

**Comment by Difegue** [comment]
![image](https://user-images.githubusercontent.com/8237712/109237242-76353200-77d1-11eb-8a92-dbe1fabf4e57.png)
✌
