### ISSUE TITLE
[New fuction required]collect metadata from info.txt generated by Hitomi-Downloader

### ISSUE THREAD

**Issue by lukemin** [Difegue/LANraragi#377]
**LRR Version and OS**
Docker V0.7.5

**Bug Details**
can not get tags from ehentai and nhentai when the name of the cbz is in Japanese
the name format is (id)-[artist]-title eg. (1172760)-[N／A]-【中國語】NanoCore「納米核心」2018.1月Ｒ１８の絵のコレクション②.cbz

**Matching Logs**
nhentai log: [2020-12-15 06:57:42] [nHentai] [info] No matching nHentai Gallery Found!
ehentai log:[2020-12-15 08:16:36] [E-Hentai Login] [info] Cookies provided (****** *********************)!
[2020-12-15 08:16:40] [E-Hentai] [info] No matching EH Gallery Found!

**Screenshots**

I downloaded all the comics for ehentai via https://github.com/KurtBestor/Hitomi-Downloader, there is info.txt generated auotmately with contents below:

图库 id: 1495165

标题: (関西けもケット6) [もふ2擬き (よろず)] もふ特盛り!!! (ポケットモンスター) [中国翻訳]

艺术家: kesupu, myako kawamoto

分组: mofumofu modoki

类型: doujinshi

系列: pokemon

人物: flareon, glaceon, eevee, umbreon

标签: male:furry

语言: Chinese

would you please add a plugin to collect metadata from this info.txt file?

**Comment by Mayriad** [comment]
I don't think this is a real issue or even a bug. The e-hentai and nhentai plugins both use title search to match galleries by default, and your problem is caused by the fact that your downloaded archives don't use the original titles. The problem is the filename format used by your downloader, and not the Japanese characters. Unless you change your setup, you can only use the e-hentai plugin with the option `Fetch using thumbnail first (falls back to title)` enabled to match galleries by thumbnail instead.

**Comment by lukemin** [comment]
> I don't think this is a real issue or even a bug. The e-hentai and nhentai plugins both use title search to match galleries by default, and I think your problem is caused by the fact that your downloaded archives don't use the original titles. The problem is the filename format used by your downloader, and not the Japanese characters. Can you successfully match your other archives with English or romaji filenames?
> 
> Unless you change your setup, right now I think you can only use the e-hentai plugin with the option `Fetch using thumbnail first (falls back to title)` enabled to match galleries by thumbnail instead.

some work, some didnet

**Comment by Difegue** [comment]
Oh joy, it's another `info.txt` variant that does its own thing, like the 30 other ones.  

![113b9de1b85ae5e8b970fba6afea2314d7e0fb95891901245adae991a91cc32d](https://user-images.githubusercontent.com/8237712/102221584-977cc680-3ee2-11eb-94ec-d84014bc7602.jpg)  

The existing [Hdoujin Downloader](https://github.com/Difegue/LANraragi/blob/909714ace51a4975aece24a9bd0bb51bc8a4d9f9/lib/LANraragi/Plugin/Metadata/Hdoujin.pm#L73) plugin's support might help, but you probably won't be able to pull all the information from your own `info.txt`s without modifying it a bit.  

I don't have the bandwidth to tackle this personally atm, but this is nothing one can't handle with some help from the [documentation.](https://sugoi.gitbook.io/lanraragi/plugin-docs/metadata)

**Comment by Mayriad** [comment]
In any case, the info.txt only seems to include the EH gallery ID and not the gallery token. You cannot locate a gallery without the token, so there is nothing special you can do with it. At most you can use the title from it for the title search to avoid problems with filename format.

**Comment by Difegue** [comment]
I don't think this issue is meant to use the txt to loopback with EH, just to consume the metadata that's already in it.

**Comment by Mayriad** [comment]
Ah, I see lukemin edited his OP even further. When it was first posted, the example data he provided basically only had the gallery ID and other fields were like "unknown", so I thought he wanted to request metadata from EH.

**Comment by lukemin** [comment]
> I don't think this issue is meant to use the txt to loopback with EH, just to consume the metadata that's already in it.

yes， you are absolutely right. I will try to modify hdoujin plugin to collect metadata from the info.txt file.
