### ISSUE TITLE
LAN access with WSL2

### ISSUE THREAD

**Issue by wickedwzrd** [Difegue/LANraragi#378]
**LRR Version and OS**
LRR Version: v.0.7.5 - Underground
OS: Windows 10 v2004

**Bug Details**
I am unable to access the reader on my LAN. I currently have LRR running on my home server and I tried to create an inbound rule for `Karen.exe` on any port and specifically 3000, but was still unable to access it from any device on my LAN.

I was scouring the closed issues and could only find that Mojolicious default config sets network to `http://*:3000`.

I would assume that LRR should work out of box over LAN so I am unsure as to what the issue may be.

**Matching Logs**
```
Executing the following command on WSL: export LRR_NETWORK=http://*:3000 && export LRR_DATA_DIRECTORY='/mnt/h/Comics/test' && cd /home/koyomi/lanraragi && rm -f script/hypnotoad.pid && mkdir -p log && mkdir -p content && mkdir -p database && sysctl vm.overcommit_memory=1 && redis-server /home/koyomi/lanraragi/tools/build/docker/redis.conf --dir '/mnt/h/Comics/test'/ --daemonize yes && perl ./script/launcher.pl -f ./script/lanraragi
vm.overcommit_memory = 1


ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!!!!!
[LANraragi] [info] LANraragi 0.7.5 started. (Production Mode)
[LANraragi] [info] Plugin Detected: Chaika.moe
[LANraragi] [info] Plugin Detected: Tag Copier
[LANraragi] [info] Plugin Detected: Date Added
[LANraragi] [info] Plugin Detected: E-Hentai
[LANraragi] [info] Plugin Detected: eze
[LANraragi] [info] Plugin Detected: Hdoujin
[LANraragi] [info] Plugin Detected: koromo
[LANraragi] [info] Plugin Detected: Mayriad's EH Master Script
[LANraragi] [info] Plugin Detected: nHentai
[LANraragi] [info] Script Detected: Migrate Favorite Tags
[LANraragi] [info] Script Detected: Subfolders to Categories
[LANraragi] [info] Script Detected: Source Finder
[LANraragi] [info] Downloader Detected: Chaika.moe Downloader
[LANraragi] [info] Downloader Detected: E*Hentai Downloader
Killing process 30 from ./script/minion.pid
[LANraragi] [info] Successfully connected to Minion database.
[Minion] [info] Starting new Minion worker in subprocess with 8 parallel jobs.
[Minion] [info] Minion worker 30 started
Killing process 31 from ./script/shinobu.pid
[Minion] [info] Warming up search cache...
Logging to "log/production.log" is DEPRECATED at /home/koyomi/lanraragi/script/../lib/LANraragi/Utils/Generic.pm line 131.
[Minion] [info] Done!
[LANraragi] [info] Routing done! Ready to receive requests.
Logging to "log/production.log" is DEPRECATED at /usr/local/share/perl5/site_perl/Mojo/Server/Hypnotoad.pm line 69.
Web application available at http://127.0.0.1:3000
[Shinobu] [info] Shinobu File Watcher started.
[Shinobu] [info] Working dir is /home/koyomi/lanraragi
[Shinobu] [info] Scanning content folder for changes...
[Shinobu] [info] Adding watcher to content folder /mnt/h/Comics/test
[Shinobu] [info] All done! Now dutifully watching your files.```

**Comment by wickedwzrd** [comment]
Another note to add is that I am running LRR with WSL v2. I just tested switching back to WSL v1 and I have no issues connecting to the server. It asked me to allow perl access to private/public networks with the file location being `%appdata%\roaming\lanraragi\distro\rootfs\usr\bin\perl`

I noticed that when running WSL v2, LRR creates an ext4 image, while WSL v1 create a rootfs folder under the Distro folder.

**Comment by Difegue** [comment]
WSL2 currently has some issues related to localhost access: https://github.com/microsoft/WSL/issues/4619  

For now I'd recommend you stick to WSL1 until said issues are fixed by Microsoft.

**Comment by huntrshado** [comment]
Seems like a firewall issue. Try creating an inbound rule for all programs to allow connection on port 3000.

I think it specifically has to do with making your firewall rule only allow Karen.exe, because when I test on my own device and configure the rule to allow only Karen.exe through port 3000, it breaks and I also become unable to access my server.

**Comment by wickedwzrd** [comment]
@huntrshado I noticed that while using WSL1, it creates a firewall rule for perl and not the `karen.exe`. However since WSL1 is easier to access the root folder so that I can edit my theme I will stick to that for now.

**Comment by Difegue** [comment]
Since there's no real fixable issue on my side, I'll be converting this to a discussion so that others can see it if they run into trouble w. WSL2 installs. Glad you got it sorted out!
