### ISSUE TITLE
Compact mode too compact on mobile

### ISSUE THREAD

**Issue by Pickleshub** [Difegue/LANraragi#379]
Hey there, thank you for fixing the settings overlay on mobile! Hate to bring yet another mobile related scaling issue but here we go again:
**LRR Version and OS**
Please tell which version you're running, as well as your OS and installation method. (Windows, Docker, Native)
Ubuntu Server 18.04, Lanraragi v0.7.5, using a docker install
**Bug Details**
Please detail the bug here. 
On a mobile device, selecting compact mode in display options causes the archive list to be compacted far too much
**Matching Logs**
Post any logs you have encountered when reproducing the bug.  
If possible, switch the app to Debug Mode in order to have more logs.

**Screenshots**
![Screenshot_Frost+_20201218-003551](https://user-images.githubusercontent.com/74097360/102579154-e9cc0c00-40c9-11eb-84fd-6639d70b9e4c.png)

**Comment by Difegue** [comment]
I fixed a few things recently in https://github.com/Difegue/LANraragi/commit/aa95fed93eae2df1728660fd51fb508a1fee938d related to the sizing of the table view, could you try a nightly build and see if that still happens?

**Comment by Pickleshub** [comment]
Hey, sorry for the late response! I updated to the nightly build and it seems to work perfect now. Thanks!
