### ISSUE TITLE
Support for HTTPS/SSL

### ISSUE THREAD

**Issue by rettisances** [Difegue/LANraragi#39]
I really want to be able to have this service open to the outside to access it easily, but I can't securely do that when it is not encrypted. I was wondering if HTTPS/SSL could be implemented similar to how Ubooquity does it with a Keystore.

**Comment by Difegue** [comment]
It's doable on my side, although I wouldn't provide keystore functionality and would just allow people to upload a certificate/key combo to the app to enable HTTPS.  
This would force me to actually add proper configuration options for ports/interfaces, which might not be a bad thing either!  

You _can_ actually already do something like:
```
npm start https://*:443?cert=/etc/tls/domain.crt&key=/etc/tls/domain.key
```
and it should work given your certificate/key files are correct, but it's a bit unwieldy, and will obviously only work if you have access to npm start to begin with (that means no Docker/Vagrant)

I'll put this on the backburner, but given how little time I get to work on this right now, don't expect it to happen very fast.  

What I personally use for [the demo website](https://dj.faglord.party/) is a reverse proxy using Apache in front.  
If you're running in a container, there's a [pretty good article about building up a reverse proxy around a container](https://autoize.com/portainer-with-nginx-reverse-proxy/) you could adapt.

**Comment by joshrharmon** [comment]
Hello again, I just got the time to set this up and I followed all of the instructions in the [link](https://autoize.com/portainer-with-nginx-reverse-proxy/) you recommended. How do I actually start the LRR container now that I have all of the portainer and nginx components set up to have it have SSL?

**Comment by Difegue** [comment]
Going from the last `docker run` command in the article: 

```docker run --name lanraragi --net dockernet -v /var/run/docker.sock:/var/run/docker.sock --mount type=bind,source=[YOUR_CONTENT_DIRECTORY],target=/home/koyomi/lanraragi/content -e VIRTUAL_HOST=domain.com -e VIRTUAL_PORT=9000 -e LETSENCRYPT_HOST=domain.com -e LETSENCRYPT_EMAIL=[email protected] --restart always -d difegue/lanraragi```

replacing domain.com, the content directory and the email with yours, of course.

**Comment by Difegue** [comment]
I'll have to get to this properly now in order to get Batch Tagging working through SSL.
