### ISSUE TITLE
EZE Plugin recognizes "gid" value as language tag

### ISSUE THREAD

**Issue by darkred3** [Difegue/LANraragi#397]
Using the eze plugin on a 7z archive including an info.json will result in the language tag being wrongly displayed. Instead of the language, Japanese, being shown, the "gid" value, 1093785, will be displayed.
[info.txt](https://github.com/Difegue/LANraragi/files/5936969/info.txt)

**Version**
LRR for Windows 10 0.7.6

**Logs**
LANraragi log
> [2021-02-06 14:12:18] [Tag Stats] [debug] Tag stats JSON is [{"text": "smell", "namespace": "female", "weight": 1 },{"text": "spanking", "namespace": "female", "weight": 1 },{"text": "Muneshiro", "namespace": "artist", "weight": 1 },{"text": "cervix penetration", "namespace": "female", "weight": 1 },{"text": "midget", "namespace": "male", "weight": 1 },{"text": "glasses", "namespace": "female", "weight": 1 },{"text": "stockings", "namespace": "female", "weight": 4 },{"text": "ffm threesome", "namespace": "misc", "weight": 1 },{"text": "Lewdua", "namespace": "artist", "weight": 2 },{"text": "big breasts", "namespace": "female", "weight": 2 },{"text": "shotacon", "namespace": "male", "weight": 2 },{"text": "tankoubon", "namespace": "misc", "weight": 1 },{"text": "western cg", "namespace": "misc", "weight": 2 },{"text": "bondage", "namespace": "female", "weight": 1 },{"text": "tomgirl", "namespace": "male", "weight": 1 },{"text": "kemonomimi", "namespace": "female", "weight": 2 },{"text": "1093785", "namespace": "language", "weight": 1 },{"text": "prostitution", "namespace": "female", "weight": 1 },{"text": "rimjob", "namespace": "male", "weight": 1 },{"text": "unusual pupils", "namespace": "female", "weight": 1 },{"text": "C91", "namespace": "event", "weight": 1 },{"text": "sole female", "namespace": "female", "weight": 1 },{"text": "blowjob", "namespace": "female", "weight": 2 },{"text": "incest", "namespace": "misc", "weight": 2 },{"text": "sex toys", "namespace": "female", "weight": 1 },{"text": "Nishi", "namespace": "artist", "weight": 1 },{"text": "dilf", "namespace": "male", "weight": 1 },{"text": "oppai loli", "namespace": "female", "weight": 1 },{"text": " exhentai.org/g/1097263/9465ceabc9", "namespace": "source", "weight": 1 },{"text": " exhentai.org/g/1201954/10aecd429b", "namespace": "source", "weight": 2 },{"text": " exhentai.org/g/1104840/38897ce8bb", "namespace": "source", "weight": 1 },{"text": "schoolgirl uniform", "namespace": "female", "weight": 1 },{"text": "first person perspective", "namespace": "female", "weight": 2 },{"text": "armpit licking", "namespace": "male", "weight": 1 },{"text": "futanari", "namespace": "female", "weight": 2 },{"text": "collar", "namespace": "female", "weight": 1 },{"text": "full censorship", "namespace": "misc", "weight": 1 },{"text": "hidden sex", "namespace": "female", "weight": 2 },{"text": "mother", "namespace": "female", "weight": 1 },{"text": "big balls", "namespace": "female", "weight": 2 },{"text": "pantyhose", "namespace": "female", "weight": 1 },{"text": "emotionless sex", "namespace": "male", "weight": 1 },{"text": "group", "namespace": "misc", "weight": 1 },{"text": "teacher", "namespace": "male", "weight": 1 },{"text": "THE IDOLM@STER CINDERELLA GIRLS", "namespace": "series", "weight": 1 },{"text": "Count2.4", "namespace": "group", "weight": 1 },{"text": "dickgirl on dickgirl", "namespace": "female", "weight": 2 },{"text": " exhentai.org/g/1093785/b5f8ed8633", "namespace": "source", "weight": 1 },{"text": "1097263", "namespace": "language", "weight": 1 },{"text": "1104840", "namespace": "language", "weight": 1 },{"text": "defloration", "namespace": "female", "weight": 1 },{"text": "sister", "namespace": "female", "weight": 1 },{"text": "catgirl", "namespace": "female", "weight": 2 },{"text": "big penis", "namespace": "female", "weight": 2 },{"text": "garter belt", "namespace": "female", "weight": 1 },{"text": "tall girl", "namespace": "female", "weight": 1 },{"text": "shiki ichinose", "namespace": "character", "weight": 1 },{"text": "anal", "namespace": "female", "weight": 5 },{"text": "gyaru", "namespace": "female", "weight": 1 },{"text": "beauty mark", "namespace": "female", "weight": 3 },{"text": "Kakitsubata Kanae", "namespace": "artist", "weight": 1 },{"text": "sole male", "namespace": "male", "weight": 1 },{"text": "cousin", "namespace": "female", "weight": 1 },{"text": "english", "namespace": "language", "weight": 2 },{"text": "1201954", "namespace": "language", "weight": 2 },{"text": "the idolmaster", "namespace": "parody", "weight": 1 },{"text": "ahegao", "namespace": "female", "weight": 1 },{"text": "smegma", "namespace": "male", "weight": 1 },{"text": "producer", "namespace": "character", "weight": 1 },{"text": "lolicon", "namespace": "female", "weight": 1 },{"text": "hairy", "namespace": "female", "weight": 2 },{"text": "nakadashi", "namespace": "female", "weight": 3 },{"text": "sweating", "namespace": "female", "weight": 1 }]

Plugin log
> [2021-02-06 14:12:02] [eze] [debug] Found and loaded the following JSON: {	"gallery_info": {		"title": "(C91) [Count2.4 (Nishi)] Secret Live After side:siki (THE IDOLM@STER CINDERELLA GIRLS)",		"title_original": "(C91) [Count2.4 (弐肆)] Secret Live After side:siki (アイドルマスター シンデレラガールズ)",		"uploader": "IRen",		"category": "Doujinshi",		"tags": {			"parody": [				"the idolmaster"			],			"character": [				"producer",				"shiki ichinose"			],			"group": [				"count2.4"			],			"artist": [				"nishi"			],			"male": [				"armpit licking",				"rimjob",				"sole male"			],			"female": [				"anal",				"blowjob",				"smell",				"sole female",				"stockings",				"sweating"			]		},		"language": "Japanese",		"translated": false,		"upload_date": [			2017,			7,			30,			8,			11,			7		],		"source": {			"site": "exhentai",			"gid": 1093785,			"token": "b5f8ed8633",			"parent_gallery": {				"gid": 1093606,				"token": "91bd38137c"			},			"newer_version": []		},		"pndafrvr": 2,		"filecount": 24,		"favorites": 826,		"rating": 4.68,		"filesize": 91241443	}}
[2021-02-06 14:12:02] [eze] [info] Sending the following tags to LRR: artist:nishi, character:producer, character:shiki ichinose, female:anal, female:blowjob, female:smell, female:sole female, female:stockings, female:sweating, group:count2.4, male:armpit licking, male:rimjob, male:sole male, parody:the idolmaster, source: exhentai.org/g/1093785/b5f8ed8633

**Comment by Difegue** [comment]
You can see in the last line of the plugin log that it only returns the following tags to LRR:  
```artist:nishi, character:producer, character:shiki ichinose, female:anal, female:blowjob, female:smell, female:sole female, female:stockings, female:sweating, group:count2.4, male:armpit licking, male:rimjob, male:sole male, parody:the idolmaster, source: exhentai.org/g/1093785/b5f8ed8633```  

I suspect the `language: 1093785` mistag is happening somewhere else -- If you have Auto-Tag enabled it might be inferring it from your archive's filename.

**Comment by darkred3** [comment]
Yes, that seems to be the case. I do believe an included json should rank higher in the priority list tho. Why a string of numbers gets recognized as a language is also beyond me.
For the time being I'll just disable the Auto-Tag plugin.

**Comment by Difegue** [comment]
Well, there's not really a priority list to speak of, the current workflow mostly just pools everything that's enabled.  ¯\\\_(ツ)_/¯  
Auto-Tag is a bit of an old feature (it dates from ye humble beginnings of the app when there was no database and just a pile of cgi scripts) and could probably be moved to a metadata plugin and disabled by default.

**Comment by darkred3** [comment]
Hmm, a few days later and I tried to add galleries again but no language tag is being parsed no matter what I do. Auto-Tag is disabled of course. Tried with both Auto-Plugin and manual Batch Tagging.
Btw, what does "Save archive title" under the eze plugin do?

**Comment by Difegue** [comment]
"Save archive title" instructs the plugin to overwrite the recorded title for the archive in the database with the one found in the json file.  
The recorded title can be either a parsed one if you have auto-tag on, or just the basic filename of the archive -- This is all done in DB only so there's no file renaming.

**Comment by darkred3** [comment]
Something slightly different is happening for me. (Auto-Tag is off btw)

```
Filename: (C95) [Anon's Flood Myth (Anon 2-okunen)] Tenpu no Ecchi EX (Fate Grand Order) [1395795].7z
Json title: (C95) [Anon's Flood Myth (Anon 2-okunen)] Tenpu no Ecchi EX (Fate/Grand Order)
```

```
Save archive title ON: Tenpu no Ecchi EX
Save archive title OFF: (C95) [Anon's Flood Myth (Anon 2-okunen)] Tenpu no Ecchi EX (Fate Grand Order) [1395795]
```

As I understand it, with ON I should be getting the Json title while in reality I'm getting a parsed one without the extra stuff like event, artist, parody etc., while OFF is working correctly.

Also I noticed that the eze plugin is working slightly differently from the e-hentai plugin. The e-hentai plugin includes these additional tags: "category", "timestamp" and "uploader". Granted, the timestamp and uploader tags are optional, but I think the eze plugin should include this as well.
But even with the e-hentai plugin, no language tag is parsed.

**Comment by Difegue** [comment]
I forgot about that, but the eze plugin does use similar regex parsing to only save the title without the extra metadata.  
I've been refactoring away auto-tag into its own plugin, so that should go away in the eze plugin as well.
