### ISSUE TITLE
[Feature Request] Add Unicode normalization support

### ISSUE THREAD

**Issue by sirius422** [Difegue/LANraragi#410]
Before talking about the issue, I want to express my thank for you. LRR librate me from the hell of arrange my manga librarys.

Most of the files in my LRR library have filenames in Japanese. I found LRR behaved abnormally when I searched my library for some certain artist:
<img width="904" alt="1" src="https://user-images.githubusercontent.com/38351200/108306534-51e0c080-71e7-11eb-9e60-c3a46fef9361.png">
The search bar suggested two entries, which looks the same. However, when I applied the filter respectively, they gave me different search results, suggesting they were actually different even though they looked the same. 
I found the former one is ジ (U+30B7) while the latter one is combined by シ (U+30B7) and ゛ (U+309B), Katakana-Hiragana Voiced Sound Mark, like U+0303, the Combining Tilde, which looks like this -> ~.

Due to lacking of support for Unicode normalization, when the metadata crawler extract metadata like title and tags from the filename, it just use whatever in the filename without normalize it, which causes the issue. Would Love if you can implement some kind of Unicode normalization when extract & edit metadata.

**Comment by Difegue** [comment]
Thank you for opening an issue for this! 👍  

I plan on eventually adding https://metacpan.org/pod/Unicode::Normalize into the dependencies and call upon it when saving tags and title to the database.

**Comment by Difegue** [comment]
Found some time after #282 and #405 to get this done today: All writes to the database that were utf-8 encoded are now also normalized to **NFC**.  

I've also added a temporary script plugin to fix existing databases by normalizing all their data to NFC:  
![image](https://user-images.githubusercontent.com/8237712/108877977-0de32680-7600-11eb-8262-57217a57303f.png) 
So you should be able to fix the issue quickly once the new release drops. 🎉
