### ISSUE TITLE
Permission error no matter in admin or root mode

### ISSUE THREAD

**Issue by lukemin** [Difegue/LANraragi#419]
**LRR Version and OS**
docker pull difegue/lanraragi
Using default tag: latest
latest: Pulling from difegue/lanraragi
Digest: sha256:1c7489ac79d8bad7dbb5fe3ac147585431c43940d41f8f2a5314cc8592b20401
Status: Image is up to date for difegue/lanraragi:latest
**also the image with latest tag is 0.7.5 not 0.7.7**
OS：
Synology Diskstation DS3615xs
DSM 6.2.3-25426 Update 3

**Bug Details**
Permission error no matter in admin or root mode
**Matching Logs**
**Running in admin mode**
uid=1024(admin) gid=100(users) groups=100(users),101(administrators)
`nit] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-lrr-setup: executing... 
Starting LANraragi with UID/GID : 1024/1000
mkdir: can't create directory '/home/koyomi/lanraragi/log': File exists
mkdir: can't create directory '/home/koyomi/lanraragi/public/temp': File exists
WARNING: overcommit_memory is set to 0! This might lead to background saving errors if your database is too large.
Please check https://redis.io/topics/faq#background-saving-fails-with-a-fork-error-under-linux-even-if-i-have-a-lot-of-free-ram for details.
[cont-init.d] 01-lrr-setup: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!!!!!
[LANraragi] [info] LANraragi 0.7.5 started. (Production Mode)
[LANraragi] [info] Plugin Detected: Chaika.moe
[LANraragi] [info] Plugin Detected: Tag Copier
[LANraragi] [info] Plugin Detected: Date Added
[LANraragi] [info] Plugin Detected: E-Hentai
[LANraragi] [info] Plugin Detected: eze
[LANraragi] [info] Plugin Detected: Hdoujin
[LANraragi] [info] Plugin Detected: koromo
[LANraragi] [info] Plugin Detected: Mayriad's EH Master Script
[LANraragi] [info] Plugin Detected: nHentai
[LANraragi] [info] Script Detected: Migrate Favorite Tags
[LANraragi] [info] Script Detected: Subfolders to Categories
[LANraragi] [info] Script Detected: Source Finder
[LANraragi] [info] Downloader Detected: Chaika.moe Downloader
[LANraragi] [info] Downloader Detected: E*Hentai Downloader
[LANraragi] [info] Successfully connected to Minion database.
[Minion] [info] Starting new Minion worker in subprocess with 4 parallel jobs.
[Minion] [info] Minion worker 7597 started
Logging to "log/production.log" is DEPRECATED at /home/koyomi/lanraragi/script/../lib/LANraragi/Utils/Generic.pm line 131.
[LANraragi] [info] Routing done! Ready to receive requests.
[Minion] [info] Warming up search cache...
[Minion] [info] Done!
Logging to "log/production.log" is DEPRECATED at /usr/local/share/perl5/site_perl/Mojo/Server/Hypnotoad.pm line 69.
Web application available at http://127.0.0.1:3000
[Shinobu] [info] Shinobu File Watcher started.
[Shinobu] [info] Working dir is /home/koyomi/lanraragi
[Shinobu] [info] Scanning content folder for changes...
Can't opendir(/home/koyomi/lanraragi/content): Permission denied
 at ./lib/Shinobu.pm line 129.
[Shinobu] [info] Adding watcher to content folder /home/koyomi/lanraragi/content
Can't opendir(/home/koyomi/lanraragi/content): Permission denied
 at /usr/local/share/perl5/site_perl/File/ChangeNotify/Watcher/Inotify.pm line 172.
[Shinobu] [info] All done! Now dutifully watching your files. 
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.`

**Running in root mode**
uid=0(root) gid=0(root) groups=0(root),2(daemon),19(log)
`>s6-init] making user provided files available at /var/run/s6/etc...exited 0.
>[s6-init] ensuring user provided files have correct perms...exited 0.
>[fix-attrs.d] applying ownership & permissions fixes...
>[fix-attrs.d] done.
>[cont-init.d] executing container initialization scripts...
>[cont-init.d] 01-lrr-setup: executing... 
>Starting LANraragi with UID/GID : 0/0
>usermod: UID '0' already exists
>groupmod: GID '0' already exists
>mkdir: can't create directory '/home/koyomi/lanraragi/log': File exists
>mkdir: can't create directory '/home/koyomi/lanraragi/public/temp': File exists
>WARNING: overcommit_memory is set to 0! This might lead to background saving errors if your database is too large.
>Please check https://redis.io/topics/faq#background-saving-fails-with-a-fork-error-under-linux-even-if-i-have-a-lot-of-free-ram for details.
>[cont-init.d] 01-lrr-setup: exited 0.
>[cont-init.d] done.
>[services.d] starting services
>[services.d] done.
>ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!!!!!
>[LANraragi] [info] LANraragi 0.7.5 started. (Production Mode)
>[LANraragi] [info] Plugin Detected: Chaika.moe
>[LANraragi] [info] Plugin Detected: Tag Copier
>[LANraragi] [info] Plugin Detected: Date Added
>[LANraragi] [info] Plugin Detected: E-Hentai
>[LANraragi] [info] Plugin Detected: eze
>[LANraragi] [info] Plugin Detected: Hdoujin
>[LANraragi] [info] Plugin Detected: koromo
>[LANraragi] [info] Plugin Detected: Mayriad's EH Master Script
>[LANraragi] [info] Plugin Detected: nHentai
>[LANraragi] [info] Script Detected: Migrate Favorite Tags
>[LANraragi] [info] Script Detected: Subfolders to Categories
>[LANraragi] [info] Script Detected: Source Finder
>[LANraragi] [info] Downloader Detected: Chaika.moe Downloader
>[LANraragi] [info] Downloader Detected: E*Hentai Downloader
>[LANraragi] [info] Successfully connected to Minion database.
>[Minion] [info] Starting new Minion worker in subprocess with 4 parallel jobs.
>[Minion] [info] Minion worker 7593 started
>[Minion] [info] Warming up search cache...
>Logging to "log/production.log" is DEPRECATED at /home/koyomi/lanraragi/script/../lib/LANraragi/Utils/Generic.pm line 131.
>[Minion] [info] Done!
>[LANraragi] [info] Routing done! Ready to receive requests.
>Logging to "log/production.log" is DEPRECATED at /usr/local/share/perl5/site_perl/Mojo/Server/Hypnotoad.pm line 69.
>Web application available at http://127.0.0.1:3000
>[Shinobu] [info] Shinobu File Watcher started.
>[Shinobu] [info] Working dir is /home/koyomi/lanraragi
>[Shinobu] [info] Scanning content folder for changes...
>Can't opendir(/home/koyomi/lanraragi/content): Permission denied
> at ./lib/Shinobu.pm line 129.
>[Shinobu] [info] Adding watcher to content folder /home/koyomi/lanraragi/content
>Can't opendir(/home/koyomi/lanraragi/content): Permission denied
> at /usr/local/share/perl5/site_perl/File/ChangeNotify/Watcher/Inotify.pm line 172.
>[Shinobu] [info] All done! Now dutifully watching your files. `

**Screenshots**

**Comment by Difegue** [comment]
You're pulling/using 0.7.5 somehow, and the `latest` tag does point to 0.7.7:  

![image](https://user-images.githubusercontent.com/8237712/111134824-47161300-857c-11eb-9772-f665967378ca.png)

**Comment by lukemin** [comment]
After repulling for dockerhub, the version was upto 0.7.7.
But a strange bug was found, some names of my mangas cannot not display fully. some of the Japane characters were missing eg Manga-649198-[音乃夏] 女子高生の腰つき [中国翻訳] was displayed  as Manga-649198-.  `[音乃夏] 女子高生の腰つき [中国翻訳]` was missing.
![LANraragi - Batch Tagging 和另外 8 个页面 - 个人 - Microsoft​ Edge 2021_3_15 23_12_47](https://user-images.githubusercontent.com/12003375/111176578-6ba5d580-85e4-11eb-8845-f966b456d83a.png)
I also attached the link of this mange, please kindly check.
[https://1drv.ms/u/s!ArlOWFXvgOaPli0O1iCIZHjwJM5C?e=muMTLT](https://1drv.ms/u/s!ArlOWFXvgOaPli0O1iCIZHjwJM5C?e=muMTLT)

**Comment by Difegue** [comment]
Right, the `Manga-xxxxx-[...]` names are tripping up the regex parsing plugin:  
```
[Shinobu] [debug] Received inotify event create on /mnt/e/Projects/lrr/content/Manga-649198-[音乃夏] 女子高生の腰つき [中国翻訳].cbz
[Shinobu] [debug] Adding /mnt/e/Projects/lrr/content/Manga-649198-[音乃夏] 女子高生の腰つき [中国翻訳].cbz to Shinobu filemap.
[Shinobu] [debug] Computed ID is cef7cbbd17a2901c7b11394021747c64e27905a9.
[Plugin System] [info] No login plugin specified, returning empty UserAgent.
[regexparse] [info] Sending the following tags to LRR: language:音乃夏
[regexparse] [info] Parsed title is Manga-649198-
```  
I recommend you either:  
- Rename your files to remove the `Manga/Doujinshi/Unknown-xxxx` prefixes, in which case regexparse should fill metadata properly since the names seem to match the standard otherwise
- Disable the regex plugin in Plugin Configuration since it won't be able to provide you proper information with names like this.
