### ISSUE TITLE
Japanese language "tag"

### ISSUE THREAD

**Issue by darkred3** [Difegue/LANraragi#422]
Sadpanda doesn't allow tagging japanese galleries as such with the exception of a few cases. It does however have a, I'll just call it _secondary language tag_.

![japanese](https://user-images.githubusercontent.com/33666486/111309539-4eace900-865c-11eb-8476-0beff8dd25b9.jpg)

I think it would be helpful if metadata plugins would recognize if no _normal language tag_ exists and then look for this _secondary language tag_ instead.

**Comment by Difegue** [comment]
This field defaults to japanese and is potentially incorrect until a proper `language:` tag is voted to 100 on EH, at which point it just shows the contents of said tag.  

(See comments in #485 for more detail)  
Closing this as wontfix for now.
