### ISSUE TITLE
favicon or similar to use as shortcut

### ISSUE THREAD

**Issue by ChronoStriker1** [Difegue/LANraragi#423]
Just a simple request for an icon to use for a bookmark or shortcut.  In my case an icon that I can use in Organizr.

**Comment by Difegue** [comment]
The current favicon.ico has been there for about 5 years and was ripped off some japanese monogatari website, so I certainly don't mind switching things up a bit while I'm at it.

<img src="https://user-images.githubusercontent.com/8237712/111383620-c1dc4c80-86a8-11eb-9e08-d07d11bdb69d.png" width="250"/>
