### ISSUE TITLE
[Issue] Invalid Argument

### ISSUE THREAD

**Issue by VeganHentai** [Difegue/LANraragi#43]
Getting an invalid argument error located in /lib/LANraragi/Model/Utils.pm line 99. This happened after it added a few archives and now it's just repeatedly outputting this in the console.

![cmd_2018-05-10_00-15-15](https://user-images.githubusercontent.com/25962087/39851875-8dd0a446-53e7-11e8-9487-d41cf00dbb1b.png)

**Comment by Difegue** [comment]
Utils.pm line 99 matches ID computation for archives, sounds like the app can't open your archives for some reason. Maybe a permission issue?

I'd recommend switching your content folder's location in Configuration.

**Comment by VeganHentai** [comment]
I changed the content folder's location to an external drive that contained all my archives and received the errors. I moved it back to the default location and copied over archives and have yet to receive any errors. It's working as of right now.

**Comment by Difegue** [comment]
Weird stuff, but glad it works! I'll add some extra logging to that part so future issues of that kind get a more thorough lookup.
