### ISSUE TITLE
Way to view tags within the reader

### ISSUE THREAD

**Issue by ub333** [Difegue/LANraragi#437]
LANraragi doesn't have a "gallery" view like most websites and goes right from the search page into the reader view. That's fine with me, but I really miss being able to view an archive's associated tags.

My use case is to view a random archive, then find similar archives using its tags. Right now, the only way to view an archive's tags is to open the edit window, read them from the edit box (yuck), copy one, then paste it back into the search window in another tab. Not very slick!

So, any way to simplify seeing an archive's tags while viewing it would be greatly appreciated. (And have the tags clickable!)

Otherwise love the program - very clean!

**Comment by Difegue** [comment]
This has been a semi-frequent feature request -- Now that https://github.com/Difegue/LANraragi/issues/336 is done it shouldn't be too hard to add clickable tags to the reader view.  

I still want to keep the one-click search -> reader workflow, so I'll probably add the extra gallery info into the page overlay that pops up when you press CTRL currently.

**Comment by ub333** [comment]
Awesome yeah, that sounds exactly how I'd want it! 🙂👍

**Comment by Difegue** [comment]
🎬 And that's a wrap for 0.7.8's features, I think.

![image](https://user-images.githubusercontent.com/8237712/113490438-2af5f980-94ca-11eb-86da-eab1b690850c.png)
