### ISSUE TITLE
🆕 The 2021 LRR User Survey is live! 🆕

### ISSUE THREAD

**Issue by Difegue** [Difegue/LANraragi#448]
![e5228ad5aaf88f97b8d639684c7bb83c016409a3c21db0e672268ae1ce4c8614](https://user-images.githubusercontent.com/8237712/113921980-04e09a00-97e7-11eb-9849-3276ce9eeb63.png)  

Suggest new features and give feedback without having to create a GitHub account!  
# Check **[here](https://tvc-16.science/lrr-survey-3.html)** for more info.

**Comment by Nixis198** [comment]
Where the hell do you find theses pictures?

**Comment by Difegue** [comment]
![6093819cb61bb83d614978a5a02b96f443cc28a56e6ac5181a66be8c478873b6](https://user-images.githubusercontent.com/8237712/114200439-81918680-9955-11eb-99c4-0fdb0ed1e647.jpg)

**Comment by Difegue** [comment]
Updating this pinned issue one last time to make it a showcase for the current user survey. ❤

**Comment by Difegue** [comment]
The survey results are in and can be read [here](https://tvc-16.science/lrr-survey-3-results.html)!
