### ISSUE TITLE
[Bug] [UI] Page preview follows the mouse after page update.

### ISSUE THREAD

**Issue by Nixis198** [Difegue/LANraragi#466]
**LRR Version and OS**
Docker Version 0.7.8, "Looking for Lester" UNRAID 6.9.2

**Bug Details**
If you hover over a title to get the page preview and then the page updates (like when it does after it is done searching for something) the page preview will follow the cursor until you click on something else.

**Screenshots**
![image](https://user-images.githubusercontent.com/29938035/117080487-ee593000-ad0b-11eb-9173-555e1b44e154.png)
Just picture that the mouse is in the pic. The screenshot didn't show the cursor.

**Comment by Nixis198** [comment]
![image](https://user-images.githubusercontent.com/29938035/121456985-ef1d5b80-c974-11eb-8a68-98fbbadb9ba0.png)
Yeah its still not fixed.
In order to recreate it click on a series title to make it search for that title, then hover over a title to make the preview show up.
Once it is done searching the preview will follow the mouse.
Also I'm not sure why it says there are no neon genesis evangelion manga's.

**Comment by Difegue** [comment]
The fix wasn't applying for every possible search path, I moved it further up so it should be good now 🤠👍
