### ISSUE TITLE
Server side progress tracking ruins UX for multiple user setups

### ISSUE THREAD

**Issue by Nodja** [Difegue/LANraragi#474]
I have several people using the same lanraragi instance, the server side progress tracking ruins the experience as things someone has seen are marked as viewed and most importantly, if you open a manga someone left halfway it resumes on the same page which can be quite annoying if you don't notice.

There's also some uncomfortable privacy implications as my instance is a fakku mirror so you can kinda tell what stuff others have read (there's only a handful of users).

Possible solutions
1. Allow server admin to disable tracking for everyone
2. Allow server admin to choose between server tracking and local tracking
3. Support multiple users and track everything server side

3\. would be ideal, but probably too hard to implement for little gain as it seems no one has even requested multi-user support. 2. probably fits the scope of the project better while 1. would be a quick fix solution at best.

**Comment by Difegue** [comment]
I've had this issue on the back of my mind since releasing server-side progress and seeing it in public LRR instances like https://voidscans.net/ (which has stopped using LRR since then, probably because it wasn't a great fit).  

I was planning to bring back the clientside progress code as a server-side toggle, which is basically solution 2 in your list. Haven't gotten to it yet though 😶

**Comment by Nodja** [comment]
As a workaround I made a small script that clears the read progress and run it on a cron job every 5 minutes.

```perl
use Redis;

my $redis = Redis->new;

my @keys = $redis->keys('?' x 40);

for (@keys) {
    $redis->hdel($_, "progress");
    $redis->hdel($_, "pagecount");
}
```

Not the cleanest way to solve the issue, but solves most of the annoyances until individual tracking gets implemented :P

**Comment by Difegue** [comment]
You now get a neat toggle to restore the previous tracking behavior:  
![image](https://user-images.githubusercontent.com/8237712/120354004-69f5cf00-c302-11eb-88cf-893be821d579.png)  

I only restored saving the progression to localStorage, the pagecount will still be recorded/saved on the server as that actually improves UX. 🥇

**Comment by Difegue** [comment]
To keep in mind:  

* Reenabling serverside tracking will run the progress migration routine on the next load of the Archive Index in a browser
* The API call to set progress now fails if clientside tracking is enabled: Clients can use the `/api/info` endpoint to check if they can call the progress API:  
![image](https://user-images.githubusercontent.com/8237712/120355114-50a15280-c303-11eb-8ec1-ccc216ff01d8.png)
FYI @Guerra24 @Utazukin

**Comment by Nodja** [comment]
Thank you for this. It seems to be working properly using the nightly docker image 👍
