### ISSUE TITLE
FAKKU plugin fails to retrieve metadata from pages that contain "Controversial Content" tags

### ISSUE THREAD

**Issue by pandafeliz** [Difegue/LANraragi#475]
**LRR Version and OS**
Version 0.7.8, "Looking for Lester" (Windows)

**Bug Details**
As the title says, the plugins fails to retrieve any information if the content is behind the "Show Controversial Content" filter.

**Matching Logs**
`Error: Can't call method "child_nodes" on an undefined value at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/Metadata/Fakku.pm line 163.`

**Screenshots**
![image](https://user-images.githubusercontent.com/72732463/118640475-a2dc6280-b79e-11eb-991e-1215d6b75540.png)

**Comment by Difegue** [comment]
IIRC the controversial content filter requires an account to get past?  
The Fakku plugin is kind of a bare-bones implementation, so I didn't bother adding account support.

**Comment by wongsaraf** [comment]
It indeed need an account, even a free account can access and search controversial contents.
