### ISSUE TITLE
Older Fakku content without descriptions causes a method call error

### ISSUE THREAD

**Issue by Fredddi43** [Difegue/LANraragi#476]
**LRR Version and OS**
Version 0.7.8 on Ubuntu Docker

**Bug Details**
Trying to import metadata through the plugin from older Fakku content such as the (NSFW obviously) [Rule of Zero](https://www.fakku.net/hentai/rule-of-zero-part-1-rule-english) series causes an error when fetching tags. Possibly related to not having descriptions.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/11667112/119418837-32cb6080-bcf9-11eb-8e40-9ba2fd45d501.png)

**Comment by Difegue** [comment]
Turns out the crash wasn't caused by the missing "Description" section, but by the "Direction" one, which I'd never seen before and didn't account for when writing the parser. Should be good now!
