### ISSUE TITLE
Empty Archive Index

### ISSUE THREAD

**Issue by Robert99943** [Difegue/LANraragi#48]
After going through and tagging a bunch of my archives, My archive index stopped showing anything. Archives can still be read if I go to a random one and they are on record in statistics. I have given it about 12 hours to make sure it wasn't just reloading from all the changes I made and restarted it. The only thing that comes up in the logs is
`[Shinobu] [info] Archive count (313) has changed since last cached value (319) OR rebuild has been forced (flag value = 0), rebuilding...
[Shinobu] [info] Done!`
every 5 seconds.
![1nlqp](https://user-images.githubusercontent.com/15913135/42121154-97711ba6-7bf7-11e8-9b6a-ea2b7fa5dacb.png)

**Comment by Difegue** [comment]
Sounds like the json cache is failing to build properly. Which OS are you running on ?  

You can try enabling debug mode in Configuration to get more detailed logs.

**Comment by Robert99943** [comment]
I am on Arch Linux. Debug LANraragi logs don't show much more and other logs don't seem to have anything that looks out of the ordinary.
```
ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!!!!!
[LANraragi] [info] LANraragi 0.5.2 (re-)started. (Debug Mode)
[LANraragi] [info] Plugin Detected: Chaika.moe
[LANraragi] [info] Plugin Detected: E-Hentai
[LANraragi] [info] Plugin Detected: eze
[LANraragi] [info] Plugin Detected: nHentai
[LANraragi] [info] Terminating previous Shinobu Worker... (PID is 30510)
[Shinobu] [info] Shinobu Background Worker started -- Content folder will be scanned every 5 seconds.
[Shinobu] [info] Working dir is /home/koto/LANraragi
[Shinobu] [info] Archive count (1361) has changed since last cached value (1442) OR rebuild has been forced (flag value = 1), rebuilding...
[Shinobu] [debug] Treated 1 archives out of 1442 .
[Shinobu] [debug] Treated 2 archives out of 1442 .
...
[Shinobu] [debug] Treated 1441 archives out of 1442 .
[Shinobu] [debug] Treated 1442 archives out of 1442 .
[Shinobu] [info] Done!```

**Comment by Difegue** [comment]
1442 files is quite a difference compared to the 313 that were on the previous log.  
However, since you're not getting any extra lines, it means all files have been properly analyzed and accounted for in the database.  

I'd need a dump of the json cache to make sure -- it's likely that incorrect json is being created for some reason.  

The json cache can be obtained in two ways:
* It's normally present in the Archive Index as a dumb javascript variable - You can work some Inspect Element magic to get it, and the browser console might be outputting some errors if it indeed is an incorrect json issue.  
* If that fails, it's in the Redis database under the LRR_JSONCACHE hash.

**Comment by Robert99943** [comment]
I had downloaded a big collection of stuff into the archive directory but the issue was happening before this.  
I think this is it, and as far as console errors go, I do get `SyntaxError: missing } after property list note: { opened at line 3160, column 2` as well as `ReferenceError: archiveJSON is not defined`
[cache.txt](https://github.com/Difegue/LANraragi/files/2151777/cache.txt)

**Comment by Robert99943** [comment]
I exported the database, removed the double quote, and re-imported it and that seems to have worked as well. Thank you for the help.

**Comment by Difegue** [comment]
Oh yeah, that works too.  
Thanks for the report! I'll be adding JSON escaping to titles alongside some better error handling on the index side for the next release.
