### ISSUE TITLE
Will there be any updates in regards to the Veracrypt issue?

### ISSUE THREAD

**Issue by RedRain77** [Difegue/LANraragi#488]
<!-- hol up senpai have you checked out the GH Discussions first ? 
Your issue/idea might've already been reported by someone else! 🐱‍👤
https://github.com/Difegue/LANraragi/discussions
->

**LRR Version and OS**
LANraragi v.0.7.9, Windows 10 19041.685

**Bug Details**
Is there any update on the bug reported [here](https://github.com/Difegue/LANraragi/issues/182)?

**Comment by RedRain77** [comment]
Sorry, My description seemed to disappear.

**LRR Version and OS**
Please tell which version you're running, as well as your OS and installation method. (Windows, Docker, Native)

**Bug Details**
Please detail the bug here. 

**Matching Logs**
Post any logs you have encountered when reproducing the bug.  
If possible, switch the app to Debug Mode in order to have more logs.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by Difegue** [comment]
VeraCrypt volumes can supposedly work if you use WSL2(can be toggled in the settings of the Windows app), according to the comment here: https://github.com/Microsoft/WSL/issues/530#issuecomment-866342690 .   

We're hitting niche-within-niche usages here, so I don't really plan on adding explicit support for Veracrypt volumes to the Windows helper app at the moment.
