### ISSUE TITLE
Issues with Config::AutoConf

### ISSUE THREAD

**Issue by KamillaPup** [Difegue/LANraragi#512]
I'm trying to install from source to an Ubuntu VM running on my QNAP and failing. I installed the prerequisites and created the user "kemoshota" for lanraragi specifically. However, when running the installer from /home/kemoshota/lanraragi I get the following error.

```
Linux QNAP-VM 5.11.0-37-generic #41-Ubuntu SMP Mon Sep 20 16:39:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Working Directory: /home/kemoshota/lanraragi

IPC::Cmd package installed, proceeding...
Config::AutoConf not installed! Trying to install now using cpanm
Can't write to cpanm home '/root/.cpanm': You should fix it with chown/chmod first.
Can't locate Config/AutoConf.pm in @INC (you may need to install the Config::AutoConf module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at ./tools/install.pl line 89
```

As a test, I ran it as root and I got the same error. In /root/ there is no file called .cpanm. I even tried adding it with no luck :<

I think QNAP natively supports Docker but i have zero experience with Docker.

**Comment by Difegue** [comment]
You might want to try installing `Config::AutoConf` manually before running the installer:
`cpanm Config::AutoConf`  

cpanm normally writes to a user-writable directory for non-root installs, so I'm not sure why it's trying to write to `/root` here.

**Comment by KamillaPup** [comment]
Thanks for the quick reply! Config:AutoConf installed without issue but I still get the same error. Here's a bit more of it.
```
kemoshota@zabivaka-VM:~/lanraragi$ sudo npm run lanraragi-installer installer-full
[sudo] password for kemoshota: 

> lanraragi@0.8.0 lanraragi-installer
> perl ./tools/install.pl "installer-full"

⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣠⣴⣶⣿⠿⠟⠛⠓⠒⠤
⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣠⣾⣿⡟⠋
⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢰⣿⣿⠋
⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⢀⣿⣿⠇⡀
⢀⢀⢀⢀⢀⢀⢀⢀⢀⣀⣤⡆⢿⣿⢀⢿⣷⣦⣄⣀
⢀⢀⢀⢀⢀⢀⢀⣶⣿⠿⠛⠁⠈⢻⡄⢀⠈⠙⠻⢿⣿⣆
⢀⢀⢀⢀⢀⢀⢸⣿⣿⣶⣤⣀⢀⢀⢀⢀⢀⣀⣤⣶⣿⣿
⢀⢀⢀⢀⢀⢀⢸⣿⣿⣿⣿⣿⣿⣶⣤⣶⣿⠿⠛⠉⣿⣿
⢀⢀⢀⢀⢀⢀⢸⣿⣿⣿⣿⣿⣿⣿⣿⠉⢀⢀⢀⢀⣿⣿
⢀⢀⢀⢀⣀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⢀⢀⢀⣠⣴⣿⣿⣦⣄⡀
⢀⣤⣶⣿⠿⠟⠉⢀⠉⠛⠿⣿⣿⣿⣿⣴⣾⡿⠿⠋⠁⠈⠙⠻⢿⣷⣦⣄
⣿⣿⣯⣅⢀⢀⢀⢀⢀⢀⢀⣀⣭⣿⣿⣿⣍⡀⢀⢀⢀⢀⢀⢀⢀⣨⣿⣿⡇
⣿⣿⣿⣿⣿⣶⣤⣀⣤⣶⣿⡿⠟⢹⣿⣿⣿⣿⣷⣦⣄⣠⣴⣾⡿⠿⠋⣿⡇
⣿⣿⣿⣿⣿⣿⣿⣿⡟⠋⠁⢀⢀⢸⣿⣿⣿⣿⣿⣿⣿⣿⠛⠉⢀⢀⢀⣿⡇
⣿⣿⣿⣿⣿⣿⣿⣿⡇⢀⢀⢀⢀⣸⣿⣿⣿⣿⣿⣿⣿⣿⢀⢀⢀⢀⢀⣿⡇
⠙⢿⣿⣿⣿⣿⣿⣿⡇⢀⣠⣴⣿⡿⠿⣿⣿⣿⣿⣿⣿⣿⢀⣀⣤⣾⣿⠟⠃
⢀⢀⠈⠙⠿⣿⣿⣿⣷⣿⠿⠛⠁⢀⢀⢀⠉⠻⢿⣿⣿⣿⣾⡿⠟⠉
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~LANraragi Installer~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Working Directory: /home/kemoshota/lanraragi

IPC::Cmd package installed, proceeding...
Config::AutoConf not installed! Trying to install now using cpanm
Can't write to cpanm home '/root/.cpanm': You should fix it with chown/chmod first.
Can't locate Config/AutoConf.pm in @INC (you may need to install the Config::AutoConf module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at ./tools/install.pl line 89.
```

**Comment by Difegue** [comment]
Hm, it's very weird that the installer can't figure out you already have the package installed here; Can you try running it without `sudo`?  

Past that I'll admit that I'm a bit stuck 😥

**Comment by KamillaPup** [comment]
No luck running without sudo. I'm at a loss too! It's too bad no one made a Debian/Ubuntu build and only arch. I have it running flawlessly on my Windows 10 and MacOS Big Sur system so it's weird I can't use the source files.

On the VM I'm using, I also have qBitorrent, PiHole, and various other services running. I'm sure one of those autoinstallers screwed with things. I may start with a fresh no-gui build of maybe Arch and let you know how that works.

**Comment by KamillaPup** [comment]
Whoops... Arch is out of date. What Linux flavor do you test with that you know works on a vanilla fresh install? Debian?

**Comment by Difegue** [comment]
I personally only use Debian for source installs, yeah.

**Comment by KamillaPup** [comment]
I just realized QNAP has a native Docker GUI application which was SO easy to setup. Pretty much set the content drive and start! Such a relief. I was able to export/import the database without issue.
<img width="1038" alt="CleanShot 2021-10-06 at 06 20 01@2x" src="https://user-images.githubusercontent.com/26353056/136193142-49aeb9d5-547e-4241-bba2-2d9b56ceeb0c.png">
