### ISSUE TITLE
Make date_added a default feature

### ISSUE THREAD

**Issue by Difegue** [Difegue/LANraragi#516]
It's been there long enough and most people seem to want to use it for sorting, so it certainly deserves the promotion.  

It'll likely be a separate database field instead of being in the tags like it currently is, which allows me to give it better formatting as well (proper dates instead of a UNIX timestamp? wow!)

**Comment by CirnoT** [comment]
How do you see it working with alternatives (such as EH plugin's `timestamp` field)?

**Comment by Difegue** [comment]
I've added specific formatting for `date_added` (and `timestamp`) in the webUI to show them as human-readable dates.  

To keep backwards compatibility (and also because it's easier lmao), the date is now added by default in the tags field.
