### ISSUE TITLE
[Bug Report] file with Chinese or Japanese character fails to load

### ISSUE THREAD

**Issue by frankli998** [Difegue/LANraragi#542]
**LRR Version and OS**
Synology(Linux) Docker
v 0.8.2

**Bug Details**
file with Chinese or Japanese character fails to load, can't generate thumbnails nor to read

**Matching Logs**
Post any logs you have encountered when reproducing the bug.  
If possible, switch the app to Debug Mode in order to have more logs.

**Screenshots**

**Comment by Difegue** [comment]
Fixed by https://github.com/Difegue/LANraragi/commit/afc9a5cd3e87f0e3c21e1c31919312ff051a441c .
