### ISSUE TITLE
[bug] pdf file wont be loaded correctly

### ISSUE THREAD

**Issue by chinobing** [Difegue/LANraragi#554]
![image](https://user-images.githubusercontent.com/27722028/143334668-e2a3088c-4dbc-490b-b405-01afe1862ddc.png)

https://lrr.tvc-16.science/reader?id=6440d00f35b4f0a008d3fd63c3cdcce32d4cb608

**Comment by Difegue** [comment]
Issue caused by a ghostscript update, apologies!  
The above commit should make things work in > 9.50 and keep compatibility with previous versions.
