### ISSUE TITLE
Can't open files

### ISSUE THREAD

**Issue by mazick** [Difegue/LANraragi#56]
[Shinobu] [error] Couldn't open A:/xxxxx/xxxxxx/xxxxxx/chapters/someshit.zip :Invalid argument at A:/LRR 0.5.4/lanraragi/lib/../lib/LANraragi/Utils/Database.pm line 104.

I get this error for every file that it trys to load, i dont know what to do about it.

**Comment by Difegue** [comment]
Sounds like a simple file permission issue. What OS/installation method are you using?

**Comment by mazick** [comment]
Windows automatic method. 

Yeah i think it should be that to but it should have permission to run. If i use upload archive it has no problem, its only when give it a directory to pull from it has a problem. Maybe im missing something?

**Comment by Difegue** [comment]
I do recall having encountered a similar issue once during Windows tests, but I can't remember how to fix it.  

Running the startup .bat as Administrator might fix your issues if it's indeed a permission problem.  
If that fails, are your files processed properly when you copy them to the default content folder ?

If that also fails, it might also be issue #42 creeping up again if you're running under Japanese locale or an equivalent - As the upload archive feature automatically converts filenames, encoding isn't an issue when using it.  

(And good ol' #42 still gets a wontfix from me by the way, too much work for little returns.)

**Comment by mazick** [comment]
Ok after forcing it to run as administrator it still just errors out although to run it as admin i had to force it through cmd, it wouldn't let me do it in the explorer window. 

I tried a manual installation just to see if that changes anything and..

[2018-10-11 14:08:50] [Shinobu] [info] Adding new file zz:/zzzzz/zzzz/zzzz/zzzz.rar with ID someidstuff

[2018-10-11 14:08:50] [Shinobu] [error] Undefined subroutine &LANraragi::Model::Plugins::exec_enabled_plugins_on_file called at ./lib/Shinobu.pm line 194.

So a slightly different error this time. 

Now to see if its a problem on the particular drive that the archive is located in i changed the directory to a folder on my desktop and put a few manga in there and had the same error as above. 

So this is still unresolved. I really wanna use this tool for my manga to T_T. Im not the most experienced with things like this so im not sure where to go from here.

**Comment by Difegue** [comment]
An undefined subroutine error shouldn't be happening at all!  
Sounds like your manual installation is either missing files or not starting the app properly, inducing broken references.

If you're not very experienced I would recommend doing a [Vagrant](https://github.com/Difegue/LANraragi/wiki/Installing-LANraragi#vagrant-installation-recommended-for-dockerless-machines) install.

**Comment by Difegue** [comment]
Welp there indeed was a bug with autodetection of archives - I'll be pushing a hotfix soon to clear this up.

Sorry for the inconvenience!

**Comment by Difegue** [comment]
Fixed in v.0.5.4-EX.
