### ISSUE TITLE
an option buttion should be shown for jumping to next chapter at the end of current chapter

### ISSUE THREAD

**Issue by chinobing** [Difegue/LANraragi#564]
an option buttion should be shown for jumping to next chapter at the end of current chapter without going back to the category.

**Comment by AbyssalMonkey** [comment]
I would assume that categories are meant to be categories, archives loosely related to confine searching that have no order; and chapter to chapter dealings would be dealt with by Meta-archives #519

**Comment by chinobing** [comment]
> 
oh, i just realized the IDs of archives are kindof random so that it cant be dealt with order problem for now at least

**Comment by Difegue** [comment]
Duplicate of #299. (sorta)
