### ISSUE TITLE
E-Hentai Plugin "Forced language to use in searches" not working.

### ISSUE THREAD

**Issue by PasserDreamer** [Difegue/LANraragi#566]
**LRR Version and OS**
Docker Version 0.8.3

**Bug Details**
"Forced language to use in searches" option set to Japanese.
However, got Korean or Spanish version instead.

**Screenshots**
![123](https://user-images.githubusercontent.com/30385417/146183511-58cd8e38-269b-44ec-9849-d4488d7b43d0.png)

**Comment by Difegue** [comment]
This might be caused by E-H not having a Japanese version of what you're looking for -- Similar to #569, I recommend you run the plugin with debug mode enabled to see what search URLs it's using.

**Comment by PasserDreamer** [comment]
I found that sad panda cannot search Japanese language.
[panda wiki](https://ehwiki.org/wiki/japanese)
Thus, to implement this function, Japanese should has its own toggle.
When toggle on, all result with tag "language" and "text cleaned" would be filtered out.

**Comment by Difegue** [comment]
Right, I'd forgotten about this.  
You can use [Tag Rules](https://sugoi.gitbook.io/lanraragi/v/dev/advanced-usage/tag-rules) to remove tags you don't want, which is a more flexible solution than a JP-language toggle that wouldn't really search for JP archives (as it's technically not really possible with EH)
