### ISSUE TITLE
[bug] EZE plugin error  malformed JSON string

### ISSUE THREAD

**Issue by wongsaraf** [Difegue/LANraragi#571]
**LRR Version and OS**
Windows 10 21H2
LRR 0.8.3 Windows version downloaded from github

**Bug Details**
adding metadata from batch or manual using EZE plugin resulting this error and fail to add the metadata from the info.json file.
adding it manually or using other plugin got no error.
Got dozens files with the same errors

```
Sleeping for 0 seconds.
Error while processing ID 85143c09a659ccb6292b60a1587be89fa235d825 (malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/local/share/perl5/site_perl/Mojo/JSON.pm line 33.
)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/12886212/147475066-4dbd0e01-225c-420d-9162-987e8131e029.png)

**files that cause the error**
https://anonfiles.com/X8i40fddx4/_C87_Wasuraruru_Tegami_Binsen_Eren_no_Touji_-_Ellen_s_Winter_Solstice_English_Mistvern_cbz

**Comment by Difegue** [comment]
Works as of latest nightly:  
![image](https://user-images.githubusercontent.com/8237712/147479406-22782c0a-cc1e-47bf-8221-2a14172451b2.png)  

I think this was fixed by 01b2d368595a17bbf11f94465860703280ffb823 .
