### ISSUE TITLE
No thumbnails from .gif

### ISSUE THREAD

**Issue by FeudalNoodle** [Difegue/LANraragi#572]
**LRR Version and OS**
LRR 0.8.3; Native; ImageMagick7-7.0.11.12

**Bug Details**
When the first image of an archive is a .gif (or any multi-frame image) there will be no thumb displayed for said archive in your library although the thumb generation task completes successfully.
With the current call to ImageMagick instead of resulting in [hash].jpg it results into [hash]-[x].jpg for each frame of the .gif (eg [hash]-0.jpg, [hash]-1.jpg).

**Screenshots**
![example](https://user-images.githubusercontent.com/88393919/147590336-b28a32cb-bce7-464f-8b14-40208f5e58e0.png)

**Comment by Difegue** [comment]
Should be fixed by the commit above.
