### ISSUE TITLE
Koromo metadata plugin sees only case-sensitive "Info.json"

### ISSUE THREAD

**Issue by Solipso** [Difegue/LANraragi#587]
**LRR Version and OS**

OS: Docker, LRR version: 0.8.4, Koromo plugin version: 2.0

**Bug Details**

Archive with "info.json" is not seen by Koromo metadata plugin (error: No koromo info.json file found in this archive!)

Archive with "Info.json" is perfectly recognized.

**Comment by ndbiaw** [comment]
This has been known and reported. At line 43 in Koromo.pm:
Change
```pm
my $path_in_archive = is_file_in_archive( $file, "Info.json" );
```
to
```pm
my $path_in_archive = is_file_in_archive( $file, "info.json" );
```

**Comment by Difegue** [comment]
While it's not a bug, the koromo plugin is increasingly becoming this weird catch-all thing since its format is kinda generic, so I don't mind adding a check for the lowercase version as well if it can unblock some people. 👍
