### ISSUE TITLE
[Feature request] support rescan the content directory manually

### ISSUE THREAD

**Issue by chu-shen** [Difegue/LANraragi#590]
0.8.4 docker NAS

1. download files(in a directory) to content directory using qbittorrent4.3.9, but will not be scanned by Shinobu

2. if mv these files to a **new** directory, it works. But if mv to an existing directory,  no files will be added

3. restart Shinobu in the setting not work for me

I need a button to force a rescan manually, anyone can help me? thank you

**Comment by ndbiaw** [comment]
Use any download manager that won't let the unfinished file name be the original filename. Because the file hasn't finished downloading, Shinobu will mark it as a corrupted file when it scans and won't rescan.

**Comment by Difegue** [comment]
Downloading straight to the content folder without renaming will likely lead to broken IDs, as the file will be picked up before it becomes at least 512KBs large. (There's a 5 second wait for sub-512KB files to try and avoid this but if you're downloading really slowly, it can still happen)  

I should probably expose an endpoint to wipe the Shinobu filemap for this kind of weird edge cases (been reported a few spare times already), but you can do it manually through the CLI for now:  

```
redis-cli
DEL LRR_FILEMAP
exit
```

**Comment by chu-shen** [comment]
Thank you for your reply @ndbiaw @Difegue 

> ```
> redis-cli
> DEL LRR_FILEMAP
> exit
> ```

Nice work, these commands work well, thank you

**Comment by Difegue** [comment]
An API endpoint and matching button in settings have been added for this:  
![image](https://user-images.githubusercontent.com/8237712/159191144-2af18406-0cf0-409b-b541-71deceae4cfc.png)

**Comment by chu-shen** [comment]
> An API endpoint and matching button in settings have been added for this: ![image](https://user-images.githubusercontent.com/8237712/159191144-2af18406-0cf0-409b-b541-71deceae4cfc.png)

Thank you💕
