### ISSUE TITLE
Eze and E-hentai plugin source URL's are not compatible

### ISSUE THREAD

**Issue by LoLsAlEd** [Difegue/LANraragi#593]
Hello, I have found a issue with the way the eze plugin stores the source URL which makes it not compatible with the e-hentai metadata plugin.

**LRR Version and OS**
LANraragi: v.0.8.4
OS: DSM 7 (Synology)
Install: Docker

**Bug Details**
If you import metadata using the Eze plugin it adds the source from the info.json to the gallery. But if we want to update the metadata using the e-hentai plugin it will not recognize the existing source tag and will attempt to search for a matching a gallery.

It looks like the issue is caused by the Eze plugin adding a space between Source: and the URL. This results in the regex not matching  the existing source.

**Eze Plugin:**
source: e-hentai.org/g/2156186/b644822831

**E-hentai Plugin:**
source:e-hentai.org/g/2156186/b644822831

To resolve this issue I think the regex to detect a existing URL in the e-hentai plugin needs to be updated to handle the space, that is included from the Eze plugin. For example:

    /.*source:\s?e(?:x|-)hentai\.org\/g\/([0-9]*)\/([0-z]*)\/*.*/gi

Please let me know if you need a sample file.

**Comment by Difegue** [comment]
The issue mostly comes from the Eze plugin incorrectly adding a space to its `source:` tags, but I've gone ahead and also improved the regex on the EH side so that existing tags with a space in them work properly.  

Let me know if there are any other issues!
