### ISSUE TITLE
Hentag plugin

### ISSUE THREAD

**Issue by hollywings** [Difegue/LANraragi#595]
I found out that a lot of archives where the fakku and chaika plugins failed to pull metadata can be found on hentag. It looks to be a great alternative to pulling straight from fakku, would you consider writing a hentag plugin?

**Comment by ndbiaw** [comment]
Your question is too naive.

**Comment by Difegue** [comment]
There's no documented API for hentag(ugh), but their vault search seems to be easily accessible:  
![image](https://user-images.githubusercontent.com/8237712/159164134-7704929d-8902-4e59-a12a-7af60d4be052.png)

It'd be doable to write a plugin for it, I'll be tagging this under volunteers in case someone wants to try their hand writing one. 👀

**Comment by siliconfeces** [comment]
It looks like they avoid public access to their API, but I'm mostly done with a plugin that reads embedded info.json files (stored in their own format).

**Comment by siliconfeces** [comment]
Scratch that, they are open to allowing API access. I'll try adding support for pulling metadata directly from hentag.

**Comment by Difegue** [comment]
Nice! An API plugin is always a bit more useful. 👍

**Comment by siliconfeces** [comment]
PR at https://github.com/Difegue/LANraragi/pull/763

**Comment by Difegue** [comment]
We merged this two weeks ago, whoops 💀
