### ISSUE TITLE
Import meta/tags using provided URL while download new archives by built-in downloader

### ISSUE THREAD

**Issue by xiazeyu** [Difegue/LANraragi#601]
When want to download an archive from the Internet, 
I use the **Adding Archives to the Library** function combined with Metadata Plugins, hoping to automatically add meta.

Take E-Hentai plugin for example, It seems that if I turn on "Run Automatically" and give "URL(s) to download".

It will always match metadata using **TITLE** instead of **URL** I provided in the downloader.

This can result in mismatch when the title contains Unicode characters, or multiple gallary shares the similar title.

My current solution is to disable "Run Automatically" option and Use "Click here to edit metadata." function to manually paste the "E-H Gallery URL (Will attach tags matching this exact gallery to your archive)".

Is it possible to just let "Mayriad's EH Master Script" to retrieve the URL I provided in the downloader, and use that information to search for metadata?

**Comment by xiazeyu** [comment]
I've switched to the `nightly` branch, and some test will be done later.

**Comment by xiazeyu** [comment]
I looked into the Meta plugin, found 

https://github.com/Difegue/LANraragi/blob/19756a1075da4cceaa311e97e931b294ed63f537/lib/LANraragi/Plugin/Metadata/MEMS.pm#L64

https://github.com/Difegue/LANraragi/blob/19756a1075da4cceaa311e97e931b294ed63f537/lib/LANraragi/Plugin/Metadata/EHentai.pm#L72

these codes seems to extract the "source" tag from existing tags.

However, when I download a new comic using `E*Hentai Downloader v.1.0 by Difegue`, the only tag I seen is "date_added:1649757812". These's no tag like "source" added, even though I download it by "Add Archives". Is it expected? Or should the "source" tag being added after the file is downloaded(just like how the "date_added" tag is added), and before Meta plugin is called?

**Comment by xiazeyu** [comment]
Another question, may be off-topic. Is there any difference between `E-Hentai v.2.5.1 by Difegue and others` and `Mayriad's EH Master Script v.1.1.0 by Mayriad`?
It seems that the MEMS just "[Mayriad's EH Master Script] [info] Source identified. Calling E-Hentai metadata plugin to retrieve metadata from EH API."

**Comment by Difegue** [comment]
The MEMS plugin is only useful if you have the matching userscript on your browser: The base EH plugin does everything you'd need as a regular user. 

As for downloading through add archives, it calls on the DL system all the same so you should be getting source tags.
More investigating needed..

**Comment by xiazeyu** [comment]
It is confirmed that if I download other books without using the plugins:
e.g. `https://github.com/sarabander/sicp-pdf/raw/master/sicp.pdf`

source tag is not added. I think it is not what I expected, correct?

**Comment by xiazeyu** [comment]
Found the source of the problem:
source tag is conflict with the "Add Timestamp Tag" option.
When "Add Timestamp Tag" is on, it will directly overwrite the "source" tag instead of append to it.

**Comment by xiazeyu** [comment]
I'm not sure if it is because of this:
https://github.com/Difegue/LANraragi/blob/543609b35d780684c7a90260dea98153c5f4c172/lib/LANraragi/Utils/Database.pm#L60-L70

Using hset causes redis to overwrite existing tags

**Comment by xiazeyu** [comment]
I found in this commit, DateAdded plugin was fully deprecated. However, considering that DateAdded plugin still exists, and the actual thing it do is a tag plugin, can I revert this commit, and remove "Add Timestamp Tag" from config pannel, and move "Use "Last modified" Time" to plugin's config?

In a word, reuse the DateAdded plugin?

https://github.com/Difegue/LANraragi/commit/32cc991e8c5bae3bbd57d163278048c50159ae9f

**Comment by Difegue** [comment]
Thanks for the detailed investigation: I don't plan on removing the built-in timestamp feature since third-party clients have come to rely on `date_added` for extra features, and forcing this back into plugin status would basically just be a regression. 😅  

I've pushed out a simple fix so that you can have `source:` and `date_added:` tags added simultaneously without issues.
