### ISSUE TITLE
hyperlink miss colon when click in source tag

### ISSUE THREAD

**Issue by xiazeyu** [Difegue/LANraragi#607]
**LRR Version and OS**
Nightly@[d6a7d8a](https://github.com/Difegue/LANraragi/commit/d6a7d8a6a86096fd5a396766a2b1aa8e7abe9f6c)

**Bug Details**
Given that the page contains three tags:
```
source:google.com, source:https://google.com, source:http://google.com
```
The hyper link for these three will be:
`google.com`, `https//google.com` and `http//google.com`

The latter two is unreachable. And in Chrome DevTools, the source is
`href="http://https://google.com"` and `href="http://http://google.com"`

**Comment by xiazeyu** [comment]
Also, is there any rules about if these should have `https` prefix for the plugin system, or it just doesn't matter?

Maybe remove `https://` in `nHentai.pm` should also be considered?
https://github.com/Difegue/LANraragi/blob/dev/lib/LANraragi/Plugin/Metadata/nHentai.pm#L213

**Comment by xiazeyu** [comment]
Also, how about adding source tag import support?
https://github.com/Difegue/LANraragi/blob/dev/lib/LANraragi/Plugin/Metadata/EHentai.pm#L72-L76
to
https://github.com/Difegue/LANraragi/blob/dev/lib/LANraragi/Plugin/Metadata/nHentai.pm#L50

**Comment by Difegue** [comment]
The scheme shouldn't be present in source tags as you've seen, so the nH plugin should be fixed.

Past that, it'd probably be possible to fix the frontend so that it handles the hyperlinks correctly even if the tags are malformed.
