### ISSUE TITLE
Error when running "Subfolders to Category" script

### ISSUE THREAD

**Issue by CDarwin7** [Difegue/LANraragi#611]
Script failed: Computed ID is for a null value, invalid source file. at /home/koyomi/lanraragi/script/../lib/LANraragi/Utils/Database.pm line 307.

fresh docker install

**Comment by CDarwin7** [comment]
Script failed: Computed ID is for a null value, invalid source file. at /home/koyomi/lanraragi/script/../lib/LANraragi/Utils/Database.pm line 307.

**Comment by Difegue** [comment]
Should be fixed, thanks for the report!
