### ISSUE TITLE
limit the count of "New Archives" on main page

### ISSUE THREAD

**Issue by xiazeyu** [Difegue/LANraragi#614]
**LRR Version and OS**
Nightly 699b81f2944de280baa87b36b1c3990687e0232c, but I'm sure related codes havn't been changed yet.

**Bug Details**
When I use the "New Archive" on the main page, due to too much NEW archive I had (about 1500), my iOS device just kept crashing. And my Chrome browser magically requested for the all 1500 thumbnails and book infos.

**Matching Logs**
The page first queries "http://server/api/search?filter=&category=&newonly=true&sortby=date_added&order=desc&start=-1"
Then, it got
```json
{"data":["TOO MUCH HERE"], "draw":0,"recordsFiltered":1500,"recordsTotal":1600}
```

Later, it queries the thumbnails for all these archives.

The "new archive" section can merely show up to 7 archives on my browser, even fewer on my iOS device, but it just kept requesting, making the whole page laggy and even crashing.

Is there anyway to limit the amount of archives that returns from the search api, like use the "Archives per page" or "count" parameter in random API? "Untagged" section on the main page may also have this problem, though didn't affect me.

**Comment by Difegue** [comment]
I've received reports about this issue already but hadn't opened an issue about it 😅

The search API supports pagination, so this is simply a matter of modifying the current carousel behavior so that it provides page parameters to the api call instead of loading everything with `start=-1` like it currently does. 
Not sure if the library we currently use allows to do that easily though. 🤔

**Comment by Difegue** [comment]
This might be enough considering the thumbnail load is what's taking the most CPU/memory: https://swiperjs.com/swiper-api#lazy-loading

**Comment by xiazeyu** [comment]
Yep, the `start` parameter allows the front-end to get data which id [start, start+page_count]. But the modification can results in other complicated stuffs like progress loading with pagination in front-end.
https://github.com/Difegue/LANraragi/blob/dev/public/js/index.js#L291
https://github.com/Difegue/LANraragi/blob/dev/lib/LANraragi/Model/Search.pm#L175

Besides, the heaviest work is quering the thumbnails, the JSON itself queried from endpoint is not very large (~800KB).

**Comment by xiazeyu** [comment]
A quick solve can be replacing
https://github.com/Difegue/LANraragi/blob/dev/public/js/index.js#L304
with 
`results.data.splice(0,20).forEach((archive) => {`.


But I've found a feature called [Virtual Slides](https://swiperjs.com/swiper-api#virtual-slides) in Swiper.
It allows to keep just required amount of slides in DOM. It is very useful in terms in performance and memory issues if you have a lot of slides, especially slides with heavyweight DOM tree or images.
