### ISSUE TITLE
Add a i18n library to the frontend to allow translations

### ISSUE THREAD

**Issue by Difegue** [Difegue/LANraragi#617]
There's been demands for TL'd versions over the years, and while I'm not sure translators would step up to the plate to help maintain the translated strings, it'd be nice for the infrastructure to be in place. (And additionally to stop using hardcoded english everywhere)

Potentially quite a bit of work since both the JS and the html templates need to be internationalized -- Not sure what's the best course of action for this.  
i18next is the standard for this on the JS side at least:  
https://dev.to/adrai/the-progressive-guide-to-jquery-internationalization-i18n-using-i18next-3dc3

**Comment by wc7086** [comment]
Any progress?

**Comment by Difegue** [comment]
Unfortunately no.
