### ISSUE TITLE
Errors on using Plugins

### ISSUE THREAD

**Issue by TheDerpySage** [Difegue/LANraragi#62]
![image](https://user-images.githubusercontent.com/11201157/47124604-6510a980-d244-11e8-84e8-35caa7791e79.png)
I'm gettin this on attempting to use a plugin.
I also get this error on startup, but no logs elsewhere.
`[Wed Oct 17 19:25:46 2018] [error] Global symbol "$globalarg" requires explicit package name (did you forget to declare "my $globalarg"?) at /home/default/lanraragi/script/../lib/LANraragi/Controller/Api.pm line 165.
Global symbol "$globalarg" requires explicit package name (did you forget to declare "my $globalarg"?) at /home/default/lanraragi/script/../lib/LANraragi/Controller/Api.pm line 165.
Global symbol "$globalarg" requires explicit package name (did you forget to declare "my $globalarg"?) at /home/default/lanraragi/script/../lib/LANraragi/Controller/Api.pm line 166.
Compilation failed in require at (eval 106) line 1.`
I didn't build my own perl but so far everything else has worked so I'm not sure where I might've fucked up.

**Comment by TheDerpySage** [comment]
Oh yeah and some other info
Ubuntu 16.04 on a Oracle Virtual Box VM
Tried installing it on the same box I had the oldcgi version running on without changing anything about the perl installation.

**Comment by TheDerpySage** [comment]
Alright, I've verified this issue also occurs on a brand new fresh install on Debian 9.

**Comment by Difegue** [comment]
You're running on the _master_ branch and not _dev_, right ?
dev is currently half-broken due to the plugin system overhaul.

**Comment by TheDerpySage** [comment]
This is on master yes. Using the default git pull SHOULD only pull from master. 
I can make absolutely sure real fast

**Comment by Difegue** [comment]
Might be because dev is the default branch of the repo in github's settings - I thought that didn't affect the actual git repository, but I guess I was wrong!  

As for the migration script, it's basically the one I used when I did my own migration - it hasn't been tested much since most of the users came in the post-CGI era. There probably aren't that many CGI installations left (if any), so I might just remove it altogether from the codebase.

**Comment by TheDerpySage** [comment]
Fair enough, I stuck to using the oldcgi version because of the special way I had my box setup, but as new features were getting added I kinda felt left behind. Out with the old and in with the new.

**Comment by TheDerpySage** [comment]
This won't affect Docker and Windows installations obviously but the for the native linux you may want to set the master back to default or add the `-b master`

**Comment by Difegue** [comment]
Updated the docs to add ```-b master```.
