### ISSUE TITLE
Getting an error at line 240 when trying to obtain metadata using the Ehentai plugin.

### ISSUE THREAD

**Issue by Deejay85** [Difegue/LANraragi#621]
Using version 8.5, and getting problems with getting metadata when running Exhentai. My information is correct, but there doesn't seem to be much I can do about it. The error message reads as follows:

```
Error while processing ID 55de74fbe0fb0bf0c75d2f6579f88fa3c13daed5 (Invalid argument at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/Metadata/EHentai.pm line 240.
)
```

The corresponding line in the .pm file simply reads

`$res = $ua->max_redirects(5)->get($url)->result;`

Obviously coding isn't my strong suit, so I have no idea what this means, but a little help would be appreciated. In the meantime I'll try to use Nhentai until this is fixed later on.

**Comment by Difegue** [comment]
I suppose you're using windows ? See #619 👍
