### ISSUE TITLE
Wrong error message encoding

### ISSUE THREAD

**Issue by xiazeyu** [Difegue/LANraragi#624]
In plugin page,
When error occurs, it gives error with wrong encoding:
![image](https://user-images.githubusercontent.com/10560038/166636567-e31876df-1696-474a-92f4-6faf2a72bece.png)
And the wrong encoding seems originates from the backend
![image](https://user-images.githubusercontent.com/10560038/166636636-e51a5a17-ca64-4426-b06c-b8c6ba9fd097.png)

I believe 
https://github.com/Difegue/LANraragi/blob/dev/lib/LANraragi/Plugin/Metadata/Eze.pm#L78
is where this problem happens. Maybe it is due to its way to process Unicode.
Is there any way to check the way it passes path? It seems that other messages like "deleting the archive" also gives wrong path encoding.

off-topic:
Please have a look at https://github.com/Difegue/LANraragi/pull/620#discussion_r864414328 in case you missed it.

**Comment by xiazeyu** [comment]
And this also occurs in the logs page.
![image](https://user-images.githubusercontent.com/10560038/166637438-df5d4be9-dce7-46db-9e41-e7e0a0609e04.png)

**Comment by Difegue** [comment]
Thanks, I'll take a look.  
Could I convince you to look at https://github.com/Difegue/LANraragi/issues/618 in the meantime ? 😁

**Comment by xiazeyu** [comment]
sry, forgot about it. I'll see that later.

**Comment by xiazeyu** [comment]
@Difegue 

Sorry but this issue seems more general.
Places like:
https://github.com/Difegue/LANraragi/blob/dev/lib/LANraragi/Plugin/Metadata/Eze.pm#L78
And https://github.com/Difegue/LANraragi/blob/dev/lib/LANraragi/Utils/Database.pm#L206-L220

havn't got fixed. And it seems that are lots of similar encoding problems related to filename just like the PR mentioned.

Also I don't know if there's a indentation at the begining of this line.
https://github.com/Difegue/LANraragi/pull/636/files#diff-a8db8756fe18689d50fa8d474003e0122b6b5099e8101ba8f99632055fb507a0R307

**Comment by Difegue** [comment]
It's likely that the error occurs in logging in various parts of the app since `redis_decode` needs to be called manually - - It might be better to change the logger directly to have it decode by default.

**Comment by Difegue** [comment]
👍 Generalized to all logging, hopefully this'll fix display issues for good (in logs at least 🥲)
