### ISSUE TITLE
how do i uninstall so i can reinstall?

### ISSUE THREAD

**Issue by shogunreaper** [Difegue/LANraragi#639]
**LRR Version and OS**
v.0.8.5 and windows 10

**Bug Details**
I want to uninstall the app but i can't do that as it says the installer ended prematurely. And doing repair from the installer ends up with a command line error

**Screenshots**
![this](https://user-images.githubusercontent.com/13224548/173584447-2a00fcda-36f3-4409-be77-4f2a5204d780.png)
![this2](https://user-images.githubusercontent.com/13224548/173584451-ad74694b-1fe6-4985-816a-b2d3bf83b57c.png)

**Comment by shogunreaper** [comment]
apparently i didn't have WSL installed so that command didn't do anything. I installed WSL and and was able to uninstall/reinstall lanraragi afterwards.

I didn't see anything about needing that so maybe put that information on the main page?

**Comment by Asinin3** [comment]
https://sugoi.gitbook.io/lanraragi/v/dev/installing-lanraragi/windows
Has WSL mention at the top

**Comment by Difegue** [comment]
The installer shouldn't even let you finish a normal install unless WSL is installed, so you probably did have it in some form already.  

As for the uninstaller failing, I've had a few similar reports already with 0.8.5, so I'll try improving the DistroInstaller portion of the Windows install process to handle things more gracefully.

**Comment by Difegue** [comment]
Done 🎉
