### ISSUE TITLE
Remember archive sort key and order on library page

### ISSUE THREAD

**Issue by IAmCaligvla** [Difegue/LANraragi#646]
Make so the archive sort key (title/date/etc) and order (ascending/descending) on the Library page is remembered on subsequent visits (maybe as an option?).

As of now whenever you exit the Library page the archive sort key and order reset on the next Library visit to _Title_ and _Ascending_, if the user has a preference for a specific sort they'll have to change it back every time they open it.

**Comment by Difegue** [comment]
This has already been implemented in a way through https://github.com/Difegue/LANraragi/issues/546, but it's only for going back to your previous search after reading a book atm.  

A "stickier" solution would involve `localStorage` -- I wasn't willing to do it for search as I thought it'd be more annoying than useful, but for sort key/order it'd probably be a good thing.

**Comment by Difegue** [comment]
I think people are going to enjoy this one. 🙃
