### ISSUE TITLE
eze plugin not fetching full metadata

### ISSUE THREAD

**Issue by virulence** [Difegue/LANraragi#65]
**LRR Version and OS**
LRR version 0.5.4
Windows 7 x64
Native installation I think (just extracted and ran the .bat from the quick starter)

**Bug Details**
The eze plugin fetches only the event/group/artist/language tags. Attached is an affected info.json converted to .txt.

**Matching Logs**
Let me know if you need a log/which log. When a file is uploaded, the output in lanrargi.log is

> [2018-10-24 17:28:51] [Auto-Tagger] [info] Executing enabled plugins on archive with id 3e1eb64f613ee00386c8b24a52bc1ec1ec5c6be1.
[2018-10-24 17:28:51] [Auto-Tagger] [info] Thumbnail hash invalid, regenerating.
[2018-10-24 17:28:51] [Auto-Tagger] [error] Wide character in subroutine entry at C:/berrybrew/5.26.0_64/perl/site/lib/Mojo/JSON.pm line 39, <$fh> line 182.

> [2018-10-24 17:28:51] [Shinobu] [info] Archive count (110) has changed since last cached value (109) OR rebuild has been forced (flag value = 1), rebuilding...
[2018-10-24 17:28:52] [Shinobu] [info] Done!

**Screenshots**
Attached.
![notepad _2018-10-24_16-15-28](https://user-images.githubusercontent.com/16786398/47462405-4a44b480-d7b1-11e8-9de0-3a5fb1c89c7d.jpg)
[info.txt](https://github.com/Difegue/LANraragi/files/2512388/info.txt)

**Comment by Difegue** [comment]
welp, looks like the same issue that I fixed with the APIs in cc19af2e8229ccef78b62599ec2f0003e5961062.  
This should be a quick fix, I'll look at it tomorrow.

**Comment by Difegue** [comment]
Done! I'd normally say you can try it out yourself by hotswapping the plugin file in your installation, but due to the plugin system changes in 0.5.5 that'd probably break.  

Here's a 0.5.4 compatible version of the eze plugin you can try in the meantime: https://a.pomf.cat/tnjcda.pm
