### ISSUE TITLE
Incorrect sorting of archives with uppercase/lowercase mixed files

### ISSUE THREAD

**Issue by kw4s** [Difegue/LANraragi#652]
**LRR Version and OS**
LRR 0.8.5, Docker, Linux host

**Bug Details**
Current file sorting algorithm sorts files in ascii code order which means that for example file "h01.jpg" (which is expanded to h0001.jpg via "magical sort" expand function) will come after OK_002.jpg. Which is unfortunately not the correct order, not in windows filename sorting, not in linux filename sorting, not in any cbz/cbr viewer I've ever seen...
Some other examples:  Z_02.jpg < h01.jpg < z_01.jpg

This issue causes some other problems - incorrect page order while reading, metadata providers not working correctly (because they rely on submitting cover page, and cover page was sorted to the end of archive...),  thumbnail generation grabbing the wrong image, etc

**Matching Logs**
No logs, sorry, but I can give you this:
```perl
# current implementation of expand
sub expand {
    my $file = shift;
    $file =~ s{(\d+)}{sprintf "%04d", $1}eg;
    return $file;
}

# expand fixed with lowercase
sub expand_lc {
    my $file = shift;
    $file =~ s{(\d+)}{sprintf "%04d", $1}eg;
    return lc($file); # <- this thing right here
}


@files = ("z_01.jpg","h01.jpg", "h01_02.jpg",   "Z_02.jpg", "OK_003.jpg", "z_2.jpg");
@files = sort { &expand($a) cmp &expand($b) } @files;
print join(', ', @files), "\n";

@files = ("z_01.jpg","h01.jpg", "h01_02.jpg",   "Z_02.jpg", "OK_003.jpg", "z_2.jpg");
@files = sort { &expand_lc($a) cmp &expand_lc($b) } @files;
print join(', ', @files), "\n";

# original list:   z_01.jpg, h01.jpg, h01_02.jpg, Z_02.jpg, OK_003.jpg, z_2.jpg
# expand:          OK_003.jpg, Z_02.jpg, h01.jpg, h01_02.jpg, z_01.jpg, z_2.jpg
# expand_lc:       h01.jpg, h01_02.jpg, OK_003.jpg, z_01.jpg, Z_02.jpg, z_2.jpg

```

**Screenshots**
No screenshots.

**Comment by Difegue** [comment]
Huh, can't believe I've missed something that simple all this time.  
Most of the time cbzs don't mixup case in their filenames, which is probably why it hasn't shown up too much. ¯\\\_(ツ)_/¯  

Thanks a lot for the detailed repro and fix!
