### ISSUE TITLE
Search function in LR doesn't return correct results; often misses entries in the filesystem

### ISSUE THREAD

**Issue by soarpasser** [Difegue/LANraragi#657]
Windows 10, 0.8.5 msi, WSL2

Issue - 
Using the search box to search for entries can be very janky, as it often misses random entries in the filesystem. 
However, while using the browser's native Ctrl+F search option in the "Categories" section one can see all the entries corresponding with the same search query in the filesystem. 

Example:
Enter a search query and hit enter, only two entires can be seen listed
![image](https://user-images.githubusercontent.com/74951691/177067830-e65b6778-aac4-4902-917b-7b9a77118dc1.png)

Go to "Categories", hit Ctrl+F and enter the exact same query, and all four of the corresponding entires are shown - which is supposed to be the correct result that the LR search returns
![image](https://user-images.githubusercontent.com/74951691/177068267-7f716cb9-281d-4bc5-93ff-a581e57626a3.png)

P.S. Interestingly, changing the search query in a way that shouldn't affect the search results (for example, removing a letter at the bottom of the search term) can cause LR's search to return different results.
![image](https://user-images.githubusercontent.com/74951691/177068655-544d9b68-957f-4d1a-b02b-6584ed45564c.png)

Pressing the "rescan archive directory" button in LR settings does absolutely nothing except making my hard drive produce some horrible sounds as it tries to work hard through the entire filesystem.

The only way to get the LR search function to work as intended is by constantly changing the search query and pressing enter.
![image](https://user-images.githubusercontent.com/74951691/177069019-5ed90dba-78ab-4571-9942-5da266b8cbc0.png)
Here you can see that the search function finally shows all the intended results.

This suggests that there's probably something wrong with the search box in LR - And seeing that the "Categories" section has no problem displaying the correct entries on the filesystem, it makes me think that this definitely has something do do with the search function, rather than some other setting in LR or on my hard drive. Hopefully this issue can be resolved as it is incredibly annoying especially when trying to add and edit new entries to LR.

**Comment by Asinin3** [comment]
Can't reproduce, shows all 4 galleries for me with same search terms.
![image](https://user-images.githubusercontent.com/15137035/177687733-66b24f26-ae29-4aa2-b91f-0ff433b9a454.png)

**Comment by soarpasser** [comment]
> Can't reproduce, shows all 4 galleries for me with same search terms. Same result if i remove last letter from search ![image](https://user-images.githubusercontent.com/15137035/177687733-66b24f26-ae29-4aa2-b91f-0ff433b9a454.png) I'm on Windows 10 as well, but using nightly builds.

Ah, well I'm using the standard build straight from the release page. Perhaps that's the difference and the issue isn't present in the nightly builds?
Also - this search term I listed above is just an example. The actual issue can happen with any random gallery and search query.

**Comment by Difegue** [comment]
I think this is a search cache issue somehow -- I believe this button should help instead of the rescan directory one:  
![image](https://user-images.githubusercontent.com/8237712/178161915-a8e32104-5945-4674-ad4d-a6f1a7946f88.png)  

The cache is normally busted whenever changes to the database happen, but it looks like it's giving you results based on incomplete DB snapshots somehow?  
Changing the query slightly prompts a cacheless search in any case so it makes sense that you'd have the correct result that way.

**Comment by soarpasser** [comment]
> 

That's even more interesting, as I've also tried using the "reset search cache" option together as well - Though I click that first and then proceed to do the database rescan. Issue still persists. Perhaps I should do it in the reverse order?

**Comment by soarpasser** [comment]
Reopening this issue as this problem seems to have gotten worse/not improved recently.
Again, archives that exist on the filesystem can sometimes not show up in search results at all despite being logged in LR's database.

Now, rescanning or clearing the search cache **_will not work_** when an exceptionally stubborn archive refuses to pop-up; in this instance usually only a restart of the application will fix the issue.
There is no reliable way to reproduce this bug.
I also couldn't find any logs related to this issue, so can't really figure out how this is happening either.

**Comment by Difegue** [comment]
With #555, I have severely reduced the amount of cache warm jobs due to search getting that much faster, which should improve phantom archive cases like what we saw here.  

In any case though, filesystem watching on the WIndows versions *is* buggy thanks to WSL and can get worse depending on how/where the content folder is stored, so I can't guarantee issues like this won't still pop up.  
Not much I can do about it besides suggesting using the Linux version on a dedicated NAS or something..
