### ISSUE TITLE
The thumbhash in backup.json can not restore to redis?

### ISSUE THREAD

**Issue by oneexph** [Difegue/LANraragi#660]
### redis:  example : no thumbhash
 hgetall "db806ecb43ee726dc9683bc31ca6e4b8cd5861d9"
 1) "title"
 2) "(\xc3\xa5\xc2\x90\xc2\x8c\xc3\xa4\xc2\xba\xc2\xba\xc3\xa8\xc2\xaa\xc2\x8c) [Come Through (\xc3\xa3\xc2\x81\xc2\x82\xc3\xa3\xc2\x81\xc2\xa5\xc3\xa3\xc2\x81\xc2\xbf\xc3\xa4\xc2\xb8\xc2\x80\xc3\xa6\xc2\xa8\xc2\xb9)] ADUMIX#16 (\xc3\xa3\xc2\x81\xc2\x94\xc3\xa6\xc2\xb3\xc2\xa8\xc3\xa6\xc2\x96\xc2\x87\xc3\xa3\xc2\x81\xc2\xaf\xc3\xa3\xc2\x81\xc2\x86\xc3\xa3\xc2\x81\xc2\x95\xc3\xa3\xc2\x81\xc2\x8e\xc3\xa3\xc2\x81\xc2\xa7\xc3\xa3\xc2\x81\xc2\x99\xc3\xa3\xc2\x81\xc2\x8b\xc3\xaf\xc2\xbc\xc2\x9f)"
 3) "file"
 4) "/home/koyomi/lanraragi/content/(\xe5\x90\x8c\xe4\xba\xba\xe8\xaa\x8c) [Come Through (\xe3\x81\x82\xe3\x81\xa5\xe3\x81\xbf\xe4\xb8\x80\xe6\xa8\xb9)] ADUMIX#16 (\xe3\x81\x94\xe6\xb3\xa8\xe6\x96\x87\xe3\x81\xaf\xe3\x81\x86\xe3\x81\x95\xe3\x81\x8e\xe3\x81\xa7\xe3\x81\x99\xe3\x81\x8b\xef\xbc\x9f).zip"
 5) "isnew"
 6) "true"
 7) "pagecount"
 8) "10"
 9) "name"
10) "(\xc3\xa5\xc2\x90\xc2\x8c\xc3\xa4\xc2\xba\xc2\xba\xc3\xa8\xc2\xaa\xc2\x8c) [Come Through (\xc3\xa3\xc2\x81\xc2\x82\xc3\xa3\xc2\x81\xc2\xa5\xc3\xa3\xc2\x81\xc2\xbf\xc3\xa4\xc2\xb8\xc2\x80\xc3\xa6\xc2\xa8\xc2\xb9)] ADUMIX#16 (\xc3\xa3\xc2\x81\xc2\x94\xc3\xa6\xc2\xb3\xc2\xa8\xc3\xa6\xc2\x96\xc2\x87\xc3\xa3\xc2\x81\xc2\xaf\xc3\xa3\xc2\x81\xc2\x86\xc3\xa3\xc2\x81\xc2\x95\xc3\xa3\xc2\x81\xc2\x8e\xc3\xa3\xc2\x81\xc2\xa7\xc3\xa3\xc2\x81\xc2\x99\xc3\xa3\xc2\x81\xc2\x8b\xc3\xaf\xc2\xbc\xc2\x9f)"
11) "tags"
12) "date_added:1658074762"

### lib/LANraragi/Model/Backup.pm/   restore_from_JSON 

 if (   $redis->hexists( $id, "thumbhash" )
                && $redis->hget( $id, "thumbhash" ) eq "" ) {
                $redis->hset( $id, "thumbhash", $thumbhash );
            }
### err?
hexists( $id, "thumbhash" )&& $redis->hget( $id, "thumbhash" ) eq ""   ------always False?

**Comment by oneexph** [comment]
### redis:  examle : dont have thumbhash
 hgetall "db806ecb43ee726dc9683bc31ca6e4b8cd5861d9"
 1) "title"
 2) "(\xc3\xa5\xc2\x90\xc2\x8c\xc3\xa4\xc2\xba\xc2\xba\xc3\xa8\xc2\xaa\xc2\x8c) [Come Through (\xc3\xa3\xc2\x81\xc2\x82\xc3\xa3\xc2\x81\xc2\xa5\xc3\xa3\xc2\x81\xc2\xbf\xc3\xa4\xc2\xb8\xc2\x80\xc3\xa6\xc2\xa8\xc2\xb9)] ADUMIX#16 (\xc3\xa3\xc2\x81\xc2\x94\xc3\xa6\xc2\xb3\xc2\xa8\xc3\xa6\xc2\x96\xc2\x87\xc3\xa3\xc2\x81\xc2\xaf\xc3\xa3\xc2\x81\xc2\x86\xc3\xa3\xc2\x81\xc2\x95\xc3\xa3\xc2\x81\xc2\x8e\xc3\xa3\xc2\x81\xc2\xa7\xc3\xa3\xc2\x81\xc2\x99\xc3\xa3\xc2\x81\xc2\x8b\xc3\xaf\xc2\xbc\xc2\x9f)"
 3) "file"
 4) "/home/koyomi/lanraragi/content/(\xe5\x90\x8c\xe4\xba\xba\xe8\xaa\x8c) [Come Through (\xe3\x81\x82\xe3\x81\xa5\xe3\x81\xbf\xe4\xb8\x80\xe6\xa8\xb9)] ADUMIX#16 (\xe3\x81\x94\xe6\xb3\xa8\xe6\x96\x87\xe3\x81\xaf\xe3\x81\x86\xe3\x81\x95\xe3\x81\x8e\xe3\x81\xa7\xe3\x81\x99\xe3\x81\x8b\xef\xbc\x9f).zip"
 5) "isnew"
 6) "true"
 7) "pagecount"
 8) "10"
 9) "name"
10) "(\xc3\xa5\xc2\x90\xc2\x8c\xc3\xa4\xc2\xba\xc2\xba\xc3\xa8\xc2\xaa\xc2\x8c) [Come Through (\xc3\xa3\xc2\x81\xc2\x82\xc3\xa3\xc2\x81\xc2\xa5\xc3\xa3\xc2\x81\xc2\xbf\xc3\xa4\xc2\xb8\xc2\x80\xc3\xa6\xc2\xa8\xc2\xb9)] ADUMIX#16 (\xc3\xa3\xc2\x81\xc2\x94\xc3\xa6\xc2\xb3\xc2\xa8\xc3\xa6\xc2\x96\xc2\x87\xc3\xa3\xc2\x81\xc2\xaf\xc3\xa3\xc2\x81\xc2\x86\xc3\xa3\xc2\x81\xc2\x95\xc3\xa3\xc2\x81\xc2\x8e\xc3\xa3\xc2\x81\xc2\xa7\xc3\xa3\xc2\x81\xc2\x99\xc3\xa3\xc2\x81\xc2\x8b\xc3\xaf\xc2\xbc\xc2\x9f)"
11) "tags"
12) "date_added:1658074762"

### lib/LANraragi/Model/Backup.pm/   restore_from_JSON 

 if (   $redis->hexists( $id, "thumbhash" )
                && $redis->hget( $id, "thumbhash" ) eq "" ) {
                $redis->hset( $id, "thumbhash", $thumbhash );
            }
hexists( $id, "thumbhash" )&& $redis->hget( $id, "thumbhash" ) eq ""   ------always False?

**Comment by Difegue** [comment]
Good catch -- Thanks!
