### ISSUE TITLE
Batch add entries to category

### ISSUE THREAD

**Issue by soarpasser** [Difegue/LANraragi#672]
It would be neat to have the option to be able to add multiple entries to a category. 
An example where this could come in handy - say we have 40 books in category A, and we want to also list them under category B at the same time. Normally this operation would require the user to manually go to each of these 40 entries, right click on it and choose "add to category" to finish this task - a very inefficient and time consuming process. Being able to do this would make the experience much better.

**Comment by Difegue** [comment]
Shouldn't be too hard to add to the existing/freshly revamped batch operations system.
