### ISSUE TITLE
Windows 0.8.6 Installer issue

### ISSUE THREAD

**Issue by Asinin3** [Difegue/LANraragi#673]
Fresh installs of LANraragi 0.8.6 results in the following error:

``Executing the following command on WSL: export LRR_NETWORK=http://*:3000 && export LRR_DATA_DIRECTORY='/mnt/f/ex' && export LRR_THUMB_DIRECTORY='/mnt/c/Users/Someone/AppData/Roaming/LANraragi/thumb' && cd /home/koyomi/lanraragi && rm -f public/temp/server.pid && mkdir -p log && mkdir -p content && mkdir -p database && sysctl vm.overcommit_memory=1 && redis-server /home/koyomi/lanraragi/tools/build/docker/redis.conf --dir '/mnt/f/ex/' --daemonize yes && perl ./script/launcher.pl -f ./script/lanraragi
The system cannot find the path specified.``

This results in LRR not installing properly, Karen can be opened, but the server can't be started. To fix it you have to go to `%APPDATA%\lanraragi` then run `DistroInstaller.exe`

**Comment by Difegue** [comment]
I've seen reports of this error that mentioned changing the directories used for content or thumb fixed it. 

I'm not quite sure what's breaking in this case, but since you have the full command in logs, you can run a shell ln the lrr distro with `wsl.exe -d lanraragi ` and execute each part of the command separately to see which one procs the "can't find the specified file" error.

**Comment by WeiYiAcc** [comment]
Poor English，so use chinese to answer
我也遇到了这个问题。主要问题在于windows防火墙没有放行。退出LANraragi，以管理员权限运行DistroInstaller， 会出现== LANraragi WSL Distro Tool ==
 r - Reinstall
 u - Uninstall
 c - Exit
点击R，会弹出防火墙，放行
如果没有退出LANraragi ，则
LANraragi for Windows is already running.
Close it to access installer options.
Press any key to exit。
 请确认LANraragi 已经退出。
希望OP尽快更新处理这个权限问题。

**Comment by zelede** [comment]
On my system, it seems that the shell is what's missing. Simply running `wsl -d lanraragi` gives `The system cannot find the path specified.`

**Comment by Undifinedu** [comment]
Still get an error while installing the latest version. I ger the error detail as follows:
wsl.exe --status returned no information
(output was :默认分发：Debian
默认版本：2

适用于 Linux 的 Windows 子系统最后更新于 2022/9/23
WSL 自动更新启用。

内核版本： 5.10.102.1

)

that means I actually have a debian wsl installed in my computer. Maybe the dection of wsl fails again.

**Comment by Difegue** [comment]
`wsl.exe --status` can be localized in some versions which causes the installer detection to consider you don't have it installed: You can try temporarily changing your windows language to english to allow the installer to proceed.
