### ISSUE TITLE
Dead after start for a while

### ISSUE THREAD

**Issue by Andor233** [Difegue/LANraragi#674]
**LRR Version and OS**
Windows 11 22622.450, both 8.15 and 8.16
**Bug Details**
LANraragi will die.

**Matching Logs**
Today I upgraded the Linux subsystem to 5.15, is it related?

**Screenshots**
![image](https://user-images.githubusercontent.com/16273755/182874712-6d57384d-4bf7-4ee2-bc43-d1ffa4332a08.png)
![image](https://user-images.githubusercontent.com/16273755/182875863-2bdd1627-b611-451b-bf6c-ca4b20f160cb.png)
And WSL is not dead

**Comment by Difegue** [comment]
Well, that `wsl_e_vm_mode_invalid_state` error looks a bit suspicious indeed! 
I suppose the wsl update mightve caused it, haven't checked in with their changes recently.

I suppose you've tried restarting the machine already? The hyper-v service sometimes just bugs out and can't be salvaged by anything other than a reboot.

**Comment by Andor233** [comment]
Yes, restarting for many times.

**Comment by Andor233** [comment]
> I suppose the wsl update mightve caused it, haven't checked in with their changes recently.

But the wired thing is, even if there is a `wsl_e_vm_mode_invalid_state` error, Lanraragi still can work for a couple of minutes, and without any error or warning log, I can not reach the port of lanraragi. But If I get into the wsl and ps, and will find the lanraragis still alive. So it is very wired.

And here is the changelog of wsl 5.15
https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.15.57.1
