### ISSUE TITLE
Expose setting/environment variable for maximum response size

### ISSUE THREAD

**Issue by Sircrab** [Difegue/LANraragi#678]
When trying to download URLs through some of the plugins, certain galleries exceed the [maximum default size for responses set by Mojolicious](https://docs.mojolicious.org/Mojolicious/Guides/FAQ#What-does-the-error-Maximum-message-size-exceeded-mean) which causes the job to fail. While this default size is useful for most cases, it'd be great to have this exposed as an environment variable (or setting). The `download_url` method in the `Upload` model seems like a good place to check and update this setting to the user agent that gets the gallery.

**Comment by Difegue** [comment]
huh, I didn't think anyone would hit the 2GB response size limit, but I guess that can happen.  
I'm not sure it's worth making this a setting, for downloads we can probably just bump it up to an obscene maximum size like 2TB.
