### ISSUE TITLE
Toggle automatic bookmarking

### ISSUE THREAD

**Issue by almant** [Difegue/LANraragi#68]
Although resuming from where you left off is very useful for conventional book/comic reading, I feel like more often than not I don't want to resume a 20 page manga.
I'm often finding myself clicking back to the first page so I can start again the next time I view it.
Could there be a settings option to disable the bookmarking feature for people who don't use it?
It would also make sense that after viewing the last page of a comic that LANraragi would not remember the position unless you flipped back to the previous page. As it is currently the reader remembers the last page and opens you up to the credits.

Really loving the progress so far with this project, just a minor improvement I think a lot of people would appreciate.

**Comment by Difegue** [comment]
The bookmarking is entirely on the client side, so I could add a reader option to disable it.  

Although I'm guessing that simply resetting the bookmark when you reach the last page would be enough in that case.

**Comment by Difegue** [comment]
See message of related commit. 🙌
