### ISSUE TITLE
Progressing tracking and "set this page as thumbnail" doesn't work in infinite scrolling mode

### ISSUE THREAD

**Issue by soarpasser** [Difegue/LANraragi#682]
0.8.6 Windows

As the title states, there's currently two problems with LR's infinite scrolling mode.

First of all the progression tracking simply does not work - every time you refresh/exit the page and open it again LR will start from the beginning of the archive again.

Another issue is the "set this page as thumbnail" option - when in infinite scrolling mode, this button will only set the first page of the archive as the thumbnail regardless of where you actually are on the page.

Not sure if these problems can be addressed properly considering the nature of infinite scrolling in the first place - but if they can't, then maybe at least add a notice for users in future updates or simply disable them when infinite scrolling mode is on.

**Comment by Difegue** [comment]
Both of those should work now.  
I also fixed the click targets in infinite scrolling so that it works the same as regular reader (click on left side to go one page back, right side to go one page forward)
