### ISSUE TITLE
Can't install to a folder name with space

### ISSUE THREAD

**Issue by Slasar41** [Difegue/LANraragi#694]
My username has space on it and the installer will stuck.
![image](https://user-images.githubusercontent.com/28888646/190283647-fc0aa95f-6744-41e6-814f-1df54acd5b74.png)
![image](https://user-images.githubusercontent.com/28888646/190283721-099dabb5-a4af-4adf-ac0e-6856a6157ae2.png)
If I change the path to a different folder with no space, then the program will install just fine.
I'm trying to install LANraragi v.0.8.6
Windows 11 22621.382

**Comment by Difegue** [comment]
Yup, DistroInstaller was unable to handle spaces in the installation path 😳 Kinda embarassing but I suspect this is one of the major reasons 0.8.6 wasn't working for some people...
Thanks for figuring it out!
