### ISSUE TITLE
please consider remove the maximum lines limit in the Tag Rules 

### ISSUE THREAD

**Issue by tecsar9000** [Difegue/LANraragi#698]
**LRR Version and OS**
docker

**Bug Details**
currently the maximum lines in tag rule is 299，but 299 line is not enough for me, I use it for translating the tag to another language that's not English

**Comment by Difegue** [comment]
![](https://imgs.xkcd.com/comics/workflow.png)  

Then again looking at the code I think the limitation on tag rules (5000 chars) is completely arbitrary, so I'll be removing it and we can see how that goes!
