### ISSUE TITLE
Resetting the scroll bar at page change

### ISSUE THREAD

**Issue by xd1986k** [Difegue/LANraragi#7]
Has the new reader already been implemented? I turned off Tampermonkey and the images were still switching quickly. Awesome :). Anyhow the images don't reset to the top on page change and so you'll have to scroll up and might even be potentially spoilered (if you could even call it that).

**Comment by Difegue** [comment]
If you pulled the latest files from the repo, yeah it's in. 
Didn't think about a reset to top, I'll get that in quickly.
