### ISSUE TITLE
Is it possible to scrape metadata from internal comicinfo.xml files?

### ISSUE THREAD

**Issue by RedRain77** [Difegue/LANraragi#705]
[ComicInfo.xml](https://github.com/anansi-project/comicinfo) seems to be the most common metadata format among the comic community, originating from the ComicRack software but now widely supported by the majority of the apps of this type
(Komga,Kavita,Codex.Ubooqity,Comictagger).

I figured it would be an option in the Hdoujin plugin as Hdoujin also supports downloading metadata into ComicInfo.xml.

Is this a feature that already exists in some third party pm plugin?

I tried messing around with one myself but have zero Perl knowledge and seemed to fail when trying to get a script to use [XML::LibXML](https://grantm.github.io/perl-libxml-by-example/).

Any information would be greatly appreciated :)

**Comment by Difegue** [comment]
👋 There's no plugin to import ComicInfo files atm, but it's certainly within the realm of possibility!  

I'd recommend you use [Mojo::DOM](https://docs.mojolicious.org/Mojo/DOM) for this; While it's technically an HTML parser there's nothing stopping you from using it for regular xml.  
It's also already used within the codebase, so you shouldn't have to do anything extra to get it to work. 👍

**Comment by Putarku** [comment]
Is it possible to scrape metadata from zip files comments?
Calibre's Embedded Comic Metadata plug-in can write metadata to comicinfo.xml files and zip files comments.
It would be much easier to read metadata from these two aspects.
just like
![image](https://user-images.githubusercontent.com/66679443/215527830-714aeb4b-1904-4499-bde9-3e1ffdbc110c.png)

**Comment by Difegue** [comment]
Sure, just needs someone to write it 😅

**Comment by Difegue** [comment]
ComicInfo support is now available as a built-in plugin! 👍
