### ISSUE TITLE
Install problem when system lanuage is chinese

### ISSUE THREAD

**Issue by Andor233** [Difegue/LANraragi#706]
Because of stupid Microsoft, wsl has been translated to Chinese(But without real work)
So the output of wsl --status is 

```
默认分发: Ubuntu
默认版本: 2
```
And cause install failed.

By the way,  `--list` has been translated to `--列表`, But when you use it, it will get an error. Only the `--list` will work.

**Comment by Difegue** [comment]
👋 I've had reports of this in #673 and others; Changing your Windows language to english will work if you want to bypass the installer error.  

The WSL detection checks for "version" in the output of `--status`, which works...sometimes, as the command line isn't localized on later versions of WSL.

**Comment by Andor233** [comment]
Yeah I guess so, but there is a way to fix that or not?

**Comment by Difegue** [comment]
Looking at https://github.com/microsoft/WSL/issues/7654 I guess there won't be a way to bypass localization, so I changed the installer to simply check for a non-zero exit code from wsl.exe instead.  
Hopefully that catches most issues.
