### ISSUE TITLE
Please add a grammar to search archives untagged

### ISSUE THREAD

**Issue by gth7754125** [Difegue/LANraragi#709]
It seems that we can only search untagged archives on the sub view. How can i do this through the search bar? formmer lanraragi can do this through the untagged button.maybe a key word needs to be added.

**Comment by Difegue** [comment]
The carousel/subview is the designed place for new/untagged searches, so I don't plan on adding a button/keyword that does the same thing for now. (The whole point of that view *was* to cut down on buttons...) 

Previously I'll admit it'd be inconvenient as the subview wouldn't update at the same time as regular searches, but now that we have faster searches through #555 I've just changed that. 😤  

In case you still want a dedicated untagged button, I believe some of the third-party clients do that through their use of the API.
