### ISSUE TITLE
automatic upgrade thumbnails

### ISSUE THREAD

**Issue by pratello** [Difegue/LANraragi#71]
Well, maybe I can't find the option, but there are a possibility to have an automatic function to upgrade the thumbnails when the page change?
I ask this because I have tried to upload too many archives.. and the result was that every new entry has a "no thumbnails" preview and for generate it, I must read every doujins.

thanks

using LRR 0.5.6 installed with the .bat

**Comment by pratello** [comment]
yes, you are right, when I upload an archive, I can see in the log that it's try to create a thumbnail, but
I founded that the error occured when in the image there are the characters [ ] like this "[something]"

this is the error:
[Auto-Tagger] [info] Thumbnail hash invalid, regenerating.
[Hash Computation] [error] Error building hash for ./public/temp/thumb/[something].jpg -- Open failed: No such file or directory at C:/LRR 0.5.6/lanraragi/lib/../lib/LANraragi/Utils/Generic.pm line 57.

**Comment by pratello** [comment]
yeah, for what I saw when I use the reader (entire extraction of the archive), the thumbnail is present.
well, sadly, the major part of the archive I have got, has some special character in it.
ok, I thank you and I will await for the switch.

**Comment by Difegue** [comment]
I finished moving to libarchive and the results are pretty darn good as I expected!  
I need to do some integration work to ensure builds on both Windows and Linux are A-OK, but hopefully I'll get 0.5.7 out the door soon.
