### ISSUE TITLE
支持启用登录

### ISSUE THREAD

**Issue by wolfcdd** [Difegue/LANraragi#710]
能否增加登录页面，现在只要知道网址就可以直接访问不需要登录，现在的登录仅是给管理员登录的

**Comment by wolfcdd** [comment]
已解决

**Comment by LemonSoda-RPG** [comment]
how do you solve it ?

**Comment by wolfcdd** [comment]
> how do you solve it ?

![image](https://user-images.githubusercontent.com/5728354/222030318-1e16aac1-ca7c-485b-bde5-34d9fdc2e33b.png)

**Comment by wolfcdd** [comment]
> how do you solve it ?

![image](https://user-images.githubusercontent.com/5728354/222030508-85a8e01a-d9ed-41e3-8635-5fa3d0d295b6.png)
