### ISSUE TITLE
The problem of using Ehentai login plug-ins in non European and American regions

### ISSUE THREAD

**Issue by Atomseek** [Difegue/LANraragi#719]
Non European and American regions cannot obtain tags using login plugin. If using a proxy log in, Then we can using cookie(ipb_member_id, ipb_pass_hash, igneous)in any region. But the Ehentai login plugin can not use igneous. Can you add a igneous input box?

I modify the plugin. it work successfully. you can have a look.
[EHentai.zip](https://github.com/Difegue/LANraragi/files/10184307/EHentai.zip)

**Comment by Difegue** [comment]
👋 I wasn't aware the igneous cookie had any real use besides blocking certain login attempts. Thanks for letting me know!    

Can you PR this in? 🙏 It'd be more convenient than me patching a zip.

**Comment by Atomseek** [comment]
I use another account PR it 🙃
