### ISSUE TITLE
Import Title from Gallery URL

### ISSUE THREAD

**Issue by Neotter** [Difegue/LANraragi#72]
Is there any way to modify title by using plugin? Sometimes due to irregular file nameing of cbz LANraragi will achives wrong title. I try to modifiy plugin to get title from gallery URL and I did it，but I can only change tags textarea in the Editing Mode, title area still the same.

**Comment by Difegue** [comment]
As of right now, plugins can only modify tags.  
The system could be extended rather easily to add title modification as well -- I'll think about it.

**Comment by Difegue** [comment]
_hee to the ho and here we go_

Plugins can now return an optional "title" field alongside the tags to change the displayed title.
