### ISSUE TITLE
An error will be reported when searching in Chinese or Japanese

### ISSUE THREAD

**Issue by LemonSoda-RPG** [Difegue/LANraragi#726]
**LRR Version and OS**

Docker    V0.8.8

**Bug Details**
Please detail the bug here. 

When I use Chinese or Japanese to search, the following error will appear.  But using English will be normal.

**Matching Logs**
Post any logs you have encountered when reproducing the bug.  
If possible, switch the app to Debug Mode in order to have more logs.

[2022-12-21 11:36:02.86626] [14198] [error] [A-tvzGEBwKml] command sent is not an octet sequence in the native encoding (Latin-1). Consider using debug mode to see the command itself. at /usr/local/share/perl5/site_perl/Redis.pm line 311.

**Screenshots**
![IMG_9457](https://user-images.githubusercontent.com/85331400/208910690-b654914e-53d7-4941-9c3b-3af628c591cf.PNG)

**Comment by Difegue** [comment]
This should be fixed in 0.8.81. Sorry for the trouble!
