### ISSUE TITLE
tag popup window is partially hidden

### ISSUE THREAD

**Issue by pratello** [Difegue/LANraragi#73]
the tag popup is partially displayed outside the broswer border, I've even tried the demo but it's the same

![sample](https://user-images.githubusercontent.com/46274109/50642187-488e2e80-0f62-11e9-9412-d781b7fbc917.jpg)

**Comment by Difegue** [comment]
Yeah, noticed that one. There used to be a css fix for this but I removed it when doing the batch tagging UI on 0.5.6 and didn't fully test the consequences. 

I'll have to make 0.5.7 a quick release since this is kinda inconvenient.

**Comment by Difegue** [comment]
🙌
