### ISSUE TITLE
Ctrl-F5 (no cache refresh) breaks the random/new archives zone

### ISSUE THREAD

**Issue by nonamethanks** [Difegue/LANraragi#732]
![image](https://user-images.githubusercontent.com/12946050/209885978-594ee181-90f1-448b-8701-28d3e7d06d55.png)

The archives start appearing in the middle. It's solved after an additional refresh, but breaks every time a hard refresh is done. Possibly related to issue #731, because the galleries with broken tooltips from that issue appear in this same zone that should have galleries but doesn't.

Tested on latest chrome & latest docker. Can be easily reproduced by hitting "disable cache" in the network tools. and refreshing the page.

Black bar added by me, obviously.

**Comment by Difegue** [comment]
Hmm, I can repro #731 but not this one, although I do remember seeing it once...

**Comment by Difegue** [comment]
Can repro on chromium browsers. (of course..)

**Comment by pastalian** [comment]
The reported behavior seems similar to swiper's [centerInsufficientSlides](https://swiperjs.com/swiper-api#param-centerInsufficientSlides) used in [index.js](https://github.com/Difegue/LANraragi/blob/dev/public/js/index.js#L167).

Maybe virtual slide didn't load thumbnails fast enough and swiper thought there were not enough slides? just a guess though.

**Comment by Difegue** [comment]
Tried quickly setting `centerInsufficientSlides` to false and it does look like that fixes it -- Guessing your hunch is correct on that one. Thanks!  

Since I'm playing around with holopin right now, I've sent you a [holobyte.](https://www.holopin.io/holobyte/clcv5c6qf353808jvinhqqd0z) ⭐
