### ISSUE TITLE
LRR doesn't start after updating to a newest version

### ISSUE THREAD

**Issue by kw4s** [Difegue/LANraragi#737]
**LRR Version and OS**
LRR version: custom "nightly" 0.8.81 build (essentially everything up to and including commit f3d09bce6e25f20b6f16959e445e7ac651dfe258) upgraded from 0.8.7 (or somewhere around that version - nightly again, but basically before #555 )
running in docker on linux

**Bug Details**
LRR doesn't start, seems to be stuck in a restart loop, logs attached in file - [lrrlogs.txt](https://github.com/Difegue/LANraragi/files/10329411/lrrlogs.txt)
Seems it processes same set of files, then crashes then starts again and processes same files and it just loops over and over again.
Despite the `[LANraragi] [info] Routing done! Ready to receive requests.` no requests are processed, seems like LRR is not listening on assigned port.

**Matching Logs**
[lrrlogs.txt](https://github.com/Difegue/LANraragi/files/10329411/lrrlogs.txt)
[redis.log](https://github.com/Difegue/LANraragi/files/10329415/redis.log)
[minion.log](https://github.com/Difegue/LANraragi/files/10329416/minion.log)

For now I just rolled back to previous version which starts and works correctly, I'm guessing the amount of archives (~25K) might pose a slight issue when indexes are being rebuilt, I will try to move the database and collection to a different machine and try different installation type/os combo, maybe that way it will work, but it will take some time...

**Comment by Difegue** [comment]
f3d09bce6e25f20b6f16959e445e7ac651dfe258 is busted, you probably should use a fixed point release for now.

**Comment by kw4s** [comment]
Cool, great, I guess it was my fault for running off of latest commit.

with 0.8.81 LRR indeed starts and responds to requests, I don't see my files but I'm guessing it will take some time to build the indexes
```
[2023-01-02 16:29:53] [Tag Stats] [info] Building stat indexes... (25295 archives)
[2023-01-02 16:30:54] [Search Engine] [error] Search engine is not initialized yet. Please wait a few seconds.
```
