### ISSUE TITLE
Hdoujin plugin

### ISSUE THREAD

**Issue by pratello** [Difegue/LANraragi#74]
using the eze plugin as template I have made this for the Hdoujin json file.
it's my first attemp in perl language, but it's seem like it's working, the only odd thing I saw for now is an automatic add tag "group" if the archive has some strange character in the filename and you are using the auto-tag function.

[Hdoujin.zip](https://github.com/Difegue/LANraragi/files/2724155/Hdoujin.zip)

**Comment by Difegue** [comment]
Thanks a lot for this! I hope you found the plugin system good enough to write for. 

I gave the code a quick read and besides some bad indentation I don't see anything wrong per se.  
Would you mind opening a pull request against the _dev_ branch to add this plugin in the codebase ? 
I'll give it proper detailed review and testing then.

**Comment by pratello** [comment]
yeah for what I understand, the system plugin is good, it was a little confusional at the beginning because of the perl commands, but then, after some studying of your code, perl and some trials and error, it's worked :)
and yeah my identation is really bad.... 

ps. I have used the "pull request" thing, I hoped is correct

**Comment by Difegue** [comment]
Hm, this isn't quite what I meant.  
If you're not familiar with the pull request model I recommend you read the matching github help: https://help.github.com/articles/creating-a-pull-request/  

It's good practice, but if you're not feeling like cloning the repo and doing all the work I guess I'll just integrate it manually.

**Comment by pratello** [comment]
uhm, if I'm right after some tries... for create a pull request, I must do a fork, am I right?
if yes, ok it's not a problem.

**Comment by Difegue** [comment]
Yep, looks good! I'll be testing this shortly.

**Comment by pratello** [comment]
good!

**Comment by Difegue** [comment]
PR #76 adds this as a base plugin. Thanks again!
