### ISSUE TITLE
Source tag not searchable until server restart

### ISSUE THREAD

**Issue by WorstGirl** [Difegue/LANraragi#760]
**LRR Version and OS**
LRR 0.8.81, Docker, Ubuntu Server 20.04 LTS (Focal)

**Bug Details**
After adding a gallery and providing metadata (Manual plugin run or downloader plugin), the source tag cannot be searched until the server is restarted.
Tested with galleries uploaded from file (Manual plugin tagged) and downloaded via plugin.
Other tags are still searchable without issue.

**Comment by Difegue** [comment]
I'm guessing the source tag isn't being live-updated in indexing? Would need to look deeper into this.
