### ISSUE TITLE
Wrong redis instance partially used in shinobu during scan

### ISSUE THREAD

**Issue by siliconfeces** [Difegue/LANraragi#779]
**LRR Version and OS**
Latest dev

**Bug Details**
A bug sneaked in during a0be2ac4b208a80d91d0bce710decd48a259d0d0 that fucks up Shinobu.

`Shinobu::add_to_filemap` accepts a redis instance equaling  `LANraragi::Model::Config->get_redis_config`. This is mostly all and good, BUT this same instance is passed on to `Shinobu::add_new_file` and finally `LANraragi::Utils::Database::add_archive_to_redis`. That sub expects `LANraragi::Model::Config->get_redis` instead, which causes some of the archive data ending up in the wrong place.

This breaks adding existing archives found by Shinobu, but newly uploaded archives still work (as that code path uses the correct redis instance).

**Comment by Difegue** [comment]
Wew, thanks for catching that! This was also breaking the entire dupe detection/ID changing system.  

Passing redis instances as subroutine parameters isn't a very good design decision and I've been trying to avoid/remove it exactly to avoid problems like those...I clearly haven't done the best job there.
