### ISSUE TITLE
Cant load doujin

### ISSUE THREAD

**Issue by happy1229** [Difegue/LANraragi#786]
**LRR Version and OS**
Windows10 0.8.90 and  Docker 0.8.90  

**Bug Details**
I put in two doujin with different names
But only shows one in Lanraragi

**Matching Logs**
https://i.imgur.com/zW235VA.png
https://i.imgur.com/Irp8UHC.png
https://i.imgur.com/CATqMhA.png

**Screenshots**
https://i.imgur.com/8sh2c6P.png
https://i.imgur.com/p2fsHun.png
https://i.imgur.com/k2SyskU.png

**Comment by Difegue** [comment]
I believe this is the same issue as https://github.com/Difegue/LANraragi/issues/365.
