### ISSUE TITLE
Avif files not loading thumbnails on windows

### ISSUE THREAD

**Issue by nikgtasa** [Difegue/LANraragi#792]
**LRR Version and OS**
win10 22h2, LRR 0.8.90, waterfox g 5.1.3

**Bug Details**
Avif images load fine but can't generate thumbnails. After a time of trying to generate them, a bunch of errors pop up saying "Error checking minion job status, error"

**Matching Logs**

[2023-04-20 02:28:00] [Archive] [info] Using current date
[2023-04-20 02:28:01] [Auto-Plugin] [info] Executing enabled metadata plugins on archive with id 542e1eba5f2285395cbde197108eab3333ec2941.
[2023-04-20 02:28:01] [Plugin System] [info] Thumbnail hash invalid, regenerating.
[2023-04-20 02:28:01] [Plugin System] [info] Applying tag rules...
[2023-04-20 02:28:01] [Auto-Plugin] [info] Executing enabled metadata plugins on archive with id 1a5337971083546fa1499810fac7bb25b679f1ab.
[2023-04-20 02:28:01] [Plugin System] [info] Thumbnail hash invalid, regenerating.

Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
[2023-04-20 03:00:03.34812] [15] [info] Creating process id file "/home/koyomi/lanraragi/public/temp/server.pid"
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
[2023-04-20 03:00:05.31036] [15] [info] Creating process id file "/home/koyomi/lanraragi/public/temp/server.pid"
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
[2023-04-20 03:00:07.34812] [15] [info] Creating process id file "/home/koyomi/lanraragi/public/temp/server.pid"
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
[2023-04-20 03:00:52.37540] [15] [info] Creating process id file "/home/koyomi/lanraragi/public/temp/server.pid"
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
Unhandled rejected promise: Redis server has gone away at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": Connect timeout at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
Compilation failed in require at (eval 88) line 1.
[2023-04-20 03:01:43.36658] [15] [info] Creating process id file "/home/koyomi/lanraragi/public/temp/server.pid"

**Screenshots**
![waterfox_08nVt1JBhG](https://user-images.githubusercontent.com/38408810/233200029-628b9b60-0e14-4b11-a741-93a9a56943d4.png)

**Comment by Difegue** [comment]
I did some testing, and it appears that Alpine 3.12's imagemagick actually did not include AVIF support yet.  
(They said it came in 7.0 but clearly it needs at least 7.1...)

**Linux/Docker logs:**  (3.16)

```
/home/koyomi/lanraragi # convert -version
Version: ImageMagick 7.1.0-50 beta Q16-HDRI x86_64 20489 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jng jpeg jxl lcms ltdl lzma png ps rsvg tiff webp x xml zlib
Compiler: gcc (11.2)

/home/koyomi/lanraragi # magick -list format | grep -i HEIC
     AVIF  HEIC      rw+   AV1 Image File Format (1.12.0)
     HEIC  HEIC      rw+   High Efficiency Image Format (1.12.0)
     HEIF  HEIC      rw+   High Efficiency Image Format (1.12.0)
```

**Windows logs:**  (3.12)

```
/home/koyomi/lanraragi# convert -version
Version: ImageMagick 7.0.10-48 Q16 x86_64 2020-12-12 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jng jpeg lcms ltdl lzma png ps rsvg tiff webp x xml zlib

/home/koyomi/lanraragi# magick -list format | grep -i HEIC
     HEIC* HEIC      rw+   High Efficiency Image Format (1.6.2)
     HEIF* HEIC      rw+   High Efficiency Image Format (1.6.2)
```

Which leads to this error when trying to make a thumbnail. It shouldn't explode as spectacularly as in your logs though, looks like the Minion job was missing an eval statement here. At least I'll be able to fix this.
```
/home/koyomi/lanraragi/public/temp/53ab5f638bccd48619ff3398d3012590b596fa5d# convert kimono.avif kimono.jpg
convert: no decode delegate for this image format `AVIF' @ error/constitute.c/ReadImage/572.
convert: no images defined `kimono.jpg' @ error/convert.c/ConvertImageCommand/3301. 
```  

But yeah tl;dr is that AVIF thumbnails won't work on Windows until I manage to move it past Alpine 3.12. 🙇   

I'm fairly hopeful the next alpine release will finally bundle in some [patches](https://bell-sw.com/blog/how-to-deal-with-alpine-dns-issues/) for #626 's DNS problems.
