### ISSUE TITLE
[EHentai Plugin] Not use artist tag by default

### ISSUE THREAD

**Issue by chu-shen** [Difegue/LANraragi#798]
If the artist's name is not in English, the text search will return 'No matching EH Gallery Found!' 

This code can be found at https://github.com/Difegue/LANraragi/blob/d54f08976347393ffbbd35fe74a89a6c660d398e/lib/LANraragi/Plugin/Metadata/EHentai.pm#L175-L181

For example:
- artist:kokutou nikke ✅
- artist:黒糖ニッケ ❎

---

It is recommended to either add a switch for this feature or remove it altogether.

**Comment by Jesan71** [comment]
Finally know why the plugin always find no match. I use Filename Parsing first and Jp artist's name tag was added.

**Comment by Difegue** [comment]
Thanks for that report. It's true that EH doesn't support non-ascii characters in their tags, so it doesn't make much sense to try and slam those in the URL searches...  

I've pushed a change to filter non-english tags out of searches. Thanks!
