### ISSUE TITLE
Complex tag searching

### ISSUE THREAD

**Issue by koma-cute** [Difegue/LANraragi#80]
It seems when searching for multiple tags seperated by spaces, the query is interpreted as a single tag. Instead, they should be treated seperately with a logical AND operator. Ideally, other operations like tag negation, the OR logical operator, etc would be supported. See [E-H's existing tag searching features](https://ehwiki.org/wiki/Gallery_Searching) for reference.

**Comment by koma-cute** [comment]
Another note, as it's somewhat related to this issue - server side searching would be much nicer for underpowered devices like phones and tablets, as the current method of loading a huge amount of HTML in large libraries to search locally can result in a lot of slowdown.

**Comment by Difegue** [comment]
The current behavior is basic AND searches for words separated by spaces. 
The interface kinda supports OR searches as well if you check multiple favorite tags at once, but it's a bit of a behind-the-scenes trick and currently doesn't work in the main search bar.  

I'm basically just using the Datatables basic search() method right now - It's worked well enough for me so far but it does indeed lack a bit in power. The way forward would be to implement a proper searching syntax (kinda like E-H's indeed) and translate it to regular expressions in the back to then feed to Datatables. 

Or I could just say fuck it and move search to the back-end, using Datatables' server-side processing instead. Perl has crazy good regex powers so it might actually be easier, and lighten up a bit the current  real messy JavaScript Datatables code.  

I won't do this right now, but it's a pretty good contender for what to work on next.

**Comment by koma-cute** [comment]
I must have been searching incorrectly. I think I had tag namespaces the wrong way around or something - the default search bar does seem to work fine.
Thanks for the consideration.

**Comment by Difegue** [comment]
When the work on #100 concludes, the APIs can be used to also provide tag suggestions in search.  

I probably won't move search to the server-side just yet - Cleaning up the current implementation to not awkwardly switch between regex and non-regex mode would be a good first step.

**Comment by Difegue** [comment]
First draft of the search API is documented here: https://sugoi.gitbook.io/lanraragi/extending-lanraragi/client-api#search-the-archive-index  

The documentation is weirdly formatted, I'll get to fixing that in a few.

**Comment by Difegue** [comment]
Server-side search is finalized and now used in the main index with an integrated cache for speed. 🎊 

I took the opportunity to write some new unit tests as well to ensure it behaves as desired for the various possible modifiers -- Hopefully I caught them all but there might be some gotchas left lurking.
