### ISSUE TITLE
Archive downloading from URL

### ISSUE THREAD

**Issue by koma-cute** [Difegue/LANraragi#84]
Implement a textfield on the add archive page, allowing URLs from various services to be downloaded, tagged, and imported to the library.
For Chaika and NH, it's as easy as adding /download to the gallery URL. EH is a bit more awkward, the API has an archiver key that can be used in the form `/archiver.php?gid=<gallery_id>&token=<gallery_token>&or=<archive_key>`, which returns an HTML page containing a redirect to the archive download:
```
function gotonext() {                                                                                                                                                      
        document.getElementById("continue").innerHTML = "Please wait...";                                                                                                  
        document.location = "http://<ip>/archive/<gallery_id>/<token>/<token>/0?autostart=1";
}                              
```
Pulling that URL out and replacing `?autostart=1` with just `?start=1` skips another confirmation redirect, and downloads the archive.

**Comment by Difegue** [comment]
The issue I'm seeing right off the bat is that for both NH and EH, downloading requires to login.  

The idea isn't bad, but I'd make it so that the textfield would only accept URLs that immediately give a file. This isn't a hill to add complexity and a login system on.

**Comment by koma-cute** [comment]
Perhaps it could leverage the existing plugin system? If the textfield recieves an input that is not a known site of any of the enabled plugins, and is not a direct zip link, then bail out.

**Comment by Asinin3** [comment]
If this does happen, I think the script should also fetch a json file and include it inside the archive it downloads. Or is that outside the scope and should be done by a plug-in?

**Comment by wongsaraf** [comment]
E-Hentai downloader forked by dnsev-h got a json file embeded into the archived.
https://github.com/dnsev-h/E-Hentai-Downloader

But it need a little bit of fix from the original ccloli one.
https://github.com/ccloli/E-Hentai-Downloader/commit/127cef2e2186b6fa11b00cb15437cd5dc824e87b

**Comment by Asinin3** [comment]
Just some feedback on the prototype downloader: It would be great to have an option be able to save the files out as cbz, which should be easy to implement as it's just renaming the extension from .zip to .cbz.

The filenames of galleries with special characters isn't changed properly into something operating systems work with either. For instance a gallery with a pipe `|` in the title, would change to `｜` there must be some code for this we can look at in the original eh script.

Including the metadata json file would also be great, but mentioned already.

**Comment by rwchunk** [comment]
You could alternatively just download all the images into a folder then pack it into an archive.
If you're considering EH/chaika/NH archival, then you'd probably be interested in this:
https://github.com/happypandax/happypandax

**Comment by Difegue** [comment]
One year and a half later, it's finally done 🙇‍♂️
For the initial release, I tried to focus on a system that avoids unnecessary code duplication:  

* Unlike in the prototype, Downloader plugins don't really perform a download, they simply take the input URL and return a direct URL to the file to download. For EH, this goes through the whole archiver.php dance, but for other sources it can be much simpler. (e.g NH, which I didn't implement as that'd require a matching login plugin)
* The part that downloads and tags the file proper is in the main codebase, so people don't have to copy/paste the same boring Mojo::UserAgent implementation each time. This brings limitations as you can _only_ download URLs off the internet with no further transformations doable on the plugin side. (Except if you run a script afterwards, of course)
* I don't plan on supporting the "download all images in a folder then zip it" approach in downloaders, I consider it flaky and there are tons of tools for it already. Nothing stopping someone from implementing it through script plugins, of course. (It should be easier now that you can call `LANraragi::Model::Upload::handle_incoming_file` with your filename and it'll do everything else automagically)
* Downloading a file appends the original URL as a `source:` tag.
* On the flipside, this means direct downloads are supported out of the box, even if you have no plugins loaded:  

![image](https://user-images.githubusercontent.com/8237712/94370815-78944280-00f2-11eb-8f29-540888586b97.png)  

Waiting for documentation to close this.

**Comment by koma-cute** [comment]
Looks good! Does this have an API endpoint too? Would make sending URLs from sites directly to LRR easier (e.g. with the hypothetical browser extension)

**Comment by Difegue** [comment]
Yes! You can send URLs to `/api/download_url` and it'll queue them up as download jobs.
