### ISSUE TITLE
Full width characters breaks the search function

### ISSUE THREAD

**Issue by soarpasser** [Difegue/LANraragi#849]
This is a problem present on current (0.8.90) version of the app, reproed on a Windows 10 msi install.

If you try to enter any full-width characters (CJK, special characters etc.) in the search bar, the search function will not return anything at all until you repeat the query without the full-width characters. 

See the video in which I place a demo archive with full-width characters in the filename into the database. The archive is registered on the filemap as you can see in the first second of the video, yet searching the exact filename returns nothing until I delete all the full width characters.

As one can imagine, this creates serious issues for anyone who has their entire database with filenames containing only such characters (e.g. full Japanese).

This issue might be related to #838.

https://github.com/Difegue/LANraragi/assets/74951691/3717a2eb-97e3-42a2-bfe9-24dc123b851b

**Comment by Difegue** [comment]
works on my machine ™️ Maybe this is windows-specific?  

![image](https://github.com/Difegue/LANraragi/assets/8237712/a7f4e572-c3d0-471d-a74d-f805c23abfaa)

**Comment by soarpasser** [comment]
> works on my machine ™️ Maybe this is windows-specific?
> 
> ![image](https://user-images.githubusercontent.com/8237712/271036992-a7f4e572-c3d0-471d-a74d-f805c23abfaa.png)

Try to add a brand new archive (with full width characters) to the database and do a "first time search" for it, you should be able to reproduce the issue. This is a bit finnicky at times, as through further testing I've realized that this only happens for newly added archives.

**Comment by Difegue** [comment]
New files were storing a double-encoded version of their filename in the search indexes - which doesn't really cause any trouble with ascii characters but goes south with any other encoding.  

Should be fixed now.
