### ISSUE TITLE
Unable to open Statistics and Modify Categories pages

### ISSUE THREAD

**Issue by skyrim663** [Difegue/LANraragi#858]
**LRR Version and OS**
Docker latest,ubuntu20,Rclone+clouddrive

**Bug Details**

 Unable to open Statistics and Modify Categories page, keep waiting will receive timeout error. Maybe it's because there are too many archives (9800).

**Matching Logs**
No relevant  log output, even with debug mode.

**Comment by Difegue** [comment]
Stats should be fairly instantaneous as long as the indexes are built - although it does some inplace calls to get the size of the content folder, I wonder if that's not broken with a rclone/FUSE filesystem as well?

**Comment by skyrim663** [comment]
After using and testing, I found that the archive list loads sluggishly every time I open it. If the default is to display 100 archives per page, 5~7 consecutive pages will fail to load the next page, the browser console prompts 503 service unavailable, which will only be restored after closing lanraragi and remounting rclone.
So I guess the inability to open the Statistics and Modify Categories page may be due to the inability to load the full list of archives?

**Comment by siliconfeces** [comment]
The stats page iterates all files in the content folder to count them and get the total size, which can be slow as gosh-darnit over networks.

**Comment by Difegue** [comment]
#864 should've improved this!
