### ISSUE TITLE
Progress tracking can fail for infinite scroll

### ISSUE THREAD

**Issue by siliconfeces** [Difegue/LANraragi#865]
**LRR Version and OS**
Latest nightly, Linux, Docker.

**Bug Details**
Progress tracking doesn't trigger in infinite scroll when pages are too tall AND when you are using the mousewheel or similar. This happens because the IntersectionObserver threshold is set to 0.8, and is thus never triggered if 80% of a page is never visible at one time.

Basically, this shit: https://github.com/w3c/IntersectionObserver/issues/124

**Comment by Difegue** [comment]
🤔 Couldn't we just lower the observer threshold?  
I wonder if this couldn't combo with https://github.com/Difegue/LANraragi/issues/743 somehow.

**Comment by siliconfeces** [comment]
Fiddling with the threshold should work, or at least make it less likely to fuck up. Omakase!

**Comment by Difegue** [comment]
I've lowered the threshold to 50%. I guess the issue can still happen with very long webtoon-ass images, but at this point I'm just putting the blame on you for not chopping up your images a teensy bit.
