### ISSUE TITLE
Read progress/partial new status

### ISSUE THREAD

**Issue by koma-cute** [Difegue/LANraragi#87]
When a book is opened, the new status is removed immediately. Instead, track which page the user read up to, and only remove the new status once the book is fully completed (especially useful on long tanks). Additionally, display the read progress of the book on the library pages, perhaps in a way similar to [Perfect Viewer](https://play.google.com/store/apps/details?id=com.rookiestudio.perfectviewer):

![Perfect Viewer Bookshelf](https://lh3.ggpht.com/aqUvkBXv60M0ja8budiKNMVlZdFUrKcOG9tEJqHXnwKHffJX1w8mt_XOQjYNHgc9iZA=w1696-h975)

**Comment by Difegue** [comment]
Agreed on the first point -- I'm probably going to remove the new status client-side instead of server-side and add a reader preference for it. (either remove when opening the archive or when you're done with it, defaulting to the second)

Won't do the second as it'd generate a shitload of thumbnails and overall look weird. I personally prefer having a nice row of covers.

**Comment by koma-cute** [comment]
I'd personally rather keep the read statuses server side, since clearing cache or switching browsers means losing a potentially large amount of information on what books are read.

Doesn't have to be done with images, could be a css `calc()` of the current and max pages on a progress bar or something.

**Comment by Difegue** [comment]
Oh, by client-side I meant only the changing operation. The status itself would still be stored in the database. I'd wrap it in an API call so third-party clients can also set an archive as read however the fuck they want.

A progress bar could be done, not sure where to put it however.

**Comment by koma-cute** [comment]
Ah, that makes more sense. As long as read progress is stored between devices, then that's all that matters really.

Maybe between the title and the thumbnail? Doesn't necessarily need to be a bar either, could be a small circle that fills up/radially wipes overlayed on the bottom of the thumbnail, maybe.

**Comment by Difegue** [comment]
Done in b9e66e536373e409c9d1b2c958e6536cef540d9f.
