### ISSUE TITLE
Keep package-lock.json for reproducibility

### ISSUE THREAD

**Issue by TomaSajt** [Difegue/LANraragi#874]
I am currently trying to package this app for Nixpkgs (https://github.com/NixOS/nixpkgs/pull/255715, still WIP), and it requires me to have a `package-lock.json` to have reproducible builds. Currently, I am just generating the lockfile and committing it to the Nixpkgs repo, but it would be helpful if that was handled here, on the upstream.

**Comment by Difegue** [comment]
I currently just gitignore the package-lock file as I thought it was unnecessary - don't mind changing that if it can help. ✌️
