### ISSUE TITLE
Secrets file crashes the server if content folder is read-only

### ISSUE THREAD

**Issue by cazendium** [Difegue/LANraragi#887]
**LRR Version and OS**
Please tell which version you're running, as well as your OS and installation method. (Windows, Docker, Native)

Mac OS

**Bug Details**
Please detail the bug here. 

LANraragi immediately stops after starting it.

After comparing the previous code and new code for launcher.pl, I commented this code out:
```
# my $secretfile_path = $ENV{LRR_DATA_DIRECTORY} ? $ENV{LRR_DATA_DIRECTORY} . "/oshino" : "oshino";
    # if ( -e $secretfile_path ) {
    #     $secret = Mojo::File->new($secretfile_path)->slurp;
    # } else {

    #     # Generate a random string as the secret and store it in a file
    #     $secret .= sprintf( "%x", rand 16 ) for 1 .. 8;
    #     Mojo::File->new($secretfile_path)->spew($secret);
    # }
```

Now LANraragi is able to run normally.

It seems this has to do with my data directory using a custom path that I set using Terminal. Not sure if this affects anyone else, it could just be Mac OS.

I was going to append the logs, but I guess I accidentally terminated the window beforehand, but it kept showing my data directory path appending "oshino".

**Matching Logs**
Post any logs you have encountered when reproducing the bug.  
If possible, switch the app to Debug Mode in order to have more logs.

**Screenshots**

**Comment by Difegue** [comment]
👋 What are you using for `LRR_DATA_DIRECTORY` ? I'm not really sure why it'd crash here, this just relocates the file containing the generated secret to your data directory so it doesn't write at the server root.  

I'd tested this with homebrew/macOS and it seemed to [perform adequately](https://github.com/Difegue/LANraragi/actions/runs/6723516848/job/18273761734).

**Comment by cazendium** [comment]
> 👋 What are you using for `LRR_DATA_DIRECTORY` ? I'm not really sure why it'd crash here, this just relocates the file containing the generated secret to your data directory so it doesn't write at the server root.
> 
> I'd tested this with homebrew/macOS and it seemed to [perform adequately](https://github.com/Difegue/LANraragi/actions/runs/6723516848/job/18273761734).
> 
> Would be good to have the details of the error if possible.

I use "export LRR_DATA_DIRECTORY=/Users/cazendium/Archives" in the ".zshenv" file in my Mac OS home folder. It's relocating that file?

I commented the code back in, here is the error:
`ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!!!!!
 load application from file "/opt/homebrew/Cellar/lanraragi/HEAD-846d0a7_2/libexec/script/lanraragi": Can't open file "/Users/cazendium/Archives/oshino": Operation not permitted at /opt/homebrew/Cellar/lanraragi/HEAD-846d0a7_2/libexec/script/../lib/LANraragi.pm line 47.`

The data directory leads to a read-only volume.

**Comment by TomaSajt** [comment]
The app is trying to create that file to store a randomized secret in it. If you don't want do give it permission to the data directory itself, I think you could also manually create this file (it just has to have some random characters) (make sure it can read this file though)

**Comment by Difegue** [comment]
Ah yeah, I set the secrets file to be written in the data directory as I wanted it to be persistent and the app directory is readonly on the homebrew version.. I forgot about people that have the content directory as readonly as well.  

@TomaSajt's workaround will work in the meantime (literally create a text file called `oshino` with whatever in it), but I'll probably move it to the temp directory instead. (and I guess it'll get wiped a bit more often but it can't be helped)

**Comment by cazendium** [comment]
Thank you both for the solution
