### ISSUE TITLE
Thumbnail not always generated using the first image file sequentially

### ISSUE THREAD

**Issue by ChronoStriker1** [Difegue/LANraragi#895]
**LRR Version and OS**
0.9.0 docker in Unraid, this has existed in the previous version of LRR as well

**Bug Details**
Thumbnail is not using the first numbered file sequentially.  Sometimes it appears to use the largest number.  It's most notable with a specific translator (I would type their name here but they use a slur in it, I will make mention on discord) who seems to make the number for their credits page very long, i.e. "99999999999542121521990.jpg"

**Comment by Difegue** [comment]
The Perl code uses some magical sorting code to order numbers/letters - It's old and at this point I'm not quite sure how it works or how it could be improved without writing a behemoth..  

There's some guessing in the current codebase to catch obvious first/credit pages, if there's enough of a pattern I suppose we could add large numbers in there:  
https://github.com/Difegue/LANraragi/blob/d2ab6807cc4b1ed1fe902c264cba7750ae07f435/lib/LANraragi/Utils/Archive.pm#L257

**Comment by ChronoStriker1** [comment]
I think it would be safe to assume if the credits page isn't caught by the first portion of that regex the largest number should be the credits page. For my group I just have the credits page be 99.png or 999.png depending on the release size as those numbers are not normally hit.

**Comment by Difegue** [comment]
I've modified the credit filter to consider all 999* pages as credit. Hopefully that's enough 🤔
