### ISSUE TITLE
TagRules cause non-English characters to become unreadable

### ISSUE THREAD

**Issue by fatecyx** [Difegue/LANraragi#899]
TagRules:
 -uploader:*

Before:
date_added:1698742838,group:valssu,artist:茶琉,series:キノの旅,parody:kino no tabi,character:kino,artist:charu,female:tentacles,other:mosaic censorship,category:doujinshi,uploader:aerd,timestamp:1439798620

After:
date_added:1698742838,group:valssu,artist:è¶ç,series:ã­ãã®æ,parody:kino no tabi,character:kino,artist:charu,female:tentacles,other:mosaic censorship,category:doujinshi,timestamp:1439798620,source:exhentai.org/g/843423/933d77be4d

BatchLog:
Processed 1 out of 1
Started Batch Operation...
************
Replaced tags for ID fe79358b686912cda6341bc0d9fec55b1e100d1d (New tags: date_added:1698742838, group:valssu, artist:è¶ç, series:ã­ãã®æ, parody:kino no tabi, character:kino, artist:charu, female:tentacles, other:mosaic censorship, category:doujinshi, timestamp:1439798620, source:exhentai.org/g/843423/933d77be4d)

************
(code 1000)

**Comment by Difegue** [comment]
Thanks, fixed.
