### ISSUE TITLE
[api] file name/path and size in archive metadata

### ISSUE THREAD

**Issue by Guerra24** [Difegue/LANraragi#906]
Title. I have been requested this information for the deduper three times, see:

https://github.com/Guerra24/LRReader/issues/21#issuecomment-980808081
https://github.com/Guerra24/LRReader/issues/33
https://github.com/Guerra24/LRReader/issues/41

So I'm opening this for consideration 👀

**Comment by Difegue** [comment]
All three of those are available and I don't mind adding file name and size -- I don't think path is a good idea as the archive objects are present in public API endpoints and you don't really want to expose server filesystem information there.

**Comment by Guerra24** [comment]
Could file path be restricted behind a toggle in the server to enable/disable it? Or that would be too much of a hustle just for this? This for users who only use it in a private network and don't mind it being *"public"*.

So when disabled it will show only the file name and when using an API key/passwordless with it enabled it will show the entire path.

**Comment by Difegue** [comment]
Looking at the dedupe tickets in detail I _think_ the filename should be enough information for now. Not sure it'd be worth it to expose the path, sorry!
