### ISSUE TITLE
The Shinobu module gets stuck in an infinite loop with  errors

### ISSUE THREAD

**Issue by ArcadoMobius** [Difegue/LANraragi#908]
**LRR Version and OS**
Windows 10, WSL1, Lanraragi v0.9.0  msi

**Bug Details**
The Shinobu module gets stuck in an infinite loop with  errors when processing files. I'm Unable to Read  Archives Properly.

**Matching Logs**
[Shinobu] [error] Error scanning /mnt/f/anime/[琥珀亭 (堺はまち)] パパ活したら生ハメされた若妻 パート編 [中国翻訳].zip: [hset] MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.,  at /usr/local/share/perl5/site_perl/Redis.pm line 321.

[Shinobu] [error] Error scanning /mnt/f/anime/[琴義弓介] ミルフスカーニバル (コミックホットミルク 2016年4月号) [中国翻訳].zip: [hset] MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.,  at /usr/local/share/perl5/site_perl/Redis.pm line 321.

[Shinobu] [error] Error scanning /mnt/f/anime/[琴義弓介] 悪乗り☆ドデカップ (ヤリスギ肉熟女) [中国翻訳].zip: [hset] MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.,  at /usr/local/share/perl5/site_perl/Redis.pm line 321.

[Shinobu] [error] Error scanning /mnt/f/anime/[琴義弓介] 義母ビッチEMG!! はじめて母と言った日 (コミックマショウ 2021年9 月号) [中国翻訳] [DL版].zip: [hset] MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.,  at /usr/local/share/perl5/site_perl/Redis.pm line 321.

**Screenshots**
![image](https://github.com/Difegue/LANraragi/assets/140962636/cd2e521b-8876-44f2-ac1e-3fe968a0b841)
![image](https://github.com/Difegue/LANraragi/assets/140962636/2432a04b-bd42-43db-ae4c-06f14c5c167b)
![image](https://github.com/Difegue/LANraragi/assets/140962636/66fc953f-9d82-470f-b96f-4696ecdb5131)

**Comment by Difegue** [comment]
Future nightly windows builds now use a native Redis server - I've ran some tests and minion support seems iffy (I blame my unfinished backend tbh), but the app itself seems stable under WSL1 again.  

Ironically it's worse on WSL2 now because mirrored networking isn't a default yet, so the distro won't be able to communicate with the native database. That's something I hope will improve in the future since microsoft is still working on that version though!
