### ISSUE TITLE
LRR Does nothing after upload

### ISSUE THREAD

**Issue by Montessquio** [Difegue/LANraragi#91]
**LRR Version and OS**
LRR Latest through docker on Ubuntu Server LTS 18.04

**Bug Details**
Uploading any archive, including ones from any supported site and ones I made myself will not complete. The upload bar will increase at a speed proportional to the size of the archive, but stop at the end and the page will do nothing (it doesn't freeze, I can still click on things) and the archive will not be added, which leads me to believe that it is uploading, and there is some internal issue preventing it from working.

In the *matching logs* section, there is a bit where it can't find the `public/temp` directory. I created and mapped it to a folder on the host as a test, this got rid of the three error messages about it but did not change the bug. The message about the regex remained.

**Matching Logs**
https://pastebin.com/raw/WXjpuBgV

Some relevant lines I found immediately post-startup:
```
2019-02-17 20:42:08,959 DEBG 'lanraragi' stderr output:
Can't stat ./public/temp: No such file or directory
 at /home/koyomi/lanraragi/script/../lib/LANraragi/Controller/Config.pm line 20.

2019-02-17 20:46:08,846 DEBG 'lanraragi' stderr output:
^* matches null string many times in regex; marked by <-- HERE in m/^* <-- HERE .+\.(png|jpg|gif|bmp|jpeg|PNG|JPG|GIF|BMP)$/ at /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Reader.pm line 99.

2019-02-17 20:46:08,850 DEBG 'lanraragi' stderr output:
Can't stat ./public/temp: No such file or directory
 at /home/koyomi/lanraragi/script/../lib/LANraragi/Controller/Api.pm line 109.

2019-02-17 20:46:09,562 DEBG 'lanraragi' stderr output:
Can't stat ./public/temp: No such file or directory
 at /home/koyomi/lanraragi/script/../lib/LANraragi/Controller/Api.pm line 109.
```

**Screenshots**
Image of where the upload freezes:
![lrrbug](https://user-images.githubusercontent.com/10977407/52919144-15fb8380-32cd-11e9-989a-c033be6d1148.PNG)

**Comment by Difegue** [comment]
The messages about ./public/temp missing are normal on first runs, as the directory is only created when we extract an archive for viewing. They're kinda polluting the logs though, I'll be adding an existence check there.  

As for your bug, the rest of the logs look rather normal. Have you mapped the content directory properly ? When an upload concludes, all we do server-side is ID computation and dropping the file in said directory.  

You might also want to look in your browser's network dev tools to see if the upload request went through or encountered a 500 of some sort. The JQuery upload plugin I use doesn't report errors very well here.

**Comment by Montessquio** [comment]
Thank you so much! I hadn't thought of checking to see if the upload was completing!

Firefox's network inspector showed the upload returned a 413, complaining the request entity is too large.

I immediately suspected my NGINX settings. Sure enough, there was a default `client_max_body_size 1m` implied directive preventing uploads larger than 1mb. I was able to circumvent this by explicitly setting it, as shown below, to zero, which meant unlimited. The uploads work now.

It may be worthwhile to add this as a warning to the setup guide, if the user is using a reverse proxy.

```
server {
    listen 80;

    server_name lanraragi.[REDACTED].net;

    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    index index.php index.html index.htm;
    server_name lanraragi.[REDACTED].net;

    client_max_body_size 0;   <----------------------- This line here

    # Cert Stuff Omitted

    location / {
        proxy_pass http://0.0.0.0:3456;
    }
}
```

**Comment by Difegue** [comment]
Oh right, we override the max_upload_size in the built-in web server to handle this, but if you're using a reverse proxy it's another barrier to break through.  
Good news anyway, I'll be amending the documentation to reference this.
