### ISSUE TITLE
Support Using lastreadtime as Namespace for sortby in Search API Endpoint

### ISSUE THREAD

**Issue by Doraemoe** [Difegue/LANraragi#911]
The search API endpoint currently does not support lastreadtime as sortby namespace. It would be great to be able to search by lastreadtime so client could easily provide a "recently read" functionality.

**Comment by Difegue** [comment]
I've been thinking about adding a "On Deck" carousel view for a bit and it'd need that - I'll try to have that done at some point.

**Comment by Difegue** [comment]
You can now use _lastread_ if you want to sort by last read time.
