### ISSUE TITLE
Chaika.moe plugin improvements

### ISSUE THREAD

**Issue by Difegue** [Difegue/LANraragi#92]
Something from /h/ again:  
> I figured out that the plugin wasn't identifying the rips because artist names on Chaika are all lowercase. The the first letter of the artist's name in the rips are usually capitalized, which I think threw off the plugin. Changing the artist's name in the filename to all lowercase fixed it.

We could probably auto-lc names before using the API.  

The API also seems to support sha-1 reverse image lookup, so it should be implemented on our end.   
See https://github.com/pandabuilder/pandachaika/blob/99a4eabbe4aabf190ed2a066571a9e5b79746db0/viewer/views/api.py for a reference.

**Comment by Suika** [comment]
Furthermore it seems chaika search has problems when the title contains `-` or `'`.
Replacing them with spaces before sending the request to chaika would solve the problem.

**Comment by Difegue** [comment]
I have pushed the aforementioned improvements to the plugin alongside a fix for the -/' issue on chaika and nhentai.

Make sure to reopen an issue if you still have problems with search using those.
