### ISSUE TITLE
Incompatibility in `source` tag format for E-Hentai plugins

### ISSUE THREAD

**Issue by RodolfoFigueroa** [Difegue/LANraragi#920]
**LRR Version and OS**
* **Version:** 0.9.0
* **OS:** Debian 11
* **Install method:** Docker

**Bug Details**
When adding an exhentai archive via URL, the downloader automatically sets the `source` tag with the provided address, using the format `source:https://exhentai.org/<gID>/<gToken>`. However, this prevents the E-Hentai metadata plugin from reading said tag, since the [corresponding regex](https://github.com/Difegue/LANraragi/blob/aabc1a7f813ec3e96da8aeeb2a49f3de1a3b72c1/lib/LANraragi/Plugin/Metadata/EHentai.pm#L73) expects a tag of the form `source:exhentai.org/<gID>/<gToken>` (without the `https`). This in turn causes it to fall back to using a title/cover search, which may cause improperly tagged archives, as mentioned in #907.

Moreover, it is impossible to coerce the downloader plugin to add a source without `https`, since its [URL regex](https://github.com/Difegue/LANraragi/blob/aabc1a7f813ec3e96da8aeeb2a49f3de1a3b72c1/lib/LANraragi/Plugin/Download/EHentai.pm#L27) prevents it.

**Matching Logs**
The following log shows the plugin using the archive title (`[OOO] The Winner Takes it All (Splatoon)`) to fetch metadata, even though the archive has the tag `source:https://exhentai.org/g/2584391/38d9349edf/`

```
[2023-12-04 22:24:07] [E-Hentai] [debug] Using URL https://exhentai.org?advsearch=1&f_sfu=on&f_sft=on&f_sfl=on&f_search=%22%5BOOO%5D%20The%20Winner%20Takes%20it%20All%20%28Splatoon%29%22 (archive title)
```

**Comment by Difegue** [comment]
I've had a few reports of this - Something changed with the downloader in 0.9.0 that makes it add `https` to the source tag, but I haven't investigated yet.
