### ISSUE TITLE
Improve Batch Tagging filter to pre-check galleries which only have artist/series/event tags

### ISSUE THREAD

**Issue by Difegue** [Difegue/LANraragi#94]
Currently, Batch Tagging pre-checks archives that have no tags whatsoever registered. (tags field empty in Redis)  
However, if name parsing is enabled it often picks up a few tags, namely event/artist/series. Those tags lead to Batch Tagging not pre-checking the gallery even though it's basically void of metadata.  

This is a pretty simple fix to make in Model/Batch.pm.

**Comment by koma-cute** [comment]
how does the above look? apologies if it's totally broke, I haven't written perl in a long time.

**Comment by Difegue** [comment]
Looks good at a glance; I'll do some quick testing and merge this if it works properly. 🤞  

Thanks a lot for taking the time to do this!
