### ISSUE TITLE
[Feature request] save japanese title from Chaika.moe metadata

### ISSUE THREAD

**Issue by sakuyamaij** [Difegue/LANraragi#943]
E-Hentai v.2.5.2 metadata plugin has a great opinion called
**Save the original title when available instead of the English or romanised title**.

Will it be possible to add this opinon to Chaika.moe v.2.3.1 metadata plugin?

I found almost every archives have "title_jpn" in chaika's api, so I guess it is possible?

**Comment by Difegue** [comment]
Sounds easy enough, tagging as volunteers.
