### ISSUE TITLE
E-Hentai metadata plugin account for appended resolutions

### ISSUE THREAD

**Issue by masterjuggler** [Difegue/LANraragi#949]
I usually download resampled archives from ehentai/sad panda that have "-1280x" or similar appended to the end of the name, and unless I remember to fix that in the file names it messes up the metadata plugins. I *think* that should be a pretty simple addition to the script, but please let me know if there's a technical reason not to do that.

**Comment by Difegue** [comment]
The E-H plugin only does a text search for the current title of the archive if there's no other info, I'd be expecting at least thumbnail reverse searching to work beforehand if you've got that enabled.  

I'm guessing you might want to run the filename parsing plugin before hand or enable it to run automatically so it cleans up the filenames if it doesn't?

**Comment by masterjuggler** [comment]
I hadn't really played with the filename parsing plugin yet, I didn't realize it also adjusts the title and not just add tags. I'm not sure how lanraragi handles the order of running plugins automatically, if it will always run the filename parser first and then the scraping plugin of choice. If so, that does sound like a good solution.

I tried the thumbnail reverse search and while it did find tags from ehentai, it didn't respect the language I set and would just grab whatever the first result was, which usually wasn't english.

**Comment by Difegue** [comment]
filename parsing is hardcoded to run first when it's enabled currently; ideally this'd be superseded by #930 at some point but we're not there yet.

**Comment by masterjuggler** [comment]
Based on the end of #789, it seems like the best solution is to implement full on scripting so users can get the logic right for their own needs lol (/s)

I'll go ahead and close this since I believe running the filename parser before another metadata plugin works for my needs. Thanks.
