### ISSUE TITLE
Failed to create thumbnails

### ISSUE THREAD

**Issue by mumu233desu** [Difegue/LANraragi#953]
**LRR Version and OS**
Docker on Debian 12

**Bug Details**
No thumbnails were generated by default, and when I regenerated them manually, regardless of whether JPEG XL was enabled or not, I got this error:
```
All thumbnails generated! Encountered the following errors:
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
```
There's no more text to show due to the small message box size, I've googled and couldn't find a solution. The thumbnail folder is writable.

**Matching Logs**
No logs about thumbnails. Do I need to post some others?

**Screenshots**
![error](https://github.com/Difegue/LANraragi/assets/89022169/375e034a-2da5-4e21-88ee-b55f360c5c49)

**Comment by Kawaii-mumu233** [comment]
Update:
shows a message when reading
```
Error checking Minion job status
Error
```

**Comment by pringleprng** [comment]
same this is the error from minion.

notes: {}
parents: []
priority: '0'
queue: default
result:
  errors:
  - ''
  - ''
retried: ~
retries: '0'
started: 2024-03-05T09:05:42.42814Z
state: finished
task: regen_all_thumbnails
worker: '81'

**Comment by pringleprng** [comment]
check your folder permissions

**Comment by Kawaii-mumu233** [comment]
> check your folder permissions

I bond the content and thumb directory to the local folder, and it does have read&write permissions, I'd executed chmod 777 or 666 to the folder.

**Comment by ramzh** [comment]
Having the same issue. Any solution to this?

**Comment by Kawaii-mumu233** [comment]
> Having the same issue. Any solution to this?

Well, I turned to Kogma after several attemps...

**Comment by Difegue** [comment]
Sorry for the delay in looking at this; Are there any errors that look like `Error while generating thumbnail` in your log files?  
Those are what land in that report at the end of the Minion job.  

It's strange that it'd just output blanks.. You can also look at the Minion console to see the result of the `regen_all_thumbnails` job directly.  
![image](https://github.com/Difegue/LANraragi/assets/8237712/eaeddf7a-dc7a-4c87-bc83-0d7db3c72222)
![image](https://github.com/Difegue/LANraragi/assets/8237712/8dd762cf-2f00-475f-a4fa-e25a3c52b0a4)

**Comment by Dr-Evil85** [comment]
I have the same problem 
that´s what i get from minion 

`---
args:
- /home/koyomi/lanraragi/content/thump
- 4ed235d05d053e5b2fc552ed24be0a0016793a78
- 0
attempts: '3'
children: []
created: 2024-06-03T21:56:57.61356Z
delayed: 2024-06-03T21:58:08.97363Z
finished: 2024-06-03T21:58:09.3646Z
id: '8266'
notes: {}
parents: []
priority: '0'
queue: default
result:
  errors:
  - |
    Error building thumbnail: mkdir /home/koyomi/lanraragi/content/thump/4e: Permission denied at /home/koyomi/lanraragi/script/../lib/LANraragi/Utils/Archive.pm line 166.
retried: 2024-06-03T21:57:52.97363Z
retries: '2'
started: 2024-06-03T21:58:09.30959Z
state: failed
task: thumbnail_task
worker: '51'`

**Comment by Kawaii-mumu233** [comment]
> Sorry for the delay in looking at this; Are there any errors that look like `Error while generating thumbnail` in your log files? Those are what land in that report at the end of the Minion job.
> 
> It's strange that it'd just output blanks.. You can also look at the Minion console to see the result of the `regen_all_thumbnails` job directly. ![image](https://private-user-images.githubusercontent.com/8237712/335908350-eaeddf7a-dc7a-4c87-bc83-0d7db3c72222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDkxNjcsIm5iZiI6MTcxNzUwODg2NywicGF0aCI6Ii84MjM3NzEyLzMzNTkwODM1MC1lYWVkZGY3YS1kYzdhLTRjODctYmM4My0wZDdkYjNjNzIyMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTM0NzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWU2Y2U3YmJhNzliOTlmMzdkZTVlNDczMGQyODRhNTlmYjFkMmMyZmZjODA1ZDE5NTFiOGJhYTBlYmMxYmMzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f5EAc1zREjBgaAHHQTSXbbH76JBdrF4XvV0C8GhG3SY) ![image](https://private-user-images.githubusercontent.com/8237712/335910251-8dd762cf-2f00-475f-a4fa-e25a3c52b0a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDkxNjcsIm5iZiI6MTcxNzUwODg2NywicGF0aCI6Ii84MjM3NzEyLzMzNTkxMDI1MS04ZGQ3NjJjZi0yZjAwLTQ3NWYtYTRmYS1lMjVhM2M1MmIwYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTM0NzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODk5OTNkNDYyYTQ4Y2MxZWUzOTVhZDBhOTg3NGEzN2ZjYWY4Y2Q3ZmEwNmZmZjVjY2FkMWU2MDk3MGI2YWQ5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1KsDrWgVK75x2SHf6A9XQjWufYhXCkLmwPaQLwkTPMg)

Thanks for reply, i'll try it next Monday ;)

**Comment by Difegue** [comment]
For permission denied errors, consider placing the thumbnail folder outside of the content folder entirely instead of the default; This same issue popped up with another user whose content folder was set to `drwxrwxr-x`.  

Normally the content folder doesn't need to be writable (that was the main impetus behind disassociating the thumbnail folder from it to begin with), but it is likely that if it tries to `mkdir` the thumbnail folder (because it doesn't exist yet) and you left it in the default location as a subfolder of the content dir, it'd fail.  

I should probably update the dockerfile to move the thumb directory somewhere else in the container by default..

**Comment by Difegue** [comment]
I've done said dockerfile updates, so I'll try tentatively closing this for now.

**Comment by jacobgkau** [comment]
In case it's relevant, I'm running the Podman container for Lanraragi's Docker image within a virtual machine, and that virtual machine itself has bind mounts from the actual physical folders on my NAS to the Podman "host" folders within the VM. For that reason, whenever I add a new archive, I've always needed to click the `Restart File Watcher` button to get Lanraragi to pick it up.

With the current config I described above, this is the new behavior after the update:
- When I add an archive and click `Restart File Watcher`, then browse to the archive, the page thumbnails are created in e.g. `thumbnails/73/730b67f4c2db94042abc0dc55d0228f6d261e711`, but the cover thumbnail is not created at e.g. `thumbnails/73/730b67f4c2db94042abc0dc55d0228f6d261e711.jpg` like it's supposed to be.
- If I click `Generate Missing Thumbnails`, then the cover thumbnail is created in the expected location & it displays properly.

I'm really confused why I now have to click `Generate Missing Thumbnails` to manually generate *only* the cover thumbnail on 0.9.1, when I used to not have to do that on 0.9.0. Under what condition would Lanraragi create the page thumbnails but not the cover thumbnail when it detects a new archive?

**Comment by jmhickman** [comment]
I also have this thing where I have to click the Generate Missing Thumbnails button, on two different instances. My `thumbs` directory is outside of the content directory I have set on both. Once I click that button everything shows up like it should.

**Comment by NagaseYami** [comment]
> I also have this thing where I have to click the Generate Missing Thumbnails button, on two different instances. My `thumbs` directory is outside of the content directory I have set on both. Once I click that button everything shows up like it should.

Same here.

**Comment by Difegue** [comment]
The `no_fallback` changes to the thumbnail endpoint broke the old behavior where asking for thumbnails would queue Minion jobs in the background to generate the thumbnails.  

This was intentional since Index loads on first launches would trigger a ton of jobs and clutter the queue real fast, but the consequence is that there really wasn't anything left to trigger thumbnail generation except for auto-plugin or opening the actual archive in full.  

I've reinstated Minion job firing to the Index (albeit at a reduced rate), but more importantly, the server will now generate thumbnails for an archive by default when it's added to the server, either via folder scanning, user upload or URL download.
