### ISSUE TITLE
Redis-server doesn't work properly when Windows get locked(Win + L). 

### ISSUE THREAD

**Issue by Tiblonde** [Difegue/LANraragi#957]
The issue looks like a former one in [#929](https://github.com/Difegue/LANraragi/discussions/929)

**LRR Version and OS**
Lanraragi 0.9.0-WSL 1, Windows, by wsl.

**Bug Details**
The LRR works right when get started, gallery can be opened and Shinobu console doesn't report error.
But once I **lock my windows** (or further unlock it, or leave it alone for a while), the gallery will die and show “Hachikuji Mayoi”.
(Get well after restart)
I find a suspicious behavier in Task Manager that when LRR works right, redis-server takes more memory but less when LRR dies.

**Matching Logs**
log from LogConsole, after I unlock windows
```
[Tag Stats] [info] Stat indexes built! (5032 archives)
[Shinobu] [info] All done! Now dutifully watching your files.
Can't load application from file "/home/koyomi/lanraragi/script/lanraragi": MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
[2024-03-20 18:34:17.56146] [13] [info] Creating process id file "/home/koyomi/lanraragi/public/temp/server.pid"
[2024-03-20 18:41:01.49212] [56] [error] [9_2vBtSjxUCs] MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. at /usr/local/share/perl5/site_perl/Mojo/Redis/Database.pm line 156.
```

**Screenshots**
"Hachikuji Mayoi":
![image](https://github.com/Difegue/LANraragi/assets/91446055/56a2e3b5-5cee-4bff-9b26-22d1d179a9d3)
![image](https://github.com/Difegue/LANraragi/assets/91446055/993db74c-d1a3-415c-8c62-587700eeb953)
Redis log:
![image](https://github.com/Difegue/LANraragi/assets/91446055/c2b6d8f3-6dd4-4672-a546-be1bae6b81b0)
Redis in Task Manager (Die):
![image](https://github.com/Difegue/LANraragi/assets/91446055/9e7eb56a-952a-4de3-bc52-8f5bda5d59ca)
Redis in Task Manager (Live):
![image](https://github.com/Difegue/LANraragi/assets/91446055/0929c8db-9bca-46db-a5ec-ae159a70ae86)

**Comment by Difegue** [comment]
That's https://github.com/Difegue/LANraragi/discussions/869 I believe, not that other issue you linked.  
There's a resolution in the comments there, but I'm planning to just drop WSL1 support and revert to using a built-in redis-server.  
(Probably bringing the legacy/oldalpine builds back for WSL1 users? idk yet)
