### ISSUE TITLE
Duplicate file handleing error in Nightly

### ISSUE THREAD

**Issue by ginobo** [Difegue/LANraragi#962]
**LRR Version and OS**
0.9.10, nightly (as of today)
https://hub.docker.com/layers/difegue/lanraragi/nightly/images/sha256-f3105f4a4ed1db14bcf916782aba7e4258979280feb163ddcd880f6feeb9ff41?context=explore
Docker Synology

**Bug Details**
Adding a duplicate file that should be overwritten triggers this error. 
```
Error while processing archive.
(Undefined  subroutine &LANraragi::Utils::Database::delete_archive called at  /home/koyomi/lanraragi/script/../lib/LANraragi/Model/Upload.pm line 79. )
```

My theory is that this method was moved or refactored and this implementation was missed, but am not familiar enough with the codebase to be able to submit a pull request pointing it to the new location.

**Comment by Difegue** [comment]
Correct, it was moved in https://github.com/Difegue/LANraragi/commit/aa4c1b284167ef5cb831e28bc3da03cb2ebec69b . Thanks!
