### ISSUE TITLE
How did these UIs appear?

### ISSUE THREAD

**Issue by happy1229** [Difegue/LANraragi#972]
In this picture,
I found that the UI above has more buttons than usual. What is the cause?
![444](https://github.com/Difegue/LANraragi/assets/91412240/193d2198-21cc-46de-9a0c-16840718dc91)

This one doesn’t have those buttons
![555](https://github.com/Difegue/LANraragi/assets/91412240/f84e3b11-eea3-4f32-b13a-b2c09be5039c)

**Comment by Difegue** [comment]
Probably just a browser extension.

**Comment by balvfr** [comment]
They're from this userscript
[https://github.com/Mayriad/Mayriads-EH-Master-Script](url)
