### ISSUE TITLE
uploaded plugins gone if docker container recreated

### ISSUE THREAD

**Issue by theggs** [Difegue/LANraragi#980]
**LRR Version and OS**
Docker
LANraragi v0.9.0

**Bug Details**
Uploaded plugins are store in `home/koyomi/lanraragi/lib/LANraragi/Plugin` along with the default plugins. This directory is come from the image.
As a result, when docker container recreate(e.g. for version upgrading, env vars updating), the directory will be restored, the uploaded plugins would gone. I have to upload the plugins, and configurate them again.

Expected: user uploaded plugins are put in an independent directory, so we can mount a local path to it.

**Matching Logs**
Post any logs you have encountered when reproducing the bug.  
If possible, switch the app to Debug Mode in order to have more logs.
No Logs.

**Screenshots**

**Comment by Nixis198** [comment]
I feel like this is a non-issue.

You should be able to make a volume map between the plugin folder in LANraragi to a system folder. It will keep any new/updated plugins and the database file will keep the settings.

Here is the command I ran to map the two folders.
![image](https://github.com/Difegue/LANraragi/assets/29938035/d98217b8-8124-4843-9a31-91cd2e66a994)

**Comment by theggs** [comment]
@Nixis198 
I thought the local emty directory will overwrite the one in container when first running.
Let me try it and feedback. Thanks.

**Comment by theggs** [comment]
@Nixis198 
It does as I expected: mounting a empty directory would overwrite the oraginal path. All metadata gone after startup. So it is not a solution.

**Comment by Nixis198** [comment]
I made a pull request that adds the plugins folder to the dockerfile. So it should be easier to add when making your container.
You will still have to reupload your plugins when/if this is accepted, but once you do it once you should be good. All your plugins will be stored not in the container, but in a local folder, and the database file should store your plugin settings.

**Comment by theggs** [comment]
> I made a pull request that adds the plugins folder to the dockerfile. So it should be easier to add when making your container. You will still have to reupload your plugins when/if this is accepted, but once you do it once you should be good. All your plugins will be stored not in the container, but in a local folder, and the database file should store your plugin settings.

it is a good idea to use VOLUME! Thank you!

**Comment by chierinyan** [comment]
Another solution is to directly mount the .pm **file** to the plugin dir
```
-v /path/to/your/fantasticPlugin.pm:/home/koyomi/lanraragi/lib/LANraragi/Plugin/<type>/fantasticPlugin.pm
```

**Comment by theggs** [comment]
> Edit: I just relized that LRR just checks all subdirs under Plugin, so if you have a lot of plugins to manage, you can also mount a custom subdir

It is nice if it check subdirectory. I think the guide about it can be add to user deploy document.

**Comment by theggs** [comment]
@chierinyan 
the uploaded plugins are put direct in `Plugin`. So even it checks all subdirs, the plugins wouldn't be in any subdirs.

**Comment by shinji257** [comment]
You can mount a subdir and just put the plugin in that subdir yourself rather than uploading via LANraragi.

**Comment by theggs** [comment]
@shinji257 I understand what you mean. It can be treated as a workaround, rather than be a end user-oriented resolution.

**Comment by Difegue** [comment]
I've added a `Sideloaded` directory in the Plugins folder, which behaves as mentioned in the comments above.  
Thanks for everyone's input on this!
