### ISSUE TITLE
FAKKU plugin has stopped working

### ISSUE THREAD

**Issue by pandafeliz** [Difegue/LANraragi#983]
**LRR Version and OS**
LRR 0.9.0 
Windows 11

**Bug Details**
The metadata plugin for FAKKU has stopped working, both in automatic and manual mode. The automatic mode stopped working a few months back but the manual mode was still fine until a few days ago, I suspect is because they made some modifications to the website. 
I know the plugin has been kinda wonky since the beginning and the suggested method was to use the chaika plugin, but they have stopped uploading any FAKKU related content for more than a year so is not really an option anymore.

**Matching Logs**
Log attached because of character limit
[fakkupluginlog.txt](https://github.com/user-attachments/files/15746269/fakkupluginlog.txt)

**Screenshots**
![image](https://github.com/Difegue/LANraragi/assets/72732463/c0587eaa-25f7-49e7-a0f2-d24e2bbadabd)

**Comment by Nixis198** [comment]
@pandafeliz I submitted a pull request to fix this. But here is the raw file you can use to patch your version so you don't have to wait on the next release.
[Fakku.zip](https://github.com/user-attachments/files/15753584/Fakku.zip)

**Comment by pandafeliz** [comment]
> @pandafeliz I submitted a pull request to fix this. But here is the raw file you can use to patch your version so you don't have to wait on the next release. [Fakku.zip](https://github.com/user-attachments/files/15753584/Fakku.zip)

Automatic mode is still broken but this fixed manual mode which is good enough for me, thanks.

**Comment by Nixis198** [comment]
Hmmm. I will do more testing to see why.

**Comment by Nixis198** [comment]
> Automatic mode is still broken but this fixed manual mode which is good enough for me, thanks.

@pandafeliz Found the issue and patched it.
[Here is the new file.](https://github.com/user-attachments/files/15755296/Fakku.zip) Let me know if you run into other issues.

**Comment by pandafeliz** [comment]
> > Automatic mode is still broken but this fixed manual mode which is good enough for me, thanks.
> 
> @pandafeliz Found the issue and patched it. [Here is the new file.](https://github.com/user-attachments/files/15755296/Fakku.zip) Let me know if you run into other issues.

That did the trick, thanks for the fix.
The only issue I could find right now is that it grabs some of the new elements that they added and parse them as tags, I don't know if there is a way to exclude them, here is an example:

![firefox_9dOfPXe8uP](https://github.com/Difegue/LANraragi/assets/72732463/0a5d1370-3693-4eba-994d-8f239c6da634)
![chrome_noVZhhIKV0](https://github.com/Difegue/LANraragi/assets/72732463/91afca3b-c00e-4a27-bc81-d0a285e78221)

**Comment by Nixis198** [comment]
> Previously it would only usually fail on archives that span multiple chapters but now it seems it just search for part of the title and grabs whatever it finds first.

Was/still is how the plugin is written to do. It just gets the file name, cleans it up, and searches it, and gets the first result.
I never use the automatic mode, even before FAKKU updated their website it had like a 30% rate of working. I always used the manual mode.
The plugin most likely will need a rewrite to better use the API search for FAKKU. I would say I'm not skilled enough to do that.

For the ":in this month." tag. It looks like FAKKU has that with the other tags in the HTML code of the webpage. The quick and dirty fix is to add it to your tag blacklist. But that's not really a good fix for it. I will see if I can update it exclude that.

**Comment by Nixis198** [comment]
Made a fix for the ":in this month." tag. It seems to be a rare edge case with it will only showing up if the doujin is in the top 10 of two categories. It will not show up if it is only in the top 10 of one category.

The fix is kinda dirty. It just checks the tag, and if it is equal to ":in this month." it just skips it. I don't really know a better way to solve this. (I'm guessing a way to test to see if the div that contains the "in this month." text is there and not to check it. But again I don't know the best way/how to do that.)

For now the plugin works great in manual mode, it just about works in auto mode (depending on the name of the file and if searching for it makes it the first result). I still only recommend that it be used in manual mode.

And as always @pandafeliz if you run into other issues or find any problems let me know and I will do my best to fix it.
[Fakku.zip](https://github.com/user-attachments/files/15779272/Fakku.zip)

**Comment by pandafeliz** [comment]
Thanks for the fixes, like I said, I also use mostly manual mode but back before they modified the site and broke the automatic mode the first time it wasn't that bad at grabbing around 70% correctly, at least on my case.

I don't think they have an API, that's why the plugin relies on grabbing the tags from the html page, but I could be wrong.

**Comment by Difegue** [comment]
Automatic mode can work but it's never been accurate since it just does a search manually and picks the first result.. There's not really much else we can do for it imo
